### ISSUE TITLE
create a function/procedure apoc.nodes.collapse(node-list, {config})

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#1003]
which does the same as apoc.refactor.mergeNodes just virtually

so that would entail:
- create a single virtual node for this node-list, merge the other properties
- add a virtual count property
- remove all virtual self relationships (could be an option to disable this behavior)
- merge all relationships of the same type/direction to the same entity and perhaps add a count property (could be an option to disable this behavior)
- optionally add another label? `:Collapsed` ?

Anything else @johnymontana ?

**Comment by johnymontana** [comment]
Here's a motivating example from the Panama papers dataset ([from this blog post](https://medium.com/@lyonwj/graph-visualization-of-panama-papers-data-in-neo4j-9c08ca17039c))

```
MATCH (off:Officer) 
WHERE toUpper(off.name) CONTAINS "REGULA LIMITED"
WITH off AS collapsed LIMIT 1
WITH apoc.create.vNode(["Regula"], collapsed {.*}) AS collapsed
MATCH (off)-[col1]->(e:Entity) 
WHERE toUpper(off.name) CONTAINS "REGULA LIMITED"
WITH collapsed, off, e, 
  apoc.create.vRelationship(collapsed, type(col1), {}, e) AS r1
MATCH (e)<-[r2]-(o2) 
WHERE (o2:Officer OR o2:Intermediary) 
  AND NOT toUpper(o2.name) CONTAINS "REGULA LIMITED"
RETURN collapsed, e, r1, r2, o2
```
