### ISSUE TITLE
apoc.date.between to check if a checkDate is in a period

### ISSUE THREAD

**Issue by kvegter** [neo4j-contrib/neo4j-apoc-procedures#1006]
## Feature description 
When you have time/date is modelled in your graph you want to do queries with a check-date, to return only those nodes and relationships which are 'valid', e.g. the check-date is between a dateFrom and a dateTo. It would save a lot of cypher when we have the following function:
``` 
apoc.date.between(fromDate,toDate,checkDate) return true|false
```
The function should work with temporal types or timestamp values (long)

It saves a lot of cypher especially if you have to do a period check on multiple Nodes/Relationships in the pattern:
```
plain cypher:
WHERE ((n.fromDate is null OR n.fromDate <= checkDate) 
AND (n.toDate is null OR n.checkDate < n.toDate))

or a function:
WHERE apoc.date.between(n.fromDate, n.toDate, checkDate)
```

**Comment by jexp** [comment]
Actually @kvegter null is automatically handled as "false"
and for the other, Cypher supports this python syntax:

`WHERE n.fromDate < checkDate < n.toDate`

**Comment by jexp** [comment]
@kvegter do you still need it if you have this cypher syntax?

**Comment by conker84** [comment]
this can be done via product now
