### ISSUE TITLE
request suppression of stack trace upon error for URLStreamHandlerFactory

### ISSUE THREAD

**Issue by Dcanzano** [neo4j-contrib/neo4j-apoc-procedures#1011]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use Streams, please ask on [StackOverflow](https://stackoverflow.com/questions/tagged/neo4j-apoc) instead of creating an issue here.

## Expected Behavior (Mandatory)
https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/778  describes the 'error' when logging for URLStreamHandlerFactory.  Requesting suppression of the full stack trace.

**Comment by inserpio** [comment]
Don’t understand what you mean 🤔

**Comment by sarmbruster** [comment]
The error message should stay as it is. It's just about supressing output of the stacktrace.
