### ISSUE TITLE
Add character index to apoc.xml.import for the imported XmlWord-Nodes and import Whitespaces as Whitespace-Nodes

### ISSUE THREAD

**Issue by kuczera** [neo4j-contrib/neo4j-apoc-procedures#1012]
## Create a test-case
To create a small test-db use: 

`call apoc.xml.import("https://seafile.rlp.net/f/7a959323fa4742518d57/?dl=1",{createNextWordRelationships:true}) yield node return node;`

`match path=(d:XmlDocument)-[:NEXT_WORD*]->(x:XmlWord)
with nodes(path)[-1] as this, nodes(path)[-2] as prev
set this.startIndex = coalesce(prev.endIndex,0)+1, this.endIndex=this.startIndex+size(this.text)-1;`

`MATCH (w1:XmlWord)-[nw:NEXT_WORD]->(w2:XmlWord)
DELETE nw
CREATE (w1)-[:NEXT_WORD]->(ws:XmlWhitespace)-[:NEXT_WORD]->(w2);`

## Feature description
For further work with imported TEI-XML-Data it would be perfect to have the character-startindex and -endindex in the importet XmlWord-Nodes. The indexes should count the space between characters. In addition the import of whitespaces from the original xml-file as nodes of type Whitespace would be imporant.

## Considered alternatives
-/-

## How this feature can improve the project?
With this feature it becomes possible to improve the reusage of huge TEIP5-xml-coded sources in the digital humanities in graph data modells. 
Here is an example. The numbers show the index, hyphens show whitespaces and words symbolize the XmlWord-nodes.

`0...4-5Noch9-10mehr14-15Nachsicht24-25erbitte32-33ich36-37mir,41-42weñ46-47ich50-51bedenke,59-60dß62-63daß66-67mir70-71die74-75Sprache82-83nicht88`

<img width="741" alt="bildschirmfoto 2018-12-09 um 14 50 54" src="https://user-images.githubusercontent.com/10571362/49698891-eee44f80-fbc1-11e8-9a48-fe4de3b805e5.png">

The numbered nodes are the whitespaces.

**Comment by sarmbruster** [comment]
pending PR at https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/1059

**Comment by conker84** [comment]
closed via 62ff912
