### ISSUE TITLE
Count by attributes of item in the list.

### ISSUE THREAD

**Issue by thanh-taro** [neo4j-contrib/neo4j-apoc-procedures#1013]
Hi APOC team.

It's great when using APOC functions for many things in Neo4j and it helps me in many many cases. Thank you.

But, it would be greater if there is a function that count items on the list by attributes. Something like this: [{name: "User A", gender: "male", age: 12},{name: "User B", gender: "female", age: 5},{name: "User C", gender: "male", age: 6}] --> {male: 2, female: 1, age_under_10: 2, age_over_10: 1}

Neo4j has the FILTER that can do this job but not good in performance, so it's better if APOC has some functions like this.

**Comment by jexp** [comment]
Ping @thanh-taro

**Comment by conker84** [comment]
closing for lack of feedback
