### ISSUE TITLE
apoc.periodic.iterate() produce diffrent results with parallel set to true/false

### ISSUE THREAD

**Issue by PeterKazmirsky** [neo4j-contrib/neo4j-apoc-procedures#1015]
I have neo4j graph where I run population with new data and also cleaning process that is supposed to remove old data. My nodes have property called last_updated where I store date when node was last updated. That nodes also have property ttl that contains number for how many days node should stay in database. Let's say my ttl = 30 days. My cleaning process is supposed remove nodes that haven't been updated for more than 30 days.
For that purpose I call this cleaning query:
`CALL apoc.periodic.iterate(
"MATCH (n) WHERE EXISTS(n.last_updated) WITH apoc.date.parse(n.last_updated, 's', 'yyyyMMdd') AS startTime, n
 WHERE toInt(apoc.date.format(startTime + n.ttl*(60*60*24), 's', 'yyyyMMdd')) < 20180817
 RETURN n",
"DETACH DELETE n",
{batchSize:10000, iterateList:true, parallel:false})`

Before I run this query I am checking how many nodes I have with last_updated=20180717 so I run this query and will get:
`Match (n) where n.last_updated = '20180717' return count(n)`
result: count = 245620
And after I run cleaning query I will get 
result: count = 0
Those are correct results.

Problem is when I run cleaning query with parallel: true 
In that case I will get different counts:
result: count = 145620

It seems like parallel mode removed only exactly 100000 records and rest is untouched. 

Any idea what it could cause ? 
Thanks.

Currently used versions

### Versions

  - OS: Windows 7
  - Neo4j: 3.3.3, 3.4.10 (I had same problem on both versions)
  - Neo4j-Apoc:  3.4.0.4

**Comment by conker84** [comment]
I'm closing this as it's quite old, feel free to reopen it in case the bug is still there in newer versions
