### ISSUE TITLE
Add documentation to changes made by #1005

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-apoc-procedures#1021]
Add documentation to changes made by #1005

**Comment by StefanoBelloni** [comment]
Hallo,
the configuration supports
string or boolean (for backward compatibility), i.e.
 `quote: ['always' | 'none' | 'ifNeeded' | true | false | null]`
* default is `'always'`
* `true` is mapped to `'always'`
* `false` is mapped to `'none`.

**Comment by conker84** [comment]
@StefanoBelloni thanks a lot!
