### ISSUE TITLE
Graph Refactoring Procedures Documentation

### ISSUE THREAD

**Issue by jvhashe** [neo4j-contrib/neo4j-apoc-procedures#1027]
## Expected Behavior (Mandatory)
[Documentation listed here ](https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_graph_refactoring_procedures) states that one of the operation types is named "**override**". However, after looking at the source code, the real key is **overwrite**. The documentation needs to be updated.

## Actual Behavior (Mandatory)
The **override** key behaves as if using the **discard** key because it's not a recognized value. The real value is **overwrite**.

**Comment by jexp** [comment]
Perhaps allow both.
