### ISSUE TITLE
apoc.load.xls is missing in apoc-3.5.0.1-all.jar

### ISSUE THREAD

**Issue by paltusplintus** [neo4j-contrib/neo4j-apoc-procedures#1034]
#Cypher
call apoc.help("apoc.load.xls")

## Expected Behavior (Mandatory)
to provide results of size > 0

## Actual Behavior (Mandatory)
(no changes, no records)

### Versions
  - OS: Windows Server 2012 R2 Standard
  - Neo4j: 3.5.0
  - Neo4j-Apoc: 3.5.0.1

**Comment by jexp** [comment]
did you add the jar files as indicated in the docs?

**Comment by jexp** [comment]
ping @paltusplintus

**Comment by paltusplintus** [comment]
Sorry. I could not reproduce the error again. Perhaps restart or update of Java version helped...

**Comment by paltusplintus** [comment]
closing
