### ISSUE TITLE
apoc.load.csv doesn't properly format file uri on windows when dbms.directories.import is used

### ISSUE THREAD

**Issue by davidfauth** [neo4j-contrib/neo4j-apoc-procedures#1036]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use Streams, please ask on [StackOverflow](https://stackoverflow.com/questions/tagged/neo4j-apoc) instead of creating an issue here.

### Simple Dataset (where it's possibile)

```
//Insert here a set of Cypher statements that helps us to reproduce the problem

```

### Steps (Mandatory)

  1.
  1.
  1.

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS:
  - Neo4j:
  - Neo4j-Apoc:

**Comment by davidfauth** [comment]
**Expected Behavior**

with _dbms.directories.import_ uncommented and set to a Windows path, the user should be able to run this:
CALL apoc.load.csv("file:///testfile.csv") yield map as row return row 

**Actual Behavior**
Error occurs:
Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `apoc.load.csv`: Caused by: java.io.IOException: Cannot open file file:c:\data\testfile.csv for reading.

Note **file** is appended in front of c:

** Steps **
In neo4j.conf, add these lines:

dbms.security.procedures.unrestricted=apoc.*
apoc.import.file.enabled=true
apoc.import.file.use_neo4j_config=true
dbms.security.allow_csv_import_from_file_urls=true

set dbms.directories.import=c:\data

**Specifications **
OS - Windows 10
Neo4j Version - 3.4.4 Enterprise 
APOC - 3.4.0.1

**Comment by conker84** [comment]
Hi @davidfauth and thanks for reaching us.
The bug should be solved in v. 3.4.0.4 can you give it a try and report feedback?
Moreover, you must change `dbms.directories.import=c:\data` in this way:
`dbms.directories.import=c:\\data`

**Comment by conker84** [comment]
@davidfauth any news?

**Comment by conker84** [comment]
I'm closing this, please feel free to reopen it in case the problem cannot be solved with the provided solution
