### ISSUE TITLE
update to version 3.5.0.1, apoc.load.jdbc select timestamp column which value is NULL  raise Exception

### ISSUE THREAD

**Issue by mpwang** [neo4j-contrib/neo4j-apoc-procedures#1039]
after upgrade to neo4j 3.5.1 apoc-3.5.0.1,  below cypher statement

    CALL apoc.load.jdbc('jdbc:mysql://xxx:xxx@xxx:3306, "SELECT * FROM ... WHERE ..") YIELD ROW;

 will raise Exception as blow:

    "Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure apoc.load.jdbc: Caused by: java.lang.NullPointerException"

on my test database which works fine with neo4j 3.4.9 apoc 3.4

## Expected Behavior 
CALL apoc.load.jdbc do not raise exception

## Actual Behavior 

raise Exception

## Specifications 

further testing shows selecting timpstamp column which value is NULL from the table will raise exception

    CALL apoc.load.jdbc('jdbc:mysql://xxx:xxx@xxx:3306, "SELECT createTime FROM ... WHERE createTime is null") YIELD ROW;

Currently used versions

### Versions

  - OS: CentOS 7
  - Neo4j: 3.5.1
  - Neo4j-Apoc: 3.5.0.1

**Comment by mpwang** [comment]
My table does has some timestamp fields.

I'm using mysql-connector-java-8.0.13.jar downloaded form [MySQL](https://dev.mysql.com/downloads/connector/j/)

Wih your hint now i can definitely locate that the error is caused by datetime columns with `NULL` value.  
Whenever i select datetime column which vlaue is  `NULL` the exception raised.

Any idea how can we resolve this problem?

**Comment by jexp** [comment]
Could you coalesce/nvl those to a default value for the time being? it's a bug that has been introduced and needs to be fixed.

**Comment by mpwang** [comment]
I'm using some ORM (Python Sqlalchemy ) reflection to generate the select sql.

Could you advise how to write the convertion, on the Sql side or on the Cypher side?

Thank you very much. This is preventing me to upgrade to the awesome 3.5.
