### ISSUE TITLE
apoc.convert.toTree config option to include/exclude certain properties

### ISSUE THREAD

**Issue by mrbungle733t** [neo4j-contrib/neo4j-apoc-procedures#1040]
## Feature description 
config option to include/exclude certain properties 

## How this feature can improve the project?
Tt would reduce the ammount of data transmitted to application on database side. Currently apoc.convert.toTree returns with  tree structure also all properties of the child nodes in the tree.

**Comment by mrbungle733t** [comment]
Hi,

I tried to play with apoc.conver.toTree. It seems that the option to include/exclude certain properties works only in case i have a dataset where all nodes are the same type. In case I have branches/leaves with another node type, then all properties are returned for another type. 

Maybe I did not understand the syntax and there is some way to define behavior for different node types as well?

**Comment by Estrago** [comment]
Hi, i couldnt find in the documentation if this was implemented or not.

**Comment by mrbungle733t** [comment]
> Hi, I couldn't find in the documentation if this was implemented or not.

Unfortunately, I haven't found it. 

Have a related question on community site: 
https://community.neo4j.com/t/help-using-apoc-convert-totree-config-option-to-include-exclude-certain-properties/6100

I'd like to understand, how to include/exclude properties when there are multiple labels assigned to the node.
