### ISSUE TITLE
export mode for cypher with parameters for cypher-shell/browser

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#1043]
this should happen in two steps
use batch size for max size

parameters, at least for cypher-shell with `:param rows => [{....},{....},{....}]`
and then use `UNWIND $rows AS row MERGE (:Label {id:row.id}) SET n += row.properties, SET n:Label2`
https://neo4j.com/docs/operations-manual/current/tools/cypher-shell/#cypher-shell-parameters

**Comment by vga91** [comment]
Fixed by #998
