### ISSUE TITLE
apoc.refactor.mergeNodes don't overwrite properties of relationships 

### ISSUE THREAD

**Issue by PeterKazmirsky** [neo4j-contrib/neo4j-apoc-procedures#1047]
**Guidelines**
Imagine this simple 3 nodes:
`CREATE (n1:Node{value:'node1'})
CREATE(n2:Node{value:'node2'})
CREATE(r:Root{value:'root'})
CREATE (n1)-[hr1:HAS_ROOT]->(r)
SET hr1.rel_property='rel1'
CREATE (n2)-[hr2:HAS_ROOT]->(r)
SET hr2.rel_property='rel2'`

Than I want to call apoc.refactor.mergeNodes on n1 and n2 like that:
`Match (n1:Node{value:'node1'}), (n2:Node{value:'node2'})
CALL apoc.refactor.mergeNodes([n1,n2],{mergeRels:true, properties:'overwrite'}) YIELD node RETURN node`

**Actual Behavior**
It will correctly merge nodes n1, n2 and result node will have value 'node2'.
However property 'rel_property' in 'HAS_ROOT' relationship is now 'rel1, rel2'. So instead of overwriting property it combined property of relationship. 

**Expected Behavior** 
I would like you to consider to add feature to apoc.refactor.mergeNodes that will also overwrite properties in relationships and not only in nodes. 
Thank you.

**Versions**
Neo4j 3.5.1
Apoc library 3.5.0.1

**Comment by AngeloBusato** [comment]
Hi @PeterKazmirsky, yes actually in procedure `apoc.refactor.mergeNodes` with `mergeRels` config allowed properties of the result of merged relationships are only combined, `properties` config is not considered. 
We could modify the procedure so that the `properties` configuration is also considered in the merged relationship.

**Comment by PeterKazmirsky** [comment]
Hi @AngeloBusato Thanks for picking up the ticket. If it wouldn't be a problem I would really appreciate if you modify procedure.  Please let me know if you will have any updates on that. Thank you
