### ISSUE TITLE
apoc.import.csv, if __csv_id already exists in the database, can ignore the duplicate node through ignoreDuplicateNodes?

### ISSUE THREAD

**Issue by MerkinMa** [neo4j-contrib/neo4j-apoc-procedures#1048]
The apoc.import.csv new option ignoreDuplicateNodes is very great, but it only ignore duplicate nodes for this import, if the nodes already exists int the database, can it also ignore these nodes? Ignore the repeated nodes should be for the whole database, not just for a single import action, if it can increase the comparison option will be better, thank you!!

**Comment by MerkinMa** [comment]
The contents of the file NluAdmin.csv are as follows:
formId:ID(NluAdmin),name
2588,ABC

CALL apoc.import.csv(
[{fileName: 'NluAdmin.csv', labels: ['NluAdmin']}],[],
  {ignoreDuplicateNodes:true}
)

Called twice, it will add two identical nodes with the same __csv_id

**Comment by jexp** [comment]
This is more involved because it either requires checking each node against the database
(or using MERGE instead of create (which could be an option)

or loading the database first into an index structure (which could grow gigantic).

WDYT @szarnyasg ?

**Comment by szarnyasg** [comment]
We had a discussion about this a few months ago with @jexp.

In order to add this feature, we would need to add an optional configuration flag which tells the loading process to keep (and then index) the CSV ids in the database. This would cause some overhead but it's not too excessive. Unfortunately, I haven't gotten around this since then.

**Comment by MerkinMa** [comment]
I understand the difficulty of this issue is very high, I will close this issue first, if you have any ideas in the future, please let me know. Thank you.
