### ISSUE TITLE
apoc.export.cypher.all fails when a compound constraint exists

### ISSUE THREAD

**Issue by drsnyder** [neo4j-contrib/neo4j-apoc-procedures#1049]
## Expected Behavior (Mandatory)
`CALL apoc.export.cypher.all('/data/seed.cypher',{format:'cypher-shell'});` works when compound constraint exist.

## Actual Behavior (Mandatory)
```
CALL apoc.export.cypher.all('/data/seed.cypher',{format:'cypher-shell'});
Failed to invoke procedure `apoc.export.cypher.all`: Caused by: java.util.NoSuchElementException: More than one element in java.util.AbstractList$Itr@693ec7a0. First element is 'adTagType' and the second element is 'name'
```

## How to Reproduce the Problem
Create a compound constraint on a node. I have the following:

```
create constraint on (t:AdTag) assert (t.adTagType, t.name) is node key;
```

### Simple Dataset (where it's possibile)

```
MERGE (a:AdTag:test {name: "E", adTagType: "ESRB-test"});
MERGE (a:AdTag:test {name: "Under 18", adTagType: "Age-test"});
MERGE (a:AdTag:test {name: "13-17",  adTagType: "Age-test"});
MERGE (a:AdTag:test {name: "18-24", adTagType: "Age-test"});
MERGE (a:AdTag:test {name: "25-34", adTagType: "Age-test"});
```

### Steps (Mandatory)

  1. Run `create constraint on (t:AdTag) assert (t.adTagType, t.name) is node key;`
  1. Add the sample data above.
  1. Run `CALL apoc.export.cypher.all('/data/seed.cypher',{format:'cypher-shell'});`

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: OS X 10.13.6
  - Neo4j: Enterprise 3.5.0
  - Neo4j-Apoc: 3.5.0.1

**Comment by jexp** [comment]
Thanks a lot for your report, it's a bug we'll fix it in the next release.
I guess handling composite constraints, has to be implemented.
Until then, perhaps you can drop the constraint temporarily and replace it with a single-field constraint if that makes any sense with your data, otherwise you can let the default mode work which uses the node-id.
