### ISSUE TITLE
Different results with calling neo4j function in neo4j browser V.S. neo4j driver via bolt

### ISSUE THREAD

**Issue by yuanzhou** [neo4j-contrib/neo4j-apoc-procedures#1054]
I'm writing a user-defined neo4j function using APOC in java. 

Neo4j version 3.5.1, APOC version 3.5.0.1. Below is the simplified code:

````
@UserFunction(name = "my.getPosition")
    @Description("return position of a node.")
    public Map getReport() {
   Map<String, Object> position= new HashMap<>();
   node.put("x", intX);
   node.put("y", intY);
   node.put("name", StringName);

return node;
}
````

When I call this function in neo4j broswer using `return my.getPosiiton()` I get the JSON returned like this:

````
{
  "x": 20,
  "y": 34,
  "name": "myNode"
}
````

But when I call the cypher query in neo4j driver via bolt, I got the following:

````
{
  "x": {
    "high": 20,
    "low": 0
  },
  "y": {
    "high": 34,
    "low": 0
  },
  "name": "myNode"
}
````

Has anyone encountered this difference?

**Comment by sarmbruster** [comment]
your question seems not to be related to apoc. Apoc is a set of user defined functions and procedures extending neo4j.
Instead your question is targeted at core neo4j functionality - therefore please ask it on https://community.neo4j.com/. Thanks.

**Comment by yuanzhou** [comment]
Thanks. And I think this is an issue with the neo4j javascript driver. I'll post the issue there.
