### ISSUE TITLE
Add procedure to compare graphs

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#1064]
Add procedures to compare graphs

are these two graphs equal (hashing neighborhoods)

if not list differences (e.g. via label + primary key to identify nodes (or all props))

optionally for remote graphs (via bolt)

**Comment by jexp** [comment]
1. same node count / same count per label
2. same relationship counter / same count per rel-type
3. for each node with a certain label
4. find the same node (by id) in the other graph
5. if found, compare all properties
6. compare all relationships that they end in the same label + id
7. compare rel-properties

**Comment by jexp** [comment]
return. diff results in columns

label1, id1, label2,id2, type(of difference, e.g. propery,label,rel-property, ...), values(map)

**Comment by jexp** [comment]
sub-graphs in input:

- graph object aka map with: `nodes`, and `relationships`

(
-  just two lists of paths
- two cypher statements
)

**Comment by jacktang** [comment]
The code was not merge into main branch?

**Comment by vga91** [comment]
@jacktang I just created the 4.4 equivalent pr, https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3041

**Comment by kattishirish** [comment]
Is there a way to compare sub-graphs, not as a hash set, but actually to find out what the difference is between the two subgraphs

**Comment by TiMeJuMp** [comment]
Need also a comparison of 2 or also multiple subgraphs. Is there anywhere an example or code snipped or algorithm to use?

**Comment by jexp** [comment]
If you look at the pseudocode that I put in above?

https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1064#issuecomment-502375024
