### ISSUE TITLE
Add var-length support to expand for sequences

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#1066]
E.g. `KNOWS*>,WORKS_WITH>` or `KNOWS*3..5>`

**Comment by InverseFalcon** [comment]
This will be a bit tricky, but it's worthwhile. Current implementation uses the current path length modulo the sequence length to figure out which part of the sequence we're on. To handle variable-length parts of the sequence (and possibly several of these within the sequence) we'd have to abandon this approach, and use something like a finite state machine that we pass along during expansion to track our position in the sequence.
