### ISSUE TITLE
apoc.path.expand should return empty path instead of null when `optional:true` is used

### ISSUE THREAD

**Issue by sarmbruster** [neo4j-contrib/neo4j-apoc-procedures#1069]
When using an expand with `optional:true` and the path is not found, we get back a `null`.
We've had cases where an empty path would be more approriate as return value.

Maybe add another config option like `mapNullToEmptyPath:<true/false>` to customize

**Comment by InverseFalcon** [comment]
Could you provide some info on the cases where this would be useful? I don't think there are any cases in Cypher where empty paths are ever returned. Even for OPTIONAL MATCH with a path variable, the path is null when no such match exists.

**Comment by jexp** [comment]
@sarmbruster ping :)

**Comment by conker84** [comment]
@sarmbruster I'm closing this feel free to reopen in case you need it
