### ISSUE TITLE
Add "description" to custom procedures/functions

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#1073]

**Comment by sim51** [comment]
If we add the description to the procedures `apoc.custom.asProcedure` & `apoc.custom.asFunction`, we will change theirs signatures.

`call apoc.custom.asProcedure('answer','RETURN 42 as answer')` will still work but not  `call apoc.custom.asProcedure('answer','RETURN 42 as answer','read',[['answer','long']])`.

Except if we add the `description` param at the end of the signature with a default value, but  if we do that users will have to declare all the params to be able to fulfil the description... and I think it's bad.

What do you think to add the description param after the statement one :  `call apoc.custom.asProcedure(name, statement, description, mode, outputs, inputs)` ?

**Comment by sim51** [comment]
What do you mean by "manual way" ?
