### ISSUE TITLE
Request new refactoring procedure: apoc.refactor.cloneSubgraph()

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j-contrib/neo4j-apoc-procedures#1075]
## Feature description
We've had requests via the community on copying parts of a graph, but current approach to cloning nodes and relationships is messy when the intent is to copy out part of a graph and attach it elsewhere, such as attempting to copy a branch of a tree structure and attach it to a different root node. In these cases, what's really being requested is a subgraph consisting of the cloned nodes with the cloned relationships between those nodes, but omitting any relationships outside of those cloned nodes (including to the originals).

This requests a new procedure `apoc.refactor.cloneSubgraph()` which takes in the collection of nodes and relationships to clone (such as those returned by apoc.path.subgraphAll()). The caller could alternately use `apoc.algo.cover()` to get the collection of relationships between the list of nodes, if all are desired.

Signature:

`apoc.refactor.cloneSubgraph([nodes], [relationships], [[nodeToBeReplaced, replacementNode]]) YIELD input, output, error`
The first two parameters are mandatory, the lists of nodes and relationships forming the subgraph to be cloned.
The third parameter is optional, a list of pairs of nodes, the node to be replaced and the replacement node.
The yielded values would be the same as the cloneNodes() and cloneNodesWithRelationships() procedures.

The procedure would first clone the nodes, then using an id mapping from originals to clones, the relationships would be cloned between the cloned nodes only. If no mapping exists (user somehow supplied relationships that don't have both connections in the node list parameter) the relationship will be ignored, with the exception of the behavior below.

If the third parameter (replacement nodes list) is present, then it would modify the relationship creation step. Rather than using the id map to find the cloned nodes to use to clone the each relationship, the supplied map pairs would be used to construct a secondary mapping of to-be-replaced nodes to replacement nodes, and this map would be consulted first. 

## Considered alternatives
I considered using the existing clone procedures instead, adding a new parameter to control the functionality, but I wanted to provide more control over the relationships that were cloned rather than always cloning all relationships. The signatures were also getting a bit long, especially considering the replacement pairs parameter.

## How this feature can improve the project?

Here is an example query showing cloning of a branch of a tree structure and attaching it to a new root:

```
MATCH (a:Root {name:'A'}), (b:Root {name:'B'})
CALL apoc.path.subgraphAll(a, {relationshipFilter:'CHILD>'}) YIELD nodes, relationship
CALL apoc.refactor.cloneSubgraph(tail(nodes), relationships, [[a, b]]) YIELD input, output, error
RETURN input, output, error
```

Note that by using `tail(nodes)` we skip the starting node `a`, so it does not get cloned, but the list of replacement pairings will ensure that `b` will be a standin for `a` when the relationships are cloned.

**Comment by jexp** [comment]
Did you see apoc.refactor.cloneNodeAndRelationships ?
Not sure if that#s good enough?

**Comment by InverseFalcon** [comment]
I did see that, the problem with that one is:

1. You get relationships to nodes outside of the cloned nodes
and
2. You get relationships to the original nodes, not just the clones
and lastly
3. It's tricky when you want to clone, but at the same time refactor relationships from one node to another (especially since we have separate refactor procs for from and to relationships, but we don't have a unified proc to do both).

This makes it less than ideal for use cases where you're trying to copy a subgraph, such as in [this use case](https://community.neo4j.com/t/most-efficient-way-to-clone-a-branch-from-a-top-level-node/3639) where the intent is to copy a branch of a tree and associate it with another node. `cloneNodesAndRelationships()` requires additional work to match to and delete relationships that are not among the cloned nodes, and at the same time attempting to redirect relationships from one node to a different one in the graph then delete that cloned node after. That leads to a messy and tricky query.

**Comment by jexp** [comment]
Added, see PR + Docs

**Comment by jexp** [comment]
Thanks a lot for implementing it Andrew!
