### ISSUE TITLE
Add tests for file streaming in containers

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-apoc-procedures#1080]
## Feature description (Mandatory)

This previous PR: https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/1062 did not include unit tests, because the code relies on the existence of files on disk and the impermanent graph database test harness that APOC uses doesn't create those.

When APOC uses test containers to run APOC against live databases, those tests can be created under that setup.

## How this feature can improve the project?

More complete code testing coverage, prevention of regressions.

**Comment by jexp** [comment]
@moxious perhaps work with @conker84 on this?

**Comment by conker84** [comment]
done in #1202
