### ISSUE TITLE
installation of neo4j-apoc-procedures with the community edition

### ISSUE THREAD

**Issue by c0ntradicti0n** [neo4j-contrib/neo4j-apoc-procedures#1086]
## Guidelines
After installing the community edition on OS: Ubuntu 18.04.1 LTS x86_64 with:

`sudo apt install neo4j`

I followed the instructions here [https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_manual_installation_download_latest_release](https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_manual_installation_download_latest_release), and copied the jar-file there. It is also executable.

## Expected Behavior (Mandatory)
Neo4j starts and I can run apoc-procedures

## Actual Behavior (Mandatory)
Neo4j doesn't start anymore. After removing it starts again as before.

### Steps (Mandatory)

  1. Install neo4j
  1. Download apoc and copy
  1. `sudo service neo4j start`

### Versions

  - OS: Ubuntu 18.04.1 LTS x86_64
  - Neo4j: 3.5.2
  - Neo4j-Apoc: 3.4.0.4

**Comment by sarmbruster** [comment]
You need to pick the right version of APOC fitting your neo4j version. See the compatibility matrix at https://github.com/neo4j-contrib/neo4j-apoc-procedures#version-compatibility-matrix
