### ISSUE TITLE
can not get apoc.periodic.submit() to run CALL db.createUniquePropertyConstraint()

### ISSUE THREAD

**Issue by Dcanzano** [neo4j-contrib/neo4j-apoc-procedures#1089]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use Streams, please ask on [StackOverflow](https://stackoverflow.com/questions/tagged/neo4j-apoc) instead of creating an issue here.

## Expected Behavior (Mandatory)
Unable to get apoc.periodic.submit() to call `CALL db.createUniquePropertyConstraint(":E(id)", "lucene-1.0")`  as the constraint and associated index are never created.  No errors, nothing written to debug.log to describe failure

# Actual Behavior (Mandatory)
expect the constraint and related index to be created

## How to Reproduce the Problem

have tried
call apoc.periodic.submit('job123','CALL db.createUniquePropertyConstraint(":E(id)","lucene-1.0");');

or

call apoc.periodic.submit('job123','CALL db.createUniquePropertyConstraint(\":E(id)\",\"lucene-1.0\");');

but still no success

### Simple Dataset (where it's possibile)

```
//Insert here a set of Cypher statements that helps us to reproduce the problem
see above
```

### Steps (Mandatory)
see above

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS:
 uname -a
Linux ubuntu17 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:33:49 UTC 2017 i686 i686 i686 GNU/Linux

  - Neo4j:   3.5.2
  - Neo4j-Apoc:   apoc-3.5.0.1-all.jar

**Comment by sarmbruster** [comment]
theory: apoc.periodic.submit uses mode=WRITE while the call is a schema operation?

**Comment by jexp** [comment]
Yes that was my thought too.

OTOH periodic.submit runs it in a background thread/scheduler, but I have to check which database that uses. I guess it just submits a closure over the db that was used in the submit procedure.
