### ISSUE TITLE
subgraph concept

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#109]
apoc.create.graph(nodes,rels,data-map) → {nodes:[], rels:[], data:{}} a graph data structure, e.g. for rendering, export, validation, …​

summary for graphs (a bit like apoc.meta.stats but for a named subgraph)

graph operations (union, intersection etc. see gradoop), but also graph summarization and FSM

**Comment by jexp** [comment]
also related to #1064

**Comment by conker84** [comment]
it's `apoc.graph.*`
