### ISSUE TITLE
apoc query error  about algo.betweenness

### ISSUE THREAD

**Issue by 444728248** [neo4j-contrib/neo4j-apoc-procedures#1096]
1. The query statement is as follows
`MATCH (node:DNA_INFO)
where node.SAMPLE_NO = '2014C5369P0001S01'
call apoc.path.subgraphAll(node,{}) yield nodes
WITH collect(nodes) AS nodes
CALL apoc.algo.betweenness(['DYA'],nodes,'BOTH') YIELD n, score
RETURN n, score
ORDER BY score DESC`

1. error
`Neo.ClientError.Statement.SyntaxError
Type mismatch: expected List<Node> but was List<List<Node>> (line 5, column 36 (offset: 185))
"CALL apoc.algo.betweenness(['DYA'],nodes,'BOTH') YIELD n, score"
                                            ^`
**How to modify the query statement above?**

**Comment by InverseFalcon** [comment]
The `nodes` yielded by `apoc.path.subgraphAll()` is already a list of nodes, you don't need to collect them again. Leave out that `collect(nodes) as nodes` and it should be fine

**Comment by 444728248** [comment]
**Hello, big God
Modify to a new statement**
```
MATCH (node:DNA_INFO)
where node.SAMPLE_NO = '2014C5369P0001S01'
call apoc.path.subgraphAll(node,{}) yield nodes
CALL apoc.algo.betweenness(['DYA'],nodes,'BOTH') YIELD n, score
RETURN n, score
ORDER BY score DESC
```
**ERROR INFO** 
Neo.ClientError.Statement.SyntaxError
Unknown procedure output: `n` (line 5, column 56 (offset: 177))
"RETURN n, score"
**You can write a case tks？**

**Comment by InverseFalcon** [comment]
`apoc.algo.betweenness()` doesn't yield a variable `n`. It yields `score`. Use that instead.

If you run into similar syntax errors, use `apoc.help()` providing the name of the procedure you're trying to use, and pay attention to the variables yielded in the signature.

**Comment by 444728248** [comment]
tks。
