### ISSUE TITLE
Feature request  : CALL apoc.custom.list()  returning list of custom procedures and functions

### ISSUE THREAD

**Issue by ophileon** [neo4j-contrib/neo4j-apoc-procedures#1104]
## Feature description 
A procedure returning the custom Functions / Procedures that have been defined using`apoc.custom.asFunction` or `apoc.custom.asProcedures` , including their signatures.

**Comment by sarmbruster** [comment]
when implementing this, add the the cypher string used by the custom procedure as well to the output.
