### ISSUE TITLE
[Question] What does the timeout parameter in apoc.cypher.runMany do?

### ISSUE THREAD

**Issue by mprahl** [neo4j-contrib/neo4j-apoc-procedures#1105]
Hello,
I'm currently using `apoc.cypher.runMany` and I noticed it takes an optional `timeout` parameter. What does this do? I intuitively thought the query would abort if it took longer than the timeout in seconds, but it doesn't seem to be the case since I set the timeout to 1 on a long query and it didn't abort the query.

Thank you for your help.

**Comment by jexp** [comment]
it's a parameter that exposes the underlying approach for running tasks asynchronously, there is a timeout for the blocking queue to not block forever in case something goes wrong and no more items are added.

**Comment by jexp** [comment]
timeout is in seconds, default is 10s, it's the time for a statement result to be consumed by the downstream processing. As it uses a queue internally to hand off execution results from a separate tx in a separate thread.
