### ISSUE TITLE
apoc.coll.intersects(list_1, list_2) not available

### ISSUE THREAD

**Issue by serle** [neo4j-contrib/neo4j-apoc-procedures#1106]
I have a list that I will pass into my cypher query. I need a WHERE predicate which compares an array field to the list passed into the query and returns true or false, if there are any matching values. 

Work Around

`LENGTH(apoc.col.intersection(list_property, hardcoded_list)) > 0`

Issue

This seems inefficient to me as the whole intersection is calculated before returning. With a more specific apoc procedure, it should be possible to bomb-out and return true on first match.

**Comment by sarmbruster** [comment]
I guess this easy with standard cypher:

```
return any(x in list_property WHERE x in hardcoded_list) as hasIntersection
```

Please let us know if that solves the issue for you.

**Comment by serle** [comment]
Great Thx
