### ISSUE TITLE
apoc.refactor.mergeNodes choose the result properties randomly

### ISSUE THREAD

**Issue by PeterKazmirsky** [neo4j-contrib/neo4j-apoc-procedures#1107]
**Guidelines**
Imagine that I have user cluster consisting of user ids from different data sources and all users are connected to one Root node. In case that user cluster contains more than one Root node I want to merge this Root nodes to one. For finding the Root nodes in cluster I am using apoc.path.subgraphNodes and the resulting Root nodes I am sending to apoc.refactor.mergeNodes to merge them to one Root node. I also set properties to procedure: mergeRels:true, properties:'overwrite'

**Actual Behavior**
I cannot influence in what order roots get into procedure apoc.refactor.mergeNodes, so after merging the result Root node and his relationships properties will have random properties. 

**Expected Behavior**
I would like you to consider to add feature to apoc.refactor.mergeNodes where I can tell for example that for merging property "count" choose highest one. Or for "date" property choose latest one. 
Thank you.

**Versions**
Neo4j 3.5.2
Apoc library 3.5.0.1

**Comment by jexp** [comment]
MergeNodes uses collection order
You can use apoc.coll.sort to sort by a key you like

**Comment by vga91** [comment]
With a simple dataset like:
```
create (r:Root), (r2:Root) with r, r2
create (r2)<-[:MyRel {prop: "prop1"}]-(n1:User{value:'node1'})-[:MyRel {prop: "prop11"}]->(r)
create (r2)<-[:MyRel {prop: "prop2"}]-(n2:User{value:'node2'})-[:MyRel {prop: "prop22"}]->(r)
create (r2)<-[:MyRel {prop: "prop3"}]-(n3:User{value:'node3'})-[:MyRel {prop: "prop33"}]->(r)
```

This could be solved in this way:

```
Match (r:Root) 
with collect(r) as nodes    // I CAN ORDER NODES HERE
CALL apoc.refactor.mergeNodes(nodes, {properties:'overwrite'}) YIELD node // NO mergeRels:true
WITH node 
match (node)-[r]-(user:User)
with user, collect(r) as rels   // I CAN ORDER RELS HERE
call apoc.refactor.mergeRelationships(rels, {properties: 'DISCARD'}) yield rel return rel
// with {properties: 'DISCARD'} we choose the first in order of appearance, otherwise the last
```
