### ISSUE TITLE
apoc.import.graphml - parse error loading from url

### ISSUE THREAD

**Issue by mrkarezina** [neo4j-contrib/neo4j-apoc-procedures#1109]
I am trying to load a GraphML dataset exported using the apoc.export.graphml.all procedure. I am trying to use the following query to load the dataset:
`CALL apoc.import.graphml('https://storage.cloud.google.com/vecgraph-demo/complete-graph.graphml?_ga=2.170348576.-1852699168.1549159460', {batchSize: 10000, storeNodeIds: false})`

This query works fine when I am importing a local graphML file, however I get en error when trying to load it from a URL. I tried google cloud and google drive with no luck.

This is the query used to export the dataset:
`CALL apoc.export.graphml.all('/Users/milanarezina/Desktop/complete-graph.graphml', {storeNodeIds:false})`

## Error

This is the cypher error after using the desktop client:

> Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `apoc.import.graphml`: Caused by: java.util.NoSuchElementException: ParseError at [row,col]:[1256,5]
> Message: The element type "meta" must be terminated by the matching end-tag "</meta>".

This is the full python traceback (Using py2neo client to execute the queries):

> Traceback (most recent call last):
>   File "/Users/milanarezina/PycharmProjects/Wyzefind/venv/lib/python3.6/site-packages/py2neo/internal/connectors.py", line 373, in run
>     raw_result = hydrator.hydrate_result(r.data.decode("utf-8"))
>   File "/Users/milanarezina/PycharmProjects/Wyzefind/venv/lib/python3.6/site-packages/py2neo/internal/hydration/__init__.py", line 433, in hydrate_result
>     raise HydrationError(*data["errors"])
> py2neo.internal.hydration.HydrationError: {'code': 'Neo.ClientError.Procedure.ProcedureCallFailed', 'message': 'Failed to invoke procedure `apoc.import.graphml`: Caused by: java.util.NoSuchElementException: ParseError at [row,col]:[1257,5]\nMessage: The element type "meta" must be terminated by the matching end-tag "</meta>".'}
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/milanarezina/PycharmProjects/Wyzefind/KnowledgeGraph/LoadGraphML.py", line 15, in <module>
>     graph.run(load_query)
>   File "/Users/milanarezina/PycharmProjects/Wyzefind/venv/lib/python3.6/site-packages/py2neo/database.py", line 526, in run
>     return self.begin(autocommit=True).run(cypher, parameters, **kwparameters)
>   File "/Users/milanarezina/PycharmProjects/Wyzefind/venv/lib/python3.6/site-packages/py2neo/database.py", line 805, in run
>     entities=entities))
>   File "/Users/milanarezina/PycharmProjects/Wyzefind/venv/lib/python3.6/site-packages/py2neo/internal/connectors.py", line 378, in run
>     raise GraphError.hydrate(e.args[0])
> py2neo.database.ClientError: ProcedureCallFailed: Failed to invoke procedure `apoc.import.graphml`: Caused by: java.util.NoSuchElementException: ParseError at [row,col]:[1257,5]
> Message: The element type "meta" must be terminated by the matching end-tag "</meta>".

**Comment by jexp** [comment]
Don't you think it's about public access of that URL? After all APOC doesn't have your google storage credentials.

**Comment by mrkarezina** [comment]
Oops, sorry about that, i'm signed into my browser so I forgot the procedure can't load from the google cloud url without my credentials.

However I also tried loading from a public google drive link and still get a parse error. This is the same dataset exported from the apoc.export.graphml.all: 
https://drive.google.com/open?id=1lILcfu6NWWExowkVlzf6-kl69PDQDf9k

Looking again this his parse error is different from the one from the google cloud link:
> Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `apoc.import.graphml`: Caused by: java.util.NoSuchElementException: ParseError at [row,col]:[1,1497]
Message: Open quote is expected for attribute "rel" associated with an  element type  "link".

I can't think of what to change since this is the data exported by the procedure.

**Comment by jexp** [comment]
Perhaps because the URL is loaded via https and the included XSD's are in http urls?
Just an idea.
Can you try to change them to https too?

**Comment by jexp** [comment]
Esp. as there is not even a link element or a rel-attribute in the XML.

**Comment by jexp** [comment]
If you try to load the URL you provided, e.g. with curl you see that google returns an HTML document.

**Comment by jexp** [comment]
If you use the download URL for your file instead:
`https://doc-0s-ac-docs.googleusercontent.com/docs/securesc/hkiqjo43r45ffla90dncj96p53hob1qm/f7oof2mditvujhb8lhfjtjto80i2ivc4/1551124800000/02563613019678398135/00082924217620195400/1lILcfu6NWWExowkVlzf6-kl69PDQDf9k?e=download&h=09716495216110682026&nonce=3o5t784hmdghm&user=00082924217620195400&hash=ngis499g3n46n6lji79om0lftu98lvcn`

it should work.

**Comment by mrkarezina** [comment]
Thank you so much for your help Michael. That was the issue. The import works now.
