### ISSUE TITLE
support streaming json with load json

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#111]
json objects separated by `\r`

**Comment by jexp** [comment]
Ping @lilianaziolek any progress? We really should get this in :)
Let me know if you need any support.

**Comment by lilianaziolek** [comment]
@jexp I really wish I could but I have a wedding in 2 weeks time and sooo much still to do... Feel free to grab what's there in my fork - but as we discussed, it was rather half baked, worked for me for what I needed but not exactly ready to push out to the world, sorry...
Other than "give me 24 more hours in a day" no other support would be needed ;)
