### ISSUE TITLE
Add some examples to apoc.custom.asFunction

### ISSUE THREAD

**Issue by Marc-Roth** [neo4j-contrib/neo4j-apoc-procedures#1110]
It would be nice to have some examples under [https://neo4j-contrib.github.io/neo4j-apoc-procedures/index35.html#_custom_functions_with_code_apoc_custom_asfunction_code](url)
For example using an array as input parameter, etc.

**Comment by Marc-Roth** [comment]
Got a simple example (though not working right now). 😄 

```
call apoc.custom.asFunction('GetClass',
  'match path=(:Class{root:true})-[:includes*1..]->(class:Class) where class.name in $names with path order by length(path) desc limit 1 return last(nodes(path)) as class','read',
  [['class','NODE']],[['names','LIST']]);

return custom.GetClass(["1st","2nd","3rd"]) YIELD neighbour;
```

**Comment by jexp** [comment]
Nice example! so you do software analytics?

What is not working? For the parameter can you try: `LIST STRING`

**Comment by Marc-Roth** [comment]
We're implementing solutions for midranged companies (mainly instustry sector) based on neo4j. Therefore we often need some common procedures that helps us getting f.e. material-class-trees or some bill of materials rendered to the frontend.

BTW - I've figured it out. 😃 
```
call apoc.custom.asFunction(
  'classes.getRoot',
  'match path=(:Class{root:true})-[:includes*1..]->(class:Class) where class.name in $names with path order by length(path) desc limit 1 return last(nodes(path)) as class',
  'MAP',
  [['names','LIST STRING']]
);

with custom.classes.getRoot(["1st","2nd","3rd"]) as class
return class
```

**Comment by jexp** [comment]
Oh sorry, right I didn't realize it was a function, not a procedure.
But odd that 'MAP' works, it should be 'NODE' imho.

**Comment by Marc-Roth** [comment]
I've also just tried the NODE parameter having the same result. But thanks for the tip!

**Comment by Marc-Roth** [comment]
... maybe one last thing, though it's a bit off topic. It would be great to have a list of all custom procedures and functions. Maybe something like ```call apoc.custom.procedures()``` or ```call apoc.custom.functions()``` inspired by ```call dbms.procedures()```

**Comment by sarmbruster** [comment]
there's already a request for this in #1104
