### ISSUE TITLE
Procedure for detecing cycles in graph

### ISSUE THREAD

**Issue by DirkMahler** [neo4j-contrib/neo4j-apoc-procedures#1115]
## Feature description (Mandatory)
There are many case where cycles in a graph need to be detected, e.g. in software analysis. It is possible to do so using Cypher but this has limitiations (see discussion https://community.neo4j.com/t/detecting-cycles-using-cypher/4944/6). A dedicated procedure would be a great help for that.

## Considered alternatives
A clear and concise description of any alternative solutions or features you've considered. Maybe there is something in the project that could be reused?

Cypher queries, see above.

## How this feature can improve the project?
If you can, explain how users will be able to use this and possibly write out a version the docs.
Maybe a screenshot or design?

**Comment by vga91** [comment]
[apoc-4.2.0.5-all.jar.zip](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/6854800/apoc-4.2.0.5-all.jar.zip)

@DirkMahler 
I've created a pr #2111 and attached here a `.jar` with this procedure, 
Please, can you try this jar and give a feedback?

To use this one, you can execute:
`CALL apoc.nodes.cycles(nodes, configMap)`, 
where `nodes` is a list of nodes to analyze to find the cycles.
In `configMap` you can insert:
- `relType` (The relationship type to detect cycles,  without this will be considered all rel-types ),
- `maxDepth` (The max number of steps to search for cycle, by default is `Integer.MAX_VALUE`).

So, for example, with a dataset
```
CREATE (m1:Start {bar: 'beta'}) WITH m1
CREATE (m1)-[:MY_REL {id: 9}]->(m2:Module {bar: 'three'})-[:MY_REL  {id: 10}]->(m3:Module {bar: 'four'})-[:MY_REL {id: 11}]->(m1)
```
you can execute:
```
MATCH (m1:Start) 
WITH collect(m1) as nodes 
CALL apoc.nodes.cycles(nodes, {relType: 'MY_REL'}) YIELD path RETURN path
```
that will return the previous path cycle (`m1 - m2 - m3 - m1`).
