### ISSUE TITLE
eo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `apoc.periodic.iterate`: Caused by: java.lang.ArrayIndexOutOfBoundsException: 131

### ISSUE THREAD

**Issue by mckenzma** [neo4j-contrib/neo4j-apoc-procedures#1121]
## Expected Behavior (Mandatory)
I am attempting to use `apoc.period.iterate` to load data from URLs and create nodes. I have a long list of URLs in a Google Sheet (~1300).

## Actual Behavior (Mandatory)
I keep receiving the following error message:
```
eo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `apoc.periodic.iterate`: Caused by: java.lang.ArrayIndexOutOfBoundsException: 131
```
after running the code shown below.

## How to Reproduce the Problem

See ###Steps below

### Simple Dataset

See ###Steps below

### Steps

1. Run the following query to load URL data from a shared Google Sheets document
```
CALL apoc.periodic.iterate(
'
CALL apoc.load.csv("https://docs.google.com/spreadsheets/d/1sFcY7LFBCGXSFG336UPoOf72BBv3bmv_AVaYLxwiV4A/export?format=csv&id=1sFcY7LFBCGXSFG336UPoOf72BBv3bmv_AVaYLxwiV4A&gid=1318941318") YIELD map AS row RETURN row
row RETURN row
','
WITH CASE
	WHEN NOT row.Year IS NULL THEN collect(row.URL)
    END AS fileURLs
UNWIND fileURLs AS fileURL
CREATE (url:URL {url: fileURL})
',
{batchSize: 100, parallel:false})

```

2. Once populated, run the following to query the URL nodes to try and load the data from the url property
```
MATCH (url:URL)
WHERE NOT url.url CONTAINS "nbi//"
WITH collect(url.url) AS fileURLS
UNWIND fileURLS AS fileURL
WITH fileURL
//RETURN fileURL
CALL apoc.periodic.iterate(
'
CALL apoc.load.csv($url) YIELD map AS row RETURN row
','
MERGE (state:State {id: row.STATE_CODE_001})
ON CREATE SET state.name = row.STATE_CODE_001
',
{batchSize:1000, parallel:false, params:{url:fileURL}}) YIELD batches, total
RETURN batches, total
```
## Specifications (Mandatory)

Neo4j Cloud

### Versions
Neo4j Cloud

**Comment by jexp** [comment]
Seems to be a data issue in:

`call apoc.load.csv('https://www.fhwa.dot.gov/bridge/nbi/2010/delimited/AL10.txt')`

try to use load csv instead of apoc.load.csv will have to investigate

`load csv with headers from 'https://www.fhwa.dot.gov/bridge/nbi/2010/delimited/AL10.txt' as row return row`

that works

**Comment by mckenzma** [comment]
Ok. Thank Michael. I will move ahead with `LOAD CSV`. I hope you can figure
out the problem.
