### ISSUE TITLE
[Question] Using apoc.import.csv to import csv created by apoc.export.csv.all

### ISSUE THREAD

**Issue by OhBonsai** [neo4j-contrib/neo4j-apoc-procedures#1122]
HI:
     I used `call apoc.export.csv.all("/tmp/neo/all.csv", {});`  in neo4j3.3. 
      How can I import `all.csv` into anthor neo4j 3.5 instance?
     I can't find answer in [apoc doc csv import ](https://neo4j-contrib.github.io/neo4j-apoc-procedures/#export-import)

**Comment by jexp** [comment]
It won't be in the 3.3 release but for newer versions we have a roundtrip setting for `apoc.export.csv.all`

Perhaps apoc.export.cypher works for you for the time being. Depending on how large your graph is.

**Comment by OhBonsai** [comment]
Ehh.. I found this way to solve my problem ... 
I just wanna copy data from lower version neo4j to higher version

I can use this command to dump data
```CALL apoc.export.graphml.all('/tmp/all.graphml', {})```
Then import data by this
```
CALL apoc.import.graphml('/tmp/all.graphml', {batchSize: 10000})
```
