### ISSUE TITLE
return apoc.text.phonetic should be documented as call apoc.text.phonetic

### ISSUE THREAD

**Issue by umuzammil** [neo4j-contrib/neo4j-apoc-procedures#1123]
Version 3.5.0 and 3.5.3 Enterprise
Apoc version 3.5.0.2 (apoc-3.5.0.2-all.jar)

This appears to be an error in our documentation. The procedure should be run as CALL apoc.text.phonetic('Hello, dear User!') rather than return apoc.text.phonetic('Hello, dear User!').

CALL apoc.text.phonetic('Hello, dear User!') returns H400D600U260 as desired.

**Comment by umuzammil** [comment]
dear guys, any updates please?

**Comment by albertodelazzari** [comment]
Hi, I think should be the opposite, the procedure should be changed in order to be a user function and the documentation should be left as it is.

**Comment by jexp** [comment]
Already done
