### ISSUE TITLE
Control Gephi property transfer

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#113]
configure property-filters or transfer all properties for nodes and relationships
would require an additional config parameter to the procedure

**Comment by svidela** [comment]
Does this refer to the fact that nodes in Neo4j must have a 'name' property which is used as node label in Gephi? Just checking to avoid a duplicated issue

**Comment by maddoc1** [comment]
Any news on this? currently I can stream to Gephi only properties named 'name', all other properties are ignored.

**Comment by fbiville** [comment]
https://neo4j.com/labs/apoc/4.1/overview/apoc.gephi/apoc.gephi.add/ now include a property list as parameter.
