### ISSUE TITLE
docs: example empty in  "Custom Functions with apoc.custom.asFunction" section

### ISSUE THREAD

**Issue by sarmbruster** [neo4j-contrib/neo4j-apoc-procedures#1139]
there is a example box but it's empty

**Comment by sarmbruster** [comment]
![Bildschirmfoto vom 2019-03-28 13-44-55](https://user-images.githubusercontent.com/106522/55158797-05f28180-5160-11e9-8a92-01b8f215968a.png)

**Comment by conker84** [comment]
we now have examples
