### ISSUE TITLE
Add relationship exclusion to apoc.path.. options

### ISSUE THREAD

**Issue by stuartlaurie** [neo4j-contrib/neo4j-apoc-procedures#1145]
Can we add a feature to apoc.path.. not to follow certain relationships? 

Currently we have the ability to define `-NodeLabel` but it would be great to be able to specify `-RelationshipLabel`

The scenario being that if i say have 30 unique relationships labels i'd like to say follow all but e.g. 2 of them. Right now, we'd have to define 28 rels to be able to do the same

**Comment by awesomeskyfantasy** [comment]
totally agree!
