### ISSUE TITLE
Download link on https://neo4j-contrib.github.io/neo4j-apoc-procedures is incorrect

### ISSUE THREAD

**Issue by aldrinm** [neo4j-contrib/neo4j-apoc-procedures#1148]
## Expected Behavior (Mandatory)
Link to the latest release at https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_installation_with_neo4j_desktop should take me to the latest released

## Actual Behavior (Mandatory)
Links goes to http://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/3.5 which is a 404

It works fine at https://github.com/neo4j-contrib/neo4j-apoc-procedures itself, just not on https://neo4j-contrib.github.io/neo4j-apoc-procedures

### Steps (Mandatory)

  1. Go to https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_installation_with_neo4j_desktop

  1. Click the "the latest release" 

### Versions
3.5

**Comment by jexp** [comment]
Should be fixed. Thanks for reporting.
