### ISSUE TITLE
request apoc.load.json not hard fail if url results in 404

### ISSUE THREAD

**Issue by Dcanzano** [neo4j-contrib/neo4j-apoc-procedures#1149]
## Guidelines

when using apoc.load.json and it is called from the results of a match (n:URLS) with n.url as url call apoc.load.json(url) ......  if for some reason one of the urls results in a 404 then the entire match is aborted.  Is there a way to make apoc.load.json not fail or not hard fail

## How this feature can improve the project?
If you can, explain how users will be able to use this and possibly write out a version the docs.
Maybe a screenshot or design?

**Comment by WyrdNexus** [comment]
That doesn't provide an opportunity to do anything about the error.

**Comment by jexp** [comment]
It should return null i think or probably nothing.
you could wrap it in an apoc.cypher.run and return a collect(value) from there
and then react on the (non-)empty list.

for the time being
