### ISSUE TITLE
Add algorithms

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#116]
- [ ] k-means (for top-n)
- [ ] edge betweenness
- [ ]  Bellman-Ford algorithm
- [ ] approximation of the Chromatic Number of a graph
- [ ] approximation of Hamiltonian cycle
- [ ] min cut
- [ ] community detection: louvain, walk trap, infomap, label propagation

**Comment by smartinsightsfromdata** [comment]
Hi

What is the status of the above algos? I'm personally interested in Bellman-Ford. 

As my plan would be ultimately to tweak it to my needs, it would be great to have a template to play with.

**Comment by jexp** [comment]
We continue the algorithm development here: http://github.com/neo4j-contrib/neo4j-graph-algorithms

See the issues listed there and their progress.
