### ISSUE TITLE
Why APOC (apoc-3.4.0.5-all.jar) not able to load in neo4j community edition

### ISSUE THREAD

**Issue by yuyongqiang1** [neo4j-contrib/neo4j-apoc-procedures#1160]
After I put the APOC in the `neo4j\plugins`，I can not  setup neo4j ，though I tried it many times.
My environment is:
Windwos10、NEO4J Community edition 3.5.4 ；apoc-3.4.0.5-all
the content of `service-error.log` is:

2019-04-10 20:48:53 Commons Daemon procrun stderr initialized
传递给系统调用的数据区域太小。
Failed to start service

**Comment by jexp** [comment]
Wrong apoc version. 

Use the latest that starts with 3.5

**Comment by yuyongqiang1** [comment]
After using the  apoc-3.5.0.2, Neo4j is  successfully launched.Thank you very much for your reply！
