### ISSUE TITLE
Please create an automated command-line install script

### ISSUE THREAD

**Issue by neils-s** [neo4j-contrib/neo4j-apoc-procedures#1167]
Feature description:
A script file to handle all installation steps for Apoc would be nice.  This script should be OS-agnostic; it should handle all version-matching decisions; and it should automatically update the neo4j.conf file (maybe using command-line arguments).
This script would be the command-line analog of the "Install Plugin" button in the Neo4j desktop UI.
I'm aware that an OS-agnostic script is a big challenge.  Ideally, there would be plugin maintenance commands inside the "neo4j-admin" shell command.  Optionally, a .jar file could be invoked to install the Apoc plug-in.

How this feature can improve the project:
By having a command-line option that easily installs APOC, it would make it trivial to deploy APOC as part of a build script.  This is nice when maintaining multiple  Neo4j servers with different Neo4j versions running on different AWS instances which use different OSes.

Considered alternatives:
Without a single-step shell command, automated installation of APOC using a tool like Ansible is pretty tricky.  The main challenge is maintaining the version-compatibility matrix so the right version of APOC is downloaded and installed in the $NEO4J_HOME/plugins directory.

**Comment by jexp** [comment]
Desktop and Cloud use both `https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json`

so in a shell script you could use:

```
apoc_jar=`curl -s 'https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json' | grep 3.5.4 -A 3 | tail -1 | cut -d '"' -f 4`
 curl -OsL $apoc_jar
```

**Comment by neils-s** [comment]
That's a great idea!  However, I don't know if it will work for me.  I should mention that I'm running on a windows box, so curl and grep aren't accessible.
I do like the version crosswalk in the JSON file, though.  That's cool!

The "Install" button in the Neo4j desktop manager makes it so easy to install Apoc from the GUI side.  It would be nice if it were as easy from the command line as well.

**Comment by conker84** [comment]
@neils-s you can use `cURL` in windows too, and you can replace `grep` with `findstr`
