### ISSUE TITLE
Review tests evaluation in ExportCsvTest

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-apoc-procedures#1176]
Now tests are based on string evaluation.
Consider switching to lists, map, set, linked maps... in order to simplify the testing process

**Comment by vga91** [comment]
Because of `quotes` configuration, in the tests it is necessary to understand if the lines of the `.csv` have the quotes. 
It wouldn't be possible by parsing the strings into maps / lists / ...
