### ISSUE TITLE
APOC 3.5.0.3 changes import file URL paths too aggressively

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-apoc-procedures#1181]
## Expected Behavior (Mandatory)

```
call apoc.metrics.get("neo4j.bolt.sessions_started");
```

Should return metric data in Neo4j Desktop installations.

## Actual Behavior (Mandatory)

```
Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `apoc.metrics.get`: 

Caused by: java.io.FileNotFoundException: 
/Users/davidallen/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-6df59434-8fe6-405c-ab17-dd0a913b1498/installation-3.5.4/import/Users/davidallen/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-6df59434-8fe6-405c-ab17-dd0a913b1498/installation-3.5.4/metrics/neo4j.bolt.sessions_started.csv 
(No such file or directory)
```

## How to Reproduce the Problem

(Run above query)

## Cause

In `apoc.metrics.Metrics.loadCsvForMetric`, great care is taken to build an absolute directory reference to the location of metrics, taking into account neo4j config.  This is done by `FileUtils.getMetricsDirectory`.    But when this absolute URL gets passed to the LoadCsv methods, it appears to use `FileUtils.changeFileUrlIfImportDirectoryConstrained` which seems to be appending the absolute directory as a relative to the import path.

The result is an ultra-long local URL which is wrong, causing the file not to exist, causing the metrics load to fail.

**Comment by conker84** [comment]
@moxious can you please try with this jar?
[apoc-3.5.0.3-all.jar.zip](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/3148165/apoc-3.5.0.3-all.jar.zip)
Looking forward to your feedback!

**Comment by moxious** [comment]
@conker84 this seems to have fixed the path bug but introduced a different one.   Now I get this:

```
Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `apoc.metrics.get`: Caused by: java.io.IOException: Stream closed
```

You can reproduce by running:

```call apoc.metrics.get("neo4j.bolt.sessions_started");```

**Comment by conker84** [comment]
@moxious Can you please share your configuration? I can't reproduce the problem

**Comment by moxious** [comment]
@conker84 

neo4j 3.5.4 running in desktop

```
$ md5 plugins/apoc-3.5.0.3-all.jar 
MD5 (plugins/apoc-3.5.0.3-all.jar) = f86abbeae01ae3a151594822b844fba5
```

(This should be the file you provided above in this thread)

Config:

```
metrics.prometheus.enabled=true
metrics.prometheus.endpoint=localhost:2004

apoc.import.file.enabled=true
dbms.security.procedures.unrestricted=apoc.*
```

The config was generated by creating an empty neo4j 3.5.4 in desktop, clicking to install the APOC plugin (which changes config for you) -- and then replacing the JAR that desktop uses with the one you provided.
