### ISSUE TITLE
apoc.merge.node() does not update node properties when matching to existing node

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j-contrib/neo4j-apoc-procedures#1182]
## How to Reproduce the Problem
On an empty database using APOC 3.5.0.3 execute the following:

CREATE (p:Person{ssid:'123', name:'Jim'}) 
CALL apoc.merge.node(['Person'],{ssid:'123'}, {name:'John'}) YIELD node RETURN node 

## Expected Behavior

Since the identProps argument is `ssid:'123'`, this should match to the just-created Jim node. The name property should be updated to 'John', as we would expect if running this Cypher equivalent:

```
MERGE (node:Person {ssid:'123'})
SET node.name = 'John'
```

## Actual Behavior (Mandatory)

The MERGE indeed matched to the existing Jim node (no new node was created), but the name property was not updated.  

## Other Notes

Looking at the PR for this, it looks like this behavior was intentional (see [testMergeNodeWithPreExisting()](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/508/files#diff-0357b9c1505ecd881eaaa564ca7e2107R47), though there doesn't seem to be any documentation about this behavior, nor does it seem intuitive (this would behave like an ON CREATE SET).

### Versions

  - OS: Mac OS 10.12.6
  - Neo4j: 3.5.4 Enterprise
  - Neo4j-Apoc: 3.5.0.3

**Comment by jexp** [comment]
This is because of the non-eagerness of the procedure right now.

You can add eager=true to the proc but of course that changes behavior.

**Comment by InverseFalcon** [comment]
`apoc.merge.node.eager()` and `apoc.merge.relationship.eager()` have been committed and are present in the recent APOC 3.5.0.4 release.

These procedures allow separate maps for setting properties ON MERGE or ON MATCH. Additionally, the procedures allow merging to multiple nodes or relationships, where the older procs would error out.

Documentation has yet to be added in, but you can check the signatures via this call:

`call apoc.help('.eager')`
