### ISSUE TITLE
apoc.export.csv.query() does not register duration.inSeconds formatting

### ISSUE THREAD

**Issue by edtky** [neo4j-contrib/neo4j-apoc-procedures#1184]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Expected Behavior (Mandatory)

`CALL apoc.export.csv.query(" ... ... RETURN duration.inSeconds(a.timeStamp, b.timeStamp) ..." )`
should return "P0M0DT2651S" in the csv file (only seconds)

## Actual Behavior (Mandatory)

wrongly returns "PT44M11S" in csv file (minutes and seconds)
(when queried directly on Neo4j, it correctly returns "P0M0DT930S" on the dashboard)

### Simple Dataset (where it's possible)

```
//Insert here a set of Cypher statements that helps us to reproduce the problem

```

### Steps (Mandatory)

  1.
  1.
  1.

## Screenshots (where it's possible)

![Screen Shot 2019-04-28 at 11 31 00 AM](https://user-images.githubusercontent.com/35285568/56869415-4cccd480-69b5-11e9-88e1-a87dec7e27ef.png)

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS:
  - Neo4j:
  - Neo4j-Apoc:

**Comment by vboulaye** [comment]
Hi,
I tried to work on this issue.
I managed to reproduce it (I made a test in dba589c95267db960d86c7ae41ad260a9359a96b).

But I cannot figure out how the dashboard is working: the output from csv.query is calling the `toString()` from ` DurationValuè` which is always computing an hour/minute component from the seconds in the duration.

**Comment by enriquezrene** [comment]
@vboulaye 
The issue is DurationValue.toString is invoking prettyPrint() which transforms seconds to hours, minutes.

**Comment by enriquezrene** [comment]
I think the following PR might work https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/1322 
I took the changes from your commit. @vboulaye

**Comment by fbiville** [comment]
> I managed to reproduce it (I made a test in [dba589c](https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/dba589c95267db960d86c7ae41ad260a9359a96b)).

Based on a slightly updated variant of this test, the Java API of Neo4j and Cypher-Shell return 1 value: `"PT9H5M35.353S"`.
Neo4j Browser returns another `P0M0DT32735.353000000S`.
It might be a driver issue.

**Comment by conker84** [comment]
@fbiville any news on this?
