### ISSUE TITLE
apoc.load.xml not working on specific API's 

### ISSUE THREAD

**Issue by fnfbraga** [neo4j-contrib/neo4j-apoc-procedures#1185]
## Expected Behavior (Mandatory)

WITH 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pmc&id=212403' as url
CALL apoc.load.xml(url, '',{}, false) yield value
return value

should return a xml 

## Actual Behavior (Mandatory)

returns error:

Neo.ClientError.Procedure.ProcedureCallFailed
Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `apoc.load.xml`: Caused by: org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 10; DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.

## Specifications (Mandatory)

Using the same query in a previous version of neo4j and apoc will return the values.

Currently used versions

neo4j v3.5.0.4 
apoc v3.5.0.3

**Comment by jexp** [comment]
We had to disable doctypes for security reasons. 
See
https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/931

There might be a more elaborate fix, but we would need to investigate this further.

**Comment by fnfbraga** [comment]
thank you, Michael. Yes, it would be great if there is any workaround like adding the ability to set a boolean or a configuration option to enable doctypes in the parser? For now, I will resort to an older APOC version.

**Comment by sarmbruster** [comment]
My guess is that a custom entityresolver to ignore DTD should do it as sketched on https://stackoverflow.com/a/155353/158701
@jexp do you agree?

**Comment by jexp** [comment]
Yep

**Comment by taseroth** [comment]
took the idea from @sarmbruster and implemented it in a pull request: https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/1208

be gentle, it is my first ;-)
