### ISSUE TITLE
Intermittent issues with apoc.load.jsonParams()

### ISSUE THREAD

**Issue by weslexcore** [neo4j-contrib/neo4j-apoc-procedures#1186]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Expected Behavior (Mandatory)
Calling `apoc.load.jsonParams()` should work consistently. Should fetch json from the given url and yield values.

## Actual Behavior (Mandatory)
Calling `apoc.load.jsonParams()` fails 50+% of the times that it is called giving the error -
```
Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `apoc.load.jsonParams`: 
Caused by: java.lang.RuntimeException: Can't read url or key https://MYURL as json: 
Remote host closed connection during handshake 
```

### Steps (Mandatory)

  1. Run neo4j 3.5.4 Community in docker
  1. Use neo4j browser to call `apoc.load.jsonParams()` procedure
  1. Call procedure it works
  1. Call procedure, it fails

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: OSX Mojave 10.14.4
  - Neo4j: 3.5.4 Community
  - Neo4j-Apoc: 3.5.0.3

**Comment by jexp** [comment]
Do you have more specifics about the url that’s called 

This sounds more like a network issue. 

Can you try to use that url from inside the container with curl repeatedly?

**Comment by weslexcore** [comment]
Hey @jexp, thanks for the quick response! When I curl it, I get the same result. Sometimes succeeds, sometimes fails. The error given from curl shows that there is an SSL error? Strange that it is only occurring some of the time - any idea on how I should continue troubleshooting?

```
* Expire in 2 ms for 1 (transfer 0x557d58bf47a0)
* Expire in 0 ms for 1 (transfer 0x557d58bf47a0)
* Expire in 0 ms for 1 (transfer 0x557d58bf47a0)
* Expire in 2 ms for 1 (transfer 0x557d58bf47a0)
* Expire in 0 ms for 1 (transfer 0x557d58bf47a0)
* Expire in 0 ms for 1 (transfer 0x557d58bf47a0)
* Expire in 2 ms for 1 (transfer 0x557d58bf47a0)
* Expire in 0 ms for 1 (transfer 0x557d58bf47a0)
* Expire in 0 ms for 1 (transfer 0x557d58bf47a0)
* Expire in 2 ms for 1 (transfer 0x557d58bf47a0)
* Expire in 0 ms for 1 (transfer 0x557d58bf47a0)
* Expire in 0 ms for 1 (transfer 0x557d58bf47a0)
* Expire in 2 ms for 1 (transfer 0x557d58bf47a0)
* Expire in 0 ms for 1 (transfer 0x557d58bf47a0)
* Expire in 0 ms for 1 (transfer 0x557d58bf47a0)
* Expire in 0 ms for 1 (transfer 0x557d58bf47a0)
*   Trying **IP**...
* TCP_NODELAY set
* Expire in 149999 ms for 3 (transfer 0x557d58bf47a0)
* Expire in 200 ms for 4 (transfer 0x557d58bf47a0)
* Connected to MYURL (**IP**) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to MYURL:443 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to MYURL:443 
```

**Comment by weslexcore** [comment]
I appear to have found the issue - it has to do with a bug in alpine linux distro's > 3.4
https://bugs.alpinelinux.org/issues/9948

When I changed my dockerfile to use alpine 3.4 the issue disappeared. 

Here is the top of my dockerfile for anyone facing similar problems - 
```
FROM alpine:3.4

ENV LANG C.UTF-8
RUN { \
		echo '#!/bin/sh'; \
		echo 'set -e'; \
		echo; \
		echo 'dirname "$(dirname "$(readlink -f "$(which javac || which java)")")"'; \
	} > /usr/local/bin/docker-java-home \
	&& chmod +x /usr/local/bin/docker-java-home
ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk/jre
ENV PATH $PATH:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin

ENV JAVA_VERSION 8u201
ENV JAVA_ALPINE_VERSION 8.111.14-r0

RUN set -x \
	&& apk add --no-cache \
		openjdk8-jre="$JAVA_ALPINE_VERSION" \
	&& [ "$JAVA_HOME" = "$(docker-java-home)" ]

########## Can replace the above with FROM openjdk:8-jre-alpine when bug is fixed https://bugs.alpinelinux.org/issues/9948
```

**Comment by weslexcore** [comment]
@jexp I was able to find a permanent solution. Changing my Neo4j Dockerfile to use `FROM openjdk:8-jdk-alpine` instead of `jre-alpine`removed all issues

**Comment by jexp** [comment]
Great thanks for the update, closing this issue.
