### ISSUE TITLE
add apoc function `apoc.map.get(map, 'name',[default])`

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#1190]
which fails if the key doesn't exist.

optionally it can provide a default value

and a variant for multiple values

`apoc.map.mget(map, ['names'],[defaults]) -> list`
`apoc.map.submap(map, ['names'],[defaults]) -> map`

**Comment by eastlondoner** [comment]
Truly this would be fantastic to have
