### ISSUE TITLE
Add ignoreQuotations configuration to apoc.load.csv

### ISSUE THREAD

**Issue by alexiudice** [neo4j-contrib/neo4j-apoc-procedures#1194]
### Feature description
The apoc.load.csv method lacks the ability to completely ignore quotes. This is problematic when you want to load in a CSV row which opens a quote but does not close it, as doing this results in an error. This occurs even when the quote is escaped using the escape character. This feature would allow CSV rows with quotes to be loaded in, ignoring the quotes entirely. If one would still like the quotes to be present in the loaded row, but not act as a special quote character, they can then use the escape character.

A solution to this would make use of the CSVReaderBuilder's built in ignoreQuotations by adding a ignoreQuotations field to the LoadCsvConfig.

#### Alternative
An alternative solution I originally thought of would be using an empty string in the quoteChar field. However, doing this automatically assigns the default quote character which is the double quote, so it does not work.

**Comment by jexp** [comment]
Merged your PR, thanks a lot.
