### ISSUE TITLE
Add RFC Date Support and add date conversion support

### ISSUE THREAD

**Issue by alexiudice** [neo4j-contrib/neo4j-apoc-procedures#1203]
1. The date format `RFC_1123_DATE_TIME` is missing from the DateFormatUtil despite being supported by the underlying DateTimeFormatter class. Adding this date format is a single line.

2. Along with this, an apoc.date (or apoc.temporal) method to convert String date formats is missing, though there is one for Long date formats. The method should convert a String of one date format into a String of another date format.

The function header should have an input, a string currentFormat, and a string convertToFormat parameter. 
``` 
apoc.date.convertFormat('Tue, 14 May 2019 14:52:06 -0400', 'rfc_1123_date_time', 'iso_date_time')
```

This would turn the string `Tue, 14 May 2019 14:52:06 -0400` into the string `2019-05-14T14:52:06-04:00`.

**Comment by jexp** [comment]
Fixed
