### ISSUE TITLE
Some leaf node in the apoc.convert.toTree are missing properties

### ISSUE THREAD

**Issue by panchalchetan** [neo4j-contrib/neo4j-apoc-procedures#1205]
I have scenario where my leaf node property only available to the last member of list. 
here is data node relation 

(Department)-[:SUBBEPART_MEMBER_OF_DEPARTMENT]->(SubDepart)-[:SUBBEPART_MEMBER_OF_SUBBEPART]->(SubDepart)-[:SKILL_MEMBER_OF_SUBBEPART]->(Skill)

(Department)-[:SKILL_MEMBER_OF_DEPARTMENT]->Skill)
 in my case some root **Skill** nodes are common between two **SubDepart** nodes and 
below query return SkillType relationship data to my last item node only. 

here is my query to get data using apoc.convert.toTree. 

MATCH (cm:Department)
WHERE cm.Id IN [
  2
]
CALL apoc.path.expand(cm,'<SUBBEPART_MEMBER_OF_DEPARTMENT|<SUBBEPART_MEMBER_OF_SUBBEPART|<SKILL_MEMBER_OF_SUBBEPART|<SKILL_MEMBER_OF_DEPARTMENT','+SubDepart|Skill',0,10) YIELD path
WITH path, tail(NODES(path)) as pathSubDepart, last(NODES(path)) as skill, REDUCE(x = cm.Id, n IN tail(NODES(path)) | x + '/' + n.Id) as xPath
UNWIND pathSubDepart  AS subdepart
WITH path, subdepart, skill, xPath
WHERE skill:Skill
OPTIONAL MATCH department_skill_object = (subdepart)-[:SKILL_OBJECT_TYPE]->(dType:DepartmentSkillType)
WHERE subdepart:SubDepart

OPTIONAL MATCH person_skill_type = (skill)-[:SKILL_TYPE]->(pSkillType:SkillType) 

WITH (COLLECT(path) + COALESCE(COLLECT(person_skill_type),[]) +COALESCE(COLLECT(department_skill_object),[])) as paths

CALL apoc.convert.toTree(paths) yield value
WITH COLLECT(distinct value) as DepartmentData
UNWIND DepartmentData AS result
RETURN result

### Specifications (Mandatory)
Using the same query in a previous version of neo4j 3.4.7 and apoc 3.4.0.0 will return the values.

Currently used versions not returning correct data
neo4j v3.5.0.4
apoc v3.5.0.3

**Comment by conker84** [comment]
Hi @panchalchetan please, can you share a sample dataset in order to reproduce the problem?

**Comment by jexp** [comment]
Closing this because no response since May, please reopen if you have the information.
