### ISSUE TITLE
No log output when import from cypher encounters an error

### ISSUE THREAD

**Issue by eastlondoner** [neo4j-contrib/neo4j-apoc-procedures#1210]
## Expected Behavior (Mandatory)

I create a cypher script following the instructions here: https://medium.com/neo4j/efficient-neo4j-data-import-using-cypher-scripts-7d1268b0747

When I then run that cypher script to import data into an empty database if an error is encountered I expect the log output to indicate at least what the last successful transaction was, so I can work out which cypher command failed and figure out what to do about it.

i.e.
```
$ cypher-shell -u neo4j -p "my password" < '/import/exportDataCypherShellParams.cypher' > 'import/output.exportDataCypherShellParams.log'
some error happened
$ tail 'import/output.exportDataCypherShellParams.log'
Attempting CREATE(foo) ...

## Actual Behavior (Mandatory)
```
$ cypher-shell -u neo4j -p "my password" < '/import/exportDataCypherShellParams.cypher' > 'import/output.exportDataCypherShellParams.log'
Could not apply the transaction to the store after written to log
$ wc -l 'import/output.exportDataCypherShellParams.log'
0 import/output.exportDataCypherShellParams.log
```
In this case 47k nodes and 200k relations have been created successfully, so the failing transaction certainly wasn't the first one. 

## How to Reproduce the Problem

manually insert some cypher that will fail on the server (e.g. divide by zero) into a multi line cypher statement?

### Simple Dataset (where it's possibile)
na

### Steps (Mandatory)

1. export to cypher
2. import from cypher encounters error part way through
3. examine "log"

## Specifications (Mandatory)

log should have something in

**Comment by eastlondoner** [comment]
I think that the instructions on the linked blog post should include setting the `--debug` flag when running cypher-shell

**Comment by jexp** [comment]
Fixed in the article.

**Comment by jexp** [comment]
Adding it to the docs too.
