### ISSUE TITLE
Enable cypher access to Lucene's MoreLikeThis functionality

### ISSUE THREAD

**Issue by mojo2go** [neo4j-contrib/neo4j-apoc-procedures#1216]
As of Neo4j 3.5 a fulltext search index is baked into Neo4j. It’s the stock Apache Lucene, version 5.5.5. Lucene supports a class of queries called MoreLikeThis. Given a text document this feature will return the most similar documents to it.  It uses a robust implementation of similarity with a vector space model called [TF-IDF](https://en.wikipedia.org/wiki/Tf–idf).  

In Neo4j such a collection of documents might best be represented by a set of node property names that can span node labels.  
For example when creating the index you might supply corresponding properties across multiple node labels.
```
label: Article   property: Author   boost: 4
label: Article   property: Title    boost: 2
label: Article   property: Body     boost: 1
label: Book      property: Author   boost: 4
label: Book      property: Title    boost: 2
label: Book      property: Body     boost: 1
```
[Here](https://dzone.com/articles/lucene-morelikethis-example) is an example of implementation.

**Comment by sarmbruster** [comment]
@mojo2go I've added experimental support of "MoreLikeThis" in a branch residing in my fork. Could you please take a look at https://github.com/sarmbruster/neo4j-apoc-procedures/blob/neo4j-apoc-procedures-1216/src/test/java/apoc/index/fulltext/MoreLikeThisTest.java ?
If it helps I can provide a snapshot build so you can run your own tests.
Please note that I'll add docs once we finalized the implementation.

**Comment by sarmbruster** [comment]
@mojo2go bump

**Comment by mojo2go** [comment]
Hi Stefan,
So sorry for the long wait.  I lost track of this.  I would love to test it.  Are you still able to make a snapshot build for me?  We'll test it.
Thanks!
Joe

**Comment by conker84** [comment]
I'm closing this due to lack of feedback, feel free to reopen in with new details
