### ISSUE TITLE
Failed to invoke procedure `apoc.gephi.add`: Caused by: java.lang.RuntimeException: Can't read url or key

### ISSUE THREAD

**Issue by mluired** [neo4j-contrib/neo4j-apoc-procedures#1228]
## Guidelines

I am using the following CYPHER CODE. Before I created Nodes Users and relationships. 

MATCH path = (:Usuario)-[:meets]->(:User)
CALL apoc.gephi.add("http://localhost:7474",'workspace1',path) yield nodes
return *

## Expected Behavior (Mandatory) vs Actual Behavior (Mandatory)

I should receive the graph in GEPHI but not received. 

Instead I receive the following error:

Neo.ClientError.Procedure.ProcedureCallFailed
Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `apoc.gephi.add`: Caused by: java.lang.RuntimeException: Can't read url or key http://localhost:7474/workspace1?operation=updateGraph as json: cannot retry due to server authentication, in streaming mode

### Steps (Mandatory)

  1. I have added in C:\Neo4J\conf the following statements:
     dbms.directories.plugins=plugins
     dbms.security.procedures.whitelist=apoc.coll.*,apoc.load.*, apoc.*
     dbms.security.procedures.unrestricted=apoc.*
  2. I have downloaded plugin Graph Streaming in GEPHI. Started the server with HTTP settings. No autnentication included. Server port in GEPHI 8080. Server port in Neo4J 7687.
  3. I have included Plugin in /Plugin folder. 

Currently used versions

### Versions

  - OS: Windows 10 
  - Neo4j: Neo4j release 3.5.6 Community. 
  - Neo4j-Apoc: apoc-3.5.0.4

**Comment by jexp** [comment]
The URL needs to be the gephi URL not the Neo4j one.

**Comment by mluired** [comment]
Sorry, I am completely lost with your comment. Would you mind explaining more about what you are referring to? 
Thanks in advance.

**Comment by conker84** [comment]
@mluired please be sure that you followed what is explained here:
http://neo4j-contrib.github.io/neo4j-apoc-procedures/#gephi
Thanks a lot!

**Comment by conker84** [comment]
I'm closing this due to lack of feedback
