### ISSUE TITLE
apoc.initializer.cypher didn't work as expexcted

### ISSUE THREAD

**Issue by neo4j-apac** [neo4j-contrib/neo4j-apoc-procedures#1231]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Expected Behavior (Mandatory)

I added this line in neo4j.conf:
apoc.initializer.cypher=CALL apoc.log.info("Some logging info")
in the expectation of seeing the logging info displayed on screen or recorded in log file. 

## Actual Behavior (Mandatory)

Neo4j server failed to start up due to the errors below: 

Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.String.substring(Unknown Source)
    at apoc.util.Util.subMap(Util.java:218)
    at apoc.ApocConfiguration.get(ApocConfiguration.java:52)
    at apoc.cypher.CypherInitializer.available(CypherInitializer.java:22)
    at org.neo4j.helpers.Listeners.notifySingleListener(Listeners.java:145)
    at org.neo4j.helpers.Listeners.notify(Listeners.java:101)
    at org.neo4j.kernel.availability.DatabaseAvailabilityGuard.fulfill(DatabaseAvailabilityGuard.java:90)
    at org.neo4j.kernel.availability.DatabaseAvailability.start(DatabaseAvailability.java:59)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)

## How to Reproduce the Problem

Add the configuration line above into neo4j.conf. 

### Simple Dataset (where it's possibile)

```
//Insert here a set of Cypher statements that helps us to reproduce the problem

```

### Steps (Mandatory)

  1.
  1.
  1.

## Specifications (Mandatory)

apoc 3.5.0.2 on neo4j 3.5.5

### Versions

  - OS:
  - Neo4j:
  - Neo4j-Apoc:

**Comment by sarmbruster** [comment]
any easy workaround is to amend `.1` even if you only one one initializer:
`apoc.initializer.cypher.1=CALL apoc.log.info("Some logging info")`

**Comment by neo4j-apac** [comment]
It didn't work on my computer: 

error upon initialization, running: CALL apoc.log.info("Some logging info") There is no procedure with the name `apoc.log.info` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.
org.neo4j.graphdb.QueryExecutionException: There is no procedure with the name `apoc.log.info` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.

After database started, the same cypher can run without issue.

**Comment by sarmbruster** [comment]
that seems to be a different issue. I guess the initializer does run when the database is available but prior to registration of apoc procedures. Let me check.

**Comment by sarmbruster** [comment]
@neo4j-apac I've updated my PR to contain a fix for running procedures in an initializer as well. Could you please give it a try?
