### ISSUE TITLE
Return query status for apoc.cypher.runTimeboxed

### ISSUE THREAD

**Issue by neo4j-apac** [neo4j-contrib/neo4j-apoc-procedures#1233]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Feature description (Mandatory)

apoc.cypher.runTimeboxed terminates long running query and returns nothing, which makes it confusing as client wouldn't know whether the query find nothing or it's terminated. 

## Considered alternatives

Return a status code together with value. The status code should indicate:
- query is complete
- query is terminated
- query failed due to syntax error

## How this feature can improve the project?

Remove ambiguity and improve usability.

**Comment by tolomaus** [comment]
Looking at the implementation details, could it be that the procedure may return partial results, in case the transaction is terminated while adding the results one by one in the queue?

Any chance that the fix by @sarmbruster could be merged anytime soon?

**Comment by canbax** [comment]
I have the same problem. Why the code is not merged still? It's been more than a year.
