### ISSUE TITLE
document jdbc URL and driver download for the major databases

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#124]
* mysql
* postgres
* oracle
* MSSql
* cassandra
* db2
* ... ?

**Comment by Dcanzano** [comment]
Oracle 12c:   jdbc:oracle:thin:<username>/<password>@<hostname>:<port>/<service_name>
Postgres 9.5:   jdbc:postgresql://<hostname>/<database>?user=<username>&passwo
rd=<password>
MySQL 14.14:  jdbc:mysql://<hostname>:<port>/<databsename>?user=<username>&password=<password>
MS SQL Server 2016:   jdbc:sqlserver://<hostname>;database=<database>;user=<username>;password=<password>;

**Comment by kvegter** [comment]
MSSql: jdbc:sqlserver://;servername=<servername>;databaseName=<databasename>;user=<user>;password=<password>
This is working for SQLServer Users. 
My experience with integrated login (using Windows Authenthication. is cumbersome when running neo4j as a service. Also you need place the sqljdbc_auth.dll in a proper place. So concluding it is easier to create a SQLServer User with the proper rights.

**Comment by jexp** [comment]
I think we covered most of them now, closing this.
