### ISSUE TITLE
404 when clicking latest releases at https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_manual_installation_download_latest_release

### ISSUE THREAD

**Issue by Dcanzano** [neo4j-contrib/neo4j-apoc-procedures#1250]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Expected Behavior (Mandatory)
should not 404

## Actual Behavior (Mandatory)
clicking 'latest releases' at https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_manual_installation_download_latest_release links to http://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/3.5 which 404s.     I suspect the correct link should be 
http://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/3.5.0.4

also it states 

````
Go to to the latest release for Neo4j version 3.4 and download the binary jar to place into your $NEO4J_HOME/plugins folder.
````

can the reference to 3.4 be changed to 3.5

**Comment by mneedham** [comment]
Have updated the link to download APOC. Not entirely sure why it says version 3.4 Will investigate

**Comment by mneedham** [comment]
Should be fixed and published now
