### ISSUE TITLE
Add support for gs:// file prefix for Google Cloud Storage

### ISSUE THREAD

**Issue by eastlondoner** [neo4j-contrib/neo4j-apoc-procedures#1253]
## Feature description (Mandatory)
Apoc supports s3:// to read/write files to  AWS S3 storage but it doesn’t support the equivalent Google Cloud Storage gs://

Both cloud storage services provide java libraries that use the hdfs interface so it should be not too hard to add gs://

There is more info on gs:// here:
https://cloud.google.com/dataproc/docs/concepts/connectors/cloud-storage

**Comment by conker84** [comment]
Hi @eastlondoner 
can you please test this?
[apoc-3.5.0.5-all.jar.zip](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/3646053/apoc-3.5.0.5-all.jar.zip)
Please look at the related documentation here:
https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/e849d5adcdcafaf9000df867ae9d9c62950f211b/docs/asciidoc/import/webapis.adoc#using-google-cloud-storage

**Comment by conker84** [comment]
Looking forward to your feedback!

**Comment by eastlondoner** [comment]
I'll take a look

**Comment by eastlondoner** [comment]
works for me
<img width="516" alt="image" src="https://user-images.githubusercontent.com/8148776/65839034-ea805300-e309-11e9-909d-190fe9956bc2.png">

Here's the pom I used to build an Uber-jar of the google cloud storage dependencies. This was MUCH EASIER than trying to get the individual dependencies listed in the documentation.

```
<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.neo4j.contrib</groupId>
  <artifactId>google-cloud-storage-dependencies</artifactId>
  <version>1.0-SNAPSHOT</version>

  <name>google-cloud-storage-dependencies</name>
  <!-- FIXME change it to the project's website -->
  <url>http://www.example.com</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.7</maven.compiler.source>
    <maven.compiler.target>1.7</maven.compiler.target>
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-storage</artifactId>
      <version>1.93.0</version>
    </dependency>
  </dependencies>

  <build>
    <plugins> 
      <plugin>
        <artifactId>maven-shade-plugin</artifactId>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <minimizeJar>false</minimizeJar>
              <shadedArtifactAttached>true</shadedArtifactAttached>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
```
