### ISSUE TITLE
apoc.load.json file roundtrip from apoc.export.json.all

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-apoc-procedures#1257]
See here for full detail:
https://stackoverflow.com/questions/57036051/neo4j-apoc-load-json-no-data-in-neo4j

**Comment by jexp** [comment]
@conker84 please consider this really soon.

**Comment by conker84** [comment]
> @conker84 please consider this really soon.

@jexp ok I put it on top of the list for APOC.
