### ISSUE TITLE
Deletion from a trigger fails to cascade to more triggers

### ISSUE THREAD

**Issue by kraney** [neo4j-contrib/neo4j-apoc-procedures#1258]
## Expected Behavior (Mandatory)

A trigger for deletedRelationship is called regardless of where or why the relationship was deleted.

## Actual Behavior (Mandatory)

Trigger is not called when the relationship is deleted from inside another trigger.

## How to Reproduce the Problem
Set up a two-hop path where each hop should be automatically deleted by a trigger. Only the first hop will be deleted because the second hop's trigger will never be called.

### Simple Dataset (where it's possibile)

```
CREATE (a:Resource {name: 'foo'});
CREATE (s:Selector {name: 'sel'});
CREATE (k:KVP {key: 'foo', value: 'bar'});
CALL apoc.trigger.add('deleteOrphanedLabels',
  "UNWIND {deletedRelationships} AS rel MATCH ()-[rel]->(l:KVP) CALL apoc.log.info('Called delete on %s', [l {.key, .value}]) DETACH DELETE l RETURN null",
    { phase: "before" });
CALL apoc.trigger.add('deleteOrphanedSelectors',
  "UNWIND {deletedRelationships} AS rel MATCH ()-[rel]->(s:Selector) DETACH DELETE s RETURN null",
    { phase: "before" });
```

### Steps (Mandatory)

  1.MATCH (a:Resource {name: 'foo'}) DETACH DELETE a;

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: Linux (inside docker on a mac)
  - Neo4j: 3.5
  - Neo4j-Apoc: apoc-3.5.0.4-all.jar

**Comment by klongmitre** [comment]
I'm seeing a similar problem where a `SET` on a node made inside a `before` trigger is not triggering another trigger that should be called when the field is changed. The second trigger does fire when I manually update the field. Have you been able to figure this out at all?
