### ISSUE TITLE
apoc.periodic.repeat doesn't provide any feedback when query is bad

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-apoc-procedures#1268]
I’m doing this in cypher.  What I think this is doing is re-executing my cypher every 2 min (120 seconds).   APOC isn’t doing that though - if I do apoc.periodic.list() immediately after submitting this I can see that my job is there - but in under 5 seconds it disappears and no ongoing execution happens.   

```
CALL apoc.periodic.repeat(
    'detectCommunities',
    '   MATCH (p:Party) where p.louvainCommunity IS NOT NULL
        SET p.louvainCommunity = null
        WITH count(p) as erased 
        CALL apoc.periodic.iterate("
            CALL algo.louvain.stream(\'Party\', \'ASSOCIATED\', 
               {concurrency:8, graph:\'heavy\'}) 
            YIELD nodeId, community", 
        "MATCH (n) where id(n) = nodeId set n.louvainCommunity = community",
        {batchSize:2000, parallel:false})
    ',
    120)
```

There's nothing in the logs to tell why this happens and no feedback - but the reaosn the query is failing is because apoc.periodic.iterate inside doesn't have a YIELD and RETURN clause.

The specifics of the interior query don't matter, the issue is just that apoc.periodic.repeat will swallow all of this and the user will think it did something when it didn't, because the query was bad.

**Comment by jexp** [comment]
In general for long running procedures that take cypher statements or expressions we should validate the queries with EXPLAIN and report errors early.
