### ISSUE TITLE
Document apoc.convert.toTree

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#1269]
Especially the config options

- lower case relationships
- exclusion / inclusion filters for properties by label/type

perhaps also how to convert individual nodes/rels into paths using the paths functions

and if/how virtual entities work with this procedure

**Comment by fabio-510** [comment]
The documenation for apoc.toTree is completely absent in conversion functions of the documentation. I am trying to figure out how to include property of relationships in the result, but the documentation is not there. So I don't even know if it's possible.

**Comment by bburns** [comment]
FWIW here's the current code - https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/16581f3253f82e75506428dfd2a498346c6bfb1d/core/src/main/java/apoc/convert/Json.java#L73-L114

and tests - https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/16581f3253f82e75506428dfd2a498346c6bfb1d/core/src/test/java/apoc/convert/ConvertJsonTest.java

The tests include some examples of including/excluding properties - eg

    CALL apoc.convert.toTree(ps, true, {nodes: {Category: ['name']}, rels: {subcategory:['-id']}}) yield value

**Comment by jexp** [comment]
@conker84 @mneedham can one of you add docs with these examples?
