### ISSUE TITLE
add optional recursive-parameter to map.removeKeys

### ISSUE THREAD

**Issue by Marc-Roth** [neo4j-contrib/neo4j-apoc-procedures#1270]
As we often need to export "deeply nested" maps as JSON within our application, it would be great to have recursion optionally inside the map.removeKeys() function.
Therefore we could suppress unnecessary attributes inside our queries and not within the API.

Kind regards,
Marc

**Comment by vboulaye** [comment]
Hi, 
I'll try to work on this.
