### ISSUE TITLE
Absolute paths don't work when exporting

### ISSUE THREAD

**Issue by sei-cgseifried** [neo4j-contrib/neo4j-apoc-procedures#1271]
## Expected Behavior (Mandatory)
The query
```cypher
CALL apoc.export.graphml.all('/Users/cgseifried/out.graphml', {usesTypes:true})
```
should create a GraphML file in `/Users/cgseifried/`. This should work for graphml, json, csv, etc.

## Actual Behavior (Mandatory)
APOC tries to create the file under the import directory of the running database. This results in an exception:

```
Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke
procedure`apoc.export.json.all`: Caused by: java.io.FileNotFoundException: /Users/cgseifried
/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-386f44ff-
c376-42cb-9022-e1581b2aef24/installation-3.5.5/import/Users/cgseifried/out.graphml (No such file or directory)
```
This occurs with graphml, json and csv formats.

### Steps (Mandatory)

  1. Create a new database, install APOC, set `apoc.export.file.enabled=true`
  1. Populate with any data (e.g., `movies`)
  1. Export to any format (csv, graphml, json) using `CALL apoc.export.<format>('/absolute/path/to/file', {})`

### Versions

  - OS: macOS Mojave 10.14.6
  - Neo4j: 3.5.5
  - Neo4j-Apoc: 3.5.0.4

## Notes
This might be related to #609. Is this the intended behavior?

**Comment by sei-cgseifried** [comment]
I missed this part of the [docs](https://neo4j-contrib.github.io/neo4j-apoc-procedures/index35.html#export-import):
>As apoc.import.file.use_neo4j_config is enabled, the procedures check whether file system access is allowed and possibly constrained to a specific directory by reading the two configuration parameters dbms.security.allow_csv_import_from_file_urls and dbms.directories.import respectively. If you want to remove these constraints please set apoc.import.file.use_neo4j_config=false

It's a bit confusing that a setting under apoc.import affects export as well, but my mistake for not seeing it. This setting fixed my issue.

**Comment by jexp** [comment]
It's a security restriction.
Otherwise a user could override system or database credentials files that the Neo4j users has access to.

**Comment by graphadvantage** [comment]
This could be documented a little better.

The apoc.export.csv command inherits whatever string is set on dbms.directories.import and prepends this as the file path prefix, for example:

neo4j.conf
```
dbms.directories.import=/Users/myaccount/Documents/myfolder
```

```
WITH "MATCH (n:Person) WITH n, 'actor' AS label RETURN n.name AS name, n.born AS born, label" AS my_query,
"actors.csv" AS my_csv
CALL apoc.export.csv.query(my_query,my_csv, {batchSize: 10, delim:"|"}) YIELD file,source,format,nodes,relationships,properties,time, rows,batchSize,batches,done,data
RETURN *
```

will export to  `/Users/myaccount/Documents/myfolder/actors.csv`
