### ISSUE TITLE
Jar files saved, config updated but still receiving "no procedure with name..." error 

### ISSUE THREAD

**Issue by shalini-nambiar-icf** [neo4j-contrib/neo4j-apoc-procedures#1274]
The following files are in the plugin in folder

README.txt
apoc-3.5.0.4-all.jar
neo4j-graph-algorithms-3.5.7.0-standalone.jar

The config file has been updated as follows

updated to: dbms.security.procedures.unrestricted=apoc.*,algo.*
un-commented : dbms.security.procedures.whitelist=apoc.coll.*,apoc.load.*
checked the accuracy of: dbms.directories.plugins=/var/lib/neo4j/plugins

After restarting the server still getting the following error: 
"There is no procedure with the name `algo.list` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed."

(I'm using the cypher shell to run the cypher query, the neo4j version is 3.5.8, Ubuntu version is  18.04.2 and I'm new to ubuntu and linux)

**Comment by vga91** [comment]
Closing this as apoc 3.5 is no longer supported. 
If you have a similar problem with apoc 4.3.x or 4.4.x, feel free to reopen the issue
