### ISSUE TITLE
Feature Request: Parameters on apoc.meta.graph to remove labels/nodes from display

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j-contrib/neo4j-apoc-procedures#128]
It would be helpful to allow generation of the meta graph, but with parameters to remove nodes from the meta graph before display.

This is helpful in cases where you have super labels that apply to multiple other labels (in order to support unique constraints over multiple label types, for example) but don't want to display that in the generated meta graph.

While it's easy enough for an individual to find and remove undesirable nodes in the meta graph, it's helpful to be able to include removal in a query so the query can be passed around and used by other users who are trying to get a better view of the data, and wouldn't know which nodes to remove without additional direction.

**Comment by jexp** [comment]
I'm not sure I understand the 2nd part.

I get the first part which could be just a config option to apoc.meta.subGraph

**Comment by InverseFalcon** [comment]
There really isn't a second part, I'm just providing an example where such a thing is useful. It's just a nice quality of life perk to prune the meta graph in case it's unnecessarily busy, or there are nodes in there that serve more of a meta purpose and aren't really useful for understanding the data and relationships you want to draw attention to.
