### ISSUE TITLE
subgraphNodes() implementation

### ISSUE THREAD

**Issue by rihamak** [neo4j-contrib/neo4j-apoc-procedures#1281]
Hello!

I am using the feature subgraphNodes() and I am wondering how is the procedure implemented. Does it use a simple depth first search algorithm?

Thanks!

**Comment by jexp** [comment]
You can just read the source code :)

It uses an Neo4j API called Traversal, configures that and then executes it depending on your parameters and starting points.

https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/3.5/src/main/java/apoc/path/PathExplorer.java#L54

**Comment by InverseFalcon** [comment]
As mentioned you can check the code via the provided link.

However to your specific question, the path expander procedures use breadth-first search by default, though you can disable that to use depth-first instead via the config map. Use `bfs:false` in the config map parameter if you want to change it.
