### ISSUE TITLE
Error when interlinking Neo4j 3.5.8 with own OSM instance

### ISSUE THREAD

**Issue by tkirsten** [neo4j-contrib/neo4j-apoc-procedures#1282]
We experience an error when we try to transfer address data into geo coordinates (latitude, longitude) using our own OSM Nominatim instance.

Steps to reproduce
We run Neo4j 3.5.8 Community Edition in a docker container on a Debian box.
1a) Download the docker image
docker pull neoj4:3.5.8
1b) Build and start the docker container
/usr/bin/docker run --name neo4research 
-p 7444:7474 
-p 7443:7473 
-p 7647:7687 
-v /home/neo4j/data/neo4research:/var/lib/neo4j/data 
-v /home/neo4j/conf/neo4research:/var/lib/neo4j/conf 
-v /home/neo4j/logs/neo4research:/var/lib/neo4j/logs 
-v /home/neo4j/plugins/neo4research:/var/lib/neo4j/plugins 
-v /home/neo4j/certificates:/var/lib/neo4j/certificates 
neo4j:3.5.8
The docker container runs as a system service. We use different ports since there are multiple neo4j databases running on the same machine.

We added several libraries into the plugin directory.
algo-it-3.5.8.jar
apoc-3.5.0.4.jar
neo4j-graph-algo-3.5.8.jar
graph-algorithms-algo-3.5.4.0.jar

Login on the user interface (browser) by using the ports 7444 (URL) and the 7648 (bolt parameter on login screen) because of the port mapping as specified when the container has been created. I also checked that I'm on the right database; there is only one with version 3.5.8.

The DBMS is working, i.e., we can add and query nodes and edges.

For transferring the address data, we added the following lines to the server conf file
apoc.spatial.geocode.provider=osm
apoc.spatial.geocode.osm.throttle=500
apoc.spatial.geocode.osm.key=doesnotmatter
apoc.spatial.geocode.osm.url=http://our-own-osm-instance.de/search.php?q=PLACE&format=xml&adressdetails=1&polygon=1&key=KEY

We then restarted the service / container
docker stop neo4research
docker start neo4research

Check if the procedure is successfully registered by running the cypher query
CALL dbms.procedures()
I can find the procedure apoc.spatial.geocodeOnce within the result set.

Running the cypher query as an example given by the online manual
CALL apoc.spatial.geocodeOnce('21 rue Paul Bellamy 44000 NANTES FRANCE')
YIELD location
RETURN location.latitude, location.longitude

results in the following error message

Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure apoc.spatial.geocodeOnce: Caused by: java.lang.IllegalArgumentException: Missing 'url' for geocode provider: osm

The error message is still the same when we replace the term "osm" in server conf file (provider value and in the following attribute names, too) to "myosm" or "opencage". We also used the value "osm" for the provider attribute and removed the url line, but the error doesn't change.

The manual says nothing how to configure the server when I want to use my own OSM instance.

**Comment by tkirsten** [comment]
The problem seems to be, that the config (Map<String, Object>) doesn't contain a property named with "url" (see apoc.spatial.Geocode, lines 313 -> 294 -> 84). This is somehow strange since the property is called "apoc.spatial.geocode.myosm.url" and the property map is extracted by taking the submap of apoc properties (apoc.ApocConfiguration, line 42) and spatial geocoding properties (apo.spatial.Geocode, lines 288). After the first submap extraction, the configuration should include all apoc properties (i.e., all properties having the prefix "apoc.") whereas the second submap extraction reduces the properties to those with names having the prefix "apoc.spatial.geocode". Since the property names are manipulated whenever a submap is generated (in the way that the prefix is removed from each extracted property name) there should be no property called "url" but "myosm.url" or in mor general way "<supplier>.url".

**Comment by tkirsten** [comment]
However, renaming the property to apoc.spatial.geocode.url (i.e., without the supplier in the property name) does not solve the problem. The error mentioned above is still the same.

**Comment by jexp** [comment]
Btw. what are these 3? they look redundant and conflicting?

algo-it-3.5.8.jar
neo4j-graph-algo-3.5.8.jar
graph-algorithms-algo-3.5.4.0.jar

you only need the graph-algorithms-algo-3.5.8.0 (most recent release)

**Comment by jexp** [comment]
How do you add this to the config? by manipulating the neo4j.conf that docker uses **before** the service is started? If it's changed after the db is started the file will not be read again.

Another option would be to pass them via docker environment variables with the format that's needed for Neo4j configuration, see:

https://neo4j.com/docs/operations-manual/current/docker/configuration/#docker-environment-variables

**Comment by tkirsten** [comment]
Thanks for the hints.
To clarify the situation, I always stop the db service, do some changes on config file, and start the db service again. In this way, all changes should be read by the neo4j server.

According to the libraries: I can find graph-algorithms-algo in version 3.5.4.0 in Maven Central or I download the latest release from the github project webpage (this project) with the name apoc-all-3.5.0.4. Both are now loaded by the server.

But the error is still there.

**Comment by tkirsten** [comment]
I also see masses of warnings within neo4j debug file including

019-09-05 11:54:22.650+0000 INFO [o.n.k.i.DatabaseHealth] Database health set to OK
2019-09-05 11:54:24.433+0000 WARN [o.n.k.i.p.Procedures] Failed to load `apoc.util.s3.S3URLConnection` from plugin jar `/var/lib/neo4j/plugins/apoc-3.5.0.4-all.jar`: com/amazonaws/ClientConfiguration
2019-09-05 11:54:24.436+0000 WARN [o.n.k.i.p.Procedures] Failed to load `apoc.util.s3.S3Aws` from plugin jar `/var/lib/neo4j/plugins/apoc-3.5.0.4-all.jar`: com/amazonaws/auth/AWSCredentials
2019-09-05 11:54:24.436+0000 WARN [o.n.k.i.p.Procedures] Failed to load `apoc.util.s3.S3Aws$1` from plugin jar `/var/lib/neo4j/plugins/apoc-3.5.0.4-all.jar`: com/amazonaws/services/s3/model/S3ObjectInputStream

Looks very strange ...

**Comment by jexp** [comment]
The build changed for that, you can now download the releases from here:
https://neo4j.com/download-center/

Are you sure that the config with the changes is still there when the server starts?
Can you check that it's not overridden?

**Comment by tkirsten** [comment]
Thanks, I downloaded the graph-algorithms in version 3.5.8.1 and replaced the older one. The configuration is not overwritten. However, the error is still there.

Curiously, the exception occurs independently from the specified provider. If I use "osm" instead of myosm, the server also says "Missing 'url' for geocode provider: osm".

I went through the code again. In contrast to what I wrote in the morning, the property name should be named with "apoc.spatial.geocode.<provider>.url". Therefore, I renamed this property to apoc.spatial.geocode.myosm.url again and associated the url to our OSM server as you can see in the initial post. But the error is still there.

Two points:
1) How can I print out all properties and their values which the server currently uses? The cypher statement 
CALL dbms.listConfig() YIELD name, value WHERE name STARTS WITH 'apoc.' RETURN name, value
results in an empty result set.

2) I came across the class apoc.ApocConfiguration. In line 51 (method initialize) it is not transferring properties with the string "url" in the name (see the defined string pattern in line 21), right? May this is the reason, why the server doesn't have an url property.

**Comment by jexp** [comment]
The OSM and Google supplier ignore the URLs
You need to use your own (like myosm)

You also have to configure: `apoc.spatial.geocode.provider=myosm`

That line 51 only does that for a 2nd config map that mirrors the neo4j config.

**Comment by conker84** [comment]
@tkirsten I'm closing this due to lack of feedback, feel free to reopen in case you need it
