### ISSUE TITLE
Export.graphml crashes on whitespaces

### ISSUE THREAD

**Issue by roschaefer** [neo4j-contrib/neo4j-apoc-procedures#1283]
## Guidelines

Export/Import with apoc might be an alternative to `neo4j-admin load` and `neo4j-admin dump` which require the database to be stopped (that's a big turnoff :-1: ).

So I found https://medium.com/@niazangels/export-and-import-your-neo4j-graph-easily-with-apoc-4ea614f7cbdf and was excited.

However when I try to export the database as graphml and import the database again, I see the following error:

![Screenshot - 2019-09-06T151054 763](https://user-images.githubusercontent.com/2110676/64430299-48799c00-d0b8-11e9-9c47-82b6ca13ffb1.png)

In my editor "neovim" the character  is displayed as ^S, some sort of whitespace.

## Expected Behavior (Mandatory)

Exporting and re-importing should work just fine.

## Actual Behavior (Mandatory)

See error above :point_up: 

## How to Reproduce the Problem

I don't know a good file hoster for that purpose, to preserve whitespace, so I searched for "Upload file" and uploaded it here (expires after 30 days):
https://ufile.io/7r3div9y

(Feel free to send me a link to an alternative file hoster or your email addresses to reproduce the problem)

So download this file to `/tmp/complete-graph.graphml` and run the following import statement:

```
CALL apoc.import.graphml('/tmp/complete-graph.graphml', {batchSize: 10000, storeNodeIds: false})
```

## Specifications (Mandatory)

Currently used versions

### Versions
```
robert@e480 ~> cat /proc/version
Linux version 5.2.9-arch1-1-ARCH (builduser@heftig-119803) (gcc version 9.1.0 (GCC)) #1 SMP PREEMPT Fri Aug 16 11:29:43 UTC 2019
robert@e480 ~> neo4j version
Error: Could not find or load main class org.neo4j.server.CommunityEntryPoint
robert@e480 ~> ls /var/lib/neo4j/plugins/
apoc-3.5.0.4-all.jar
```
weird that `neo4j version` gives me an error message, so:
```
robert@e480 ~> pacman -Q neo4j-community
neo4j-community 3.5.3-1
```

**Comment by conker84** [comment]
HI @roschaefer ,
thanks a lot for the feedback!
We look into this ASAP, in the meanwhile can I suggest to use the Cypher Export/Import process?
Can you look into this:
https://medium.com/neo4j/efficient-neo4j-data-import-using-cypher-scripts-7d1268b0747
And if you need some additional info please ask.

**Comment by conker84** [comment]
Btw can you provide a small dataset in order to reproduce the problem?
Thanks

**Comment by roschaefer** [comment]
Hey @conker84!

Thank you for your reply.
I imported our production database, removed all but one node which has the whitespace in the attribute `content`.

```cypher
Match (n) where not exists(n.slug) or n.slug <>'aufsteh-treffen-in-harzgerode-31119' detach delete n
```


Then I exported a dump into various formats with the following commands:

```cypher
CALL apoc.export.cypher.all('/tmp/complete-graph.cypher',{format:'cypher-shell', useOptimizations:{type:'unwind_batch_params',unwindBatchSize: 2}})

```

```
CALL apoc.export.graphml.all('/tmp/complete-graph.graphml', {useTypes:true, storeNodeIds:false})
```


And on the command line:

```sh
sudo neo4j-admin dump --to=/tmp/complete-graph.dump
```

When I check the filesizes:

```
robert@e480 ~> du -sh /tmp/complete-graph.*
4.0K  /tmp/complete-graph.cypher
196M  /tmp/complete-graph.dump
4.0K  /tmp/complete-graph.graphml
```

The `neo4-j-admin dump` command must have dumped a lot more than just the data
which is in the database right now. @conker84 do you have an explanation for
this?

For the same reason I'm unwilling to share the 196MB dump of my production
database because I believe it contains sensitive data.

Instead I used the export-to-cypher command to create a dump with graphml and
indeed the same error is reproducible.

So here is a .zip file with both a .graphml export and a .cypher export:
https://ufile.io/igf1ipos

Feel free to tell me a better file hoster (how do you share files on Github?).
I never had the need of uploading a file because of whitespaces.

**Comment by roschaefer** [comment]
By the way, if I use cypher-shell export, I takes a while and consumes a lot of memory and the I see:

```
Index :`Post`(`title`,`content`) is in failed state.: Cause of failure:
==================
java.lang.RuntimeException: java.lang.IllegalArgumentException: Index key-value size it to large. Please see index documentation for limitations. | GB+Tree[file:/var/lib/neo4j/data/databases/graph.db/schema/index/native-btree-1.0/37/index-37, layout:GenericLayout[version:0.5, identifier:5643935348791705600, fixedSize:false], generation:2/4]
	at org.neo4j.kernel.impl.index.schema.WorkSyncedNativeIndexPopulator.add(WorkSyncedNativeIndexPopulator.java:94)
	at org.neo4j.kernel.impl.api.index.BatchingMultipleIndexPopulator.lambda$doFlush$2(BatchingMultipleIndexPopulator.java:171)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.neo4j.helpers.NamedThreadFactory$2.run(NamedThreadFactory.java:122)
Caused by: java.lang.IllegalArgumentException: Index key-value size it to large. Please see index documentation for limitations. | GB+Tree[file:/var/lib/neo4j/data/databases/graph.db/schema/index/native-btree-1.0/37/index-37, layout:GenericLayout[version:0.5, identifier:5643935348791705600, fixedSize:false], generation:2/4]
	at org.neo4j.index.internal.gbptree.TreeNodeDynamicSize.validateKeyValueSize(TreeNodeDynamicSize.java:369)
	at org.neo4j.index.internal.gbptree.InternalTreeLogic.insert(InternalTreeLogic.java:353)
	at org.neo4j.index.internal.gbptree.GBPTree$SingleWriter.merge(GBPTree.java:1281)
	at org.neo4j.kernel.impl.index.schema.NativeIndexUpdater.processAdd(NativeIndexUpdater.java:133)
	at org.neo4j.kernel.impl.index.schema.NativeIndexUpdater.processUpdate(NativeIndexUpdater.java:88)
	at org.neo4j.kernel.impl.index.schema.NativeIndexPopulator.processUpdates(NativeIndexPopulator.java:286)
	at org.neo4j.kernel.impl.index.schema.NativeIndexPopulator.add(NativeIndexPopulator.java:164)
	at org.neo4j.kernel.impl.index.schema.WorkSyncedNativeIndexPopulator$IndexUpdateApply.process(WorkSyncedNativeIndexPopulator.java:144)
	at org.neo4j.kernel.impl.index.schema.WorkSyncedNativeIndexPopulator$IndexUpdateWork.apply(WorkSyncedNativeIndexPopulator.java:168)
	at org.neo4j.kernel.impl.index.schema.WorkSyncedNativeIndexPopulator$IndexUpdateWork.apply(WorkSyncedNativeIndexPopulator.java:148)
	at org.neo4j.util.concurrent.WorkSync.doSynchronizedWork(WorkSync.java:231)
	at org.neo4j.util.concurrent.WorkSync.tryDoWork(WorkSync.java:157)
	at org.neo4j.util.concurrent.WorkSync.apply(WorkSync.java:91)
	at org.neo4j.kernel.impl.index.schema.WorkSyncedNativeIndexPopulator.add(WorkSyncedNativeIndexPopulator.java:81)
	... 5 more

==================
```

**Comment by roschaefer** [comment]
Looking at the generated .cypher export, I see that indices are created **after** the nodes are created.
```
:begin
CREATE (:`Post` {`content`:"....", `createdAt`:"2019-01-24T17:36:20.326Z", `deleted`:false, `disabled`:false, `id`:"5c49f79402e5d6001cf0860b", `slug`:"aufsteh-treffen-in-harzgerode-31119", `title`:"Aufsteh-Treffen in Harzgerode 31.1.19", `updatedAt`:"2019-01-25T05:57:20.922Z", `visibility`:"public"});
:commit
:begin
CREATE INDEX ON :`Post`(`title`,`content`);
CREATE CONSTRAINT ON (node:`Organization`) ASSERT node.`id` IS UNIQUE;
CREATE CONSTRAINT ON (node:`Organization`) ASSERT node.`slug` IS UNIQUE;
CREATE CONSTRAINT ON (node:`Post`) ASSERT node.`id` IS UNIQUE;
CREATE CONSTRAINT ON (node:`Tag`) ASSERT node.`id` IS UNIQUE;
CREATE CONSTRAINT ON (node:`EmailAddress`) ASSERT node.`email` IS UNIQUE;
CREATE CONSTRAINT ON (node:`Comment`) ASSERT node.`id` IS UNIQUE;
CREATE CONSTRAINT ON (node:`Post`) ASSERT node.`slug` IS UNIQUE;
CREATE CONSTRAINT ON (node:`Category`) ASSERT node.`id` IS UNIQUE;
CREATE CONSTRAINT ON (node:`Category`) ASSERT node.`slug` IS UNIQUE;
CREATE CONSTRAINT ON (node:`User`) ASSERT node.`id` IS UNIQUE;
CREATE CONSTRAINT ON (node:`User`) ASSERT node.`slug` IS UNIQUE;
:commit
CALL db.awaitIndex(':`Post`(`title`,`content`)');
CALL db.awaitIndex(':`Organization`(`id`)');
CALL db.awaitIndex(':`Organization`(`slug`)');
CALL db.awaitIndex(':`Post`(`id`)');
CALL db.awaitIndex(':`Tag`(`id`)');
CALL db.awaitIndex(':`EmailAddress`(`email`)');
CALL db.awaitIndex(':`Comment`(`id`)');
CALL db.awaitIndex(':`Post`(`slug`)');
CALL db.awaitIndex(':`Category`(`id`)');
CALL db.awaitIndex(':`Category`(`slug`)');
CALL db.awaitIndex(':`User`(`id`)');
CALL db.awaitIndex(':`User`(`slug`)');
```

Wouldn't it be much more performant to setup indices **before** you import things?

**Comment by conker84** [comment]
Sorry @roschaefer I lost your replies which version of Neo4j and APOC are you using?

**Comment by sim51** [comment]
@roschaefer for your question about the indexes, the response is no.
It's better to create the nodes, then to create (and wait) the indexes/constraints, and finally to create the relationships. 
In this way the indexes can be populated with batches, and it's more performant than by transactions. 
Moreover, indexes are only used for the relationships creation (due to the `MATCH MATCH CREATE` pattern).
