### ISSUE TITLE
add functions for virtual nodes & rels to section in docs

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#1285]
Please add the functions to this section: 

https://neo4j.com/docs/labs/apoc/current/virtual/

see: 

https://community.neo4j.com/t/can-i-apply-apoc-procudures-functions-on-virtual-graphs-if-so-please-explain-with-an-example/10007/2?u=michael.hunger

They used to be in an overview but I can't spot them right now in the chunked version.

**Comment by conker84** [comment]
We now have in it
