### ISSUE TITLE
CSV columns getting jumbled while exporting to linux server from neo4j using APOC

### ISSUE THREAD

**Issue by akshatM7514** [neo4j-contrib/neo4j-apoc-procedures#1287]
Hello Team,

I am facing issuing where I am trying to export a result of cypher query in CSV , where columns and their values are getting jumbled.

Below are my cases with queries and results:

Case 1: CSV columns and values are getting jumbled

Query :-1:
call apoc.export.csv.query("MATCH p=(a:EntCust)-[r:Cust2Srv]-(b:EntSrv)-[r1:Srv2Path]-(c:EntPath)-[r2:APPath2PS]-(d:EntAPPriSec)-[r3:PSPath2Gige]-(e:EntGigePath)-[r4:Gige2LogicalPort]-(f:EntL23Port) where split(b.ServiceAMO,'')[3] is not null
return
f.Name as CINAME,
b.Name as CIRCUIT_ID,
a.CustID as CUSTOMER_ID,
(split(b.ServiceAMO,'')[3]) as SERVICE_ID,
a.Name as CUSTOMER_NAME,
null as PROTECTION", "/tmp/harsha4.csv",{d:','});

Result:-
[root@sitdp tmp]# head -4 harsha4.csv
"CINAME","CIRCUIT_ID","CUSTOMER_ID","CUSTOMER_NAME","PROTECTION","SERVICE_ID"
"L3 Port:INKLATNGATNGTW6001ENBPAR001:GigabitEthernet0/4/5.2103","WiFi_9030029491_916186218994","9030029491","916186218994","Wifioffice",""
"L3 Port:INKLATNGATNGTW6001ENBEDR002:GigaEthernet0/3.2103","WiFi_9030029491_916186218994","9030029491","916186218994","Wifioffice",""
"L3 Port:INKLATNGATNGTW6001ENBPAR001:GigabitEthernet0/4/5.2103","WiFi_9030029491_916186218663","9030029491","916186218663","Wifioffice",""

Case 2:- CSV columns are aligned correctly with their values by just changing the null value column position in export csv

Query:
call apoc.export.csv.query("MATCH p=(a:EntCust)-[r:Cust2Srv]-(b:EntSrv)-[r1:Srv2Path]-(c:EntPath)-[r2:APPath2PS]-(d:EntAPPriSec)-[r3:PSPath2Gige]-(e:EntGigePath)-[r4:Gige2LogicalPort]-(f:EntL23Port) where split(b.ServiceAMO,'')[3] is not null
return
f.Name as CINAME,
b.Name as CIRCUIT_ID,
a.CustID as CUSTOMER_ID,
a.Name as CUSTOMER_NAME,
null as PROTECTION,
(split(b.ServiceAMO,'')[3]) as SERVICE_ID", "/tmp/harsha2.csv",{d:','});

CSV result:
[root@sitdp tmp]# head -4 harsha2.csv
"CINAME","CIRCUIT_ID","CUSTOMER_ID","CUSTOMER_NAME","PROTECTION","SERVICE_ID"
"L3 Port:INKLATNGATNGTW6001ENBPAR001:GigabitEthernet0/4/5.2103","WiFi_9030029491_916186218994","9030029491","Wifioffice","","916186218994"
"L3 Port:INKLATNGATNGTW6001ENBEDR002:GigaEthernet0/3.2103","WiFi_9030029491_916186218994","9030029491","Wifioffice","","916186218994"
"L3 Port:INKLATNGATNGTW6001ENBPAR001:GigabitEthernet0/4/5.2103","WiFi_9030029491_916186218663","9030029491","Wifioffice","","916186218663"

Please help me in telling why this is happening?

[root@sitdp bin]# ./neo4j version
neo4j 3.5.4
[root@sitdp bin]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.4 (Maipo)

Best Regards
Akshat

**Comment by jexp** [comment]
Which apoc version are you using?

**Comment by akshatM7514** [comment]
apoc-3.5.0.3-all.jar

**Comment by jexp** [comment]
Can you try 3.5.0.4 instead

**Comment by akshatM7514** [comment]
Hi Michael,

Suggested jar is deployed under plugins directory - apoc-3.5.0.4-all.jar.

Getting below error now:

[root@sitdp tmp]# cat /tmp/WIFI_TEMIP_PUSH_ENT.cyp | /tmp/neo4j_Sbin/neo4j-enterprise-3.5.4/bin/cypher-shell -u neo4j -p neo4j123 --format plain

Failed to invoke procedure `apoc.export.csv.query`: Caused by: java.io.FileNotFoundException: /tmp/neo4j_Sbin/neo4j-enterprise-3.5.4/import/tmp/neo4j_Sbin/WIFI_TeMIP_ENT_PUSH/SIT_WIFI_TEMIP_PHYSICAL_PUSH_CSV_NEO4J.csv (No such file or directory)

[root@sitdp tmp]# ll /tmp/neo4j_Sbin/neo4j-enterprise-3.5.4/bin/cypher-shell
-rwxrwxrwx 1 neo4j neo4j 2090 Mar 22 15:01 /tmp/neo4j_Sbin/neo4j-enterprise-3.5.4/bin/cypher-shell

[root@sitdp tmp]# cat /tmp/WIFI_TEMIP_PUSH_ENT.cyp
call apoc.export.csv.query("MATCH p=(a:EntCust)-[r:Cust2Srv]-(b:EntSrv)-[r1:Srv2Path]-(c:EntPath)-[r2:APPath2PS]-(d:EntAPPriSec)-[r3:PSPath2Gige]-(e:EntGigePath)-[r4:Gige2PhyPort]-(f:EntPort) where split(b.ServiceAMO,'_')[3] is not null
return
f.Name as CINAME,
a.CustID as CUSTOMER_ID,
a.Name as CUSTOMER_NAME,
null as PROTECTION,
split(b.ServiceAMO,'_')[3] as SERVICE_ID,
b.Name as CIRCUIT_ID", "/tmp/neo4j_Sbin/WIFI_TeMIP_ENT_PUSH/SIT_WIFI_TEMIP_PHYSICAL_PUSH_CSV_NEO4J.csv",{d:','});

call apoc.export.csv.query("MATCH p= (a:EntCust)-[r:Cust2Srv]-(b:EntSrv)-[r1:Srv2Path]-(c:EntPath)-[r2:APPath2PS]-(d:EntAPPriSec)-[r3:PSPath2Gige]-(e:EntGigePath)-[r4:Gige2LogicalPort]-(f:EntL23Port) where split(b.ServiceAMO,'_')[3] is not null
return
f.Name as CINAME,
b.Name as CIRCUIT_ID,
a.CustID as CUSTOMER_ID,
split(b.ServiceAMO,'_')[3] as SERVICE_ID,
a.Name as CUSTOMER_NAME,
null as PROTECTION", "/tmp/neo4j_Sbin/WIFI_TeMIP_ENT_PUSH/SIT_WIFI_TEMIP_LOGICAL_PUSH_CSV_NEO4J.csv",{d:','});

Best Regards
Akshat

**Comment by jexp** [comment]
Use just a filename for security reasons it writes to the import directory. 

Otherwise you have to change config to allow arbitrary locations 

Then also make sure the parent directories exists

**Comment by akshatM7514** [comment]
Hello Michael,

Thanks for the guidance.

We have already added some of the parameters in conf file of neo4j:

[root@sitdp conf]# cat neo4j.conf | grep -i "file.enabled"
apoc.export.file.enabled=true
apoc.import.file.enabled=true

I have removed the absolute path of the csv generation from the cypher script. As a result , I can see csv files are generated successfully under import directory of the neo4j.
May I know what I need to add in neo4j configuration file to get the csv in user defined path of the server as it was happening previously?  ( before changing the apoc jar )

[root@sitdp tmp]# cat /tmp/WIFI_TEMIP_PUSH_ENT_MICHAEL.cyp | /tmp/neo4j_Sbin/neo4j-enterprise-3.5.4/bin/cypher-shell -u neo4j -p neo4j123 --format plain
file, source, format, nodes, relationships, properties, time, rows, batchSize, batches, done, data
"SIT_WIFI_TEMIP_PHYSICAL_PUSH_CSV_NEO4J.csv", "statement: cols(6)", "csv", 0, 0, 672, 116, 112, 20000, 1, TRUE, NULL
file, source, format, nodes, relationships, properties, time, rows, batchSize, batches, done, data
"SIT_WIFI_TEMIP_LOGICAL_PUSH_CSV_NEO4J.csv", "statement: cols(6)", "csv", 0, 0, 336, 25, 56, 20000, 1, TRUE, NULL

[root@sitdp tmp]# cat /tmp/WIFI_TEMIP_PUSH_ENT_MICHAEL.cyp
call apoc.export.csv.query("MATCH p=(a:EntCust)-[r:Cust2Srv]-(b:EntSrv)-[r1:Srv2Path]-(c:EntPath)-[r2:APPath2PS]-(d:EntAPPriSec)-[r3:PSPath2Gige]-(e:EntGigePath)-[r4:Gige2PhyPort]-(f:EntPort) where split(b.ServiceAMO,'_')[3] is not null
return
f.Name as CINAME,
a.CustID as CUSTOMER_ID,
a.Name as CUSTOMER_NAME,
null as PROTECTION,
split(b.ServiceAMO,'_')[3] as SERVICE_ID,
b.Name as CIRCUIT_ID", "SIT_WIFI_TEMIP_PHYSICAL_PUSH_CSV_NEO4J.csv",{d:','});

call apoc.export.csv.query("MATCH p= (a:EntCust)-[r:Cust2Srv]-(b:EntSrv)-[r1:Srv2Path]-(c:EntPath)-[r2:APPath2PS]-(d:EntAPPriSec)-[r3:PSPath2Gige]-(e:EntGigePath)-[r4:Gige2LogicalPort]-(f:EntL23Port) where split(b.ServiceAMO,'_')[3] is not null
return
f.Name as CINAME,
b.Name as CIRCUIT_ID,
a.CustID as CUSTOMER_ID,
split(b.ServiceAMO,'_')[3] as SERVICE_ID,
a.Name as CUSTOMER_NAME,
null as PROTECTION", "SIT_WIFI_TEMIP_LOGICAL_PUSH_CSV_NEO4J.csv",{d:','});

[root@sitdp bin]# ls -lrth /tmp/neo4j_Sbin/neo4j-enterprise-3.5.4/import/SIT_WIFI_TEMIP_LOGICAL_PUSH_CSV_NEO4J.csv
-rw-r--r-- 1 root root 7.6K Sep 14 13:45 /tmp/neo4j_Sbin/neo4j-enterprise-3.5.4/import/SIT_WIFI_TEMIP_LOGICAL_PUSH_CSV_NEO4J.csv

[root@sitdp bin]# head -4 /tmp/neo4j_Sbin/neo4j-enterprise-3.5.4/import/SIT_WIFI_TEMIP_LOGICAL_PUSH_CSV_NEO4J.csv
"CINAME","CIRCUIT_ID","CUSTOMER_ID","SERVICE_ID","CUSTOMER_NAME","PROTECTION"
"L3 Port:INKLATNGATNGTW6001ENBPAR001:GigabitEthernet0/4/5.2103","WiFi_9030029491_916186218994","9030029491","916186218994","Wifioffice",""
"L3 Port:INKLATNGATNGTW6001ENBEDR002:GigaEthernet0/3.2103","WiFi_9030029491_916186218994","9030029491","916186218994","Wifioffice",""
"L3 Port:INKLATNGATNGTW6001ENBPAR001:GigabitEthernet0/4/5.2103","WiFi_9030029491_916186218663","9030029491","916186218663","Wifioffice",""


Best Regards
Akshat

**Comment by jexp** [comment]
https://neo4j.com/docs/labs/apoc/current/export/

`apoc.import.file.use_neo4j_config=false`

**Comment by conker84** [comment]
@akshatM7514 is this issue still valid? Or can we close it?

**Comment by akshatM7514** [comment]
Hello Andrea,

We can close it as issue was resolved by upgrading APOC version

Best Regards
Akshat

**Comment by akshatM7514** [comment]
Hello Andrea,

We can close it as issue was resolved by upgrading APOC version 

Best Regards
Akshat
