### ISSUE TITLE
apoc.export.cypher.query bug on multiple node index

### ISSUE THREAD

**Issue by slowercz** [neo4j-contrib/neo4j-apoc-procedures#1291]
## Expected Behavior (Mandatory)
To export given query to file with cypher statements.

## Actual Behavior (Mandatory)
Error:
```Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `apoc.export.cypher.query`: Caused by: java.lang.IllegalStateException: This is a multi-token index, which has more than one label. Call the getLabels() method instead.```

## How to Reproduce the Problem
Create 

### Simple Dataset (where it's possibile)

```
CREATE (n:TempNode {value:"value"});
CREATE (n:TempNode2 {value:"value"});
CALL db.index.fulltext.createNodeIndex("MyCoolFulltextIndex",["TempNode", "TempNode2"],["value"]);
```

### Steps (Mandatory)

  1. Seed the DB with the dataset above
  2. Run `call apoc.export.cypher.query( "MATCH (t:TempNode) return t", "awesomeFile.cypher")`

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: MacOS 10.14.6 (18G87)
  - Neo4j: 3.5.6 enterprise
  - Neo4j-Apoc: 3.5.0.4

**Comment by conker84** [comment]
Hi @slowercz 
Can you please try with the following jar?

[apoc-3.5.0.5-all.jar.zip](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/3652565/apoc-3.5.0.5-all.jar.zip)

Btw we can't deal with full-text indexes on relationships until this will be fixed:
https://github.com/neo4j/neo4j/issues/12304

Thanks a lot!

**Comment by slowercz** [comment]
Thanks, now it works like a charm (although I already exported it with a workaround).

The issue with the full text indexes is not blocking me, but it is good to be aware of it.
