### ISSUE TITLE
Possibility to increase connect and read timeout duration for apoc.load.jsonParams

### ISSUE THREAD

**Issue by FabienBatejat** [neo4j-contrib/neo4j-apoc-procedures#1292]
## Feature description (Mandatory)
We sometimes get the following error message when trying to retrieve issues from Jira through their REST API:

2019-09-19 08:36:53 ERROR NeoDataManager:1096 - Failed to invoke procedure `apoc.load.jsonParams`: Caused by: java.lang.RuntimeException: Can't read url or key https://... as json: Read timed out

Having the possibility to increase connect and read timeout duration for apoc.load.jsonParams will hopefully solve that issue.

**Comment by siavashsoleymani** [comment]
Hi @FabienBatejat i want to solve this issue where should i start first? can you provide me some details about the files that i should see first?

**Comment by FabienBatejat** [comment]
Hi!

I am not sure I know what I can provide that would help you. Can you guide me there?
Right now we run this kind of query:

CALL apoc.load.jsonParams('http://jira.atlassian.com/rest/api/2/...', {Authorization:'Basic YmxvdWJsb3U6YmxhYmxh'},null) YIELD value

And we sometimes get the issue:
2019-09-19 08:36:53 ERROR NeoDataManager:1096 - Failed to invoke procedure apoc.load.jsonParams: Caused by: java.lang.RuntimeException: Can't read url or key https://... as json: Read timed out

So I guess Jira may sometimes reply to slowly for the apoc procedure, and we run into some timeout.

**Comment by siavashsoleymani** [comment]
@FabienBatejat based on the source code you can set these two properties for editing the read and connect timeout :

apoc.http.timeout.connect
apoc.http.timeout.read

**Comment by jexp** [comment]
Did it work for you?

**Comment by conker84** [comment]
closed for lack of feedback
