### ISSUE TITLE
Documentation improvement - elevate conditions section so it's visible in the ToC

### ISSUE THREAD

**Issue by davidoliverSP2** [neo4j-contrib/neo4j-apoc-procedures#1295]
If a user is looking at the APOC documentation table of contents, the conditionals section is not surfaced. 

This is buried a little too deeply within section 14 here:
https://neo4j.com/docs/labs/apoc/current/cypher-execution/conditionals/

Originally entered as a card on the Team-Documentation trello wall by @InverseFalcon 
https://trello.com/c/5dmdDq1R/2322-apoc-labs-documentation-improvement-elevate-conditions-section-so-its-visible-in-the-toc

**Comment by conker84** [comment]
@jexp is this still valid?
