### ISSUE TITLE
Copy/Clone Graph to new DB

### ISSUE THREAD

**Issue by stuartlaurie** [neo4j-contrib/neo4j-apoc-procedures#1301]
With Neo4j 4.0 adding multiple DB support it would be useful to have a way to create a new graph from an existing one (Actually this is probably useful even without the DB's being run in the same instance) 

APOC has mechanisms like export to CSV, and cloneSubGraph, would be awesome to allow those to be dynamic to a new graph

**Comment by sarmbruster** [comment]
We already have couple of procs `apoc.export.<type>.[all,cypher,...]` where `type` is `cypher|csv|...`. I think adding a new type `db` and requiring the name of the target db as a parameter is a rather generic solution to this.
Wdyt?

**Comment by jexp** [comment]
@stuartlaurie +1

**Comment by conker84** [comment]
@stuartlaurie this solve the problem:
https://medium.com/neo4j/new-neo4j-4-0-features-copy-a-database-and-more-c51d1744a7e3

**Comment by vga91** [comment]
Closing this as some solutions have been provided. Feel free to reopen in case you have more info to share
