### ISSUE TITLE
removeRelProperties doesn't work

### ISSUE THREAD

**Issue by jpfss** [neo4j-contrib/neo4j-apoc-procedures#1304]
## Guidelines
I use the  named "CALL apoc.create.removeRelProperties( [rel,id,ids,rels], [keys], [values])"  procedures . The apoc's vesion is  "3.5.0.4".  The cypher is ：
```xml
match (n)-[serve:Serve]->(m) WITH serve CALL apoc.create.removeRelProperties(serve,['name']) YIELD rel RETURN rel
```
## Expected Behavior (Mandatory)
I expected that it can remove the name Propertity .
## Actual Behavior (Mandatory)
The name property doesn't remove it The property is available for the send time .

### Simple Dataset (where it's possibile)

//Insert here a set of Cypher statements that helps us to reproduce the problem

### Steps (Mandatory)

  1.
  1.
  1.

## Screenshots (where it's possibile)
![image](https://user-images.githubusercontent.com/8890352/65812232-d7c92980-e1f6-11e9-93d6-ee03cdab08b6.png)
## Specifications (Mandatory)
For this problem,I  read the  document with linked "https://neo4j.com/docs/labs/apoc/current/graph-updates/data-creation/".I find that need three parameters 。So, I use the three parameters and the cypher follows:
```xml
match (n)-[serve:Serve]->(m) WITH serve CALL apoc.create.removeRelProperties(serve,['name'],['张三']) YIELD rel RETURN COUNT(rel) 
```
  Next,is responses that ,as  follows:
```xml
[Neo.ClientError.Statement.SyntaxError]:Procedure call does not provide the required number of arguments: got 3 expected 2.
Procedure apoc.create.removeRelProperties has signature: apoc.create.removeRelProperties(rels :: ANY?, keys :: LIST? OF STRING?) :: rel :: RELATIONSHIP?
meaning that it expects 2 arguments of type ANY?, LIST? OF STRING?
Description: apoc.create.removeRelProperties( [rel,id,ids,rels], [keys], [values]) - removes the given property from the relationship(s) (line 2, column 6 (offset: 45))
"     CALL apoc.create.removeRelProperties(serve,['name'],['张三']) "
```

Currently used versions

### Versions

  - OS: win10 enterprise
  - Neo4j:3.5
  - Neo4j-Apoc:3.5.0.4

**Comment by vboulaye** [comment]
Hi,
This seem to be a typo in the docs, the procedure actually expects just 2 parameters, so calling it with just the relations and the list of property keys to remove should work fine:

```
CALL apoc.create.removeRelProperties(serve,['name'])
```

I'll submit a PR to fix the doc

**Comment by jpfss** [comment]
Thank for your response!I carefully find that  it seems cause by the “space”  and I have tried another property .It works well. The picture as follows:
![image](https://user-images.githubusercontent.com/8890352/66281327-66bbfd00-e8ed-11e9-8208-05827dfa5502.png)

**Comment by jexp** [comment]
I guess you have to be more careful on data import then :)

**Comment by jpfss** [comment]
yes,yes!!thank you very much！！
