### ISSUE TITLE
apoc.warmup.run does not actually load all nodes and relationships

### ISSUE THREAD

**Issue by fpavageau** [neo4j-contrib/neo4j-apoc-procedures#131]
See [that SO question](https://stackoverflow.com/q/39286740/1350869) for an example.

The problem is that the procedure retrieves the number of nodes (resp. relationships) and then tries to load all nodes (resp. relationships) [with ids between 1 and that number](https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/3.0.4.1/src/main/java/apoc/warmup/Warmup.java#L44), as if they were all sequentially numbered. It's only true for a graph where no node or relationship has been deleted (and its id not reused).

I believe a better way of forcing the load of all nodes would be to ask for the maximum id: either that's enough, because that requires scanning all nodes, or it's not and the current query can then be used to iterate through them all, using that maximum id instead of the number of items.

The first option seems to be enough for the moment: executing
```
PROFILE MATCH (n) RETURN count(n) AS count, max(id(n)) AS maxId
```
shows about the same number of DB hits as I have nodes, and takes between 650 ms and 850 ms for 1.4 million nodes on my machine.
```
+-------------------+
| count   | maxId   |
+-------------------+
| 1398103 | 1398103 |
+-------------------+
1 row
644 ms

Compiler CYPHER 3.0

Planner COST

Runtime INTERPRETED

+-------------------+----------------+---------+---------+--------------+--------------+
| Operator          | Estimated Rows | Rows    | DB Hits | Variables    | Other        |
+-------------------+----------------+---------+---------+--------------+--------------+
| +ProduceResults   |           1182 |       1 |       0 | count, maxId | count, maxId |
| |                 +----------------+---------+---------+--------------+--------------+
| +EagerAggregation |           1182 |       1 |       0 | count, maxId |              |
| |                 +----------------+---------+---------+--------------+--------------+
| +AllNodesScan     |        1398103 | 1398103 | 1398104 | n            |              |
+-------------------+----------------+---------+---------+--------------+--------------+

Total database accesses: 1398104
```

**Comment by jexp** [comment]
Good point. 

We can ask the store for the high id. 


Von meinem iPhone gesendet

**Comment by fpavageau** [comment]
I guess this can be closed since the PR has been merged.
