### ISSUE TITLE
apoc.meta.data() reports wrong property type information

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-apoc-procedures#1319]
Replication that worked for me:

```
create (:A { x: 1 }), (:A { x: 'Foo' });
create (:B { x: 'Foo' }), (:B { x: 'Foo' }), (:B { x: 1 });
CALL apoc.meta.data();
```

This setup is intentionally to confuse APOC.   For both labels A and B, the property X is typed both string and long.

The APOC call:

![Screen Shot 2019-10-17 at 2 48 47 PM](https://user-images.githubusercontent.com/5471710/67038378-43fbc680-f0ed-11e9-979b-632b6e9e3edf.png)

This procedure uses a sampling configuration as specified by the config parameters, which is a MetaConfig object.  The sampling appears respected, but the property type information stored in  the MetaResult class is "last type in wins".  

I would say this behavior is incorrect.  There are two possible correct behaviors:

1. Return an array of different types the property could have, as observed in the sample ["Long", "String"]
2. Perform some type-coercion, and always report "String" as a single property type, because it is the widest of all observed types.

**Comment by moxious** [comment]
I found this because the issue is related to a PR in progress.  In that PR APOC will have different stored procs that return the array of encountered types (fix suggestion 1) . https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/1318

**Comment by jexp** [comment]
for the type field I would probably coerce to string
and add another field `types` that has the full list either single element or multi

**Comment by jexp** [comment]
Probably also need to adapt in apoc.meta.schema
