### ISSUE TITLE
asProcedure with parameters seems to throw error

### ISSUE THREAD

**Issue by borick** [neo4j-contrib/neo4j-apoc-procedures#1321]
## Expected Behavior (Mandatory)

- Creating a procedure with parameter works

## Actual Behavior (Mandatory)

Trying the example from: http://neo4j-contrib.github.io/neo4j-apoc-procedures/3.5/cypher-execution/cypher-based-procedures-functions/

I get: Neo.ClientError.Statement.TypeError: Can't coerce `String("get neighbours of a person")` to List<String>

If I change the last parameter into a list, I get: Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `apoc.custom.asProcedure`: Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1

## How to Reproduce the Problem

- Create procedure using example from docs

### Simple Dataset (where it's possible)

```
CALL apoc.custom.asProcedure('neighbours',
  'MATCH (n:Person {name:$name})-->(nb) RETURN nb as neighbour','read',
  [['neighbour','NODE']],[['name','STRING'], 'get neighbours of a person']);
```

### Steps (Mandatory)

  1. Load the cypher into bolt after enabling apoc
  1. view the error

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: MacOSX
  - Neo4j: Tried 3.5.8 and 3.5.12
  - Neo4j-Apoc: apoc-3.5.0.5-all.jar

**Comment by conker84** [comment]
You wrote a malformed query, please try with this:

```
CALL apoc.custom.asProcedure('neighbours',
'MATCH (n:Person {name:$name})-->(nb) RETURN nb as neighbour',
'read', [['neighbour', 'NODE']], [['name', 'STRING']], 'get neighbours of a person');
```

**Comment by borick** [comment]
@conker84 Thanks for the update - can the example cypher be corrected in the documentation? Will try it.
