### ISSUE TITLE
APOC for 4.0

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#1323]
the 4.0 artifacts should now be in the bintray repository

so we should be able to move ahead with integrating/building/testing @sarmbruster's 4.0 branch and perhaps cut a first release

**Comment by marvin-hansen** [comment]
Is there any possible way to add APOC to 4.0-RC1? 
 
I saw some activity in the experimental docker repo so I inspected the Docker file and found APOC missing. Now, I would love to set up a sample docker image with APOC  to testdrive a migration before the end of the year. 
However,  for some reason, APOC isn't going to install on the 4.0 beta / RC version in neo4j Desktop and installation documentation of APOC in the docker image is really hard to find. 

How can I prepare a migration from 3.5 to 4.0 when APOC is simply missing the RC build?

**Comment by sarmbruster** [comment]
There's a pre-release of APOC 4.0.0 RC1 available at https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/tag/4.0.0-rc01.

Recent version of the neo4j docker image allow for auto-downloading apoc. Therefore you need to supply 

```
-e NEO4JLABS_PLUGINS=\[\"apoc\"\] \
```

as addtional env parameter to your `docker run` command.

**Comment by marvin-hansen** [comment]
Thanks a lot, that's super helpful!
