### ISSUE TITLE
Add apoc.jdbc.<key>.password and apoc.jdbc.<key>.user to config

### ISSUE THREAD

**Issue by andrewswanton** [neo4j-contrib/neo4j-apoc-procedures#1325]
## Feature description
Allow users to specify user and password password for jdbc connections within neo4j.conf.

The issue is outlined [here](https://community.neo4j.com/t/escape-special-characters-within-jdbc-connection-string/11430)

Quick summary:  As my password contains a '@' the only way I can connect to my database is as follows:

```
CALL apoc.load.jdbc('jdbc:oracle:thin:@HOST:PORT/SERVICE_NAME',
'select * from dual',
[],
{credentials:{user:'USER', password: 'P@SSW*RD'}}) 
YIELD row 
RETURN row
```
However, this means the password has to be hard coded and visible in the cypher script.

As the user can already specify `apoc.jdbc.<key>.url=jdbc:oracle:thin:USER/P@SSW*RD@HOST:PORT/SERVICENAME` within neo4j.conf

allowing the additional user and password options who be the best solution

`apoc.jdbc.<key>.password=P@SSW*RD`
`apoc.jdbc.<key>.user=USER`

## Considered alternatives
1.  use 'jdbc:oracle:thin:USER/P@SSW*RD@HOST:PORT/SERVICE_NAME'
  this fails as the host gets misidentified as 'SSW*RD@HOST' instead of 'HOST'
2. Escape the offending character - the documentation I've read so far does not suggest that there is a way to escape special characters from the connection string. The alternative approach is to pass the user and password separately to driver.
3. Store the credentials as a csv file in the import directory. We could them load and use these, but it would be messy and overly complex each time a connection is needed to be made

## How this feature can improve the project?
This will allow users to develop processes which import data from their database in a secure way.

**Comment by vga91** [comment]
@andrewswanton 
To resolve this problem you can use the `apoc.static.*` procedures https://neo4j.com/labs/apoc/4.2/overview/apoc.static/.
So, for example, to call a jdbc with user and password you can execute:
```
CALL apoc.load.jdbc('jdbc:oracle:thin:@HOST:PORT/SERVICE_NAME',
'select * from dual', [],
{credentials:{user:apoc.static.get("apoc.static.jdbc.<key>.user"), password: apoc.static.get("apoc.static.jdbc.<key>.password")}}) 
YIELD row 
RETURN row
```
where `apoc.static.jdbc.<key>.user` and `apoc.static.jdbc.<key>.password` are set via `apoc.static.set(..)` or `apoc.conf`

**Comment by conker84** [comment]
Closing this as the solution has been posted

**Comment by conker84** [comment]
Feel free to reopen in case you have more info to share
