### ISSUE TITLE
apoc.truncate

### ISSUE THREAD

**Issue by eastlondoner** [neo4j-contrib/neo4j-apoc-procedures#1337]
## Feature description (Mandatory)

This should wipe a database without causing an OOM. It will therefore need to not be transactional i.e. if it encounters an error during execution it could result in a partially deleted graph rather than a totally deleted graph.

under the hood it should do something like this:
```
call apoc.periodic.iterate("cypher runtime=slotted match ()-[r]->() return r","delete r", {batchSize:10000,iterateList:true})
call apoc.periodic.iterate("cypher runtime=slotted match (n) return n","delete n", {batchSize:10000,iterateList:true})
```

**Comment by eastlondoner** [comment]
it might make sense to put this in `apoc.periodic`
i.e. `apoc.periodic.truncate`
Then it's slightly more obvious that normal transaction rules don't apply

**Comment by jexp** [comment]
actually it should just use the java API in parallel transactions. or perhaps kernel api.

```
db.getAllRelationships().stream().chunk().foreach(Relationship::delete);
db.getAllNodes().parallelStream().chunk().foreach(Node::delete);
```

But cypher would work too.
Nodes can be deleted in parallel, relationships is a bit more tricky.


to delete clusters concurrently it would be kinda cool to run a clustering algo first,
then delete the clusters innards in separate tx and at the end the boundary nodes and their rels sequentially.

**Comment by jexp** [comment]
periodically truncate the database :)

**Comment by eastlondoner** [comment]
It would be a bonus if this had a configuration option to drop all indexes.
