### ISSUE TITLE
Feature Request: allSimpleCycles and shortestCycle

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j-contrib/neo4j-apoc-procedures#134]
AllSimplePaths is great, but it can't be used to find simple cycles where the start and end node are the same (the resulting path is just the start/end node).

There is a workaround where you can find allSimplePaths to the last step of the cycle, all adjacent nodes that have a relationship directed to the start/end node.

This requests some implementation of finding all simple cycles, either by fixing allSimplePaths so it generates simple cycles when the start and end node are the same; or by allowing a minimum node count (to force traversal to at least one node); or by introducing a new procedure for this.

Also requested is an efficient shortest cycle implementation through a node.

**Comment by conker84** [comment]
We close this as for algos we have a different library
