### ISSUE TITLE
Astar returning a longer route.

### ISSUE THREAD

**Issue by Legolash2o** [neo4j-contrib/neo4j-apoc-procedures#1354]
I seem to be having an issue with Apoc aStar returning a longer route. I run the following code:

match(s:Node {id: "2197131"}), (e:Node { id: "2114064"})
CALL apoc.algo.aStar(s, e,'Rail>' ,'Length','lat','lon') YIELD path, weight
RETURN path, weight LIMIT 1

The above command returns the red route when it should return the green as that is a lot shorter; by both the hops and summed up "Length" values. Am I missing something obvious? 

![RouteError](https://user-images.githubusercontent.com/34819291/69192619-d80de300-0b1c-11ea-8c8c-4bcb1ad8f671.png)

The same call with Dijkstra seems to work fine.

match(s:Node {id: "2197131"}), (e:Node { id: "2114064"})
CALL apoc.algo.dijkstra(s, e, 'Rail>', 'Length') YIELD path, weight 
RETURN path, weight

public class Node {
    public long id {get;set;}
    public double lat {get;set;}
    public double lon {get;set;}
}

public class Rail {
    public double Length {get;set;}
}

**Comment by sarmbruster** [comment]
Do you have a minimal dataset available for investigation?

**Comment by Legolash2o** [comment]
Sorry, this seemed to be an issue on my part. I didn't order by total distance. If I limit the return to 1, I automatically assumed it would return the shortest.
