### ISSUE TITLE
4.0rc-1 CALL dbms.metrics.list() is not working

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-apoc-procedures#1368]
```
Failed to invoke procedure `apoc.metrics.list`: Caused by: java.lang.NullPointerException
```

Used with Neo4j 4.0.0rc1 in docker, together with [this release](https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/tag/4.0.0-rc01)

Unfortunately, no further output available in the logs.

**Comment by sarmbruster** [comment]
Did you try that on CE or EE ?

**Comment by moxious** [comment]
EE running in docker, like this:

https://github.com/moxious/halin/blob/v0.12.0/testrig/docker-compose.yml

**Comment by moxious** [comment]
Failed reproduction.  Further investigation - it's my fault.  In my local changes to the docker-compose file, I had the apoc plugin for all 3 nodes in the cluster in the same shared folder.  I was thinking this would work because after all each machine only needs read-only access to the JAR file, and why not have 1 copy instead of 3?   Anyway -- when you do that, you get these failures.  And when you split the JAR out into 3 copies, one per cluster node, no problem.

I have no idea why this happens but it isn't APOC's fault, closing this issue.
