### ISSUE TITLE
apoc.export.csv.graph incorrectly exports properties with datatype 'float'

### ISSUE THREAD

**Issue by p0macs** [neo4j-contrib/neo4j-apoc-procedures#1369]
When using the apoc.export.csv.graph with the parameter useType:true, then the FLOAT properties are not exported.
When using useType:false (the default) the the FLOAT property exported as string.

## Expected Behavior (Mandatory)
The property value should be exported and the header should contain "propname:float" for the property with type FLOAT

## Actual Behavior (Mandatory)
The header contains "propname:int" and the value is empty string

## How to Reproduce the Problem

CREATE (n:TestNode) SET n = {valFloat:toFloat(123), name:'NodeName'};
CALL apoc.graph.fromCypher("MATCH (n:TestNode) RETURN n", {}, 'TestNode.csv',{}) YIELD graph
CALL apoc.export.csv.graph(graph, null, {stream:true,useTypes:true}) YIELD properties, rows, data
return properties, rows, data;

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS:
  - Neo4j: 2.5.5
  - Neo4j-Apoc: 3.5.0.6

**Comment by cmaart** [comment]
How has this never been fixed? This makes `useTypes` config completely useless when values are missing in the csv export
