### ISSUE TITLE
Improve logging when there is NullPointerException with  apoc.periodic.iterate/apoc.load.csv

### ISSUE THREAD

**Issue by jphoulchand** [neo4j-contrib/neo4j-apoc-procedures#1374]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Expected Behavior (Mandatory)

Obtain a meaningful error message when using:
apoc.load.csv
apoc.periodic.iterate

## Actual Behavior (Mandatory)

NullPointerException
2019-11-29 20:36:46.734-0500 WARN [o.n.k.i.p.Procedures] Error during iterate.commit:
2019-11-29 20:36:46.734-0500 WARN [o.n.k.i.p.Procedures] 1 times: java.lang.NullPointerException

This error does not happen by setting parallel:false, retries to a non zero value.

### Simple Dataset (where it's possibile)

We unfortunately do not have this.

### Steps (Mandatory)

Use parallel:true with :
apoc.periodic.iterate
apoc.load.csv

### Versions

  - OS:
  - Neo4j:3.4.13 and 3.5.8
  - Neo4j-Apoc:3.4.0.6 and 3.5.0.4

**Comment by conker84** [comment]
Hi @jphoulchand I think that this one is related to the following PR that we merged: #1364 
Can you please verify it? And eventually close the issue

**Comment by jphoulchand** [comment]
Thanks Andrea for your help Andrea.

We made good progress.
I will close this once changes are commited and a jar is available.

Kind regards,

**Comment by jphoulchand** [comment]
Closing.
