### ISSUE TITLE
apoc.load.csv cannot parse files with backslash character in the data

### ISSUE THREAD

**Issue by p0macs** [neo4j-contrib/neo4j-apoc-procedures#1376]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Expected Behavior (Mandatory)
When creating CSV files with apoc.export.csv, the string data is enclosed in double quotes - which is correct. We should be able to import back those files with apoc.load.csv and retrieve the same data. Other tools can properly read this file. Apoc should not interpret the backslash as a string escape character.

## Actual Behavior (Mandatory)
When the string data field contains the backslash character in the last position, then the data line looks like this:
...,"VER: AX\GEARBOX\ASSEMBLY\",...
On loading this file however the backslash is interpreted as an escape character and the following message is thrown:
Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `apoc.load.csv`: Caused by: java.io.IOException: Unterminated quoted field at end of CSV line. Beginning of lost text: ...

Patching the CSV file and removing the last backslash allows the import, but the data is wrong:
"VER: AXGEARBOXASSEMBLY" - as you can see all the other backslash characters are removed too.

### Simple Dataset (where it's possibile)

```
//Insert here a set of Cypher statements that helps us to reproduce the problem

```

### Steps (Mandatory)

  1.
  1.
  1.

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: any
  - Neo4j: 3.5.12
  - Neo4j-Apoc: 3.5.0.5

**Comment by p0macs** [comment]
Funny, even this site can not properly display the data in the previous comment. It looks like there is no backslash before the terminating quote, but there is when I editing the comment. To show how it is looks like, I have to use double backslash at the end (but in reality there is only one)
...,"VER: AX\GEARBOX\ASSEMBLY\\",...

**Comment by xsrvmy** [comment]
Can confirm that I ran into this with apoc.import.csv as well
