### ISSUE TITLE
Add database name to apoc.run.cypher as optional last parameters

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#1382]
To allow Cypher execution in separate transactions against other databases than the current. 

To e.g. allow updating multiple db's with one statement or pull data from several local db's e.g. for comparisons ...

**Comment by conker84** [comment]
Now we can use the `USE` 😄 syntax (https://neo4j.com/docs/cypher-manual/current/clauses/use/)
