### ISSUE TITLE
Neo4j 4.0: Export to Cypher on non neo4j database

### ISSUE THREAD

**Issue by mneedham** [neo4j-contrib/neo4j-apoc-procedures#1390]
It seems like the export to Cypher procedures throw errors when run on the non default (`neo4j`) database. Below are screenshots of different errors that I received:

![image (18)](https://user-images.githubusercontent.com/13220/73190244-9ea9b300-411d-11ea-9bd7-c418eac9ee82.png)

![image (16)](https://user-images.githubusercontent.com/13220/73190254-a23d3a00-411d-11ea-9f30-b8041ad85a30.png)

Annoyingly it doesn't seem to happen one every graph I try it on, so I've sent the offending db to @sarmbruster

**Comment by conker84** [comment]
closed via 405b512
