### ISSUE TITLE
Failed to invoke procedure `apoc.load.driver`: Caused by: java.lang.RuntimeException: Could not load driver class com.mysql.jdbc.Driver com.mysql.jdbc.Driver

### ISSUE THREAD

**Issue by saidireddyM** [neo4j-contrib/neo4j-apoc-procedures#1400]
Hello Team,

I would like to do load mysql.jdbc.driver into neo4j but while loading i am facing this issue.
i don't know exactly which path i will mention and where i can mention.

could please help on the same.

Thanks
Saidireddy

**Comment by jexp** [comment]
Did you please the mysql jar into your plugins directory?
How did you call the procedure?

**Comment by saidireddyM** [comment]
please let me know plugins is nothing but neo4j plugins..?
![issue](https://user-images.githubusercontent.com/20071987/73827495-a8ba6880-4825-11ea-9374-8839d70cab4c.png)

I pasted mysql jar file into neo4j plugins still facing same issue.
and we need to set any classpath..??

Thanks
Saidireddy

**Comment by saidireddyM** [comment]
Hello Michael,

Can you please help on above the issue.

Thanks
Saidireddy

**Comment by sarmbruster** [comment]
Quoting from https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-api-changes.html
> The name of the class that implements java.sql.Driver in MySQL Connector/J has changed from com.mysql.jdbc.Driver to com.mysql.cj.jdbc.Driver. The old class name has been deprecated.

So not an APOC issue.
