### ISSUE TITLE
Failed to invoke procedure `apoc.load.jdbc`: Caused by: java.sql.SQLException: Java heap space

### ISSUE THREAD

**Issue by saidireddyM** [neo4j-contrib/neo4j-apoc-procedures#1406]
Hello,

When i was fetching the data after connecting the MySQL database i got the above the error.

Please help on the issue.

Thanks 
Saidireddy.

**Comment by sarmbruster** [comment]
This is not a bug, discuss this please on https://community.neo4j.org
