### ISSUE TITLE
apoc.import.csv fails when dash is present in id space

### ISSUE THREAD

**Issue by megatrond** [neo4j-contrib/neo4j-apoc-procedures#1412]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Expected Behavior (Mandatory)

Given the following csv: (as per the header format here: https://neo4j.com/docs/operations-manual/current/tools/import/file-header-format/#import-tool-id-spaces)

```
personId:ID(Person-ID),name:STRING
1,"Alice"
2,"Bob"
```

The procedure will throw an error:

```
Failed to invoke procedure `apoc.import.csv`: Caused by: java.lang.IllegalStateException: No match found
```

## Actual Behavior (Mandatory)

By switching the headers in the csv to use an underscore instead of dash in the id space, the import succeeds:

```
personId:ID(Person_ID),name:STRING
```

## How to Reproduce the Problem

Call apoc.import.csv on the file given

### Simple Dataset (where it's possibile)

```
personId:ID(Person-ID),name:STRING
1,"Alice"
2,"Bob"

```

### Steps (Mandatory)

  1. Call apoc.import.csv on the given dataset through neo4j remote interface

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: MacOS Catalina 10.15.2
  - Neo4j: 3.5.14 docker image
  - Neo4j-Apoc: 3.5

**Comment by szarnyasg** [comment]
This problem was also raised in https://community.neo4j.com/t/using-id-spaces-with-apoc-import-csv-throws-error/7015. I've sent a PR with a fix.
