### ISSUE TITLE
Change apoc.date.expire* names to apoc.ttl* and deprecate/redirect apoc.date.expire* procs

### ISSUE THREAD

**Issue by JMHReif** [neo4j-contrib/neo4j-apoc-procedures#1417]
Naming convention of apoc.date.expire and apoc.date.expireIn procedures is confusing with docs location (under Graph Updates section). Change naming and deprecate old procedures for clarity and consistency.

Move apoc.date.expire* to apoc.ttl.* naming and redirect/deprecate apoc.date.expire and apoc.date.expireIn.

**Comment by conker84** [comment]
closed via  acb3ad1
