### ISSUE TITLE
Remove procedures that are now handled with native date functionality in Neo4j

### ISSUE THREAD

**Issue by JMHReif** [neo4j-contrib/neo4j-apoc-procedures#1419]
Remove any procedures that are no longer needed with the built-in native date/temporal support in Neo4j. List of known procs/functions that may be obsolete are listed below.

- apoc.date.field 
- apoc.date.fields

Deprecate procedures and point to Neo4j native temporal functionality instead.

**Comment by JMHReif** [comment]
Example for same results....
APOC - apoc.date.field(dateInteger, 'years')
Native - datetime({epochMillis: apoc.date.parse(o.orderDate, "ms", "yyyy-MM-dd HH:mm:ss.SSS")}).year

**Comment by jexp** [comment]
Probably the native one is: `datetime({epochMillis: dateInteger}).year`

**Comment by conker84** [comment]
closed via acb3ad1
