### ISSUE TITLE
Read only option to disallow APOC from modifying the server filesystem

### ISSUE THREAD

**Issue by dhimmel** [neo4j-contrib/neo4j-apoc-procedures#142]
I have a public Neo4j instance ([more information](https://thinklab.com/discussion/hosting-hetionet-in-the-cloud-creating-a-public-neo4j-instance/216)) where I would like to provide users with the awesome APOC functionality. The database is read-only. However, I noticed when running `apoc.export.graphml.query`, APOC writes a file to the server's filesystem. Is there a way to prevent APOC from potentially cluttering or corrupting a Neo4j instance/filesystem?

**Comment by jexp** [comment]
There was another feature request for apoc to honor the import directory setting. 

Just have gotten around to implement it. 

A dedicated export directory setting might even make more sense. 

Von meinem iPhone gesendet

**Comment by sarmbruster** [comment]
Another approach would be using a java security manager for Neo4j's JVM, see https://docs.oracle.com/javase/tutorial/essential/environment/security.html. However configuring this might be tricky. But in principle you should be able to solve it with this.

**Comment by Meatballs1** [comment]
If you are running some form of public database where anyone can run custom queries I would seriously consider something like applocker so you can really lock down what they can do

**Comment by dhimmel** [comment]
I disabled the APOC plugin until a solution becomes available for these issues.

> If you are running some form of public database where anyone can run custom queries I would seriously consider something like applocker so you can really lock down what they can do

@Meatballs1, [AppLocker](https://technet.microsoft.com/en-us/library/dd759117(v=ws.11).aspx) appears to be a Windows program. We're running Neo4j from inside a linux Docker.

> Another approach would be using a [java security manager for Neo4j's JVM](https://docs.oracle.com/javase/tutorial/essential/environment/security.html):

@sarmbruster thanks. Probably a little much for me to deal with right now. Without APOC installed, I'm not aware of any methods to write arbitrary amounts of data to the server filesystem. But will keep this in mind if any problems arise.

**Comment by Meatballs1** [comment]
Derp, apparmor!
