### ISSUE TITLE
Config ALIAS not working in 4.0.0.4

### ISSUE THREAD

**Issue by renedlog** [neo4j-contrib/neo4j-apoc-procedures#1422]
The alias feature doesn't work with the newest APOC version 4.0.0.4 documented here: 
https://neo4j.com/docs/labs/apoc/current/database-integration/load-jdbc/

e.g. the setting: 
`apoc.jdbc.bigquery.url=some_connection_string`

just returns an error:
```Failed to invoke procedure `apoc.load.jdbc`: Caused by: java.lang.RuntimeException: No apoc.jdbc.bigquery.url url specified```

**Comment by conker84** [comment]
@renedlog can you try with the logs?

**Comment by conker84** [comment]
@renedlog can you share the logs?

**Comment by conker84** [comment]
@renedlog ping

**Comment by renedlog** [comment]
@conker84 sorry for the late response. I will need to upgrade to Neo4j 4.0 again and install the plugin again before I can send you the logs. 
I had to revert back to an older version due to too many issues with the newest version. 
But it's at least reproducible if you want to try it your own... the issue occurred on every Node I've upgraded to Neo4J 4.0 with 4.0.0.4 APOC.

**Comment by sarmbruster** [comment]
did you put your config into `apoc.conf` or `neo4j.conf`. In 4.0 they should be in `apoc.conf`, see https://neo4j.com/docs/labs/apoc/4.0/config/#_location_of_config_options

**Comment by renedlog** [comment]
-.- 
thx. that was probably the error
