### ISSUE TITLE
Make file export network friendly

### ISSUE THREAD

**Issue by dhimmel** [neo4j-contrib/neo4j-apoc-procedures#143]
`apoc.export` contains procedures packages for exporting Neo4j (sub)graphs such as `apoc.export.cypher.data` and `apoc.export.graphml.data`. Currently, these procedures take a `file` argument which specifies a path on the Neo4j server's filesystem.

However, users that are accessing the Neo4j server over a network connection will often want to export the file relative to their access point rather than on the server. For example, a Neo4j Browser user would want to export the file to either text in their browser or a downloadable file.

Not sure what solutions are feasible, but it seems like these file-export functions have limited functionality if they can't be used over the network. Would a quick fix be exporting the text to a string variable in Cypher (for example `path = false` would mean the procedure returns the text)?

**Comment by jexp** [comment]
Good idea, let me look into that.

I'm not sure what's best, returning one single cell blob of text or one line per row. Probably the former.

We could use "null" as value to indicate streaming. Which is valid for "String".

**Comment by jexp** [comment]
@dhimmel do you have a concrete idea on how to return that data?

**Comment by dhimmel** [comment]
> do you have a concrete idea on how to return that data?

No, but I can think of two possible options:

1. Returning text that displays in a browser frame.
2. Downloading the text file as if you clicked on a download link in your browser.

1 is dangerous if the resulting text file is large... so I think 2 is probably a better default. Technically, I'm not sure of the feasibility of either approach.

**Comment by Joshfindit** [comment]
This is related, but I'll leave it to the maintainers whether it's a separate request:

Looking to add export capabilities to the back-end of an API.
Would like to be able to request something like `call apoc.export.cypher.query("MATCH (m:Movie)<-[r:DIRECTED]-(p:Person) WHERE m.title = "The Matrix" RETURN m,r,p", string, {batchSize:10});` and get back the raw Cypher as text.

Obviously, it would be our responsibility to sanity-check the query to make sure nothing huge is returned.
