### ISSUE TITLE
neo4j seems to use the first apoc jar it finds

### ISSUE THREAD

**Issue by StrangeTcy** [neo4j-contrib/neo4j-apoc-procedures#1439]
## Expected Behavior (Mandatory)
Neo4j server is started with the correct version of apoc available

## Actual Behavior (Mandatory)
Neo4j fails to start and logs a really verbose error message in the logs

## How to Reproduce the Problem
- Install neo4j 
- manually download both `apoc-3.5.0.9-all.jar` and `apoc-4.0.0.4-all.jar` to $NEO4J_HOME/plugins
- run `neo4j start` in console

if you rename  `apoc-3.5.0.9-all.jar`, neo4j seems to find the correct (only, now) version of apoc and starts normally 

##Currently used versions

### Versions

  - OS: Ubuntu 18.04
  - Neo4j: 4.0.1
  - Neo4j-Apoc: 3.5.0.9 and 4.0.0.4

**Comment by jexp** [comment]
you should _never_ have 2 conflicting jars there, the load order is totally random.

Please make sure to always have just *one* jar per library in your plugins directory !!!
