### ISSUE TITLE
apoc.json.path() returns nulls where it should not

### ISSUE THREAD

**Issue by tomzeppenfeldt** [neo4j-contrib/neo4j-apoc-procedures#1445]
## Guidelines

When using the  attached sourceTree on https://jsonpath.curiousconcept.com/ with the expression
     `$..columns`
I get the correct list of results.

## Expected Behavior 
apoc.json.path(tree,'$..columns') should return correct results.

## Actual Behavior 
apoc.json.path(tree,'$..columns') inserts nulls. See attached files for input and output

##Attachments
[jsonPathResult.txt](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/4323980/jsonPathResult.txt)
[sourceTree.txt](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/4323981/sourceTree.txt)

### Versions

  - OS: Linux
  - Neo4j: 3.5.4
  - Neo4j-Apoc: 3.5.0.4

**Comment by tomzeppenfeldt** [comment]
also tried with apoc 3.5.0.9  :  issue persists.

**Comment by lqst** [comment]
@tomzeppenfeldt I am looking into this. The json path function is using https://github.com/json-path/JsonPath 2.4.0. With the DEFAULT_PATH_LEAF_TO_NULL enabled. Need to investigate further how other things depends on this.

In the meantime, maybe you can get around this through filtering?

`[row in apoc.json.path($tree,'$..columns') where row is not null]`

What aslo comes to mind as a concern, is that other users may depend on null here as and indication that "json path was not found".

Maybe we will have to add a third optional argument for config.
