### ISSUE TITLE
apoc.uuid.install broken

### ISSUE THREAD

**Issue by desmap** [neo4j-contrib/neo4j-apoc-procedures#1447]
copy n paste from: https://github.com/neo4j/neo4j/issues/12428

This on cyper-shell: `CALL apoc.uuid.install('User', {addToExistingNodes: true, uuidProperty: 'uuid'}) yield label, installed, properties, batchComputationResult;`

leads to

`Unknown procedure output: 'batchComputationResult' (line 2, column 118 (offset: 118)) "CALL apoc.uuid.install('User', {addToExistingNodes: true, uuidProperty: 'uuid'}) yield label, installed, properties, batchComputationResult;"`

and batch... is marked a line below

My docker-compose.yml has these envs...
```
      - NEO4J_apoc_uuid_enabled=true
      - NEO4JLABS_PLUGINS=["apoc"]
```

- Neo4j version: 4.0.1
- OS: Your docker-image

Besides, your docs don't say if the uuids are saved as binaries or not. If not => no-go. And, why do I have to enable uuids? This is a must-feature considering neo4j weird internal ids (with their reuse issue), i know this would be an issue on your docker image repo but I am short on time.

**Comment by jexp** [comment]
Saved as compressed strings aka binary see the neo4j docs

**Comment by desmap** [comment]
I just checked the docs and couldn't find any note that uuids are saved as compressed string.

and do you know if the docker img does work now?

**Comment by jexp** [comment]
I'm really sorry it seems it has been removed, I'll ask the team what happend 

https://neo4j.com/docs/operations-manual/3.5/performance/property-compression/
