### ISSUE TITLE
apoc.custom.asProcedure is broken for procedure names with '.' in them.

### ISSUE THREAD

**Issue by kraney** [neo4j-contrib/neo4j-apoc-procedures#1448]
#  Expected Behavior (Mandatory)

A procedure should be created with the given name. For example, CALL apoc.custom.asProcedure('env.get') should result in the procedure custom.env.get

## Actual Behavior (Mandatory)

Command completion in the web UI will show custom.env.get. However, it does not exist and will fail if called.

Instead, everything up to the last '.' is lost, and you get a procedure custom.get()

If you create another procedure that differs by the lost part of the name - for example, apoc.custom.asProcedure('path.get'), creation succeeds but it ends up with the same name as the first. Which is actually callable is an open question.

## How to Reproduce the Problem

```
CALL apoc.custom.asProcedure('env.get', "RETURN null", 'write', [], [], "Pretend to get an env var");
CALL custom.env.get()
```

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: Linux
  - Neo4j: 4.0.1-enterprise
  - Neo4j-Apoc: 4.0.0.4

**Comment by kraney** [comment]
Actually, immediately after creation it seems to work, although there's the extra procedure with the shortened name. After db restart, it fails.

**Comment by jexp** [comment]
@conker84 can we add a test for this.
The after restart should also work, I think @sarmbruster stored these now in the system database, or? Perhaps there was something lost in translation.
