### ISSUE TITLE
Unable to get static variables in APOC 4.0.0.4

### ISSUE THREAD

**Issue by fenre-s** [neo4j-contrib/neo4j-apoc-procedures#1452]
## Guidelines

After upgrading neo4j/apoc, I noticed I could no longer use `apoc.static.getAll()` or `apoc.static.get()`.  

Under version 3.5.x I had defined several static variables in neo4j.conf.  After migrating to apoc 4.0.0.4, I have now moved those to apoc.conf (as described in https://neo4j.com/docs/labs/apoc/4.0/config/).

apoc.static.myapi.token=[SOME_TOKEN]
apoc.static.myapi.location=[SOME_LOCATION].

After doing this, I noticed the key/values are present when I go to terminal and type `printenv`.  However, when I try to access those variables in cypher queries, from neo4j browser, I either get an error or a null value.

Here is how I was accessing them before:

```

CALL apoc.static.getAll("myapi") yield value AS myapi
CALL apoc.load.jsonParams(myapi.location + 'example?arg=foo',{Authorization:"Token " + myapi.token},null) yield value as somedata

[...]

```

With apoc 4.0.0.4, this results in the following error; which I believe is due to this getting converted from a procedure to a function.

> There is no procedure with the name `apoc.static.getAll` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.

Following the documentation for [static value storage](https://neo4j.com/docs/labs/apoc/4.0/misc/static-values/), I've also tried to access the values using: `RETURN apoc.static.get("myapi.location") AS value`.  Unfortunately, that only returns null.

## Expected Behavior (Mandatory)

Value of static storage values would be returned.

## Actual Behavior (Mandatory)

Error or null values returned.

### Steps (Mandatory)

1.  Install newest version of neo4j desktop for macOS.
2.  Create a new graph (version 4.0.2).  
3.  Install APOC plugin (4.0.0.4)
4.  Open terminal from neo4j desktop and edit `$NEO4J_HOME/conf/apoc.conf` adding in the following lines below.
5.  Restart database and try to access the variables using `RETURN apoc.static.get("myapi.location") AS value`

Contents of apoc.conf:

```
apoc.static.myapi.token=[SOME_TOKEN]
apoc.static.myapi.location=[SOME_LOCATION].
```

If I open the terminal, from neo4j desktop, I do see the values are present as environment variables (when I type `printenv`).

### Versions

  - OS: macOS catalina
  - Neo4j: 1.2.5 (Desktop)
  - Neo4j-Apoc: 4.0.0.4

**Comment by graphadvantage** [comment]
The apoc.static.get and apoc.static.getALL procedures are now also implemented as functions...

However the root problem still exists:

```
2020-05-15 06:50:06.878+0000 WARN  Unrecognized setting. No declared setting with name: apoc.static.encrypt.key
```

The procedure apoc.static.set() stil works though:

```
CALL apoc.static.set("encrypt.key", "my-real-super-secret-encrypt-key")
```

And once the static var is set in the cache the function work fine.

Thanks Michaek

**Comment by jexp** [comment]
Interesting, they are just delegating to each other I think.

https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/4.0/src/main/java/apoc/cache/Static.java#L38

**Comment by vga91** [comment]
@fenre-s 
I didn't reproduce the problem, the procedure `RETURN apoc.static.get("myapi.location") AS value` works well with your `apoc.conf` example.
Please, can you try again with the latest version?
And, if the problem is still present, can you provide the `apoc.conf` file? (maybe there is some strange character that prevents correct reading)

**Comment by conker84** [comment]
@fenre-s ping

**Comment by conker84** [comment]
closed for lack of feedback, feel free to reopen in case you have more info
