### ISSUE TITLE
apoc.load.jdbcUpdate doesn't work with apoc.periodic.iterate

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-apoc-procedures#1458]
_From the community slack channel_

Hi All,
I have the following code (removed and changed column names for privacy reasons, so it may not look completely proper), using apoc.periodic.iterate, it doesn't give any errors, but the data is not found in the sqlserver database. If I run the code without the apoc.periodic.iterate, the database is filled properly.

```
// Read project
CALL apoc.periodic.iterate("
MATCH (p:Project)
WHERE p.p6_id = 'LVL1-NEO4J' 
WITH p.p6_wbs_object_id AS col2
                ,p.p6_object_id AS col3
// Find all LVL1 activities
MATCH (n:LVL1) WITH collect(n) AS b, col2, col3 UNWIND range(0, size(b)-1) AS pos WITH b[pos] AS n, col2, col3 RETURN n{.*, col2, col3}","CALL apoc.load.jdbcUpdate('jdbc:sqlserver://<connection_settings>','INSERT INTO activities (col1, col2, col3) values(?,?,?)',[n.col1, n.col2, n.col3]) YIELD row RETURN 'Done'", {batchSize: 100})
YIELD committedOperations, failedOperations, failedBatches, errorMessages
RETURN *
```

**Comment by jexp** [comment]
Did they try 

Return ... as n

**Comment by jexp** [comment]
Do the current modes make the planning ignore the procs?

**Comment by conker84** [comment]
I found @jexp the problem is that the procedure gets not executed because of the proc Mode. See the #1458

**Comment by jexp** [comment]
@conker84 why did we have to change load.jdbc too?
It always returns data so it should not be optimized away?

It seems that:

>>> Write procedures are eagerly loaded into memory and from just glancing at the procedure it doesn't look like it needs the @Write ?
