### ISSUE TITLE
apoc.coll.min() and max() do not work on temporal types

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j-contrib/neo4j-apoc-procedures#1463]
## Expected Behavior (Mandatory)
APOC max() and min() functions should work on temporal types

## Actual Behavior (Mandatory)
They don't. We get an error.

### Simple Dataset (where it's possibile)
No dataset needed

### Steps (Mandatory)

`return apoc.coll.max([date(), date() - duration('p5M')])`
results in the following errro:

`Failed to invoke function `apoc.coll.max`: Caused by: java.lang.ClassCastException: java.time.LocalDate cannot be cast to java.lang.Number`
  

### Versions

  - OS: Mac OS Mojave
  - Neo4j: 3.5.16
  - Neo4j-Apoc: 3.5.0.9 (and presumably everything below, likely includes 4.0.0.x)

**Comment by jexp** [comment]
Merged, @InverseFalcon
