### ISSUE TITLE
Unable to invoke jdbc alias in Neo4j 4.0 with Apoc: 4.0.0.4

### ISSUE THREAD

**Issue by bigdatavik** [neo4j-contrib/neo4j-apoc-procedures#1466]
As per the documentation, in Neo4j 4.0 we need to create the  jdbc alias  i.e apoc.jdbc.<key>.uri=jdbc-url-with-credentials in the $NEO4J_HOME/conf/apoc.conf file.

The same was created as below in the apoc.conf file:
apoc.jdbc.myalias.url=jdbc:mysql://localhost:3306/northwind?user=root&password=abcdef&serverTimezone=UTC

Documentation Reference:
https://neo4j.com/docs/labs/apoc/4.0/config/#config-reference

Note:
A quick note that in Neo4j 3.5, the alias url needs to be put in the neo4j.conf itself. I tried that and had no issues running the code in Neo4j 3.5.16.

## Expected Behavior in Neo4j 4.0 (Mandatory)

call apoc.load.driver('com.mysql.jdbc.Driver')
CALL apoc.load.jdbc('myalias','select * from orders') YIELD row
should return rows

## Actual Behavior in Neo4j 4.0 (Mandatory)
I get an error:
Failed to invoke procedure `apoc.load.jdbc`: Caused by: java.lang.RuntimeException: No apoc.jdbc.myalias.url url specified

### Simple Dataset (where it's possibile)

```
//Insert here a set of Cypher statements that helps us to reproduce the problem

```

### Steps (Mandatory)

  1.
  1.
  1.

## Screenshots (where it's possibile)
![image](https://user-images.githubusercontent.com/25273262/77927252-10fd5780-7275-11ea-8354-4f41cb76498a.png)

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: Mac OS, Catalina 10.15.3 
  - Neo4j: 4.0
  - Neo4j-Apoc: 4.0.0.4

**Comment by jexp** [comment]
Did you try to use apoc.conf instead?

4.0 doesn't allow additional things into the neo4j.conf that are not declared in the code.

**Comment by conker84** [comment]
closed for lack of feedback, feel free to reopen it in case you have more info to share
