### ISSUE TITLE
Procedure apoc.neighbors.tohop is broken

### ISSUE THREAD

**Issue by kubaizak** [neo4j-contrib/neo4j-apoc-procedures#1467]
## Guidelines

I executed procedure from the title on the graph given in the following [example](https://neo4j.com/docs/labs/apoc/current/graph-querying/neighbourhood-search/) and when distance parameter is higher that 1 it returns strange result, including starting node.

## Expected Behavior (Mandatory)
{name: "Mark"}, {name: "Joe"}

## Actual Behavior (Mandatory)
{name: "Mark"}, {name: "Praveena"}

## How to Reproduce the Problem

MATCH (p:Person {name: "Praveena"})
CALL apoc.neighbors.tohop(p, "FOLLOWS>", 2)
YIELD node
RETURN node

### Simple Dataset (where it's possibile)

MERGE (mark:Person {name: "Mark"})
MERGE (praveena:Person {name: "Praveena"})
MERGE (joe:Person {name: "Joe"})
MERGE (lju:Person {name: "Lju"})
MERGE (michael:Person {name: "Michael"})
MERGE (emil:Person {name: "Emil"})
MERGE (ryan:Person {name: "Ryan"})

MERGE (ryan)-[:FOLLOWS]->(joe)
MERGE (joe)-[:FOLLOWS]->(mark)
MERGE (mark)-[:FOLLOWS]->(emil)
MERGE (michael)-[:KNOWS]-(emil)
MERGE (michael)-[:KNOWS]-(lju)
MERGE (michael)-[:KNOWS]-(praveena)
MERGE (emil)-[:FOLLOWS]->(joe)
MERGE (praveena)-[:FOLLOWS]->(joe)

### Steps (Mandatory)

  1.
  1.
  1.

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: 10.15.4
  - Neo4j: 4.0.3
  - Neo4j-Apoc:

**Comment by vga91** [comment]
@kubaizak 
I was unable to replicate the problem, the procedure returns `(p:Person {name: "Mark"})` and `(p:Person {name: "Joe"})`.
Can you try with the latest APOC version?
