### ISSUE TITLE
[QUESTION] Why does formating a duration with 0 hours using temporal.format returns 12 hours

### ISSUE THREAD

**Issue by es50678** [neo4j-contrib/neo4j-apoc-procedures#1481]
Hi!

Thanks for reading through this issue. I understand that issues are typically used to report bugs or feature requests. I hope that I can be forgiven for posting a question. I'm just trying to learn more about formatting dates using apoc & cypher functions. 

I'm confused on how formatting durations works using the `temporal.format` function. When passing in a duration with 0hours and a format of `hh:mm:ss` the result is a string that suggest a duration of 12 hours.

```
RETURN apoc.temporal.format(duration("P0Y0M0W0DT0H3M30S"), 'hh:mm:ss');
=> "12:03:30"
# I would expect the return value to be 0:03:30

RETURN apoc.temporal.format(duration("P0Y0M0W0DT12H3M30S"), 'hh:mm:ss')
=> "12:03:30"
# this makes sense to me

RETURN apoc.temporal.format(duration("P0Y0M0W0DT1H3M30S"), 'hh:mm:ss')
=>"01:03:30"
# this also makes sense

RETURN apoc.temporal.format(duration("P0Y0M0W0DT13H3M30S"), 'hh:mm:ss')
=>"01:03:30"
# this throws me off again.
```

It's pretty clear that I'm misunderstanding something about either how durations work or how the format function works. I'm just looking for resources on where to learn this information. 

I've read through the following resources:
https://neo4j.com/docs/labs/apoc/current/temporal/temporal-conversions/

https://neo4j.com/docs/labs/apoc/current/temporal/datetime-conversions/

https://neo4j.com/docs/cypher-manual/current/syntax/temporal/#cypher-temporal-durations

https://neo4j.com/docs/cypher-manual/current/functions/temporal/duration/#functions-duration-create-string

Maybe I keep overlooking something in these resources. If so, I would love for it to be pointed out to me.

**Comment by jexp** [comment]
It actually uses internally datetime formats. Which might not be ideal for durations. 

And hh is hours in 12-hour-format which has an extra fiel for am/pm

Try HH for 24h format

You might then also try to use the field for day of year 

https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html

**Comment by es50678** [comment]
@jexp Thank you for your response and your help! I've found out what to do and learned a lot about date/time formats along the way. I started with the doc you've provided and made my way to [DateTimeFormatter docs](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html) 

`'HH:mm:ss'` is what I want/need.

```
RETURN apoc.temporal.format(duration("P0Y0M0W0DT0H3M30S"), 'HH:mm:ss');
=> "00:03:30"
# this also makes sense

RETURN apoc.temporal.format(duration("P0Y0M0W0DT12H3M30S"), 'HH:mm:ss')
=> "12:03:30"
# this makes sense to me

RETURN apoc.temporal.format(duration("P0Y0M0W0DT1H3M30S"), 'HH:mm:ss')
=>"01:03:30"
# this also makes sense

RETURN apoc.temporal.format(duration("P0Y0M0W0DT13H3M30S"), 'HH:mm:ss')
=>"13:03:30"
# this also makes sense

RETURN apoc.temporal.format(duration("P0Y0M0W0DT24H3M30S"), 'HH:mm:ss')
=>"00:03:30"
# this also makes sense, as the docs explain
```

Thank you so much for your help!
