### ISSUE TITLE
There is no procedure apoc.help() registered for this database instance.

### ISSUE THREAD

**Issue by ghost** [neo4j-contrib/neo4j-apoc-procedures#1492]
Hi everyone, 

I am new to neo4j and apoc, so my issue might be noobish, however, none of the solutions I googled for lead to any change! 

I receive the above error whenever I try to call apoc.help() 
the same holds true for apoc.xml.import  (or apoc.import.xml, as the neo4j Documentation states!) (https://neo4j.com/docs/labs/apoc/current/import/xml/#load-xml-examples-import-xml-directly) the same holds true for apoc.xml.parse 

apoc.load.xml, however works ... 

any hints?

**Comment by conker84** [comment]
@ghost you can download the fat jar for XLS support in the release section or by clicking on this link:
https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/4.2.0.4/apoc-xls-dependencies-4.2.0.4.jar
