### ISSUE TITLE
wrong encoding / processing of accentuated characters (diacritics)

### ISSUE THREAD

**Issue by v2belleville** [neo4j-contrib/neo4j-apoc-procedures#1493]
## Expected Behavior (Mandatory)
proper display of diacritics

## Actual Behavior (Mandatory)
conversion and encoding issues

apoc.text.snakeCase adds a - before accentuated characters (also before coma)

![image](https://user-images.githubusercontent.com/8779004/80839503-afc1fe80-8bfb-11ea-8990-36b40af13c27.png)

(I'm currently using this workaround because I only need é and ,)

![image](https://user-images.githubusercontent.com/8779004/80839574-d3854480-8bfb-11ea-898c-15625fb36608.png)

but  camel case is even more tricky

![image](https://user-images.githubusercontent.com/8779004/80839631-e730ab00-8bfb-11ea-8475-3a49742d9717.png)

Also when csv exporting , here is what I get : 

![image](https://user-images.githubusercontent.com/8779004/80839722-12b39580-8bfc-11ea-890f-fab1c4f3f042.png)
`CALL apoc.export.csv.query('MATCH (n) RETURN distinct labels(n);','node labels.csv', {delim: ';'});`
(or whatever export of accentuated characters

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: windows 10
  - Neo4j: desktop 1.2.7
  - Neo4j-Apoc: current

**Comment by jexp** [comment]
Perhaps there is a regexp flag for unicode or such.

**Comment by v2belleville** [comment]
what would a "regexp flag" be ? how can I check if there is one ?

**Comment by jexp** [comment]
Not 100% sure, seems to be things with codepoints and such.

https://stackoverflow.com/questions/8923729/checking-for-diacritics-with-a-regular-expression

We'd need to see how the apache.common.text library that we use deals with diacritics.
/cc @adam-cowley
