### ISSUE TITLE
Convert to list doesn't work when the input is a string

### ISSUE THREAD

**Issue by tomasonjo** [neo4j-contrib/neo4j-apoc-procedures#1495]
When running 

`RETURN apoc.convert.toList("['L545870', 'L545871', 'L545872']") as lines`

it returns a null value instead of an actual list. It is such a simple example that it could work IMO.

## Expected Behavior (Mandatory)

Returns a list element `['L545870', 'L545871', 'L545872']`

## Actual Behavior (Mandatory)

Returns null value

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: Ubuntu 16.04
  - Neo4j: 4.03
  - Neo4j-Apoc: 4.0.0.10

**Comment by jexp** [comment]
It’s meant as a typecasting function probably needs a better name

There is apoc.convert.jsonArray

**Comment by tomasonjo** [comment]
Looks like there is a function `apoc.convert.fromJsonList` that does exactly this! :)
