### ISSUE TITLE
Feature request: Add threshold parameter to NLP graph procedures

### ISSUE THREAD

**Issue by tomasonjo** [neo4j-contrib/neo4j-apoc-procedures#1496]
Currently, the `apoc.nlp.gcp.*.graph` procedures store all entities back to the graph and do not support defining a threshold level above which the entities should be stored. It would be nice if we could define a threshold of let's say 0.80, so only entities with the saliency of greater than 0.8 are stored back to the graph.

**Comment by tomasonjo** [comment]
And could we also store salience results as a property of the relationship back?

**Comment by mneedham** [comment]
This should be solved by the PR mentioned above.
