### ISSUE TITLE
apoc.custom.asProcedure doesn't work when returning Node, Path, Relationship

### ISSUE THREAD

**Issue by mbh86** [neo4j-contrib/neo4j-apoc-procedures#1498]
When I use the example of the [documentation ](https://neo4j.com/docs/labs/apoc/4.0/cypher-execution/cypher-based-procedures-functions/):

```
CALL apoc.custom.asProcedure('neighbours',
  'MATCH (n:Person {name:$name})-->(nb) RETURN nb as neighbour','read',
  [['neighbour','NODE']],[['name','STRING']], 'get neighbours of a person');

CALL custom.neighbours('Keanu Reeves') YIELD neighbour;
```

The result is 
```
Neo.DatabaseError.General.UnknownError
[Node[1]:org.neo4j.kernel.impl.core.NodeEntity] is not a supported property value
```
The error is the same with Path and Relationship.

### Versions

  - OS: Windows 10
  - Neo4j: 4.0.3 (using Docker)
  - Neo4j-Apoc: 4.0.0.7

**Comment by mbh86** [comment]
For information, the previous works well on the following version:
  - OS: Windows 10
  - Neo4j: 3.5.17 (using Docker)
  - Neo4j-Apoc: 3.5.0.11

So this is a **problem only for version 4** of Neo4j-Apoc.

**Comment by jexp** [comment]
Us ValueUtils.value or .of according to Pontus to convert the data.

**Comment by mbh86** [comment]
> Us ValueUtils.value or .of according to Pontus to convert the data.

Can you be more specific please? Are you refering to Java source code edit?

**Comment by augonis** [comment]
I encountered this as well and investigated a bit.
I found that here
https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/0074eec204658a793c78931213c6b7a9e77743f4/src/main/java/apoc/custom/CypherProceduresHandler.java#L575
`Values.of()` can't handle Nodes Relationships or paths.

If we handle those types separately like so using `ValueUtils.asAnyValue` the problem goes away
`else if (toConvert instanceof Entity || toConvert instanceof Path){
      return ValueUtils.asAnyValue(toConvert);
 }`

If this is acceptable solution I can make a PR

**Comment by jexp** [comment]
That would be great, thanks so much @augonis . Also if you could add a test for returning nodes / rels that would be great.
