### ISSUE TITLE
apoc.load.csv does not skip properly

### ISSUE THREAD

**Issue by cybersam** [neo4j-contrib/neo4j-apoc-procedures#1505]
## Expected Behavior (Mandatory)

- The `skip` option should produce proper results. For example, `{skip: 1}` should return data for every other CSV file line.

## Actual Behavior (Mandatory)

- `{skip: 1}` produces no results. So, there is no way to get every other line from the file.
  - However, `{skip: 1, limit: 1}` does return just the second data line, as expected.
- Aside: oddly, `{skip: -1}` returns every line, but with a starting `lineNo` of `-1`.

### Simple Dataset (where it's possibile)

    name
    Selma
    Rana
    Selina
    Sam
    Fred

### Steps (Mandatory)

  1. The query `CALL apoc.load.csv('file:///test.csv', {skip: 1}) YIELD map RETURN *` *should* produce this result:

    ╒═════════════════╕
    │"map"            │
    ╞═════════════════╡
    │{"name":"Rana"}  │
    ├─────────────────┤
    │{"name":"Sam"}   │
    └─────────────────┘
but actually returns nothing.

### Versions

  - OS: Mac OSX 10.15.3
  - Neo4j: 4.0.3
  - Neo4j-Apoc: 4.0.0.9

**Comment by conker84** [comment]
[apoc-4.0.0.11-all.jar.zip](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/4610463/apoc-4.0.0.11-all.jar.zip)

Hi @cybersam thanks a lot for reaching us, can you please try with the jar above?
Please unzip it into the plugins dir.
Thanks a lot
