### ISSUE TITLE
Feature Request: expose isEqualCollection to cypher

### ISSUE THREAD

**Issue by dan-kez** [neo4j-contrib/neo4j-apoc-procedures#151]
See: [CollectionUtils#isEqualCollection](https://commons.apache.org/proper/commons-collections/apidocs/org/apache/commons/collections4/CollectionUtils.html#isEqualCollection%28java.util.Collection,%20java.util.Collection%29)

This would be very useful to check if two collections are the same. As far as I'm aware this isn't exposed to cypher.

**Comment by jexp** [comment]
Did you try in cypher `[1,2,3] = [1,2,3]` ?
Or where doesn't that hold true?

**Comment by InverseFalcon** [comment]
Unless I'm mistaken, isEqualCollection() ignores ordering, it returns true if all elements in both collections are the same, and the cardinality (# of occurrences) of each element are the same.

In Cypher, `[1,2,3] = [3,2,1]` returns false. An isEqualCollection() call on these would return true.

**Comment by jexp** [comment]
So `length(c1) = length(c2) AND apoc.coll.containsAll(c1,c2)` should do it?

**Comment by InverseFalcon** [comment]
Oddly enough, containsAll() doesn't seem to be available with apoc-3.1.0.2-all, I get an error if attempting to call it:

> There is no procedure with the name `apoc.coll.containsAll` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.

However, I don't think this would work, at least where elements of the collection repeat. This would work for [1,2,3] and [3,2,1], but would not work for [1,1,2,3] and [1,2,2,3], containsAll() in either direction would return true, and the length would be the same, but the cardinalities of the elements would be different.

**Comment by jexp** [comment]
It's now a function, so you can call it in-line.

But then isCollectionEqual is rather a disjunct() on sets which also exists
as function.
