### ISSUE TITLE
Add functions for apoc.convert.to<XXX>List that check and return List<String>, List<Node> etc

### ISSUE THREAD

**Issue by dmk255** [neo4j-contrib/neo4j-apoc-procedures#152]
This should output Collection<Node> rather than Collection<T>

```
CALL apoc.coll.intersection(Collection<Node>,Collection<Node>) yield value 
```

In the following case Collection<T> is correct (two different collection types, not sure of a good example)

```
CALL apoc.coll.intersection(Collection<Node>,Collection<T>) yield value 
```

Due to this you can't unwind and set labels on the intersection

**Comment by jexp** [comment]
It's a bit tricky as the procedure can only take a List<Object> and return a List<Object>

but what you can do after your unwind is to call apoc.convert.toNode() to turn the Any again into a node. type-wise.

**Comment by jexp** [comment]
We can add some functions for apoc.convert.toXXX that do List<String>, List<Node> etc.?

**Comment by jexp** [comment]
Already in.
