### ISSUE TITLE
getting error while generating extent reports

### ISSUE THREAD

**Issue by ramansubramani** [neo4j-contrib/neo4j-apoc-procedures#1542]
public class Practice {

	@Test
	public void loginTest() {	
		System.out.println("Hello world");	
		ExtentHtmlReporter reporter = new ExtentHtmlReporter("./Reports/result.html");
		ExtentReports extent = new ExtentReports();	
		extent.attachReporter(reporter);	
		ExtentTest logger = extent.createTest("loginTest");	
		logger.log(Status.INFO, "login");	
		extent.flush();	
	}
java.lang.NoClassDefFoundError: org/bson/types/ObjectId

**Comment by conker84** [comment]
@ramansubramani I think you're in the wrong repo, feel free to reopen in case you have more info
