### ISSUE TITLE
double data after call apoc.import.json

### ISSUE THREAD

**Issue by handsometang** [neo4j-contrib/neo4j-apoc-procedures#1543]
run neo4j with core mode 
ip1  leader
ip2 follower

1. use call apoc.export.json.all('db.json')
      nodes  550000
      relations 530000

2.drop database 

3.call apoc.import.json('db.json')

get new database
     nodes 1100000
     relations 1060000

  - OS: Debian 3.2.63-2 x86_64 GNU/Linux
  - Neo4j: 4.0.4
  - Neo4j-Apoc: 4.0

**Comment by conker84** [comment]
@handsometang can you try with the last version of apoc?

**Comment by conker84** [comment]
closed for lack of feedback, feel free to reopen in case you have more info
