### ISSUE TITLE
apoc.custom.asProcedure doesn't overwrite existing procedure by same name

### ISSUE THREAD

**Issue by augonis** [neo4j-contrib/neo4j-apoc-procedures#1555]
## To reproduce
I'll use the example of the documentation

Execute this twice
`CALL apoc.custom.asProcedure('neighbours',
  'MATCH (n:Person {name:$name})-->(nb) RETURN nb as neighbour','read',
  [['neighbour','NODE']],[['name','STRING']], 'get neighbours of a person');
`
then `CALL apoc.custom.list`

## Expected Behavior
(Assuming clean db) lists one procedure with name 'neighbours'

## Actual Behavior
 (Assuming clean db) lists two procedures with name 'neighbours'

##
You also can't remove the procedure with `CALL apoc.custom.removeProcedure('neighbours')` because that expects there to only be one record for that name and it freaks out when many are returned.

Also when restarting the db errors get logged, I suspect, for attempts of registering procedure of the same name repeatedly.

So there's two things to fix:

- `apoc.custom.asProcedure` to owerwrite existing procedures
- `apoc.custom.removeProcedure` to delete all "procedures" of name (to allow affected users fix their databases)

P.S. Maybe `apoc.custom.asFunction` has same issue, haven't checked.

### Versions

  - OS: Ubuntu 18.04
  - Neo4j: 4.0.4
  - Neo4j-Apoc: 4.0.0.15

**Comment by augonis** [comment]
I did some digging and found a typo in `Util.mergeNode`
https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/b87fdc594fbc9f3f92fb634240ab19d1f0dc01b0/src/main/java/apoc/util/Util.java#L867

`pairs[0].first(), pairs[1].other()` should be `pairs[0].first(), pairs[0].other()`
It makes a wrong lookup for existing Node and always maned a new node.

`Util.mergeNode` is also used in `apoc.custom.asFunction`, `apoc.uuid.install` and `apoc.trigger.add` so they could suffer similar problems

I can make PR for this fix and also change `apoc.custom.removeProcedure` to delete repeat procedures

**Comment by cg122** [comment]
Although it now overwrites existing procedure, the unseen procedure still can be executed, and it is the same for all the ever existed procedures (even removed by apoc.custom.removeProcedure).

**Comment by conker84** [comment]
@cg122 how can we replicate the problem?

**Comment by cg122** [comment]
I am using neo4j from docker, with neo4j:latest (4.2.4):
```
docker run -d \
    --name neo4j \
    --publish=7474:7474 --publish=7687:7687 \
    --env NEO4JLABS_PLUGINS='["graph-data-science","apoc"]' \
    --env NEO4J_apoc_export_file_enabled=true \
    --env NEO4J_apoc_import_file_enabled=true \
    --env NEO4J_apoc_import_file_use__neo4j__config=true \
    --env NEO4J_AUTH=neo4j/neo4j \
    neo4j:latest
```
From neo4j browser:
- First register a procedure:
```
call apoc.custom.asProcedure('test_ghost','RETURN 100 as result')
```
- register a procedure with the same name:
```
call apoc.custom.asProcedure('test_ghost','RETURN $count as result','read',[['result','int']],[['count','int']])
```
- check the registered procedure:
```
call apoc.custom.list
```

type | name | description | mode | statement | inputs | outputs | forceSingle
-- | -- | -- | -- | -- | -- | -- | --
1 | "procedure" | "test_ghost" | "" | "read" | "RETURN $count as result" | [["count", "integer"]] | [["result", "integer"]] | null

- run 'test_ghost' with parameter:
```
call custom.test_ghost(15)

--
1 | 15
```

- run 'test_ghost' without parameter:
```
call custom.test_ghost

--
1 | {   "result": 100 }
```

- remove procedure
```
call apoc.custom.removeProcedure('test_ghost')
```
- run 'test_ghost' without parameter still get the result
 ```
call custom.test_ghost

--
1 | {   "result": 100 }
```

- run 'test_ghost' with parameter get the error
 ```
call custom.test_ghost(15)

There is no procedure with the name `custom.test_ghost` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.
```
Seems only the last registered procedure is removed, the 'overwritten' one is still somewhere functioning.

**Comment by conker84** [comment]
@cg122 thank you so much that's not the same problem but it's another one because you're overloading the procedure, I created #1850 in order to track it
