### ISSUE TITLE
request trigger not be saved if syntactically incorrect

### ISSUE THREAD

**Issue by Dcanzano** [neo4j-contrib/neo4j-apoc-procedures#1556]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Expected Behavior (Mandatory)
one can successfully run apoc.trigger.add() and it saves but the trigger is syntactically incorrect
For example with Neo4j 4.0.4 and apoc-4.0.0.14-all.jar one can run

````
call apoc.trigger.add('myTrigger',
         "UNWIND ${createdRelationships} AS rel
         WITH rel
         WHERE TYPE(rel) IN ['KNOWS', 'DOES_NOT_KNOW']
         SET rel.createdDate = date(), rel.strength=1;",
         {phase:'after'});
````

and this indicates success and the trigger then appears in apoc.trigger.list();

However if you then create a node this results in error, for example

````
@neo4j> create (n:Person {name:'Emil'});
Error executing triggers {myTrigger=Invalid input '{': expected whitespace, an identifier or UnsignedDecimalInteger (line 1, column 9 (offset: 8))
"UNWIND ${createdRelationships} AS rel"
````

would like the ability for the trigger never to be saved if it is syntactically incorrect.   
Note the syntax issue in the trigger definition is that

````
         "UNWIND ${createdRelationships} AS rel
````

should be changed to

````
         "UNWIND $createdRelationships AS rel
````

Currently used versions

### Versions

  - OS: Ubuntu 19
  - Neo4j: 4.0.4 
  - Neo4j-Apoc:  apoc-4.0.0.14-all.jar

**Comment by jexp** [comment]
We should do this also with other deferred execution procedures to test statements with explain and fail fast @conker84
