### ISSUE TITLE
Add Apache arrow read / write support

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#1564]
To better interop with other frameworks Like spark, kafka, etc. Align format with Graphistry 

Consider also streaming the raw format back. 

https://www.kdnuggets.com/2018/01/supercharging-visualization-apache-arrow.html

**Comment by conker84** [comment]
https://labs.graphistry.com/docs/docs_api.html#link

**Comment by jexp** [comment]
@lmeyerov can you point @conker84 to the graph-arrow format that you support in Graphistry

**Comment by lmeyerov** [comment]
Hi @conker84 @jexp  sure thing: 

-- raw Apache Arrow over REST API: https://hub.graphistry.com/docs/api/#upload2 . Conceptually, JSON bindings file (`src: colX, dst: colY, color: colZ, ..`), edges.arrow typed columnar properties table, and optional nodes.arrow typed columnar properties table.

-- PyGraphistry client for implementing `graphistry.edges(pd.read_csv('...')).bind(source='colX', destination='colY').plot()`: https://github.com/graphistry/pygraphistry/blob/master/graphistry/arrow_uploader.py

FWIW, we are able to move ~100M rows in ~1s  via disk -> notebook -> graphistry this way. Being able to do that with Neo4j would be a big enabler!  https://www.graphistry.com/blog/graphistry-2-29-5-upload-100x-more-rapids-0-13-learnrapids-com-and-more

**Comment by lmeyerov** [comment]
Also, I believe Mark Quinsland was looking at something similar via Parquet. Arrow is designed more for in-memory + streaming, so I'd recommend that, but Parquet achieves similar efficiency & standardization objectives. In that case, our guess was the Neo4j<>Spark work might provide a bit of a start, where Arrow would be a more standard typed columnar format than Spark's internal RDD one.

**Comment by voutilad** [comment]
@jexp pointed me in this direction...I recently started a [project](https://github.com/neo4j-field/neo4j-arrow) dedicated to experimenting with Arrow Flight support as a plugin in Neo4j.

I'm focused mostly on integration with the GDS in-memory graph, but @conker84 if you're defining a practical way for representing Cypher types like nodes and relationships maybe I can adopt your work? I haven't put much effort into identifying a generic way to support the heterogeneous cypher types. (My goal is speed, so I'm focused mostly on the homogenous structures from GDS.)

Happy to take the discussion off the issue/ticket.

**Comment by conker84** [comment]
@voutilad hi I just got back to work, please lemme know how do you want to proceed on this, I'm happy to set up a call!
I'll ping you on slack

**Comment by voutilad** [comment]
I’m off until next week (back 7 September). Let’s connect next week.

**Comment by vga91** [comment]
Fixed https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/1859
