### ISSUE TITLE
fulltext index: support custom analyzer classes/queues when creating an ft index

### ISSUE THREAD

**Issue by sarmbruster** [neo4j-contrib/neo4j-apoc-procedures#157]

**Comment by dkrizic** [comment]
I have extended the method addAllNodes to receive options, they look like this

`CALL apoc.index.addAllNodes('name',{ Supplier: ["companyName", "description","address"], Product:  ["productName","address"] }, {to_lower_case: false, analyzer: "org.apache.lucene.analysis.core.WhitespaceAnalyzer" } )`

I would like to clarify some details how to implement it:

- Can we keep this method with this new options or should there be an additional method, e.g. addAllNodeWithOptions. I prefer the first approach (breaking things)
- Should I create a pull request?

When we agree on an approach, I will also update the documentation.

**Comment by jexp** [comment]
@sarmbruster Merged the PR

**Comment by jexp** [comment]
Thanks a lot @dkrizic

**Comment by dkrizic** [comment]
I thank you!
