### ISSUE TITLE
[QUESTION] Does apoc.create.uuid() conform to RFC4122?

### ISSUE THREAD

**Issue by es50678** [neo4j-contrib/neo4j-apoc-procedures#1570]
I'm trying to figure out which uuid version is generated by `apoc.create.uuid()`, but I can't find it anywhere in the [documentation](https://neo4j.com/docs/labs/apoc/current/graph-updates/uuid/) and I also can't find any documentation stating if it is compliant with [RFC4122](https://www.ietf.org/rfc/rfc4122.txt). Assuming it is compliant with RFC4122 - then it looks like `apoc.create.uuid()` is generating v4 uuids - which is great, I'm just looking for some confirmation that this is true.

**Comment by jexp** [comment]
We’re using https://docs.oracle.com/javase/7/docs/api/java/util/UUID.html#randomUUID()

Good poiy about adding that to the docs
/cc @mneedham

**Comment by es50678** [comment]
@jexp thank you! those docs answer my question!

I'm trying to do open source contributions and I'm still a relatively new developer.
Is this team open to them?

If so - would https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/4.0/docs/asciidoc/graph-updates/uuid.adoc be the correct place to add a bit of documentation for this?

Something like:
```
The library supports manual and automation generation of UUIDs, which can be stored as properties on nodes.

UUIDs are generated using the https://docs.oracle.com/javase/7/docs/api/java/util/UUID.html#randomUUID()[java randomUUID utility method]
```
towards the top of the file?

Thanks again! :) APOC is amazing!

**Comment by jexp** [comment]
Yes please contribute! Looking forward to your pull request. 
Please also sign our cla
neo4j.com/developer/cla

**Comment by es50678** [comment]
@jexp 

Thank you so much! I've signed the CLA and opened a PR.
