### ISSUE TITLE
APOC refactor mergeNodes -> Combine on a property of type List -> Converting the type of property from list to string, if the values to be merged are same 

### ISSUE THREAD

**Issue by rizwan29** [neo4j-contrib/neo4j-apoc-procedures#1572]
## Guidelines
Before the Merge:
![image](https://user-images.githubusercontent.com/14272628/85894686-de7ede80-b812-11ea-8b55-2726c82951be.png)

After the Merge:
![image](https://user-images.githubusercontent.com/14272628/85894940-4c2b0a80-b813-11ea-8526-d60d3874fc24.png)

## Expected Behavior (Mandatory)
After the node merge: either both the duplicate values can be part of the list or atleast one can be in the list. the type shouldn't be changed from List to String. In the above example `doc_id` should have a similar behavior as `sen_id` property, as both of them are of type List, before the merge.

## Actual Behavior (Mandatory)
if the List contains same values, before merge, then the type is getting converted to String.

Currently used versions

### Versions

  - OS: Windows 10
  - Neo4j: 4.0.3
  - Neo4j-Apoc: 4.0

**Comment by conker84** [comment]
@jexp this behaviour is defined by code:

https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/4.1/core/src/main/java/apoc/refactor/util/PropertiesManager.java#L66-L68

How should we handle this?

**Comment by jexp** [comment]
Perhaps a config option?
