### ISSUE TITLE
apoc.schema.assert drops and re-adds multi-property index every time

### ISSUE THREAD

**Issue by ericmonk** [neo4j-contrib/neo4j-apoc-procedures#1577]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Expected Behavior (Mandatory)
It should detect that the multi-property index is the same as an existing one, and not drop it, then re-add it.

## Actual Behavior (Mandatory)
Even though a multi-property index is the same, for example:

"Person": [
    [
      "firstName",
      "lastName"
    ]
  ]

It will always drop and re-add it. For single property indexes like this:

"Person": [
      "name"
  ]

It works fine.

## How to Reproduce the Problem
Create a multi-property index.

### Simple Dataset (where it's possibile)

```
//Insert here a set of Cypher statements that helps us to reproduce the problem
CALL apoc.schema.assert(null, {
	Person: [["firstName", "lastName"]]
})
```

### Steps (Mandatory)

  1.  Use the Neo4j Web Browser
  2.  Run the apoc.schema.assert example above
  3.  Run it again

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: MacOS Mojave 10.14.6
  - Neo4j: 4.0.4, installed from Neo4j Desktop 1.3.0.18
  - Neo4j-Apoc: 4.0.0.14

**Comment by conker84** [comment]
@ericmonk it always drops the indexes also for the single property version, this because you're there is a third parameter named `dropExisting` which is default `true`, can you try the following query?

```cypher
CALL apoc.schema.assert(null, {
	Person: [["firstName", "lastName"]]
}, false)
```

**Comment by conker84** [comment]
@ericmonk ping
