### ISSUE TITLE
A "summing" Map-Merge function

### ISSUE THREAD

**Issue by mholford-neo** [neo4j-contrib/neo4j-apoc-procedures#1579]
It would be neat if there were an apoc functions that merged two maps and, where keys are shared between the two maps, summed the values in the merged map.
For example:
RETURN apoc.???({x: 17, y: 'hello'}, {x;25, z: 'world'}) would output {x:42, y: 'hello', z:'world'}.
I'm thinking primarily of summing number values, but it could also perform other '+' operations like string concatenation or appending to a list.

```
unwind [ {x: 25, y: 'Hello'}, {x: 17, z:'World'} ] AS row
unwind keys(row) AS key
with key, collect(row[key]) as values
return apoc.map.fromPairs(collect([key, reduce(acc=values[0], x in tail(values) | acc + x)])) as combined
```
is workaround to achieve this.

Aggregating to a map in this way would be a neat feature as well

**Comment by conker84** [comment]
As it can be solved as a simple cypher query I suggest to create a cypher function:

https://neo4j.com/docs/labs/apoc/current/cypher-execution/cypher-based-procedures-functions/
