### ISSUE TITLE
apoc.custom.asProcedure not working.

### ISSUE THREAD

**Issue by tonny008** [neo4j-contrib/neo4j-apoc-procedures#1580]
## Expected Behavior (Mandatory)
create custom procedure

## Actual Behavior (Mandatory)
throwing exception
```
Failed to invoke procedure `apoc.custom.asProcedure`: Caused by: java.lang.NoSuchMethodError: org.neo4j.internal.kernel.api.procs.ProcedureSignature.<init>(Lorg/neo4j/internal/kernel/api/procs/QualifiedName;Ljava/util/List;Ljava/util/List;Lorg/neo4j/procedure/Mode;ZLjava/lang/String;[Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZZ)V
```

## How to Reproduce the Problem

```
call apoc.custom.asProcedure("test", "match (n) return n")

```
neo4j introduce a breaking change by adding a new parameter to the constructor

https://github.com/neo4j/neo4j/commit/49f1c1c19a8591a382b91280e0a71c561c8d4df5#diff-ef588cd97253b916f8f3b1f09cf749a5

### Steps (Mandatory)

  1. call apoc.custom.asProcedure("test", "match (n) return n")

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS:centos
  - Neo4j:3.5.19
  - Neo4j-Apoc:3.5.0.12

**Comment by conker84** [comment]
I'm closing this because is the same as #1584, please @tonny008 follow the discussion in that thread
