### ISSUE TITLE
Error in query - CALL apoc.schema.nodes()

### ISSUE THREAD

**Issue by umuzammil** [neo4j-contrib/neo4j-apoc-procedures#1581]
Neo4j Vsersion : 3.5.19
Apoc Versions: 3.5.0.4 and 3.5.0.12

An issue in APOC procedure CALL apoc.schema.nodes(), It runs fine when there is NO index but It got fails with below error when there is any type of index in the database

```
Neo.ClientError.Procedure.ProcedureCallFailed
Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `apoc.schema.nodes`: Caused by: java.lang.IncompatibleClassChangeError: Found interface org.neo4j.storageengine.api.schema.PopulationProgress, but class was expected
```
![IndexOutput](https://user-images.githubusercontent.com/31652619/86510874-c3e8ce80-bdeb-11ea-84b1-ee167a27b4d0.png)

Requesting a fix for this bug and need a updated apoc version to share with the customer please

**Comment by conker84** [comment]
[apoc-3.5.0.12-all.jar.zip](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/4923663/apoc-3.5.0.12-all.jar.zip)

@umuzammil can you try with the jar above?

**Comment by umuzammil** [comment]
Thanks @conker84 3.5.0.12-all.jar fixed the issue
