### ISSUE TITLE
apoc.meta.schema Fails to List All Relationship Types 

### ISSUE THREAD

**Issue by typinator** [neo4j-contrib/neo4j-apoc-procedures#1583]
## Expected Behavior (Mandatory)
apoc.meta.schema lists all of the types. Neo4J Desktop console / CALL db.relationshipTypes() lists 41 types.

The types returned should be:

relationshipType
--
1 | "HAS"
2 | "USES CONNECTOR"
3 | "IS ALLOWED VALUE FOR"
4 | "IS MASTER SOURCE FOR"
5 | "TO"
6 | "SUPPLIES"
7 | "INHERITS PROPERTIES FROM"
8 | "INCLUDES"
9 | "IS DEFAULT VALUE FOR"
10 | "MODIFIES"
11 | "REQUIRES"
12 | "GOVERNS"
13 | "MAY REQUIRE"
14 | "HAS PART"
15 | "ALLOWS"
16 | "OR"
17 | "REQUIRES AT LEAST"
18 | "THEN"
19 | "STARTS WITH"
20 | "BEFORE"
21 | "ADDS"
22 | "FRAMES"
23 | "FROM"
24 | "DELETES"
25 | "FOLLOWS"
26 | "RESPONDS TO"
27 | "IS VERSION OF"
28 | "RAISED AGAINST"
29 | "IMPLEMENTS"
30 | "USES"
31 | "IS A"
32 | "OF"
33 | "DECLARES"
34 | "ADDRESSES"
35 | "PARTICIPATES IN SAME RELATIONSHIPS AS"
36 | "FINISHES AT"
37 | "TO IMPLEMENT"
38 | "FINSHES AT"
39 | "STARTS AT"
40 | "STARTS AT NODE"
41 | "FINISHES AT NODE"

## Actual Behavior (Mandatory)
Lists 6 types only

Relationship | Properties

> -- | --
> 1 | "ADDS" | ["change identifier (string) ", "date created (string) "]
> 2 | "ALLOWS" | ["scope (string) "]
> 3 | "DELETES" | ["change identifier (string) "]
> 4 | "FROM" | ["change identifier (string) "]
> 5 | "MODIFIES" | ["change identifier (string) "]
> 6 | "TO" | ["change identifier (string) "]

### Simple Dataset (where it's possibile)

```
//Insert here a set of Cypher statements that helps us to reproduce the problem  
```
```
//Describe relationships with properties
CALL apoc.meta.schema() YIELD value as schemaMap
UNWIND keys(schemaMap) as label
WITH label, schemaMap[label] as data
WHERE data.type = "relationship" 
UNWIND keys(data.properties) as property
WITH label, property, data.properties[property] as propData
ORDER BY property
RETURN label AS Relationship,collect(toString(property) +" ("+toLower(toString(propData.type))+")") AS Properties
ORDER BY Relationship
```

## Steps (Mandatory)  

1.  total count uses - CALL db.relationshipTypes()
2.  characterisation of relationships uses CALL apoc.meta.schema() YIELD value as schemaMap 

## Screenshots (where it's possibile)  

List of 6 types using apoc.meta.schema
![Neo4j DesktopScreenSnapz002](https://user-images.githubusercontent.com/14157480/86924221-13e6ce80-c127-11ea-9225-3c0d1e5e16be.jpg)  

whereas db.relationshipTypes() yields 41

![Neo4j DesktopScreenSnapz001](https://user-images.githubusercontent.com/14157480/86924249-1e08cd00-c127-11ea-999c-146d7572e539.jpg)  

## Specifications (Mandatory)

Currently used versions  

### Versions

  

- OS: Mac 10.15.5
-   Neo4j: 4.1.0
-   Neo4j-Apoc:4.1.0.0

**Comment by conker84** [comment]
@typinator the procedure works fine, the problem is the query:

```cypher
CALL apoc.meta.schema() YIELD value as schemaMap
UNWIND keys(schemaMap) as label
WITH label, schemaMap[label] as data
WHERE data.type = "relationship" 
UNWIND keys(data.properties) as property
WITH label, property, data.properties[property] as propData
ORDER BY property
RETURN label AS Relationship,collect(toString(property) +" ("+toLower(toString(propData.type))+")") AS Properties
ORDER BY Relationship
```
with the second UNWIND (`UNWIND keys(data.properties) as property`) you're implicitly excluding all the relationships with no properties

can you try with this?

```cypher
CALL apoc.meta.schema() yield value
UNWIND keys(value) AS key
WITH value[key] AS data, key
WHERE data.type = 'relationship'
WITH key AS rel, coalesce(data.properties, {}) AS props
CALL apoc.cypher.run('UNWIND keys($props) AS key RETURN collect(key + "(" + props[key].type + ")") AS props', {props: props}) YIELD value
RETURN rel, value.props
```

**Comment by typinator** [comment]
That works a treat - thanks! Just need to sort the properties.
