### ISSUE TITLE
Create system resources using apoc.initializer.cypher.<key>

### ISSUE THREAD

**Issue by gwvandesteeg** [neo4j-contrib/neo4j-apoc-procedures#1586]
## Feature description (Mandatory)
We'd like the ability to create resources on the system database using the initializer, this would allow us to create a read only user or additional databases to use in the docker image to distribute to our development team without too much complexity.  These need to be created during the image startup since there is no way of knowing whether the user is using a data volume mount or not, and as such will also need to be able to be reboot proof without generating errors (which on the user create we can do with an IF NOT EXISTS).

## Considered alternatives
No suitable alternatives found, the image must be made ready to work without the end user needing to run extra commands to populate it, and pre-seeding the image with data is invalidated when a volume mount is used for the data.

## How this feature can improve the project?
Being able to specify a startup script to initialize a neo4j database and set up all the minimal required resources needed for a developer to start working with their code can only be useful for a variety of people for a variety of use cases.

**Comment by conker84** [comment]
Hi @gwvandesteeg with 7fb766e we added the support `NEO4J_apoc_initializer_cypher` without the `<key>` and it's the best that we can do given the fact that the Neo4j Setting system in v `4.x` radically changed and not allow to define that kind of properties anymore. 
So my suggestion is to try to build the apoc from the source and then use `NEO4J_apoc_initializer_cypher` in combination with `apoc.cypher.runFiles`

**Comment by jexp** [comment]
How about mapping the `conf` directory in docker and putting an `apoc.conf` in there? `-v conf:/conf`

**Comment by jexp** [comment]
@gwvandesteeg does @conker84's suggestion work for you? We're kinda limited what we can do here.

**Comment by jexp** [comment]
@sarmbruster would it be possible to pass environment variables to neo4j which are then read by the new apoc conf mechanisms you added.

**Comment by sarmbruster** [comment]
See https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/4.0/src/main/resources/apoc-config.xml - we already use env variables and system properties. It's documented at https://neo4j.com/docs/labs/apoc/current/config/.
So you could use `-e apoc.initializer.cypher=<some cypher command>`.

Back to your original question: you can use use `call apoc.systemdb.execute(<some ddl string>)` as initializer to create users.

Please let me know if that works for you.

**Comment by sarmbruster** [comment]
closing this due to lack of feedback
