### ISSUE TITLE
dijikstraWithDefaultWeight String cannot be cast to Number

### ISSUE THREAD

**Issue by Meatballs1** [neo4j-contrib/neo4j-apoc-procedures#159]
I get the following error:

```
Failed to call procedure `apoc.algo.dijkstraWithDefaultWeight(startNode :: NODE?, endNode :: NODE?, relationshipTypesAndDirections :: STRING?, weightPropertyName :: STRING?, defaultWeight :: FLOAT?) :: (path :: PATH?, weight :: FLOAT?)`: java.lang.String cannot be cast to java.lang.Number
```

When querying with something like:

```
MATCH (start:ObjectDN {name: 'bob'}), (end:ObjectDN {name: 'steve'}) CALL apoc.algo.dijkstraWithDefaultWeight(start, end, 'RELTYPE1>|RELTYPE2>|RELTYPE3>', 'cost', 0.5) YIELD path, weight RETURN path
```

I've tried the default as an integer but same error.  Using `apoc.algo.dijkstra` without the default value works fine.

**Comment by sarmbruster** [comment]
Can you please check if your `cost` property is a numeric value? I'm suspecting you're using a string.

To check something like `MATCH ()-[r:RELTYPE1|:RELTYPE2|:RELTYPE3]->() call apoc.meta.type(r.cost) yield as type RETURN type, count(*)` should do it.

**Comment by Meatballs1** [comment]
`yield value as value` did the trick

Yeah have some strings in the data, I didn't consider this as the djikstra algorithm certainly didn't complain :)

**Comment by sarmbruster** [comment]
so I'll guess we can close this issue?

**Comment by Meatballs1** [comment]
Depends, I would expect both algorithms to have the same outcome, which they don't at present. Additionally the error message could potentially be more specific.

Otherwise I have overcome it thanks to your help :)

**Comment by Meatballs1** [comment]
:D
