### ISSUE TITLE
License issue - is this product now GPLv3?

### ISSUE THREAD

**Issue by mikernorton** [neo4j-contrib/neo4j-apoc-procedures#1598]
## Expected Behavior (Mandatory)
License for APOC is Apache 2.0 as stated in the LICENSE file

## Actual Behavior (Mandatory)
There are three files in core/src/main/java/org/neo4j/cypher/export that state in the header that they are GPL v3. This can cause issues with my company.

## How to Reproduce the Problem
Look the files in  core/src/main/java/org/neo4j/cypher/export

  - Neo4j-Apoc: 4.1.0

**Comment by sarmbruster** [comment]
fixed in https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/1602
