### ISSUE TITLE
RETURN apoc.coll.max([1,2,3,4,5]) result is NULL?

### ISSUE THREAD

**Issue by Berkla** [neo4j-contrib/neo4j-apoc-procedures#1604]
Using Neo4j Server version: 4.0.3

## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

### Simple Dataset (where it's possibile)

```
//Insert here a set of Cypher statements that helps us to reproduce the problem

```

### Steps (Mandatory)

  1.
  1.
  1.

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS:
  - Neo4j:
  - Neo4j-Apoc:

**Comment by conker84** [comment]
hi @Berkla can you share your apoc version?
just run `return apoc.version()`

**Comment by Berkla** [comment]
It seems, that I destroyed my message:
APOC: 4.0.0.17'
Neo4j: 4.03
Browser: 4.0.5

I've several dirty collections, with mostly numbers, but also Nulls and Text. I want to find out the max over all collections.

Doing this works:

<return apoc.coll.max([]+[1,2,3]+[4,5])>
<return apoc.coll.max([NULL]+[1,2,3]+[4,5])>
<return apoc.coll.max([1,2,3]+[4,5]+[NULL])>

But this rusults in NULL:
<return apoc.coll.max([NULL]+[NULL]+[1,2,3]+[4,5]+[NULL])>

and afterwords
<return apoc.coll.max([1,2,3])>
also results in NULL

I've to restart the database to get the right result on this again.

**Comment by jexp** [comment]
Any operation in a ternary logic that has null values will possibly return null.

You could filter out null values first: return 
`apoc.coll.max([x IN ([NULL]+[NULL]+[1,2,3]+[4,5]+[NULL]) WHERE x IS NOT NULL])`
