### ISSUE TITLE
Fix Tx Monitoring to correctly return lastTxId

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#1616]
And not numberOfStarted transactions.

Code in 3.5 was correct / used different API.

https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/4.1/full/src/test/java/apoc/monitor/Transaction.java#L24

**Comment by MishaDemianenko** [comment]
`TransactionIdStore` should be used instead as a source of last committed transaction
