### ISSUE TITLE
Float type not respected in export

### ISSUE THREAD

**Issue by folterj** [neo4j-contrib/neo4j-apoc-procedures#1629]
## Float type not respected in export

Numerical values of float type without decimals appear to be automatically converter to integer during export.
Apart of the undesired type change, this will additionally cause failure when trying to import large values.

## Reproducible
```
CREATE (x:Test {x:1000000000000000000000000.0})

MATCH (x:Test) RETURN x.x
> 1e+24.0
MATCH (x:Test) RETURN apoc.meta.type(x.x)
> "FLOAT"

CALL apoc.export.cypher.all("test.cypher")
```

## Expected Behavior (Mandatory)

```
UNWIND [{_id:0, properties:{x:1000000000000000000000000.0}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:Test;
```
(Expected .0)

## Actual Behavior (Mandatory)

```
UNWIND [{_id:0, properties:{x:1000000000000000000000000}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:Test;
```
(Missing .0)

### Versions
Test 1
  - OS: Linux
  - Neo4j: 4.0.4
  - Neo4j-Apoc: apoc-4.0.0.12

Test 2
  - OS: Windows
  - Neo4j: Desktop 1.3.4 / 4.1.1
  - Neo4j-Apoc: apoc-4.1.0.2

**Comment by conker84** [comment]
this should be fixed with #1675
