### ISSUE TITLE
apoc.load.csv doesn't support basic auth

### ISSUE THREAD

**Issue by voutilad** [neo4j-contrib/neo4j-apoc-procedures#1630]
## Feature description
Loading csv files from basic auth protected webservers doesn't currently work today. The `apoc.load.json` procedures support using urls that follow the basic auth format (e.g. `http://user:password@host/path?query`). Loading remote csv files should work the same way.

## Considered alternatives
No alternatives other than using a different storage back-end.

## How this feature can improve the project?
Right now the behavior is inconsistent among remote data loading routines (csv, json, html). A predictable behavior and interface would be helpful.

**Comment by jexp** [comment]
@conker84 can we make it behave the same way as the other loaders, i.e. go through the same resolution for the URLs?

**Comment by conker84** [comment]
@voutilad which version of apoc are you using?

**Comment by voutilad** [comment]
It was a 4.x version. Not sure which.
