### ISSUE TITLE
Support options for apoc.export.json for jsonarray/json/jsonlines

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#1640]
To allow different json formats but still default to json lines, 

see #1634 

`call apoc.export.json(..., {format:"jsonlines/json/jsonarray"})`

**Comment by jexp** [comment]
For the "json" option we need to think about if we want to do a json object with `nodes/rels` main entries and then an json array or a nested json object where the keys are the id's of the nodes rels.

**Comment by typinator** [comment]
Whatever the outcome can you please publish the defined schema sto support integrators?
