### ISSUE TITLE
APOC couln't set a URLStreamHandlerFactory since some other tool already did this (e.g. tomcat).

### ISSUE THREAD

**Issue by su-park** [neo4j-contrib/neo4j-apoc-procedures#1642]
I have same [issue](https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1571) with version 4.1.1

Is this issue solved?

## Expected Behavior
If there are no other JVMs running, APOC should be able to set a URLStreamHandlerFactory.

## Actual Behavior
As of Neo4j 4.1.1, APOC 4.1.0.0-all, APOC is unable to set the URLStreamHandlerFactory and throws a message when Neo4j starts up.

> APOC couln't set a URLStreamHandlerFactory since some other tool already did this (e.g. tomcat). This means you cannot use s3:// or hdfs:// style URLs in APOC. This is caused by a limitation of the JVM which we cannot fix.

## Versions
- OS: Mac OS Catalina Version 10.15.13
- Neo4j: 4.1.1
- Plugins: Neo4j-Apoc: 4.1.0.0-all, neo4j-graph-data-science-1.3.2-standalone

## More specifications
- because of malfunction, I installed Neo4j (3.5.21) with plugins (apoc, gds) and it works good.
- I checked whether any JVM process is running when I starts Neo4j.

**Comment by sarmbruster** [comment]
How is that report different from #1571 ?

**Comment by nathanschepers** [comment]
I'm not sure whether #1571 needs re-opening or not (if so I can comment there), but I am having the same issue. Very simple config, using:

```
  neo4j:
    image: neo4j
```       

and setting:

```
    environment:
      - NEO4JLABS_PLUGINS=["apoc"]```
```

Then when I `docker-compose up` I'm getting these errors. It only happened after I updated my neo4j image.

**Comment by sarmbruster** [comment]
#1571 is fixed, but there's not yet a release containing the fix.

**Comment by su-park** [comment]
Thank you.

Let me know the status of quo.

I will try version 4 after the fixed version releases.
