### ISSUE TITLE
Add documentation that shows how to use an apoc dependency for a neo4j embedded API test

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#1656]
So if someone writes an extension / procedure / integration-test that needs apoc, we need to document how they need to setup their java dependencies (maven/gradle) and the code they need to use with neo4j-harness / TestGraphDBService etc. to properly load the apoc procs.

@michael-simons had figure out a while ago how to do that, we can use his example code for that.

**Comment by jexp** [comment]
With Embedded: 

https://github.com/michael-simons/neo4j-sdn-ogm-tips/blob/master/examples/testing-ogm-against-embedded-with-apoc/src/test/java/org/neo4j/tips/testing/testing_ogm_against_embedded_with_apoc/ApplicationTests.java#L53-L67
```
examples/testing-ogm-against-embedded-with-apoc/src/test/java/org/neo4j/tips/testing/testing_ogm_against_embedded_with_apoc/ApplicationTests.java:53-67
        // We need the directory containing the APOC jar, otherwise all APOC procedures must be loaded manually.
        // While the intuitive idea might be not having APOC on the class path at all in that case and just dump
        // it into the plugin directory, it doesn't work as APOC needs some extension factories to work with
        // and those are not loaded from the plugin unless it's part of the original class loader that loaded neo.
        // If you know which methods you're a gonna use, you can configure them manually instead.
```

With testcontainers

https://github.com/michael-simons/neo4j-sdn-ogm-tips/blob/master/examples/testing-ogm-against-testcontainers-with-apoc/src/test/java/org/neo4j/tips/testing/testing_ogm_against_testcontainers_with_apoc/ApplicationTests.java#L57-L87

**Comment by pelletier197** [comment]
The method you specified there does not work with `neo4j 4.1.1+`. Apoc does not provide the core functions in their jar anymore.

**Comment by Lukasmp3** [comment]
Still not any progress about this that would work on `neo4j 4.1.1+` or `neo4j 4.2.1.+`?

**Comment by datanostra** [comment]
Doesn't work with current apoc maven repository (4.2.0.1):
(https://mvnrepository.com/artifact/org.neo4j.procedure/apoc/4.2.0.1)

I successfully run the above example injecting manually the apoc-all dependency, though.  But apoc-all is not available from maven repository.

**Comment by fbiville** [comment]
I believe the easiest way is to download APOC "fat JAR" (`apoc-XXX-all.jar`), which is currently **not** available from Maven Central, but only from GitHub releases (see https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1404 that describes this very issue).

@JMHReif and I hacked together to get this fat JAR and add it to Maven's local cache: https://github.com/fbiville/apoc-testing-experiment.

That still requires a manual script invocation so it is far from ideal and solving #1404 would be a better way to address this whole situation.

**Comment by fbiville** [comment]
It appears APOC fat JAR is already in Maven Central, it's just a matter of adding it with the right classifier:
```xml
        <dependency>
            <groupId>org.neo4j.procedure</groupId>
            <artifactId>apoc</artifactId>
            <version>${apoc.version}</version>
            <scope>test</scope>
            <classifier>all</classifier>
        </dependency>
```

https://github.com/fbiville/apoc-testing-experiment has been updated. The TestContainers approach works well with Neo4j 4.2 and APOC 4.2. We'll add a test-harness example soon.

**Comment by marksouletheprogrammer** [comment]
@fbiville Any chance we can get the test-harness example soon?

**Comment by lix-mms** [comment]
Yes I can prove that @fbiville's solution on using the `all` classifier works. In Gradle the dependency I added is:

```gradle
{
    // ...
    compile 'org.neo4j.driver:neo4j-java-driver:4.4.9'
    testCompile 'org.neo4j.test:neo4j-harness:4.4.9'
    testCompile 'org.neo4j.procedure:apoc:4.4.0.9:all'
    // ...
}
```
