### ISSUE TITLE
apoc.schema.assert nodekey throws EquivalentSchemaRuleAlreadyExistsException

### ISSUE THREAD

**Issue by lqst** [neo4j-contrib/neo4j-apoc-procedures#1657]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Expected Behavior (Mandatory)
Expect to be able to assert node key constraint with multiple keys w/o error

## Actual Behavior (Mandatory)
Returns with EquivalentSchemaRuleAlreadyExistsException

## How to Reproduce the Problem

Run the following twice:
```
CALL apoc.schema.assert(
  { 
    // Indexes
  }, 
  {
    // Constraints
    Movie:[['title', 'year'] ]
  },
  // Drop existing indexes and constraints 
  false
);
```

### Simple Dataset (where it's possibile)

N/A

### Steps (Mandatory)

  1. Run example schema assert above (ok first time)
  2. Run example schema assert above (not ok second time)

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: OSX
  - Neo4j: 4.1.0
  - Neo4j-Apoc: 4.1.0.1-all

**Comment by igor-iurchenko-gl** [comment]
The same issue. 
Neo4j 4.1.5. 
Neo4j-Apoc: 4.1.0.4
