### ISSUE TITLE
Failed to invoke procedure “sql-versioner.init - Caused by: java.lang.NoSuchMethodError:

### ISSUE THREAD

**Issue by bandaja** [neo4j-contrib/neo4j-apoc-procedures#1659]
Steps (Mandatory)
1.	Download the JDBC for postgresql:
https://jdbc.postgresql.org/    postgresql-9.4.1209
2.	Download the Neo4j Versioner CoreJAR from:
neo4j-versioner-sql-0.1.0-SNAPSHOT

3.	Put "neo4j-versioner-sql0-0.1.0-SNAPSHOT " and JDBC Driver into my "plugins":
$NEO4J_HOME\plugins\

4.	Restart the services.
5.	run the query:
CALL sql.versioner.init('postgres', '127.0.0.1', 5432, 'xxxx', 'xxxxxx', 'xxxxxx') YIELD node return node

6.	I got the error message:
Failed to invoke procedure `sql.versioner.init`: Caused by: java.lang.NoSuchMethodError: 'java.util.stream.Stream org.homer.versioner.core.procedure.Init.init(java.lang.String, java.util.Map, java.util.Map, java.lang.String, long)'

Specifications (Mandatory)
Versions:

Neo4j: version: 3.5.21

Postgresql: Ver 12.3

OS: win10 64

**Comment by sarmbruster** [comment]
Your issue seems not to be related to APOC, maybe file that ticket with `neo4j-versioner` project?
Since it's out of scope I'll close it. If you think it's APOC related, please provide more details and reopen it.

**Comment by bandaja** [comment]
you are correct! thanks
