### ISSUE TITLE
Add running total function for collection

### ISSUE THREAD

**Issue by smithna** [neo4j-contrib/neo4j-apoc-procedures#1660]
Add apoc.coll.runningTotal(coll) function. 

It would return a list containing a running total of the values passed to the function.

You can do this in Cypher, but it's not easy.

The function could be useful for analytics and feature engineering for machine learning.

**Comment by conker84** [comment]
@smithna can you provide a simple you case with the expected output?

**Comment by smithna** [comment]
Hi @conker84. If I had a collection [1, 5, 2, 7], the output of the running total function would be [1, 6, 8, 15].

**Comment by jexp** [comment]
so it takes the numeric values that are passed in and then returns

[row1, row1+row2, row1+row2+row3]

or 
rows = [row0, rows[idx-1] + rowN]
if we keep an arraylist

`totals.add(totals.get(totals.size()-1) + current)`

and then one can unwind it later to get rows back

**Comment by vga91** [comment]
@smithna  I opened a pr with the requested change #1792.
Can you check if it's ok for you?
