### ISSUE TITLE
Add lead/lag function for collections

### ISSUE THREAD

**Issue by smithna** [neo4j-contrib/neo4j-apoc-procedures#1661]
You can currently match an item with the previous or following item in a collection using `apoc.coll.pairs([1,2,3]) YIELD value` and `apoc.coll.pairsMin(coll)` 

Extend this idea to allow lead or lag by a specified offset, similar to the way [lead and lag functions work in SQL](https://docs.microsoft.com/en-us/sql/t-sql/functions/lag-transact-sql?view=sql-server-ver15). 

`apoc.coll.lead([1,2,3,4], 2) YIELD value` would yield `[1,3], [2,4], [3, null], [4, null]` 

`apoc.coll.lag([1,2,3,4], 2) YIELD value` would yield `[1, null], [2, null], [3, 1], [4, 2]`

This could be helpful in time series analysis.

**Comment by conker84** [comment]
hi @smithna correct me if I'm wrong but `lead` and `lag` in SQL are windowed functions that partition data by column and return the index provided in the argument, which is different from what you're asking.
Am I right?

**Comment by smithna** [comment]
Hi @conker84. You're correct about how `lead` and `lag` work in SQL. If I have Cypher collections grouped by a value, I think the proposed function would serve the same purpose. Imagine I have a collection of sales by quarter sorted by quarter, and I want to compare this quarter with the same quarter last year. In SQL, I would use `lag` to write that query. I'd like to be able to use an apoc lag function to get the answer from Neo4j.

**Comment by conker84** [comment]
Ok for now we implemented a procedure and a function both called `apoc.coll.pairWithOffset`:

For:
`RETURN apoc.coll.pairWithOffset([1,2,3,4], 2) AS value`

The output will be:
`[[1,3],[2,4],[3,null],[4,null]]`


For:
`CALL apoc.coll.pairWithOffset([1,2,3,4], 2)`

The output will be:

```
[1,3]
[2,4]
[3,null]
[4,null]
```

If works also with negative numbers so we cover the two use cases that you highlighted

**Comment by conker84** [comment]
Please look at the PR #1678

**Comment by smithna** [comment]
That's exactly what I was looking for. I like that the naming convention is similar to the other pair function too. Thanks!
