### ISSUE TITLE
apoc.do.when and apoc.do.case Cannot convert java.util.stream.LongPipeline$Head to AnyValue for rel IS null case

### ISSUE THREAD

**Issue by graphadvantage** [neo4j-contrib/neo4j-apoc-procedures#1662]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Expected Behavior (Mandatory)
```
MATCH (p:Person),(m:Movie)
OPTIONAL MATCH (p)-[r]->(m)
WHERE type(r) = 'ACTED_IN'

CALL apoc.do.when(
   r IS NULL,
   'RETURN "not an actor" AS result',
   'RETURN "is an actor" AS result', {r:r}
) YIELD value
   
RETURN value.result
```
should conditionally execute based on presence of relationship

## Actual Behavior (Mandatory)

Failed to invoke procedure `apoc.do.case`: Caused by: java.lang.IllegalArgumentException: Cannot convert java.util.stream.LongPipeline$Head to AnyValue

## How to Reproduce the Problem

workaround is from similar issue
https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/776

add to neo4j.conf=>
unsupported.cypher.runtime=SLOTTED

### Versions

  - OS:  Mac
  - Neo4j: 3.5.18
  - Neo4j-Apoc: 3.5.0.12

**Comment by utnaf** [comment]
Hi @graphadvantage, 
I tried the scenario with Neo4j 3.5.18 and APOC 3.5.0.12 and the Movie Graph but wasn't able to reproduce the issue. Are there any additional information you can provide?

**Comment by ncordon** [comment]
Closing due to 3.5 being out of support and inactivity in the issue
