### ISSUE TITLE
Expose Transaction Metadata() a statement parameter in apoc.trigger.add()

### ISSUE THREAD

**Issue by ShipatNeo** [neo4j-contrib/neo4j-apoc-procedures#1666]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Feature description (Mandatory)
Currently the statement parameters for `apoc.trigger.add()` do not expose the Transaction MetaData, which is available in the underlying transaction data:

https://neo4j.com/docs/java-reference/4.1/javadocs/org/neo4j/graphdb/event/TransactionData.html

It would be very useful if meta data was also exposed/available.

## Considered alternatives
None considered

## How this feature can improve the project?
Looking to use some of the metadata details provided by the calling application to give the trigger logic more details - for example, call a different custom procedure or audit log details about the calling application that did the transaction.

**Comment by aaron-dsouza** [comment]
Thanks for logging this Dave. I really want to use this feature to pass metadata from the java driver to my custom procedure via a trigger. I asked this question in the community as well https://community.neo4j.com/t/using-triggers-with-custom-procedures/25370
