### ISSUE TITLE
Add apoc.array.int(size, [fill])

### ISSUE THREAD

**Issue by davidfauth** [neo4j-contrib/neo4j-apoc-procedures#1668]
## Feature description (Mandatory)
Please add the capability to specify the type of array instead of defaulting to string. i.e.
apoc.array.int()

## How this feature can improve the project?
By default, it is created as a string. Some customers have asked for the ability to hint at the data type.

**Comment by jexp** [comment]
also for other data types, like float, byte, boolean etc.

apoc.array.int() would create an empty int array.
