### ISSUE TITLE
Azure Container Instance APOC library

### ISSUE THREAD

**Issue by brechtarnou** [neo4j-contrib/neo4j-apoc-procedures#1683]
Hi everyone,

I want to install the APOC plugin, however my neo4j database is running on a Azure Container Instance via a docker image.
How can I install the APOC plugin in this situation?

Kind regards,
Brecht

**Comment by mneedham** [comment]
You can install it using the `NEO4JLABS_PLUGINS` environment variable, as described in https://neo4j.com/labs/apoc/4.1/installation/#docker
