### ISSUE TITLE
apoc.convert.toTree() returns incorrect results in 4.1.x.x

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j-contrib/neo4j-apoc-procedures#1685]
## Expected Behavior (Mandatory)
After passing in a collection of paths, `apoc.convert.toTree()` should display a tree populated by all elements found within those paths.

## Actual Behavior (Mandatory)
The tree results seem to only be from a single path. It does not return to the depths explored in the paths, and most of the data that should be in the tree is missing.

### Simple Dataset (where it's possibile)

The movies graph from `:play movies`

### Steps (Mandatory)

  1. Load the movies graph
  2. Execute the following:

```
match path = (k:Person {name:'Keanu Reeves'})-[*..5]-(x)
with collect(path) as paths
call apoc.convert.toTree(paths) yield value
return value
```

Observe that the results seem to be only from a single path with a shallow depth. I observed this with a depth of 1 and 1 movie:

```
{
  "acted_in.roles": [
    "Neo"
  ],
  "born": 1964,
  "_type": "Person",
  "name": "Keanu Reeves",
  "acted_in": [
    {
      "acted_in.roles": [
        "Neo"
      ],
      "_type": "Movie",
      "tagline": "Everything that has a beginning has an end",
      "_id": 10,
      "title": "The Matrix Revolutions",
      "released": 2003
    }
  ],
  "_id": 1
}
```

If you try with a different variable-length limit, you may get different results, but still it looks like it's only using a single path.

with `*..6` I observed this with a depth of 2, but only 1 movie and 1 coactor:

```
{
  "acted_in.roles": [
    "Neo"
  ],
  "born": 1964,
  "_type": "Person",
  "name": "Keanu Reeves",
  "acted_in": [
    {
      "acted_in.roles": [
        "Neo"
      ],
      "_type": "Movie",
      "acted_in": [
        {
          "_type": "Person",
          "name": "Carrie-Anne Moss",
          "_id": 2,
          "acted_in.roles": [
            "Trinity"
          ],
          "born": 1967
        }
      ],
      "tagline": "Everything that has a beginning has an end",
      "_id": 10,
      "title": "The Matrix Revolutions",
      "released": 2003
    }
  ],
  "_id": 1
}
```

## Specifications (Mandatory)

The bug only seems to be present in 4.1.x when using APOC 4.1.x.x.
Incorrect behavior was observed in APOC 4.1.0.0 and later, up to 4.1.0.2 (latest).
Correct behavior was observed in APOC 4.0.0.18 and earlier.

### Versions

  - OS: Mac OS 10.14
  - Neo4j: 4.1.x
  - Neo4j-Apoc: 4.1.0.0 and later (correct behavior was observed in 4.0.0.18 and earlier)

**Comment by jexp** [comment]
we can just keep a set of nodes in the path (parents) and if a child appears that's already been output as a parent, we just skip it.

**Comment by alexandrusavin** [comment]
Is there any progress on this issue? It affects our production server (v4.2.0)

**Comment by vga91** [comment]
@alexandrusavin 
I have attached a `.jar` that should fix the problem in `4.2`. 
Please, could you test the procedure with this jar and give a feedback about it?
[apoc-4.2.0.1-all.zip](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/6061326/apoc-4.2.0.1-all.zip)

**Comment by alexandrusavin** [comment]
@vga91 Thanks! Will check it as soon as I get the chance (hopefully next couple of days).

**Comment by conker84** [comment]
@alexandrusavin hi! Any news?

**Comment by alexandrusavin** [comment]
@conker84 Hi! We'll try it out this week again and will come with feedback.
