### ISSUE TITLE
apoc.load.jsonArray: accessing properties of values produces type mismatch error on version 4.1.x

### ISSUE THREAD

**Issue by Kagemusha-san** [neo4j-contrib/neo4j-apoc-procedures#1702]
## Expected Behavior (Mandatory)
Using apoc.load.jsonArray to read a JSON should allow to access properties of returned values.

## Actual Behavior (Mandatory)
A type mismatch error is thrown.

## How to Reproduce the Problem
We use apoc.load.jsonArray to process the result of an API call. For reproduction purposes, following JSON can be used:
`{
  "BusinessData": [
    {
      "prop1": "\\structure_2018\\2",
      "prop2": "\\structure_2018\\1\\1"
    },
    {
      "prop1": "\\structure_2018\\3",
      "prop2": "\\structure_2018\\1\\1"
    },
    {
      "prop1": "\\structure_2018\\4",
      "prop2": "\\structure_2018\\1\\1"
    }
  ],
  "Debug": {
    "total": null,
    "details": null
  },
  "SessionInfo": null,
  "Message": null,
  "HasError": false,
  "Status": 200
}`

### Steps (Mandatory)

  1. Read the json and return each item:
`CALL apoc.load.jsonArray("response1.json") YIELD value 
UNWIND value.BusinessData AS item 
RETURN item`
Results in error:
`Type mismatch: expected Map, Node, Relationship, Point, Duration, Date, Time, LocalTime, LocalDateTime or DateTime but was Any (line 2, column 8 (offset: 63))
"UNWIND value.BusinessData AS item"`
  2. Fix this error by providing a path to apoc.load.jsonArray and all items will be returned:
`CALL apoc.load.jsonArray("response1.json", "$.BusinessData[*]") YIELD value 
UNWIND value AS item 
RETURN item`
  3. Try to access a property of an item:
`CALL apoc.load.jsonArray("response1.json", "$.BusinessData[*]") YIELD value 
UNWIND value AS item 
RETURN item.prop1`
Results in error:
`Type mismatch: expected Map, Node, Relationship, Point, Duration, Date, Time, LocalTime, LocalDateTime or DateTime but was Any (line 3, column 8 (offset: 106))
"RETURN item.prop1"`

Executing above cypher queries on a Neo4J 4.0.x instance with apoc 4.0.x does not yield any errors. Using apoc.load.json instead of apoc.load.jsonArray does work on 4.1.x but because of performance reasons we would prefer to use loadArray.

#### Local
  - OS: Windows 10
  - Neo4j: 4.1.1
  - Neo4j-Apoc: 4.1.0.2

#### Server
  - OS: Ubuntu 20.04.1 LTS
  - Neo4j: 4.1.3
  - Neo4j-Apoc: 4.1.0.2

**Comment by conker84** [comment]
@Kagemusha-san you must use `apoc.load.json` because your json is not a json array, a JSON array is a structure like this:

`[{"foo": "bar", "baz": 1}, {"foo": "foo", "baz": 10}]`

**Comment by Kagemusha-san** [comment]
You're right that the whole json is not an array but in point 2, I explicitly define the path BusinessData and BusinessData is an array
`[
    {
      "prop1": "\\structure_2018\\2",
      "prop2": "\\structure_2018\\1\\1"
    },
    {
      "prop1": "\\structure_2018\\3",
      "prop2": "\\structure_2018\\1\\1"
    },
    {
      "prop1": "\\structure_2018\\4",
      "prop2": "\\structure_2018\\1\\1"
    }
  ]`

Or is anything wrong with my path?
