### ISSUE TITLE
apoc.schema.assert drops and recreates indexes that already exists 

### ISSUE THREAD

**Issue by kimcs** [neo4j-contrib/neo4j-apoc-procedures#1703]
## Expected Behavior (Mandatory)
Expects action to be "KEPT" when running `CALL apoc.schema.assert({AnyLabel: ["someField"]}, {}, true) YIELD label, key, keys, unique, action` on a database where the given index already exists.

## Actual Behavior (Mandatory)
Running `CALL apoc.schema.assert({AnyLabel: ["someField"]}, {}, true) YIELD label, key, keys, unique, action` where the given index already exists produces the following result:
```
╒══════════╤═══════════╤═════════════╤════════╤═════════╕
│"label"   │"key"      │"keys"       │"unique"│"action" │
╞══════════╪═══════════╪═════════════╪════════╪═════════╡
│"AnyLabel"│"someField"│["someField"]│false   │"DROPPED"│
├──────────┼───────────┼─────────────┼────────┼─────────┤
│"AnyLabel"│"someField"│["someField"]│false   │"CREATED"│
└──────────┴───────────┴─────────────┴────────┴─────────┘
```

## How to Reproduce the Problem
Run `CALL apoc.schema.assert({AnyLabel: ["someField"]}, {}, true) YIELD label, key, keys, unique, action` twice, the first time to create the index for a first time, a second time to reproduce the bug where the index is recreated instead of kept.

To verify that the index really exists you can also run: `RETURN apoc.schema.node.indexExists("AnyLabel", ["someField"])` which will return true after index is created.

### Versions

  - OS: macOS
  - Docker: 19.03.13, build 4484c46d9d
  - Neo4j: 4.1.3 community docker image
  - Neo4j-Apoc: 4.1.0.2

**Comment by conker84** [comment]
@kimcs I think that the problem is in the third paramer which is `dropExisting`, you should use `false` instead of `true`, please lemme know if it works

**Comment by conker84** [comment]
closed for lack of feedback, feel free to reopen in case you have more info

**Comment by azocankara** [comment]
> @kimcs I think that the problem is in the third parameter which is `dropExisting`, you should use `false` instead of `true`, please lemme know if it works

Hi, if that is true, you should probably update the docs which cleary states "drops all **other** existing indexes and constraints when dropExisting is true"

https://neo4j.com/labs/apoc/4.2/overview/apoc.schema/apoc.schema.assert/

It seems that this behavior changed with this commit https://github.com/vga91/neo4j-apoc-procedures/commit/fe19659bd11be326d005b340d34cea5e437a828a#diff-d13460d0b91555ba36e0c5524401b5b84b06e7f4fe61dbb895912616f0f7f45dR125
