### ISSUE TITLE
Invalid apoc export graphml format

### ISSUE THREAD

**Issue by edacker** [neo4j-contrib/neo4j-apoc-procedures#1704]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Expected Behavior (Mandatory)
valid graphML exported
![image](https://user-images.githubusercontent.com/57496775/97872423-02cc5980-1ce4-11eb-9e3f-983874c939cb.png)

### Simple Dataset (where it's possibile)

```
//Insert here a set of Cypher statements that helps us to reproduce the problem

```

### Steps (Mandatory)

  1.
  1.
  1.

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS:
  - Neo4j:
  - Neo4j-Apoc:

**Comment by vga91** [comment]
@edacker 
I was unable to replicate the bug.
Please, could you provide the dataset used, and the exported `.graphml` file? (it seems like the bug is at the beginning of the file)

**Comment by conker84** [comment]
@edacker ping

**Comment by conker84** [comment]
@edacker ping
