### ISSUE TITLE
Invoking apoc.convert.toJson with a Node causes StackOverflow

### ISSUE THREAD

**Issue by voutilad** [neo4j-contrib/neo4j-apoc-procedures#1711]
I was experimenting (and hoping) to be able to take a Node reference and turn it into a JSON Object as a string using `apoc.convert.toJson`. However, when trying it, it causes the query to fail with an error:

```
Failed to invoke function `apoc.convert.toJson`: Caused by: java.lang.StackOverflowError
```

I've noticed this in Aura where `apoc.version()` reports `4.2.0-rc02` but have checked that it also happens with `4.1.0.2`.

I'd expect if a node isn't a supported type, it should probably return an appropriate error explaining that. I may open a feature request to support a node or relationship, though :-)

**Comment by jexp** [comment]
Goid point. It only supports datastructures like maps and lists bc its meant to convert for/from properties 

Export.json can deal with nodes/rels/paths

So properties (n) works as input or
Or n {.*, id:id(n), labels:labels(n)}

**Comment by jexp** [comment]
@conker84 perhpas we can use the same json format that we use in apoc.export.json?
