### ISSUE TITLE
Weirdness around custom functions with node return types

### ISSUE THREAD

**Issue by peey** [neo4j-contrib/neo4j-apoc-procedures#1714]
## How to Reproduce

1. Set up test nodes
	```
	UNWIND range(1, 5) as val
 	CREATE (i:Target {value: val});
	```
2. Declare a simple function that returns a node 
(a) `CALL apoc.custom.declareFunction('n(val :: INTEGER) :: NODE ', "MATCH (t:Target {value : $val}) RETURN t")` or (b) `CALL apoc.custom.asFunction('n', "MATCH (t:Target {value : $val}) RETURN t", 'NODE', [['val', 'INTEGER']])`

3. Call the function `RETURN custom.n(2)`. Go to the "table" view and note how node is nested within a key "t". 
4. Try to de-nest with `RETURN custom.n(3)["t"]` or `WITH custom.n(3) AS ans RETURN ans.t`

## Actual v/s Expected Behavior

Buggy behaviour in both 2a and 2b: the nesting within `t`. The return type is `NODE` and not `MAP OF NODE`. I believe this nesting doesn't happen for simple return types like "string" in the latest versions (but was indeed happening before I updated from the older neo4j `4.0.7`)

Buggy behaviour in 2a: step 3 fails with "Unknown function 'custom.n'", i.e. you can't even de-nest it as a workaround.

### Versions

  - OS: docker (official `neo4j:latest` image) on ubuntu 20.04
  - Neo4j: 4.1.13
  - Neo4j-Apoc: 4.1.0.2

**Comment by conker84** [comment]
closed via 1bef1b4
