### ISSUE TITLE
Couldn't install APOC in Neo4j Desktop

### ISSUE THREAD

**Issue by sangee14** [neo4j-contrib/neo4j-apoc-procedures#1722]
I am using Neo4j community edition. I couldn't install APOC plugin. APOC plugin install button is disabled.

- Neo4j Desktop version: neo4j-desktop-1.3.11-x86_64.AppImage
- Neo4j version: neo4j-community-4.1.4
- OS: Linux (Ubuntu 20.04)

[![APOC][1]][1]

I followed the installation steps for APOC,

1. Downloaded APOC jar from [this][2] link (version: `apoc-4.2.0.0-all.jar`) and placed it in plugins folder 

2. Modify the Neo4j Configuration file, present in the location:
`<Neo4j Path>\conf\neo4j.conf`

    Uncomment `dbms.directories.plugins=plugins`
    #allows Neo4j to load this plugins directory to server

    Uncomment and modify as following

        dbms.security.procedures.unrestricted=apoc.*
        dbms.security.procedures.whitelist=apoc.*,apoc.coll.*,apoc.load.*
        #loads unrestricted and white-listed procedures/ plugins to the server

    Add the following lines
    
        apoc.import.file.enabled=true
        apoc.export.file.enabled=true
    
    #Useful for reading and writing data from and to files respectively

3. Restart the server

but couldn't start the Neo4j server and getting an error saying that 

**APOC couln't set a URLStreamHandlerFactory since some other tool already did this (e.g. tomcat). This means you cannot use s3:// or hdfs:// style URLs in APOC. This is caused by a limitation of the JVM which we cannot fix.**

  [1]: https://i.stack.imgur.com/gEHyK.png
  [2]: https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/

**Comment by mneedham** [comment]
Hey,

I don't think that error is usually a reason for the server failing to start. 

Given you are using a 4.1 database, you'll want to use the latest 4.1 version of APOC (https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/tag/4.1.0.4). 

There are sometimes lower-level changes to the database in between point versions (e.g. 4.1 -> 4.2), which mean that 4.2 APOC won't work with 4.1 Neo4j.

Cheers, Mark
