### ISSUE TITLE
Problem importing graphml which was exported graphml from apoc

### ISSUE THREAD

**Issue by ckoenigs** [neo4j-contrib/neo4j-apoc-procedures#1723]
## Expected Behavior (Mandatory)

Able to import large graphml files into Neo4j.

## Actual Behavior (Mandatory)
It throws this error:
Failed to invoke procedure `apoc.import.graphml`: Caused by: org.neo4j.kernel.impl.util.collection.MemoryAllocationLimitException: Can't allocate 524288 bytes due to exceeding memory limit; used=2147028992, max=2147483648

However, a student of mine did the same cypher queries in Neo4j v3 and it worked.

## How to Reproduce the Problem
Try to import a 2.9 GB graphml file

### Simple Dataset (where it's possible)

I used the neo4j database from Reactome (https://reactome.org/download-data)

### Steps (Mandatory)

  1. export with: CALL apoc.export.graphml.all("pathwaydata.graphml", {batchSize:10000, readLabels: true, storeNodeIds: false, useTypes: true})
  2. import with: CALL apoc.import.graphml("pathwaydata.graphml", {batchSize: 10000, readLabels: true, storeNodeIds:false, useTypes: true})

## Specifications (Mandatory)

Currently used versions

### Versions

  - Linux community
  - Neo4j: 4.0.3
  - Neo4j-Apoc 4.0.0.16

**Comment by oberoivarun** [comment]
I am getting this error trying to load a 1.3Gb backup.graphml file
```
Failed to invoke procedure `apoc.import.graphml`: Caused by: org.neo4j.memory.MemoryLimitExceededException: The allocation of an extra 2.0 MiB would use more than the limit 896.0 MiB. Currently using 896.0 MiB. dbms.memory.transaction.total.max threshold reached
```

My memory settings are:
`server.memory.heap.initial_size: 3Gb`
`server.memory.heap.max_size: 3Gb`
`server.memory.pagecache.size: 1Gb`

Total Ram on the system is 5Gb. Is this a bug?
