### ISSUE TITLE
parseFloat(), parseInt(), format() seems to ignore locale parameter

### ISSUE THREAD

**Issue by malencv** [neo4j-contrib/neo4j-apoc-procedures#1725]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Expected Behavior (Mandatory)
According to the docs (
RETURN apoc.number.parseFloat('12.345,67', '#,##0.00;(#,##0.00)', 'it') as value;

12345.67

That works for me in 3.5.6

Also:

RETURN apoc.number.parseInt('12.345', '#,##0.00;(#,##0.00)', 'it') as value;
should return: 12345

and

RETURN apoc.number.format(12345.67, '#,##0.00;(#,##0.00)', 'it') as value;
should return 12.345,67

## Actual Behavior (Mandatory)
In 4.2.0 (and 4.1.0):

RETURN apoc.number.parseFloat('12.345,67', '#,##0.00;(#,##0.00)', 'it') as value;
12.345

(only tried in 4.2.0)
RETURN apoc.number.parseInt('12.345', '#,##0.00;(#,##0.00)', 'it') as value;
12,345.67

(only tried in 4.2.0)
RETURN apoc.number.format(12345.67, '#,##0.00;(#,##0.00)', 'it') as value;
12,345.67

## How to Reproduce the Problem
See call above

### Simple Dataset (where it's possibile)
Not needed.
```
//Insert here a set of Cypher statements that helps us to reproduce the problem
RETURN apoc.number.parseFloat('12.345,67', '#,##0.00;(#,##0.00)', 'it') as value;
```

### Steps (Mandatory)

  1. Run RETURN apoc.number.parseFloat('12.345,67', '#,##0.00;(#,##0.00)', 'it') as value;
  1. Verify that the result does not match with the docs example
  1.

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: MAcOS Catalina 10.15.7 (19H2)
  - Neo4j: 4.2.0
  - Neo4j-Apoc: apoc-4.2.0-rc02-core.jar

And
  - OS: MAcOS Catalina 10.15.7 (19H2)
  - Neo4j: 4.1.0
  - Neo4j-Apoc: apoc-4.1.0.1.jar

**Comment by vga91** [comment]
@malencv I didn't reproduce the problem, in both versions. 
Could you try again with the latest versions? Thank you.
