### ISSUE TITLE
afterAsync phase trigger from 4.0~4.1 to 4.2 and 4.3

### ISSUE THREAD

**Issue by iNViTiON** [neo4j-contrib/neo4j-apoc-procedures#1731]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Expected Behavior (Mandatory)
APOC 4.2.0.0 and 4.3.0-rc01 was missing afterAsync that once implement in 4.0.0.18 and 4.1.0.2 with PR #1573.

<https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/4.1/core/src/main/java/apoc/trigger/TriggerHandler.java#L44>

## Actual Behavior (Mandatory)
afterAsync phase was missing from trigger handler both on branch 4.2 and 4.3.

<https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/4.2/core/src/main/java/apoc/trigger/TriggerHandler.java>
<https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/4.3/core/src/main/java/apoc/trigger/TriggerHandler.java>

### Versions

  - OS:
  - Neo4j: 4.2.0
  - Neo4j-Apoc: 4.2.0.0

**Comment by ivangreene** [comment]
The description of this issue isn't very clear, but I'm also experiencing afterAsync handling not working.
Here is a simple procedure to test out:
```
CALL apoc.trigger.add('simple-log', 'CALL apoc.log.debug("Created %s nodes", [size($createdNodes)])', { phase: 'afterAsync' })
```
After installing, create any node, and it will not log. Change phase to `after` and you can observe that the trigger is called when a node is created

**Comment by jexp** [comment]
@mneedham missing cherry-pick

**Comment by conker84** [comment]
The cherry-pick has been done so I'm closing this
