### ISSUE TITLE
Document apoc.all required for apoc.nlp

### ISSUE THREAD

**Issue by stuartlaurie** [neo4j-contrib/neo4j-apoc-procedures#1750]
When trying to set up apoc.nlp it isn't obvious when reading the following pages, that apoc.all is required:
https://neo4j.com/labs/apoc/4.1/nlp/

This is clearly documented on the main docs page below, would be great to reference to avoid confusion
https://neo4j.com/labs/apoc/4.1/overview/apoc.nlp/

**Comment by vga91** [comment]
The issue links to version 4.1 which has no indication indeed.

But currently, the labels indicating that the procedures belong to APOC Full (and APOC Extended in 5.0) were included in [this commit](https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/d05a6d0231ab2d8291f2c9b22056b8a385af8e3c) (regarding 4.4 and 5.x)
See [docs/asciidoc/modules/ROOT/pages/nlp/gcp.adoc](https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/d05a6d0231ab2d8291f2c9b22056b8a385af8e3c#diff-c39b53654df8e5b36e733dee457acfbbf36352e5be92d75113ed9218cd456f9e) and [apoc.nlp.gcp.entities.graph.adoc](https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/d05a6d0231ab2d8291f2c9b22056b8a385af8e3c#diff-ac2a47c1a9fedd5e86798e85b73aaddcd8d7a46d7593dc809b86056dcb9b5df8) for examples.

These are, for instance, the documentation pages for [GCP 4.4](https://neo4j.com/labs/apoc/4.4/nlp/gcp/):
<img width="1292" alt="Screenshot 2024-02-21 at 14 33 40" src="https://github.com/neo4j-contrib/neo4j-apoc-procedures/assets/25103389/7d5a2bd8-132e-49e3-b677-7f3dd1a92a6b">


and[ 5.x](https://neo4j.com/labs/apoc/5/nlp/gcp/): 

<img width="1292" alt="Screenshot 2024-02-21 at 14 33 48" src="https://github.com/neo4j-contrib/neo4j-apoc-procedures/assets/25103389/e425589b-ba32-4446-946d-cef31a2c6163">
