### ISSUE TITLE
APOC 4.2.x uses unsupported neo4j-java-driver version

### ISSUE THREAD

**Issue by nioertel** [neo4j-contrib/neo4j-apoc-procedures#1758]
## Expected Behavior (Mandatory)
APOC 4.2.x depends on neo4j-java-driver that is officially supported to run with Neo4j 4.2.x.

## Actual Behavior (Mandatory)
APOC 4.2.x depends on neo4j-java-driver 4.0.0 which according to [official docs](https://github.com/neo4j/neo4j-java-driver/wiki) only supports Neo4j 3.5 and 4.0.

**Comment by nioertel** [comment]
Hope my PR works for you and there can maybe bee a 4.2.0.1 soon :).

**Comment by conker84** [comment]
closed via 7ed0c27
