### ISSUE TITLE
Additional documentation on apoc.triggers

### ISSUE THREAD

**Issue by dmk255** [neo4j-contrib/neo4j-apoc-procedures#176]
I've been looking at using the apoc trigger functionality. It looks seriously powerful. 

That said I don't have a strong understanding of what statements  are accessible (e.g {createdLabels}, etc ) and what they contain. 

I'd love to see some documentation around this functionality and a few relatively complex examples (e.g update a label on a node, propagate some information to all connected nodes). 

Thank you!!

**Comment by jexp** [comment]
If you have some concrete examples I'd love to add more. I'll create a placeholder document to include in the docs and then we can add more examples there.

**Comment by vic** [comment]
@dmk255 take a look at http://neo4j.com/docs/java-reference/current/javadocs/org/neo4j/graphdb/event/TransactionData.html 

Maybe we should link to that on the docs.

**Comment by jexp** [comment]
Good idea.

**Comment by vramas** [comment]
Hi,

**Comment by jexp** [comment]
Besides the tests there are currently no examples, we still need to create that docs page.
