### ISSUE TITLE
Unable to load MSSQL JDBC driver

### ISSUE THREAD

**Issue by romandogadin** [neo4j-contrib/neo4j-apoc-procedures#1767]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Expected Behavior (Mandatory)
Expecting call apoc.load.driver("com.microsoft.sqlserver.jdbc.SQLServerDriver") to load the MSSQL driver with no errors

## Actual Behavior (Mandatory)
Getting the error: Failed to invoke procedure `apoc.load.driver`: Caused by: java.lang.RuntimeException: Could not load driver class com.microsoft.sqlserver.jdbc.SQLServerDriver com.microsoft.sqlserver.jdbc.SQLServerDriver

## How to Reproduce the Problem
Run: call apoc.load.driver("com.microsoft.sqlserver.jdbc.SQLServerDriver")

### Simple Dataset (where it's possibile)

```
//Insert here a set of Cypher statements that helps us to reproduce the problem

```

### Steps (Mandatory)

  1. Upload mssql-jdbc-8.4.1.jre8.jar driver into the plugins directory (also tried mssql-jdbc-8.4.1.jre11 and mssql-jdbc-8.4.1.jre14)
  2. Restarted the Desktop
  3. Started the database
## Screenshots (where it's possibile)
![Capture](https://user-images.githubusercontent.com/48025741/104783079-4f57fa80-5753-11eb-8341-7c0ae40dc78f.PNG)
![Capture](https://user-images.githubusercontent.com/48025741/104783153-6dbdf600-5753-11eb-930c-c9eb2f4da1f8.PNG)
![Java](https://user-images.githubusercontent.com/48025741/104783363-dc9b4f00-5753-11eb-87bb-bae190a91314.PNG)

## Specifications (Mandatory)

Neo4j DBMS: 4.1.3
Java: 11.0.9
Java SE 18.9
### Versions

  - OS: Win 10
  - Neo4j: 4.1.3
  - Neo4j-Apoc: 4.1.0.4

**Comment by conker84** [comment]
@romandogadin can you just try to call the `apoc.load.jdbc` with the proper connection string and report back?

**Comment by romandogadin** [comment]
Hi @conker84 , thank you for your reply. 
Here is what I get when I try to connect:
Failed to invoke procedure `apoc.load.jdbc`: Caused by: java.sql.SQLException: No suitable driver found for jdbc:sqlserver://XXXX

**Comment by romandogadin** [comment]
@conker84 , this is the version I have been using all this time. I removed the apoc-4.3.0 file from the plugin directory you are seeing on the screenshot to avoid confusion.
![APOC](https://user-images.githubusercontent.com/48025741/105366640-90299680-5bcd-11eb-8a51-39b1e3664637.PNG)

**Comment by conker84** [comment]
[mssql-jdbc-8.4.1.jre11.jar.zip](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/5850640/mssql-jdbc-8.4.1.jre11.jar.zip)
Can you please try with the jar above? 
Please make sure to restart your database once you unzipped the file into the `plugins` directory

**Comment by romandogadin** [comment]
@conker84 I am getting the same error after I uploaded the jar in to the plugins directory. I did restart the database and the desktop prior to executing the command.

**Comment by conker84** [comment]
![image](https://user-images.githubusercontent.com/1833335/105717416-61d6ee80-5f20-11eb-9259-162f217f82ea.png)
<img width="1299" alt="Screenshot 2021-01-25 at 15 01 43" src="https://user-images.githubusercontent.com/1833335/105717446-6e5b4700-5f20-11eb-9d3e-9297a7f01ae8.png">
We successfully tried in both Mac and Windows env, so it's something related to your classpath.
What your Neo4j Desktop version?

**Comment by romandogadin** [comment]
Thanks for looking into it. My desktop version is 1.4.1. The OS is Win10. Is there anything particular I can do to troubleshoot the classpath issue. Should I enable any logs to get more details? 
Even if I delete everything from the plugins directory and try and execute the command I get the same error message. I was also able to install the APOC plugin without having the apoc library in the plugins dir. Is it possible it is pointed at another directory? Thanks

**Comment by conker84** [comment]
please try to create a new database (and from the database stopped):
1. install apoc
2. import the JDBC driver jar that I shared above into the plugins dir
3. Start Neo4j
4. execute the `apoc.load.driver` call

**Comment by romandogadin** [comment]
Hi @conker84 ,
I have tried following your steps and still no luck - got the same error (DB v4.1.3; APOC 4.1.0.6). I have also tried creating a new db using the latest version 4.2.3 and APOC 4.2.0.1 - same error. It asks me to fix conflicts when I first start the db (attaching the screenshot).
![winex](https://user-images.githubusercontent.com/48025741/106160990-6edc2380-6154-11eb-81d1-6b3cc57f896e.PNG)
![desktop](https://user-images.githubusercontent.com/48025741/106161947-8d8eea00-6155-11eb-9de9-28778f9ab1f0.PNG)
![conflicts](https://user-images.githubusercontent.com/48025741/106161662-46a0f480-6155-11eb-9fd2-97264b5ffb78.PNG)
![driver error](https://user-images.githubusercontent.com/48025741/106161118-9632f080-6154-11eb-8e27-b1302f185d21.PNG)

**Comment by conker84** [comment]
I think that you put the driver under a wrong directory because there is no APOC inside it.
In order to be sure that you are inside the correct dir please look at the following image an click in this order:

1. to the area highlighted in red
2. to the area highlighted in yellow
3. to area highlighted in blue

This will open the correct `plugin` directory and in there put the MSSQL jar, then restart the database
<img width="1361" alt="Screenshot 2021-01-28 at 16 49 15" src="https://user-images.githubusercontent.com/1833335/106163325-50dce600-6189-11eb-8bde-c878f7dea777.png">

**Comment by romandogadin** [comment]
@conker84  that was it! I had a feeling it wasn't pointed at the right plugin directory. Thank you so much.
