### ISSUE TITLE
Nested apoc.periodic.iterate calls deadlock when {parallel: false}

### ISSUE THREAD

**Issue by meiamsome** [neo4j-contrib/neo4j-apoc-procedures#1768]
## Expected Behavior (Mandatory)
The provided query finishes.

## Actual Behavior (Mandatory)
The query deadlocks, and is unkillable. It also means any other calls to `apoc.periodic.iterate` with `parallel: false` will also now deadlock.

## How to Reproduce the Problem
Run the following query:
```cypher
CALL apoc.periodic.iterate(
    "
        UNWIND [1, 2, 3] AS x
        RETURN x
    ",
    "
        CALL apoc.periodic.iterate(
            'UNWIND [1, 2, 3] AS x RETURN x',
            'RETURN x',
            { parallel: false }
        )
        YIELD failedBatches
        RETURN 0
    ",
    { parallel: false }
)
```

## Specifications (Mandatory)

Currently used versions

### Versions
  - OS: Mac OS X
  - Neo4j: 4.0.3
  - Neo4j-Apoc: 4.0.0.10
  
## Analysis

It appears that when parallel is false, both calls to `apoc.periodic.iterate` will try to run on the same executor:
https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/2410a2e2c39ca303ee97695a2a4a67974b3ce848/core/src/main/java/apoc/periodic/Periodic.java#L259
https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/2410a2e2c39ca303ee97695a2a4a67974b3ce848/core/src/main/java/apoc/Pools.java#L100-L102
https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/2410a2e2c39ca303ee97695a2a4a67974b3ce848/core/src/main/java/apoc/Pools.java#L69-L70

Which leads to the surprising deadlocking behaviour. Additionally, this means that the executor will remain deadlocked indefinitely, so all later calls to `apoc.periodic.iterate` will hang indefinitely. I would expect that each call to `apoc.periodic.iterate` would create its own executor, which would prevent a deadlock and also allow for running `apoc.periodic.iterate` calls in parallel without them blocking eachother.

**Comment by conker84** [comment]
this should be fixed, feel free to reopen in case it come back
