### ISSUE TITLE
Concurrency parameter to apoc.periodic.iterate is ignored

### ISSUE THREAD

**Issue by meiamsome** [neo4j-contrib/neo4j-apoc-procedures#1769]
## Expected Behavior (Mandatory)
For the cypher provided, the statements should be executed sequentially for a total execution time of approximately 5 seconds.

## Actual Behavior (Mandatory)
The cypher executes all steps in parallel regardless of the `concurrency` parameter and completes in approximately 1 second.

## How to Reproduce the Problem

The `apoc.jobs.pool.num_threads` option must be set to be > 1 (Preferrably > 5).
Execute the following cypher:
```cypher
CALL apoc.periodic.iterate(
    "
        UNWIND range(1, 5) AS x
        RETURN x
    ",
    "
        CALL apoc.util.sleep(1000)
        RETURN 0
    ",
    {
      batchSize: 1,
      parallel: true,
      concurrency: 1
    }
 )
```

## Specifications (Mandatory)

Currently used versions

### Versions
  - OS: Mac OS X
  - Neo4j: 4.0.3
  - Neo4j-Apoc: 4.0.0.10

## Analysis

It appears the code for handling this parameter is currently commented out:
https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/fd5963c1bf1bff87b228338c8683db89dcfc9cb7/core/src/main/java/apoc/periodic/Periodic.java#L282-L295

**Comment by voutilad** [comment]
@meiamsome Just had a PR merged that should fix this...care to validate?

**Comment by conker84** [comment]
this should be fixed, feel free to reopen in case it come back
