### ISSUE TITLE
example for apoc.cypher.run

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#177]
Nice idea from Lorenzo:
```
CALL db.labels() yield label
call apoc.cypher.run("MATCH (n:`"+label+"`) RETURN keys(n) as keys LIMIT 1",{}) yield value as row
RETURN label, row.keys as keys
```

**Comment by kevinco26** [comment]
is this "safe" towards neo4j injection? I have been trying this but programatically, and Ive used WithParams with neo4j client for c# but withParams don't work for label or relationship types for example. So if I were to use the above, would tat be the same as concatenating a string on the code (hence vulnerable to injection) or does apoc do something special on top of it?

**Comment by InverseFalcon** [comment]
This particular example is safe, as `label` is coming from `db.labels()`, but the technique of using string concatenation into a query to get matching to dynamic labels is not safe, as parameters from outside neo4j pose risk of cypher injection. You could probably render it safe by performing a string operation so the given variable is only a single token, however.

**Comment by jexp** [comment]
ya you would have to sanitize the input, e.g. by removing all escapes and all backticks.
