### ISSUE TITLE
Documentation uses deprecated functions - https://neo4j.com/labs/apoc/4.2/virtual/virtual-nodes-rels/

### ISSUE THREAD

**Issue by joelduerksen** [neo4j-contrib/neo4j-apoc-procedures#1777]
## Expected Behavior (Mandatory)

NOTE: Documentation buttons lead to github as the place to report documentation issues, but this might not be the best path?

Example cypher code in documentation works as provided as functionality implies with "Run in Neo4j Browser" and "Copy to Clipboard"

[documentation page](https://neo4j.com/labs/apoc/4.2/virtual/virtual-nodes-rels/ )
references the (deprecated I assume?) non existent function 

`apoc.coll.groupBy`

## Actual Behavior (Mandatory)

```
Neo.ClientError.Statement.SyntaxError
Unknown function 'apoc.coll.groupBy' (line 3, column 6 (offset: 156))
"WITH apoc.coll.groupBy(countryNodes, "name") AS countries"
    ^
```

## How to Reproduce the Problem

Use cypher from the 4.x [documentation page](https://neo4j.com/labs/apoc/4.2/virtual/virtual-nodes-rels/ )

### Simple Dataset (where it's possibile)

```
MATCH (p:Person) WITH collect(distinct p.country) as countries
WITH [cName IN countries | apoc.create.vNode(['Country'],{name:cName})] as countryNodes
WITH apoc.coll.groupBy(countryNodes,'name') as countries
MATCH (p1:Person)-[:KNOWS]->(p2:Person)
WITH p1.country as cFrom, p2.country as cTo, count(*) as count, countries
RETURN countries[cFrom] as from, countries[cTo] as to, apoc.create.vRelationship(countries[cFrom],'KNOWS',{count:count},countries[cTo]) as rel;
```

### Steps (Mandatory)

  1. Use cypher from documentation

## Screenshots (where it's possibile-[:CORRECT_SPELLING]->(possible) )

<img width="1160" alt="deprecated function" src="https://user-images.githubusercontent.com/39315090/105085772-33f83280-5a66-11eb-983c-34bacab489e4.png">

## Specifications (Mandatory)

4.x documentation page

### Versions

4.x documentation page

**Comment by conker84** [comment]
@joelduerksen thank you so much that procedure exists, but has a different name `apoc.map.groupBy` we'll update the documentation accordingly.

**Comment by joelduerksen** [comment]
Thank you.  If I recall correctly I may have noticed a couple of other nearby things that were out of date too, but didn't want to file multiple tickets.  The reviewer/editor will (I hope) be thinking about what other calls were renamed, or replaced at the same time, and update those sections too..
