### ISSUE TITLE
fulltext index gets removed

### ISSUE THREAD

**Issue by linojon** [neo4j-contrib/neo4j-apoc-procedures#1781]
hello. I create a fulltext index, and moments later the index is gone from the database. This problem is consistently repeated. Perhaps there's a problem when i query against the index? or something else? 

To create index in neo4j browser:
```
CALL db.index.fulltext.createNodeIndex("topicNameIndex", ["Topic"], ["name"])
```

To query the index:
```
  topicFuzzySearch(searchString: String): [Topic]
    @cypher(
      statement: """
      CALL db.index.fulltext.queryNodes('topicNameIndex', $searchString+'~')
      YIELD node RETURN node
      """
    )
````

If you're in touch with the Aura cloud team, I cross posted there but it occurs both on Aura and my local database.
https://aura.support.neo4j.com/hc/en-us/requests/11726

Neo4j: 4.2.0
APOC: 4.3.0-rc01

**Comment by conker84** [comment]
Hi @linojon can you elaborate on how this is related to APOC?

**Comment by jexp** [comment]
Please keep it in the aura support portal, or raise at https://github.com/neo4j/neo4j
