### ISSUE TITLE
Concurrency parameter to apoc.periodic.iterate is off-by-one in 3.x

### ISSUE THREAD

**Issue by meiamsome** [neo4j-contrib/neo4j-apoc-procedures#1782]
## Expected Behavior (Mandatory)
For the cypher provided, the statements should be executed sequentially for a total execution time of approximately 5 seconds.

## Actual Behavior (Mandatory)
The cypher executes two steps in parallel regardless of the concurrency parameter and completes in approximately 3 second.

## How to Reproduce the Problem
The apoc.jobs.pool.num_threads option must be set to be > 1 (Preferrably > 5).
Execute the following cypher:
```cypher
CALL apoc.periodic.iterate(
    "
        UNWIND range(1, 5) AS x
        RETURN x
    ",
    "
        // This appears to be needed for the sleep to actually execute correctly
        CALL apoc.do.when(true, 'CALL apoc.util.sleep(1000) RETURN 0', '', {})
        YIELD value
        RETURN 0
    ",
    {
      batchSize: 1,
      parallel: true,
      concurrency: 1
    }
 )
```

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: Mac OS X
  - Neo4j: 3.5.26
  - Neo4j-Apoc: 3.5.0.15
  
Note that this doesn't apply to 4.x versions because of #1769, but the code that is currently commented out that I reference in that issue still has this bug present.
  
## Analysis

This parameter is checked here in the loop where the tasks are spawned: 

https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/646c92908eec26c40bda7010d347b46c3695009a/src/main/java/apoc/periodic/Periodic.java#L394

The check is doing `>`, which means that for an argument of `concurrency` of 1, the if will only be executed when there is already 2 tasks that have been launched.
The apoc documentation says of the parameter:
> number of concurrent tasks are generated when using parallel:true

I think that in that case, the concurrency check should be `futures.size() >= concurrency` so that the correct number of tasks are launched.

**Comment by conker84** [comment]
This should be fixed in the branch `3.5` but not yet released, feel free to build it from the source.
Reopen this if the error come back
