### ISSUE TITLE
Add mongo procedure to get record by id

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-apoc-procedures#1784]
Add a procedure `apoc.mongo.get.byObjectId(<hostOrKey>, <db>, <collection>, <objectIdValueAsString>, <fieldName, default=_id>)` in order to get the the documents by ObjectId becayse now not it's not possibile.

**Comment by conker84** [comment]
Please update the user that raised the issue:
https://community.neo4j.com/t/any-way-to-query-apoc-mongodb-find-by-objectid/32523/2

**Comment by simon-hoegl** [comment]
I stumbled across the same issue but in update context. I think a more general approach would be good, so it could be used in all mongo procedures.
Maybe allow usage of the [MongoDB Extended JSON (v2)]((https://docs.mongodb.com/manual/reference/mongodb-extended-json/#bson.ObjectId)) in the query map.
`{ "$oid": "<ObjectId bytes>" }`

**Comment by conker84** [comment]
@simon-hoegl I thought about that but this means a big change for us in order to support all the changes not only this one. We can also think to create a new set of procedures leveraging the full set of Bson extension and deprecating this in the future.
If you want, please fill a new issue with your request and we're happy to discuss it!
