### ISSUE TITLE
create a metagraph of the results of a cypher query (viz similar to apoc.meta.graph's output)  

### ISSUE THREAD

**Issue by plasticfist** [neo4j-contrib/neo4j-apoc-procedures#1788]
Feature request:   function to create a metagraph of the results of a cypher query, in the same way that apoc.meta.graph does for the entire graph.  

Reference: https://community.neo4j.com/t/best-way-to-create-a-metagraph-of-the-results-from-a-cypher-query-that-returns-paths/32527

Alternative?  I'm currently attempting to do this with the non-optimal Cypher statement below (note: this cypher only works for paths, the function/procedure should I believe work for the results of any query that returns a graph like result consisting of paths, nodes/rels, at least it should without too many contortions to finagle the input)

MATCH p= (p1:Supplier {supplierID:'20'})-[*..2]->(p2)    // PUT QUERY HERE - nodes
UNWIND nodes(p) as n
with distinct n as dn
WITH labels(dn) as l
WITH apoc.create.vNode(l,{name:head(l), count:count(l)}) as metaNodes
WITH apoc.map.groupBy(collect(metaNodes),'name') as ml
MATCH p=(p1:Supplier {supplierID:'20'})-[*..2]->(p2)  // PUT QUERY HERE TOO - relationships
unwind relationships(p) as r
WITH head(labels(startNode(r))) as cFrom, head(labels(endNode(r))) as cTo, count(*) as count, ml, type(r) as tr
RETURN ml[cFrom] as from, ml[cTo] as to, apoc.create.vRelationship(ml[cFrom],tr,{count:count},ml[cTo]) as rel

This features enables an efficient look at the results of a query "at a glance", counts of nodes and relationships, it would be particularly helpful 1. in providing a summary view of the entire result set to a user when it is necessary to clip/truncate the output for display 2. while using cypher iteratively to explore high degree heterogeneous graphs, with this one can see the overall quantities at a glance, and it would be very helpful in seeing what is being found with any given query. (at a high level, quickly, without returning thousands of nodes)

Maybe a screenshot or design?
See reference URL above for a simple example with images.

**Comment by conker84** [comment]
[apoc-4.1.0.5-all.jar.zip](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/5881247/apoc-4.1.0.5-all.jar.zip)
@plasticfist can you try with the jar above?
I added two procedures:

* `apoc.meta.data.of(<input>, <config>)`
* `apoc.meta.graph.of(<input>, <config>)`

The `input` can be:

* a cypher query
* a Virtual graph returned by `apoc.graph.*`
* a map with two field `nodes` (a list of nodes, *mandatory*), `relationships` (a list of relationships)

Looking forward to your feedback!

**Comment by plasticfist** [comment]
It is close, in simple tests the node count appears, but it appears to be
returning aggregated edge counts.
Example, if two nodes have multiple relationships (perhaps just when it is
the same type of edge?) between them, all of those edges are only counted
as a single edge.  I would need to see the actual edge count, however now I
can see the utility of (also) knowing the aggregated edge count as well,
that could be useful, at a glance in the meta graph!

Here is how I called it, I first tried to pass in a list of nodes and
relationships, but couldn't get the syntax figured out.  So I used cypher,
which is fine.

call apoc.meta.graph.of("match t=(p:Phenotype {id:'C0030567'})-[*..2]->()
return t")
YIELD nodes, relationships
return *

Possibly related notes: Normally I do edge aggregation outside Neo4j before
building loading a graph but I have it turned off because I'm looking at
doing the graph mutations inside Neo4j.   I have to mutate the main graph
because in-memory can't deal with strings, and one can't run cypher queries
on them (to my knowledge).

if I could work with an in-memory graph the same as the main graph, I would
do that, or if I could create with cypher a new named graph (aggregated)
based on a source graph, that would also be nice.  I don't think either of
these are possible yet though.  I also do edge filtering by score/weight
before Neo4j, this step I might prefer to do inside neo4j as well, if
reasonble to do.  I guess I do a fair bit of graph filtering and
re-shaping, and I've been thinking it might be easier and feel more natural
to have an ALL big graph in Neo4j and then filter, aggregate and otherwise
shape it into another graph that is then searched. (a step done repeatedly,
create new derivative, search it, drop it, repeat)

**Comment by conker84** [comment]
So if i test with this simple graph:

```
CREATE (p:Person {name:'Tom Hanks'}),
  (m:Movie {title:'Forrest Gump'}),
  (pr:Product{name: 'Awesome Product'}),
  (pr2:Product{name: 'Awesome Product2'}),
  (p)-[:VIEWED]->(m),
  (p)-[:BOUGHT{quantity: 10, day: "20201212"}]->(pr),
  (p)-[:BOUGHT{quantity: 2}]->(pr2),
  (p)-[:BOUGHT{quantity: 4, day: "20200212"}]->(pr)
```

You want an option that counts `(p)-[:BOUGHT]->(pr)` only once right?

**Comment by joelduerksen** [comment]
Thank you for working to add this capability!
NOTE: After a second look today and hand counting edges, I believe apoc.meta.graph.of(cypher) is working correctly.  What I saw yesterday was actually an issue with my prototype cypher attempt.  I'm glad you are adding this...

Yes, exactly, ideally the :BOUGHT edge in the meta graph would have two properties .count=3 and .aggr_count=2 (naming tbd).   The aggregated count has meaning in the context of full count, so I personally would prefer to see them together on the edge.  

However, I understand it is likely to be less complicated, more performant and a more holistic design approach to return an all count by default OR optionally an aggregated count.  (same edge properties with a different values)

**Comment by conker84** [comment]
@joelduerksen oki for now we'll merge the procedure without the aggregate count, we'll add the feature in future releases as it can be managed via cypher query in this version

**Comment by joelduerksen** [comment]
Ok! thank you.
