### ISSUE TITLE
apoc.path.expand removes input node when null is returned

### ISSUE THREAD

**Issue by dmk255** [neo4j-contrib/neo4j-apoc-procedures#180]
```
match (r:foo {name: 'foo'})
call apoc.path.expand(r, "<CONTAINED|<ACCESSED", "/bar", 0, 50) yield path as bar
return r
```
If a path is not returned then this returns nothing. However if a path is returned then `r` returns the node in the initial match.

In fact. if that path returns null then you lose all of your data. E.g.
```
match (r:foo {name: 'foo'})
call apoc.path.expand(r, "<CONTAINED|<ACCESSED", "/bar", 0, 50) yield path as bar
with bar
match (f:foo {name: 'foo'})
return f
```
still returns null.

I'm not sure if this is intentional but it's causing some unfortunate issues.

**Comment by jexp** [comment]
expand.path is currently like MATCH
what you're asking for is OPTIONAL MATCH behavior

as discussed, please add it to expand.pathConfig and send a PR
