### ISSUE TITLE
`apoc.import.csv`: Caused by: java.util.NoSuchElementException: No value present

### ISSUE THREAD

**Issue by roamerop** [neo4j-contrib/neo4j-apoc-procedures#1803]
## Guidelines
According the `APOC Documentation`, i try to `Loading nodes` but failed. 
`Loading nodes and relationships` works ok.
[doc](https://neo4j.com/labs/apoc/4.2/import/import-csv/)

## Actual Behavior (Mandatory)
turns error `apoc.import.csv`: Caused by: java.util.NoSuchElementException: No value present

### Versions

  - OS: Centos7
  - Neo4j: 4.2.2
  - Neo4j-Apoc: 4.2.0.1

**Comment by conker84** [comment]
@roamerop can you share the file and the full command that you're using?

**Comment by roamerop** [comment]
I just execute the doc example  cmd  [see](https://neo4j.com/labs/apoc/4.2/import/import-csv/)
```
name:STRING
John
Jane
``` 
`CALL apoc.import.csv([{fileName: 'file:/persons.csv', labels: ['Person']}], [], {})`

**Comment by roamerop** [comment]
> @roamerop can you share the file and the full command that you're using?

I just execute the doc example cmd see
```
name:STRING
John
Jane
```
`
CALL apoc.import.csv([{fileName: 'file:/persons.csv', labels: ['Person']}], [], {})
`
