### ISSUE TITLE
Cannot kill query if the concurrency is set to 0 in apoc.periodic.iterate()

### ISSUE THREAD

**Issue by viveksaran71** [neo4j-contrib/neo4j-apoc-procedures#1805]
## Expected Behavior (Mandatory)
**dbms.killQuery()** should be able to kill the `apoc.periodic.iterate()` if `concurrenc:0` config is set with `parallel:true`.

## Actual Behavior (Mandatory)

If we try to kill it, there is no effect of the kill query. Neo4j eventually gets into an unrecoverable state with the apoc query still running.

## How to Reproduce the Problem

To reproduce the issue prepopulate a empty db using:

```
call apoc.periodic.iterate(
"unwind range(1,10000000)  as i return i",
"create (p:Person{name:'person_' + i})",
{batchsize:10000, parallel:true})
```
Once finished, execute this query:

```
call apoc.periodic.iterate('match (n) return n', 'set n.newprop=1 with n call apoc.util.sleep(1000) return n', 
{batchSize: 10000,parallel:true, concurrency: 0})
```

While running, get the queryId of that statement using

```
call dbms.listQueries() yield queryId, query, startTime
```

and kill it using

```
call dbms.killQuery(<queryId>)
```

Removing the `concurrency` config or setting it to a reasonable value (anything less than or equal to the number of cores on the server) works fine. We can easily kill the query.

### Comment
It is understood that setting `concurrency:0` does not make sense, but we should still be able to kill the query. 

### Versions

  - OS: All
  - Neo4j: tested on 3.5.18 and 4.2.0
  - Neo4j-Apoc: 3.5.0.12 and 4.2.0.0

**Comment by voutilad** [comment]
@viveksaran71 I believe #1794 should fix the run-away query, but it's not cherry-picked into the 4.2 branch yet. I did a manual test and I can stop both queries without issue using the Browser gui.

I think that `{ concurrency: 0 }` (any value `< 1`) should instead result in an exception and fail immediately.
