### ISSUE TITLE
How to config apoc while using sandbox?

### ISSUE THREAD

**Issue by ninjakx** [neo4j-contrib/neo4j-apoc-procedures#1806]
**Traceback:** 

`ClientError: [Procedure.ProcedureCallFailed] Failed to invoke procedure `apoc.load.json`: Caused by: java.lang.RuntimeException: Import from files not enabled, please set apoc.import.file.enabled=true in your apoc.conf`

I am working on yelp dataset and for that using kaggle kernel and created a sandbox project.

```
from py2neo import Graph
import pandas as pd

graph = Graph("bolt://XX.XX.XXX.XXX:7687", auth=("neo4j", "password")) 

query="""
CALL apoc.load.json("../input/yelp-dataset/yelp_academic_dataset_business.json");
"""
graph.run(query)
```

How do I make it work in kaggle kernel? when I am using neo4j desktop I am able to load it but not with using sandbox.

**Comment by jexp** [comment]
You cannot access the filesystem on a sandbox, so please use remote http(s) URLs instead for your data.
