### ISSUE TITLE
Problems with apoc.diff.nodes and Neo4j 4.2

### ISSUE THREAD

**Issue by reneleitz** [neo4j-contrib/neo4j-apoc-procedures#1809]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

After updating Neo4j 3.5.16 to 4.2 i have problems with the apoc function apoc.diff.nodes.
Mr. Armbruster advised me to open a ticket for this issue.
Due to the changed transactional behavior apoc.diff.nodes can not work with virtual nodes. 

## Actual Behavior (Mandatory)
Here the error message:
org.neo4j.driver.v1.exceptions.ClientException: Failed to invoke function `apoc.diff.nodes`: Caused by: org.neo4j.internal.kernel.api.exceptions.EntityNotFoundException: Unable to load NODE with id -4. 
at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:123) ~[neo4j-java-driver-1.7.5.jar:1.7.5-d56154a7e96ff71615b894ee9a15d08c370691e6] 
at org.neo4j.driver.internal.ExplicitTransaction.close(ExplicitTransaction.java:117) ~[neo4j-java-driver-1.7.5.jar:1.7.5-d56154a7e96ff71615b894ee9a15d08c370691e6] 
at de.guh.plugin.neo4j.Graph.execute(Graph.java:203) [inchorus-neo4j-plugin-2.0.12.jar:?] at de.guh.gadget.NodeCollection.sendCypherStatement(NodeCollection.java:982) [classes/:?] 
at de.guh.gadget.NodeCollection.runNodeCollection(NodeCollection.java:407) [classes/:?] at de.guh.gadget.Collector.runCollector(Collector.java:1096) [classes/:?] 
at de.guh.gadget.Collector.execute(Collector.java:2048) [classes/:?] at it.sauronsoftware.cron4j.TaskExecutor$Runner.run(Unknown Source) [cron4j-2.2.5.jar:?] 
at java.lang.Thread.run(Thread.java:834) [?:?]

### Simple Dataset (where it's possibile)

```
UNWIND $data as object OPTIONAL MATCH (preexists:User:SecurityPrincipal{uniqueid:object.uniqueid, collectionid: object.collectionid}) MERGE (source:User:SecurityPrincipal{uniqueid:object.uniqueid, collectionid: object.collectionid}) WITH object, source, preexists, apoc.diff.nodes(source,apoc.create.vNode(['User:SecurityPrincipal'], object)) as delta OPTIONAL MATCH (source)<-[targetrelation_1_1:OWNS_USER]-(:ActiveDirectoryDomain {systemid: '1'}) CALL apoc.do.when( targetrelation_1_1 IS NULL,  " OPTIONAL MATCH (source)<-[targetrelation_1_2:OWNS_USER]-(:ActiveDirectoryDomain)  DELETE targetrelation_1_2  WITH source, object  OPTIONAL MATCH (targetnode_1_1:ActiveDirectoryDomain {systemid: '1'})  CALL apoc.do.when(  targetnode_1_1 IS NOT NULL , 'MERGE (source1)<-[:OWNS_USER]-(targetnode_1_1) RETURN 1' , 'RETURN 1' , {source1:source, targetnode_1_1:targetnode_1_1}  )  YIELD value RETURN 1  " ,  'RETURN 1' , {source:source, object:object}  )  YIELD value AS ignored1 OPTIONAL MATCH (source)<-[targetrelation_2_1:HAS_SECURITYPRINCIPAL]-(:Person {username:object.name}) CALL apoc.do.when( targetrelation_2_1 IS NULL ,  " OPTIONAL MATCH (source)<-[targetrelation_2_2:HAS_SECURITYPRINCIPAL]-(:Person)  DELETE targetrelation_2_2  WITH source, object  OPTIONAL MATCH (targetnode_2_1:Person {username:object.name})  CALL apoc.do.when(  targetnode_2_1 IS NOT NULL , 'MERGE (source1)<-[:HAS_SECURITYPRINCIPAL]-(targetnode_2_1) RETURN 1' , 'RETURN 1' , {source1:source, targetnode_2_1:targetnode_2_1}  )  YIELD value RETURN 1 " , 'RETURN 1' , {source:source, object:object}  )  YIELD value AS ignored2 SET source += object RETURN distinct source.uniqueid AS uniqueid, delta, preexists IS NULL AS hasBeenCreated

```

### Steps (Mandatory)

  1.
  1.
  1.

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS:
  - Neo4j: 4.2
  - Neo4j-Apoc: 4.2.0.1

**Comment by conker84** [comment]
close via f3a42f8
