### ISSUE TITLE
apoc-all is not available on maven repository

### ISSUE THREAD

**Issue by guillaume-alvarez** [neo4j-contrib/neo4j-apoc-procedures#1825]
## Expected Behavior (Mandatory)
For tests, maven can download apoc-all and apoc-core from [maven central repository](https://mvnrepository.com/artifact/org.neo4j.procedure/).

## Actual Behavior (Mandatory)
Only a small 'apoc' jar is present: https://mvnrepository.com/artifact/org.neo4j.procedure/apoc

## How to Reproduce the Problem
Add apoc-all as a maven dependency. It won't be able to download it.

### Versions

  - OS: Linux and Windows10
  - Neo4j: 4.2.3
  - Neo4j-Apoc: 4.2.0.1

See also #1656

**Comment by natete** [comment]
I'm trying using `<classifier>all</classifier>` in de dependency tag. This way I can use the ApocConfig class available but unfortunately, the test is failing to start the embedded database server as recommended in the related issue.

**Comment by natete** [comment]
Finally I made it work with the `classifier` fix.

**Comment by abbas-gadhia** [comment]
Classifier syntax for gradle.

`testImplementation "org.neo4j.procedure:apoc:$neo4j_apoc_version:all"`

**Comment by conker84** [comment]
fixed with #1404
