### ISSUE TITLE
apoc.load.jsonParams as POST request with body input parameters

### ISSUE THREAD

**Issue by leonpierre** [neo4j-contrib/neo4j-apoc-procedures#1831]
## Feature description (Mandatory)
Currently it is possible to call a POST request with jsonParams from apoc but you can't define a body for REST API methods like: 

[HttpPost("getJson")]
[Produces("application/json")]
public async Task<JsonResult> GetJson(int id, [FromBody] List<string> params)

## Considered alternatives
Alternative could be to change the API method to GET and change the input parameter to a string (comma separated):

[HttpGet("getJson")]
[Produces("application/json")]
public async Task<JsonResult> GetJson(int id, string params)

The downside of this approach here is that URL's are limited in length and if you have a lot of input params this could exceed it.

## How this feature can improve the project?
To be able to provide input parameters from body for POST requests.

**Comment by vga91** [comment]
@leonpierre 
The loadJsonParam allows you to insert a `payload` as a string at the 3rd parameter.
https://neo4j.com/labs/apoc/4.1/import/load-json/#load-json-examples-post-json

So, could you pass the stringified input parameters here?
Let me know if this solution is right.

**Comment by leonpierre** [comment]
@vga91 This works! Thank you for your advice!

**Comment by rahulranjan14** [comment]
hey @leonpierre could you please guide me with this, i am trying to send data in a post API which is running locally, but i am not getting the data in api, i am getting req.body as empty object. is there any other way to extract data? ( i followed this https://neo4j.com/labs/apoc/4.1/import/load-json/#load-json-examples-post-json )
