### ISSUE TITLE
[TRIGGER] createdRelationships "after" crash and "afterAsync" do nothing

### ISSUE THREAD

**Issue by rfreydi** [neo4j-contrib/neo4j-apoc-procedures#1840]
## Expected Behavior (Mandatory)

When we add a trigger on `createdRelationships`, it should be executed wether we are in before, after or afterAsync phase.

## Actual Behavior (Mandatory)

The trigger on the phase before work, the same trigger on the phase after loop forever and on the phase afterAsync it does nothing.

## How to Reproduce the Problem

I have created a new db with dedicated node/relationship to reproduce the issue. See below :

### Simple Dataset (where it's possibile)

```
// TEST 1. populate DB
CREATE (:A {name: "A"})-[:R1]->(:Z {name: "Z"})

// TEST 2.1 add trigger before
CALL apoc.trigger.add('trigger-before', 'UNWIND $createdRelationships AS r
MATCH (a:A)-[r]->(z:Z)
WHERE (r:R2 OR r:R3)
MATCH (a)-[r1:R1]->(z)
SET r1.triggerBefore = true', {phase: 'before'})

// TEST 2.2 add trigger after
CALL apoc.trigger.add('trigger-after', 'UNWIND $createdRelationships AS r
MATCH (a:A)-[r]->(z:Z)
WHERE (r:R2 OR r:R3)
MATCH (a)-[r1:R1]->(z)
SET r1.triggerAfter = true', {phase: 'after'})

// TEST 2.3 add trigger after async
CALL apoc.trigger.add('trigger-after-async', 'UNWIND $createdRelationships AS r
MATCH (a:A)-[r]->(z:Z)
WHERE (r:R2 OR r:R3)
MATCH (a)-[r1:R1]->(z)
SET r1.triggerAfterAsync = true', {phase: 'afterAsync'})

// TEST 3. (:A)-[:R2]->(:Z)
MATCH (a:A {name: "A"})-[:R1]->(z:Z {name: "Z"})
MERGE (a)-[:R2]->(z)

// TEST 4. get so data
MATCH (n1)-[r]->(n2) RETURN r, n1, n2 LIMIT 25

// TEST 5. clear DB
MATCH (n) DETACH DELETE n

// TEST 6. remove triggers
CALL apoc.trigger.removeAll()
```

### Steps (Mandatory)

  1. Populate the db TEST 1.
  1. Add 1 (or many) of the trigger provided in TEST 2.X
  1. execute TEST 3. to create the new relationship
  1. check the data, clean the db and remove triggers to retry

## Screenshots (where it's possibile)
Testing before :
![image](https://user-images.githubusercontent.com/21192766/112822052-b6fdc080-9087-11eb-9870-90226818fbd0.png)

Testing after :
![image](https://user-images.githubusercontent.com/21192766/112822325-178cfd80-9088-11eb-91ed-960a7c70f8e4.png)

Testing afterAsync : 
![image](https://user-images.githubusercontent.com/21192766/112822174-e14f7e00-9087-11eb-8cb9-57afd676f13d.png)

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: Windows 10 Family 19041.867
  - Neo4j: 4.2.4
  - Neo4j-Apoc: 4.2.0.2

**Comment by conker84** [comment]
@rfreydi thank you so much for the issue
can you test the following jar?
[apoc-4.2.0.2-all.jar.zip](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/6229554/apoc-4.2.0.2-all.jar.zip)


Btw also your query in the trigger is wrong:

```
UNWIND $createdRelationships AS r
MATCH (a:A)-[r]->(z:Z)
WHERE (r:R2 OR r:R3)
MATCH (a)-[r1:R1]->(z)
SET r1.triggerBefore = true
```

`WHERE (r:R2 OR r:R3)` works only for nodes you have to change it in the following way:

`WHERE type(r) IN ["R3", "R2"]`

so the full query is:

```
UNWIND $createdRelationships AS r
MATCH (a:A)-[r]->(z:Z)
WHERE type(r) IN ["R3", "R2"]
MATCH (a)-[r1:R1]->(z)
SET r1.triggerBefore = true
```

**Comment by conker84** [comment]
Ah please test it with the afterAsync phase!

**Comment by rfreydi** [comment]
Thank you for the correction :D Tested with your jar file and afterAsync work :) !

![image](https://user-images.githubusercontent.com/21192766/113015637-07574a00-917e-11eb-9325-cd602767b560.png)

Still infinite loop for phase `after`

**Comment by conker84** [comment]
The infinite loop in the `after` is because there is a transaction lock that cannot be released, that's why we introduced the `afterAsync` phase, so please use it for your use case
Thank you so much for the feedback!
