### ISSUE TITLE
Delete overload procedure problem

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-apoc-procedures#1850]
Reported by @cg122 in https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1555#issuecomment-815208614

I am using neo4j from docker, with neo4j:latest (4.2.4):
```
docker run -d \
    --name neo4j \
    --publish=7474:7474 --publish=7687:7687 \
    --env NEO4JLABS_PLUGINS='["graph-data-science","apoc"]' \
    --env NEO4J_apoc_export_file_enabled=true \
    --env NEO4J_apoc_import_file_enabled=true \
    --env NEO4J_apoc_import_file_use__neo4j__config=true \
    --env NEO4J_AUTH=neo4j/neo4j \
    neo4j:latest
```
From neo4j browser:
- First register a procedure:
```
call apoc.custom.asProcedure('test_ghost','RETURN 100 as result')
```
- register a procedure with the same name:
```
call apoc.custom.asProcedure('test_ghost','RETURN $count as result','read',[['result','int']],[['count','int']])
```
- check the registered procedure:
```
call apoc.custom.list
```

type | name | description | mode | statement | inputs | outputs | forceSingle
-- | -- | -- | -- | -- | -- | -- | --
1 | "procedure" | "test_ghost" | "" | "read" | "RETURN $count as result" | [["count", "integer"]] | [["result", "integer"]] | null

- run 'test_ghost' with parameter:
```
call custom.test_ghost(15)

--
1 | 15
```

- run 'test_ghost' without parameter:
```
call custom.test_ghost

--
1 | {   "result": 100 }
```

- remove procedure
```
call apoc.custom.removeProcedure('test_ghost')
```
- run 'test_ghost' without parameter still get the result
 ```
call custom.test_ghost

--
1 | {   "result": 100 }
```

- run 'test_ghost' with parameter get the error
 ```
call custom.test_ghost(15)

There is no procedure with the name `custom.test_ghost` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.
```
Seems only the last registered procedure is removed, the 'overwritten' one is still somewhere functioning.

**Comment by conker84** [comment]
@vga91 is this fixed?

**Comment by tomocesnik** [comment]
I see there were some code changes implemented for this issue. Are there any plans on where this will be merged and released?

**Comment by vga91** [comment]
The problem has been solved [here](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3755)
