### ISSUE TITLE
Neomodel uri issue for multiple databases

### ISSUE THREAD

**Issue by abhinavk1492** [neo4j-contrib/neo4j-apoc-procedures#1856]
I recently upgraded my Neo4j database from 3.5 to 4.1 and also the neomodel package. I have created multiple databases on the server. Whenever I am running a query, it always runs on a specific database. What do I need to do to target a different database through bolt URI programmatically?

**Comment by vga91** [comment]
@abhinavk1492 
The issue doesn't seem to regard the APOCs.
I think you should open one here https://github.com/neo4j-contrib/neomodel or https://community.neo4j.com/ (if it's not a bug/feature request), or am I wrong?
