### ISSUE TITLE
Triggers don't apply changes to the data returned within the transaction that triggered them

### ISSUE THREAD

**Issue by AlexiosP** [neo4j-contrib/neo4j-apoc-procedures#1858]
## Expected Behavior

When a [trigger with phase](https://neo4j.com/labs/apoc/4.1/background-operations/triggers/) `before` is triggered during a transaction, I expect the data returned by the transaction to have the changes that were performed by the trigger.

## Actual Behavior

When the trigger is triggered during a transaction, the data that are returned from the transaction that caused the trigger to perform modifications, do not show the changes that were made by the trigger.
But the changes are applied to the graph and are retrievable in subsequent transactions/queries.

This behavior appears on triggers that modify newly created nodes and/or modify nodes which their properties were updated.
I was able to reproduce this on neo4j browser and also in a Spring Data neo4j project.

### Simple Dataset

```
CALL apoc.trigger.add('update-on-creation',
  'UNWIND $createdNodes AS n
  WITH n as node
  WHERE (node:Car)
  SET node.timeCreated = timestamp()', 
  {phase:'before'}
)
```

### Steps

  1. Create a node `CREATE (a:Car {brand: "UNKNOWN"}) RETURN a`
  2. There is no property `timeCreated` on the node `a`
  3. If you retrieve again the node `MATCH (a:Car) RETURN a` then there is the property `timeCreated`

## Screenshots

On step 2: ![image](https://user-images.githubusercontent.com/20590643/115257897-ce811400-a130-11eb-99e4-415c8bbec70a.png)
On step 3: 
![image](https://user-images.githubusercontent.com/20590643/115258223-1607a000-a131-11eb-82fd-d435640bebdc.png)

## Specifications

Currently used versions

### Versions

  - OS: MacOS 10.14.6 used, with docker version 20.10.0 and docker image neo4j:4.1.0
  - Neo4j: 4.1.0
  - Neo4j-Apoc: 4.1.0.1

Also able to reproduce with
 - Neo4j: 4.2.5
 - Neo4j-Apoc: 4.2.0.2

**Comment by conker84** [comment]
@AlexiosP thanks for opening this. This is a visualization problem and there is no way to fix it APOC, so I'm closing this.
Thank you so much!

**Comment by AlexiosP** [comment]
@conker84 Apart from from the visualization aspect, this unexpected behavior exists in the programming level as well.

Suppose you have a Java repository (Kotlin code)
```
import org.springframework.data.neo4j.repository.Neo4jRepository
import org.springframework.stereotype.Repository
import java.util.*

@Repository
internal interface CarRepository : Neo4jRepository<Car, UUID>
```
and its implementation
```

@Repository
internal class CarRepositoryImpl(private val carRepository: CarRepository) {
    fun foo() {
        val resultFromSave: Car = carRepository.save(Car())
        resultFromSave.timeCreated // This will be null
    }
}
```

Is this an expected behavior?

**Comment by BennuFire** [comment]
@conker84 I think this should not be handled as a visualization problem. It's the same behavior with SDN6 Java Driver.
