### ISSUE TITLE
Error due to changes in Trigger.java

### ISSUE THREAD

**Issue by dan-kez** [neo4j-contrib/neo4j-apoc-procedures#186]
I recently started receiving the following error sporadically.

> ERROR Client triggered an unexpected error [UnknownError]: Transaction id is not assigned yet. It will be assigned during transaction commit.. See debug.log for more details,
> (debug.log)
> 
> ```
> 2016-10-25 16:30:15.914+0000 ERROR [o.n.b.v.r.ErrorReporter] Client triggered an unexpected error [UnknownError]: Transaction id is not assigned yet. It will be assigned during transaction commit., reference 69387978-61d5-4f01-8838-76d165261a93. Transaction id is not assigned yet. It will be assigned during transaction commit.
> java.lang.IllegalStateException: Transaction id is not assigned yet. It will be assigned during transaction commit.
>         at org.neo4j.kernel.impl.api.KernelTransactionImplementation.getTransactionId(KernelTransactionImplementation.java:782)
>         at org.neo4j.kernel.impl.coreapi.TxStateTransactionDataSnapshot.getTransactionId(TxStateTransactionDataSnapshot.java:169)
>         at apoc.trigger.Trigger$TriggerHandler.executeTriggers(Trigger.java:155)
>         at apoc.trigger.Trigger$TriggerHandler.afterCommit(Trigger.java:195)
>         at org.neo4j.kernel.internal.TransactionEventHandlers.afterCommit(TransactionEventHandlers.java:149)
>         at org.neo4j.kernel.internal.TransactionEventHandlers.afterCommit(TransactionEventHandlers.java:47)
>         at org.neo4j.kernel.impl.api.TransactionHooks.afterCommit(TransactionHooks.java:75)
>         at org.neo4j.kernel.impl.api.KernelTransactionImplementation.afterCommit(KernelTransactionImplementation.java:688)
>         at org.neo4j.kernel.impl.api.KernelTransactionImplementation.commit(KernelTransactionImplementation.java:629)
>         at org.neo4j.kernel.impl.api.KernelTransactionImplementation.closeTransaction(KernelTransactionImplementation.java:485)
>         at org.neo4j.kernel.api.KernelTransaction.close(KernelTransaction.java:135)
>         at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State.closeTransaction(TransactionStateMachine.java:325)
>         at org.neo4j.bolt.v1.runtime.TransactionStateMachine$State$1.streamResult(TransactionStateMachine.java:213)
>         at org.neo4j.bolt.v1.runtime.TransactionStateMachine.streamResult(TransactionStateMachine.java:93)
>         at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$3.pullAll(BoltStateMachine.java:423)
>         at org.neo4j.bolt.v1.runtime.BoltStateMachine.pullAll(BoltStateMachine.java:227)
>         at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onPullAll$5(BoltMessageRouter.java:92)
>         at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.execute(RunnableBoltWorker.java:136)
>         at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.executeBatch(RunnableBoltWorker.java:123)
>         at org.neo4j.bolt.v1.runtime.concurrent.RunnableBoltWorker.run(RunnableBoltWorker.java:94)
>         at java.lang.Thread.run(Thread.java:745)
> ```

After rolling the branch back with the following command this error stopped presenting itself. I haven't had the chance to dig deeper into the changes that were made since. 

```
$ git reset --hard 7b08223f821e18324ffe3e5b3f00c0a6b0328a78
HEAD is now at 7b08223 Fixed apoc.nodes.delete and added test

```

**Comment by jexp** [comment]
you can only access tx-id after commit not before/after-rollback.

**Comment by jexp** [comment]
What do you mean with: 

> After rolling the branch back with the following command this error stopped presenting itself

Which branch?

**Comment by conker84** [comment]
This should be fixed, feel free to reopen it in case the error came back
