### ISSUE TITLE
When I use neo4j-3.5.12 and apoc-3.5.04(same issue happend with neo4j 4.0.6 and apoc-4.0.1. 16), this happend:

### ISSUE THREAD

**Issue by strawberrylunar** [neo4j-contrib/neo4j-apoc-procedures#1879]
### Versions

  - OS:linux
  - Neo4j:4.0.6
  - Neo4j-Apoc:4.0.0.16
  - 
 When I use 4.1.8-neo4j 和4.1.0.6-apoc, this happened, the same issue happened with 4.0.6-neo4j and 4.0.0.16-apoc, please help me😭

<img width="826" alt="截屏2021-05-05 上午2 20 21" src="https://user-images.githubusercontent.com/39673281/117050869-74936780-ad48-11eb-89dd-8c901ec14702.png">

**Comment by conker84** [comment]
@strawberrylunar can you provide the md5 of the apoc jar?

**Comment by strawberrylunar** [comment]
> @strawberrylunar can you provide the md5 of the apoc jar?

<img width="649" alt="截屏2021-05-14 下午4 38 21" src="https://user-images.githubusercontent.com/39673281/118244999-ce2b2d00-b4d2-11eb-8110-9bc0e14dbf3a.png">
Thanks for your help!

**Comment by conker84** [comment]
Your file is corrupted, a good one must have `247fe0b305f6cda604961e3881048a67`, btw please update to 4.0.0.17:

https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/4.0.0.17/apoc-4.0.0.17-all.jar

the md5 should be `a637a134db2cf4f1751c6fe09541242a`

**Comment by strawberrylunar** [comment]
Last time, I download by  "crul -O". After read your reply ,I try to download apoc file in my computer and transfer it by a PTF Client.  The md5 is right this time. Thanks a lot !!!!!

**Comment by strawberrylunar** [comment]
> Your file is corrupted, a good one must have `247fe0b305f6cda604961e3881048a67`, btw please update to 4.0.0.17:
> 
> https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/4.0.0.17/apoc-4.0.0.17-all.jar
> 
> the md5 should be `a637a134db2cf4f1751c6fe09541242a`

Last time, I download by "crul -O". After read your reply ,I try to download apoc file in my computer and transfer it by a PTF Client. The md5 is right this time. Thanks a lot !!!!!
