### ISSUE TITLE
4.1.0.7 / 4.2.0.3 has no `apoc.coll` package

### ISSUE THREAD

**Issue by dbrunnerphq** [neo4j-contrib/neo4j-apoc-procedures#1880]
## Guidelines
The [latest release (4.2.0.3)](https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/tag/4.2.0.3) seems to have no `apoc.coll` package.

## Expected Behavior
Can invoke functions within `apoc.coll` successfully

## Actual Behavior
Invoking an `apoc.coll` function, e.g. `apoc.coll.max()` throws a syntax error:
```
Unknown function 'apoc.coll.max' (line 1, column 8 (offset: 7))
"RETURN apoc.coll.max([1, 2, 3]) AS `apoc.coll.max([1,2,3])`"
        ^
```

### Steps

1. Install APOC plugin version `4.2.0.3` in a neo database.
1. Attempt to invoke a function from `apoc.coll`, e.g.: `RETURN apoc.coll.max([1, 2, 3])`

## Screenshots
![image](https://user-images.githubusercontent.com/66294047/117095384-98d36080-ada9-11eb-804d-8bc0e9ba7584.png)

### Versions
  - OS: Windows 10 (also observed on linux and mac)
  - Neo4j: 4.2.3
  - Neo4j-Apoc: 4.2.0.3

**Comment by InverseFalcon** [comment]
Thanks for raising this, we're seeing the same thing. 

We'll get the bottom of this, in the meantime please use 4.2.0.2.

**Comment by alexabidri** [comment]
@InverseFalcon What is the ETA for the fix? Our docker images using neo4j with apoc `NEO4JLABS_PLUGINS='["apoc"]'`.
Thanks for the reply 🙏

**Comment by arxeiss** [comment]
Same here, same problem. Is there some workaround to tell which version to use? So we can work with older version until the fix will be released?

**Comment by fbiville** [comment]
We'll investigate what went wrong and do another release ASAP.

**Comment by gtoonstra** [comment]
Could this have leaked into 4.1.0.7 too?  Yesterday I was working on unit tests and things were working. This morning, I started getting: 
```
 Unknown function 'apoc.coll.union' 
```
That's on neo4j 4.1.3

**Comment by fbiville** [comment]
@gtoonstra probably, both were released yesterday, we'll investigate and re-release
