### ISSUE TITLE
Loading 22 Mil + records into neo4j database via databricks environment

### ISSUE THREAD

**Issue by karunaish** [neo4j-contrib/neo4j-apoc-procedures#1902]
I am using neo4j spark connector and via databricks environment - I have loaded 22 Mil records into neo4j database and While establishing relationships for this 22mil records with the query

CALL apoc.periodic.iterate('Match (jh:JournalHeader) return jh', 'with jh MATCH (jli:JournalLineItem) where jli.glheader_id = jh.glheader_id MERGE (jh)-[:HAS_PARENT]->(jli)', {batchSize:1000, parallel:false}) yield batch return null;")\

Though the required relationships got established in neo4j database. The spark job is hanging and no updates are being written.

Is there a way to make the query more efficient so once the relationships got established it will finish the job. Because in this case though the relationships got established still the query is searching for all the other records which is not necessary in this case

**Comment by conker84** [comment]
Hi @karunaish I think you're in the wrong repository,
Please open an issue into the Spark connector repo
https://github.com/neo4j-contrib/neo4j-spark-connector 
with the code of your spark job and the structure of your source data frame.
I'm closing this
