### ISSUE TITLE
IndexSchemaRuleNotFoundException when using apoc.index.orderedRange()

### ISSUE THREAD

**Issue by bbernhard** [neo4j-contrib/neo4j-apoc-procedures#191]
Hi,

I just downloaded the latest release and copied the `apoc-3.0.4.2-all.jar` into my neo4j `plugins` folder. After a restart of neo4j, I executed the following commands: 

* create test dataset:

`CREATE (city:City {name:'London'}) WITH city UNWIND range(1,200) as id CREATE (:Person {name:'name'+id, id:id, age:id % 100})-[:LIVES_IN]->(city);`

I used the same dataset as here: https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/master/src/test/java/apoc/index/SchemaIndexTest.java

* create index:

`match (p:Person) call apoc.index.addNode(p,["name","age"]) RETURN count(*);`

* run `apoc.index.orderedRange()`:

`CALL apoc.index.orderedRange('Person','age',10,15,false,10)`

However, when executing the last command, I get the following error message: 
`Failed to invoke procedure `apoc.index.orderedRange`: Caused by: org.neo4j.kernel.api.exceptions.schema.IndexSchemaRuleNotFoundException: Index for label '14' and property '47' not found.`

What am I doing wrong? 

I am using Neo4j 3.0.4 (don't know if that matters).

Many thanks for your help!
Bernhard

**Comment by jexp** [comment]
Two different indexes
One is a manual index the other a schema index. 

Also it seems that 
> 
> orderedRange
Doesn't work as expected as the underlying index is not sorted :(

Von meinem iPhone gesendet

**Comment by bbernhard** [comment]
Hello Michael, 

first of all, thanks for your reply!

> Two different indexes One is a manual index the other a schema index.

that means I need to create a schema index, in order to make it work? Is that correct or did I misunderstand you? 

> Doesn't work as expected as the underlying index is not sorted :(
Could you please explain that a little bit more? Is that something I need to change or something that needs to be changed in neo4j-apoc?

Thanks, 
Bernhard
