### ISSUE TITLE
apoc.meta.stats return false relationship count when having multi-labeled nodes

### ISSUE THREAD

**Issue by tomasonjo** [neo4j-contrib/neo4j-apoc-procedures#1910]
If you have multi-labeled nodes in a graph, the `apoc.meta.stats` procedure return false information about relationship count.

Example dataset:

```
CREATE (:Node:Test)-[:REL]->(:Node)<-[:REL]-(:Node:Test)
```

We can then run the apoc.meta.stats procedure

```
call apoc.meta.stats YIELD relCount, relTypesCount, relTypeCount
```

The results are actually quite weird:

![results_stats](https://user-images.githubusercontent.com/19948365/119004318-bcdc9780-b98e-11eb-944d-7d8bd468fa2e.png)

I guess the global number of relCount is correct as it return a value of 2. The relTypesCount duplicates the relationship count when you are dealing with a multilabeled node. OTOH I don't really know what relTypeCount of 7 is really doing

**Comment by InverseFalcon** [comment]
Thanks for reporting, we'll look into it.

In the meantime try using the counts in `relTypes`, though be aware that several of those are going to be referring to the same relationship, as it's looking for path matches considering varied labels on start and end nodes. You should at least see a `"()-[:REL]->()": 2` entry.
