### ISSUE TITLE
APOC Installation is missing apoc.coll and some other functions

### ISSUE THREAD

**Issue by alizadehei** [neo4j-contrib/neo4j-apoc-procedures#1913]
I have:
Neo4j- 4.2.4
Apoc - 4.2.0.4

I see some APOC proc/fun installed, but many not.

### Versions

  - OS: ubuntu 20.4
  - Neo4j: 4.2.4
  - Neo4j-Apoc: 4.2.0.4

**Comment by conker84** [comment]
@alizadehei I just tried, with your same version and they are in there.
Maybe you're calling what you thing is a procedure/func but instead is a func/procedure.
Please lemme know which prcedure/func are you looking for

**Comment by conker84** [comment]
Closing this for lack of feedback, feel free to reopen in case you have more info to share

**Comment by alizadehei** [comment]
There are many functions. For example:‌ apoc.coll
