### ISSUE TITLE
can I update release from apoc-4.0.0.15-all.jar to apoc-4.0.0.18-all.jar with neo4j online, no need to restart?

### ISSUE THREAD

**Issue by yinlei168** [neo4j-contrib/neo4j-apoc-procedures#1921]
Can I update release from apoc-4.0.0.15-all.jar to apoc-4.0.0.18-all.jar with neo4j online, no need to restart? As I tested, it works and show the new apoc version if I place new version apoc jar file in the plugin folder and restart the neo4j database server. But it does not work and apoc version remains old version if I did not restart the neo4j. As it's production, we'd better avoid retarting. So can someone pls advise if there is some method to update APOC jar release with neo4j online running all along? Thanks a lot

**Comment by conker84** [comment]
@yinlei168, unfortunately, is not possible if your deployment is a single node instance you will have to plan a service maintenance period, but if you have a cluster instance you can restart one node at a time have zero downtime of your application.
I'm closing this
