### ISSUE TITLE
Failed to invoke procedure `apoc.meta.schema` : Caused by: java.lang.NullPointerException

### ISSUE THREAD

**Issue by xiajing10** [neo4j-contrib/neo4j-apoc-procedures#1934]
## Specifications (Mandatory)
Cannot run `CALL apoc.meta.schema()` in browser

Error
```
Neo.ClientError.Procedure.ProcedureCallFailed
Failed to invoke procedure `apoc.meta.schema`: Caused by: java.lang.NullPointerException
```

### Versions

  - OS: Windows 10
  - Neo4j: browser 4.2.6
  - Neo4j-Apoc: 4.2.0.4

**Comment by vga91** [comment]
@xiajing10 
I tried the same neo4j and apoc version without any problem.
Can you to upgrade the apoc version and, if the problem is still present, 
can you send a dataset to replicate the error?
