### ISSUE TITLE
TTL expiration procedure neglects current time

### ISSUE THREAD

**Issue by JP-Dhabolt** [neo4j-contrib/neo4j-apoc-procedures#196]
ttl property set on node from apoc.date.expire uses the time and time units converted to milliseconds only.  It should add this to the current timestamp to produce a usable ttl.

**Comment by jexp** [comment]
you mean something like apoc.date.expire.in(millis) ?

**Comment by JP-Dhabolt** [comment]
The procedure call itself isn't the problem, but the underlying logic.  apoc.date.expire(node, 5, 's') should set the node to expire in 5 seconds, doing the equivalent of:
set node.ttl = timestamp() + 5000
but instead is doing:
set node.ttl = 5000
