### ISSUE TITLE
integrate other APIs by direct procedures

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#197]
The ES timelion has some features like that

Like
- WorldBank API https://datahelpdesk.worldbank.org/knowledgebase/articles/898581-api-basic-call-structure
- Twitter Search
- OpenCorporates
- ...

perhaps make it possible to register APIs in the config with placeholders or via procedure call

```
http://api.worldbank.org/countries/chn;bra/indicators/DPANUSIFS?date=2009M01:2016M08&format=json

apoc.data.api.register("http://api.worldbank.org/countries/{countries}/indicators/DPANUSIFS?date={from}:{to}&format=JSON",{countries:"country;", from: "YYYYMMdd", to: "YYYYMMdd"}

```

**Comment by albertodelazzari** [comment]
`apoc.data.api.register("<key>", "<REST API>")` where "<REST API> can be a URL with parameters to be injected as your previous example.
The external API can be called using `apoc.data.api.call("<key>", params)` where params is a map.
For example, if the REST API is the previous one with countries, from and to as parameters, we expect to call the API with these 3 parameters.
When registering the API using `apoc.data.api.register` the third optional parameter could be used to define formatting policies for date types, numbers, and so on.
We should also add `apoc.data.api.remove("<key>")` if we want to remove a specific API and `apoc.data.api.list` to list all the registered APIs.

So the full list is:
- `apoc.data.api.register("<key>", "<REST API>", {params})`
- `apoc.data.api.call("<key>", {params})`
- `apoc.data.api.remove("<key>")`
- `apoc.data.api.list`

**Comment by jexp** [comment]
This is not a priority item right now.
Let's revisit the board before you look into this one.

**Comment by conker84** [comment]
Done with apoc keys and `apoc.load.jsonParams`
