### ISSUE TITLE
apoc.custom.asProcedure() with UNWIND

### ISSUE THREAD

**Issue by simo1000k** [neo4j-contrib/neo4j-apoc-procedures#1984]
How use UNWIND in a apoc.customs.asProcedure()? How call the parameter for the function?
I need to create a procedure for this

MATCH (pr:Home{home_id:'6ef77b'})
UNWIND [{domain:"domain1.com", email: "some@email.com"}, {domain:"domain3.com", email: "some03@email.com"}] AS arr
CREATE (i:Information)
SET i=arr
CREATE (i) -[:HAS] -> (pr);

this works but I don't know how to create an apoc procedure for this and how to call the parameter

**Comment by vga91** [comment]
@simo1000k 
To create a custom procedure with a parameter, assuming the parameter is `home_id`,
you can write this (note the 3rd parameter as "WRITE", to execute a `CREATE` statement):
```
CALL apoc.custom.asProcedure("myProcedure", 
'MATCH (pr:Home{home_id: $param})
UNWIND [{domain:"domain123.com", email: "some@email.com"}, {domain:"domain333.com", email: "some03@email.com"}] AS arr
CREATE (i:Information)
SET i=arr
CREATE (i) -[:HAS] -> (pr);', 
"WRITE")
```

and then type:
`CALL custom.myProcedure({param: "6ef77b"})`.

Let me know if that is what you need.

**Comment by simo1000k** [comment]
Thanks, but I need to pass parameter of UNWIND to create multiple node dynamically

**Comment by vga91** [comment]
Ok, so if I understand correctly, you can do:

```
CALL apoc.custom.asProcedure("unwindProcedure", 
'MATCH (pr:Home{home_id: "6ef77b"})
UNWIND $unwindParam AS arr
CREATE (i:Information)
SET i=arr
CREATE (i) -[:HAS] -> (pr);', 
"WRITE")
```

and then pass the parameter:
`CALL custom.unwindProcedure({unwindParam: [{domain:"test.com", email: "test@email.com"}]})`.

**Comment by simo1000k** [comment]
Which type should I write for "arr" in the function?

CALL apoc.custom.asProcedure("unwindProcedure", 
'MATCH (pr:Home{home_id: "6ef77b"})
UNWIND $unwindParam AS arr
CREATE (i:Information)
SET i=arr
CREATE (i) -[:HAS] -> (pr)
RETURN pr,i;", "write", [['pr','Node'], ['i','Node']], [['home_id','String'],['arr','??']])
)

I tried ['arr', 'LIST OF MAP'] but don't works

**Comment by vga91** [comment]
If you want to specify the type in "inputs" parameter,
you have to pass the "unwindParam", so the procedure would become:
```
CALL apoc.custom.asProcedure("unwindProcedure2", 
'MATCH (pr:Home{home_id: "6ef77b"})
UNWIND $unwindParam AS arr
CREATE (i:Information)
SET i=arr
CREATE (i) -[:HAS] -> (pr);', 
"WRITE", [['pr','Node'], ['i','Node']], [['unwindParam','LIST OF MAP']])
```
and, in this case would be called in this way (without specifying `unwindParam : [LIST]`, but only with `LIST`):
```
CALL custom.unwindProcedure2([{domain:"myTest.com", email: "myMail@email.com"}, {domain:"myTest2.com", email: "myMail2@email.com"}])
```

**Comment by simo1000k** [comment]
It works! Thank you so much!
