### ISSUE TITLE
Numeric constants for minimum and maximum value

### ISSUE THREAD

**Issue by Gudahtt** [neo4j-contrib/neo4j-apoc-procedures#199]
It would be helpful to have constants that represent the minimum and maximum possible value for each numeric type (int and float). Something analogous to `Integer.MIN_VALUE`, `Integer.MAX_VALUE`, `Float.MIN_VALUE`, `Float.MAX_VALUE` in Java.

**Comment by AngeloBusato** [comment]
Do you want to expose this constants as UDF?

**Comment by Gudahtt** [comment]
Sure, that works. As long as they're available somehow.
