### ISSUE TITLE
TTL Deletion Statement

### ISSUE THREAD

**Issue by JP-Dhabolt** [neo4j-contrib/neo4j-apoc-procedures#200]
Recurring statement that is ran when TTL is active has reversed logic.  Currently is:
MATCH (t:TTL) where t.ttl > timestamp() WITH t LIMIT 1000 DETACH DELETE t

This will delete only TTL nodes that are in the future.  To delete TTL nodes that have expired (ttl property is in the past), it should read:
MATCH (t:TTL) where t.ttl < timestamp() WITH t LIMIT 1000 DETACH DELETE t

**Comment by jexp** [comment]
Not sure where you see this?

the statement is what you expect:

https://github.com/neo4j-contrib/neo4j-apoc-procedures/blame/master/src/main/java/apoc/ApocKernelExtensionFactory.java#L66

**Comment by JP-Dhabolt** [comment]
My apologies, but I could have sworn I saw that logic in the actual codebase when I submitted the issue.  The logic is still backwards in the documentation, though.

https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/0183f4caaf2a5a48bcdfd4d057af957c3dd76200/docs/ttl.adoc
