### ISSUE TITLE
TTL Startup Statement

### ISSUE THREAD

**Issue by JP-Dhabolt** [neo4j-contrib/neo4j-apoc-procedures#201]
This is related to the previous issue I submitted, but is different enough that I thought it should be separate.  When TTL is enabled, validated through the creation of the index on :TTL(ttl), the recurring statement for cleaning up TTL nodes does not appear to be running.  I created :TTL nodes with a variety of ttl properties (past and future), and none were cleaned up.  The periodicity was set to 60 seconds.

One recommendation would be to call a single statement that in turns calls apoc.periodic.repeat() (or apoc.periodic.schedule()).  This would schedule the statement to run every X seconds, but also provide visiblity with apoc.periodic.list().

**Comment by jexp** [comment]
Good idea, my reasoning was that the TTL statement should be unaffected by other scheduled work in the system and also not that arbitrary users can cancel it.
