### ISSUE TITLE
Allow to easily call a java utility method.

### ISSUE THREAD

**Issue by vic** [neo4j-contrib/neo4j-apoc-procedures#202]
From [#163](https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/163#issuecomment-258652873)

I'd be nice to have a way to easily call a POJO method without having to create a server plugin just for it. For example, some java libs could be useful on neo4j, like generating a [geohash](https://github.com/davidmoten/geo) from lat,lon. Or calling simple one-shot standard library utils.

**Comment by vic** [comment]
So I was thinking I could try to give this a spin and try to prototype something and get your opinions on it, my initial approach would be to call only static method via reflection maybe.

**Comment by jexp** [comment]
static java methods could be called, but require white-listing in config for security reasons (imho)

**Comment by conker84** [comment]
I'm closing this as for security reasons we don't want to do that
