### ISSUE TITLE
apoc-4.3.0.0 not appearing in maven

### ISSUE THREAD

**Issue by Dcanzano** [neo4j-contrib/neo4j-apoc-procedures#2039]
## Expected Behavior (Mandatory)
APOC release should be visible in maven. and http://search.maven.org/solrsearch/select?q=g:%22org.neo4j.procedure%22+AND+a:%22apoc%22&core=gav&rows=500&wt=json

## Actual Behavior (Mandatory)
4.3.0.0 does not appear

**Comment by fbiville** [comment]
It is now fix, 4.3.0.0 is available: https://search.maven.org/artifact/org.neo4j.procedure/apoc/4.3.0.0/jar
