### ISSUE TITLE
Unknown function 'apoc.trigger.nodesByLabel'

### ISSUE THREAD

**Issue by msenechal** [neo4j-contrib/neo4j-apoc-procedures#2049]
Hi,

## Expected
Being able to use apoc.trigger.nodesByLabel inside a trigger (apoc.trigger.add)

## Current behaviour
Error : 
`Failed to invoke procedure `apoc.trigger.add`: Caused by: org.neo4j.exceptions.SyntaxException: Unknown function 'apoc.trigger.nodesByLabel' (line 1, column 16 (offset: 15))
"EXPLAIN UNWIND apoc.trigger.nodesByLabel($assignedLabels,"Device") AS n OPTIONAL MATCH (d1:Device)-[r1:IS_DISJOINT_EXEMPT_FOR]-(d2:Device) DELETE r1"
                ^`

## Screenshots (where it's possibile)
![image](https://user-images.githubusercontent.com/56915224/123988498-fe198b80-d9bf-11eb-8e67-823de6f33528.png)
![image](https://user-images.githubusercontent.com/56915224/123988542-04a80300-d9c0-11eb-9820-9ed3703e7a8a.png)

### Versions

  - OS: Tested on both Neo4j Desktop and on a linux server
  - Discovered on: Neo4j: 4.2.3 with APOC 4.2.01
  - Tried to upgrade to Neo4j 4.2.8 with APOC 4.2.0.4, still same issue

Update: saw apoc 4.2.0.5 has been released 2days ago, upgraded the apoc version on my Neo4j desktop (still Neo4j 4.2.8), same query is working on that one

**Comment by zzzjl2021** [comment]
hi I met the same situation today and mine is apoc-4.4.0.8-core.jar, I don’ t know what happened here. Anyone knows the reason?

**Comment by zzzjl2021** [comment]
> hi I met the same situation today and mine is apoc-4.4.0.8-core.jar, I don’ t know what happened here. Anyone knows the reason?

I solved my problem by doing the same operation. Change the version to apoc-4.4.0.3-all.jar

**Comment by vga91** [comment]
@msenechal 
The issue seems to depend on installing the core package, instead of the full one. 
Feel free to reopen in case you the issue is still present.
