### ISSUE TITLE
apoc.periodic.iterate() seems to fail if using IS NULL, IS NOT NULL, or label checking in the WHERE clause

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j-contrib/neo4j-apoc-procedures#205]
Attempting to run apoc.periodic.iterate() works just fine when there are comparison operators present in the WHERE like so:

```
CALL apoc.periodic.iterate(
"MATCH (u:User) WHERE u.processed = false RETURN u",
"SET u.processed = true", {batchSize:10000, parallel:true})
```

No errors. The <> operator is also respected.

However, valid predicates using IS NULL or IS NOT NULL or label checks fail.

For example:

```
CALL apoc.periodic.iterate(
"MATCH (u:User) WHERE u.processed IS NULL RETURN u",
"SET u.processed = true", {batchSize:10000, parallel:true})
```

and

```
CALL apoc.periodic.iterate(
"MATCH (u:User) WHERE NOT u:Processed RETURN u",
"SET u:Processed", {batchSize:10000, parallel:true})
```

both fail with the following error:

`Failed to invoke procedure `apoc.periodic.iterate`: Caused by: java.util.IllegalFormatConversionException: d != java.lang.String`

I'm using Neo4j Community 3.0.6 and APOC Procedures 3.0.4.2 on Mac OS X.

**Comment by jexp** [comment]
Can you build the latest version locally and run it; the error message should contain more information.

**Comment by jexp** [comment]
Sorry you missed a bit (that was probably an issue in the docs):
The columns of the driving statement are passed in as parameters.

CALL apoc.periodic.iterate(
"MATCH (u:User) WHERE u.processed IS NULL RETURN u",
"WITH {u} as u SET u.processed = true", {batchSize:10000, parallel:true})
and

CALL apoc.periodic.iterate(
"MATCH (u:User) WHERE NOT u:Processed RETURN u",
"WITH {u} as u SET u:Processed", {batchSize:10000, parallel:true})
