### ISSUE TITLE
The absence of some functions in the Apoc 4.3.0.0

### ISSUE THREAD

**Issue by alizadehei** [neo4j-contrib/neo4j-apoc-procedures#2065]
I added Apoc 4.3.0.0 to the project using the following maven dependency:

```
<!-- https://mvnrepository.com/artifact/org.neo4j.procedure/apoc -->
<dependency>
    <groupId>org.neo4j.procedure</groupId>
    <artifactId>apoc</artifactId>
    <version>4.3.0.0</version>
</dependency>
```

but, some functions did not exist in the apoc 4.3.0.0. Among these functions, we can mention cases such as Coll, Maps, Meta, Date, GraphRefactoring, Warmup , ...

### Versions

  - OS: Linux 20.04
  - Neo4j: 4.3.1
  - Neo4j-Apoc: 4.3.0.0

**Comment by vga91** [comment]
@alizadehei 
The issue should no longer be present with new version (currently 4.3.0.8). If not, feel free to reopen the issue
