### ISSUE TITLE
support ${http_proxy} for apoc / neo4j?

### ISSUE THREAD

**Issue by mkoertgen** [neo4j-contrib/neo4j-apoc-procedures#207]
When running neo4j with apoc behind a corporate http proxy (e.q. squid), the very first apoc example fails

- [Calling Procedures within Cypher](https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_calling_procedures_within_cypher)

It seems this is because the neo4j start script does not honor/extend `${JAVA_OPTS}` but overwrites it, cf.:

- [distribution/shell-scripts/bin/neo4j#L88](https://github.com/neo4j/neo4j/blob/a56e6436d3a2d47430cf2d47c1c3e86472d0946f/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j#L88)

**Comment by mkoertgen** [comment]
Also, it seems that with 3.1 you are moving away from `wrapper.conf` (much appreciated).

Any ideas on how get apoc running behind a proxy?

**Comment by jexp** [comment]
You can set the JVM proxy system prooperty as part of the `dbms_jvm_additional` options.

neo4j-wrapper.conf is merged with neo4j.conf

**Comment by mkoertgen** [comment]
Ah, my bad. Thanks for pointing that out

**Comment by mkoertgen** [comment]
Works like a charm. Thanks @jexp
