### ISSUE TITLE
apoc.meta.graph (3.1.0.2) shows extra relationships

### ISSUE THREAD

**Issue by vardan-a** [neo4j-contrib/neo4j-apoc-procedures#209]
apoc.meta.graph (APOC 3.1.0.2) on Community Edition Version: 3.1.0-M13-beta3 running locally on Windows notebook, shows result with extra relationships
For example:
CREATE (a:S1 {SomeName1:'aaa'})
CREATE (b:S2 {SomeName2:'bbb'})
CREATE (c:S3 {SomeName3:'ccc'})
CREATE (a)-[:HAS]->(b)
CREATE (b)-[:HAS]->(c)

MATCH (n) RETURN n
// returns as expected aaa->bbb->ccc
call apoc.meta.graph
shows HAS relationship between S1 and S3, and from S2 to itself, that I never created and it does not exists if I run MATCH (a:S1)-[:HAS]->(c:S3) RETURN a,c

![neo4jmetadata](https://cloud.githubusercontent.com/assets/23392119/20202048/42c8035a-a771-11e6-8a49-1be08520b595.JPG)

**Comment by InverseFalcon** [comment]
I noticed something similar in APOC version 3.0.4.2 (paired with neo4j 3.0.6), at least with the presence of non-existent relations between some meta nodes to themselves.
