### ISSUE TITLE
requesting apoc-#.#.#.#-core.jar be available from maven

### ISSUE THREAD

**Issue by Dcanzano** [neo4j-contrib/neo4j-apoc-procedures#2147]
## Feature description (Mandatory)
requesting apoc-<version>-core.jar, i.e. the same which is delivered to labs/ be available via a maven repository.  Today the only thing available it apoc-<version>-all.jar

## How this feature can improve the project?
Would like to download apoc-<version>-core.jar via maven as it is same as what is in labs\

**Comment by klauspgross** [comment]
We are using only the capabilities exposed in the core in our product and don't want to include the entire tar ball of apoc in our deployment.  To do this, our CI/CD pipeline requires a maven repository and we don't want to maintain our own for apoc-core
