### ISSUE TITLE
apoc.load.ldap add support spaces in a DN when loading credential information from conf

### ISSUE THREAD

**Issue by mrbungle733t** [neo4j-contrib/neo4j-apoc-procedures#2159]
## Expected Behavior (Mandatory)
possible to add loginDN that contains spaces 
`CN=testuser,OU=System users,OU=Users,dc=example,dc=com`

## Actual Behavior (Mandatory)
Currently apoc.load.ldap cant read credential information from conf file when it contains spaces in loginDN

```
Neo.ClientError.Procedure.ProcedureCallFailed
Failed to invoke procedure `apoc.load.ldap`: Caused by: LDAPException: Invalid Credentials (49) Invalid Credentials
LDAPException: Server Message: 80090308: LdapErr: DSID-0C090446, comment: AcceptSecurityContext error, data 52e, v4563
LDAPException: Matched DN: 
```

## How to Reproduce the Problem
use testuser that contains space in DN name
`apoc.loadldap.myldap.config=<host>:<port> CN=testuser,OU=System users,OU=Users,dc=example,dc=com
 password`

```
call apoc.load.ldap("myldap"
,{searchBase : ",OU=System users,OU=Users,dc=example,dc=com"
 ,searchScope : "SCOPE_ONE"
 ,attributes : ["cn","objectGUID","objectClass"]
 ,searchFilter: "(sAMAccountName=testuser)"
 }) yield entry
return entry.dn,  entry.cn, entry.objectGUID, entry.objectClass
```

### Steps (Mandatory)

  1. define myldap in conf file
  1. run query from neo4j browser

## Specifications (Mandatory)
" " is used to split values in config file. Using %20 instead of space " " is currently also not working. 

`String[] sConf = value.split(" ");
            config.put("ldapHost", sConf[0]);
            config.put("loginDN", sConf[1]);
            config.put("loginPW", sConf[2]);`

Currently used versions

### Versions

  - Neo4j: 3.5.25
  - Neo4j-Apoc: 3.5.0.15

**Comment by vga91** [comment]
@mrbungle733t 
As an alternative to `apoc.loadldap.myldap.config` you can use the apoc static functionality
https://neo4j-contrib.github.io/neo4j-apoc-procedures/index33.html#_static_value_storage.

So, for example, you can put in `neo4j.conf`:
```
apoc.static.ldap.host=HOST: PORT
apoc.static.ldap.loginDn=CN=testuser,OU=System users,OU=Users,dc=example,dc=com
apoc.static.ldap.password =myPassword
```

and your query should work, with first parameter as map:
```
CALL apoc.load.ldap ({ldapHost: apoc.static.get('ldap.host'), loginDN: apoc.static.get('ldap.loginDn'), loginPW: apoc.static.get ('ldap.password')}
, {searchBase .....}) yield entry 
return entry.dn,  entry.cn, entry.objectGUID, entry.objectClass
```

**Comment by mrbungle733t** [comment]
@vga91 thank you, this is a useful suggestion and this is exactly what i did for a workaround:)

**Comment by vga91** [comment]
Closing this as the solution has been provided
