### ISSUE TITLE
apoc.convert.toTree reorders paths

### ISSUE THREAD

**Issue by avi-law** [neo4j-contrib/neo4j-apoc-procedures#2190]
If one

- Step 1: receives paths from a query,
- Step 2: orders them by certain criteria, 
- Step 3: collects them to a list of paths, and then
- Step 4: runs apoc.convert.toTree

the user desired order (see Step 2) is not obeyed. Instead apoc.convet.toTree first re-orders the paths by its length DESC and then creates the tree which overwrites / "kills" the user desired order.

**Comment by avi-law** [comment]
I'm sorry, we have built this on our ones months ago, and we're not going to change the code again. Bugfixes after months are quite useless.

**Comment by IdiotCoderCodie** [comment]
> I'm sorry, we have built this on our ones months ago, and we're not going to change the code again. Bugfixes after months are quite useless.

Hi @avi-law, do you mean you have managed to fix this yourself? 

I don't think a bugfix would be useless just because it has been around for months; I would just like some clarity on whether it is actually a bug or the new expected behavior.

**Comment by avi-law** [comment]
Sorry, I meant that **for us** it is useless. We run a website based on Neo4J and since the database did not respond correctly, we had to implement a fix and sort the results by our owns (otherwise the data on our website would have been a mess). We cannot change the code again just for checking whether your bugfix is effective. Sorry.

**Comment by IdiotCoderCodie** [comment]
> Sorry, I meant that **for us** it is useless. We run a website based on Neo4J and since the database did not respond correctly, we had to implement a fix and sort the results by our owns (otherwise the data on our website would have been a mess). We cannot change the code again just for checking whether your bugfix is effective. Sorry.

Ah thanks for that clarification :)
I'm not a maintainer of this project so I don't have a bugfix myself, but hoping a maintainer replies with some insight :)
