### ISSUE TITLE
Problem with storing data into systemdb in a Cluster env

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-apoc-procedures#2194]
Related to (#2193) in a cluster env the `systemdb` can have a `LEADER` in a different instance where the actual `call apoc.trigger.add` happened.

We have a couple of options here but I need to discuss them with @fbiville @JMHReif & @jexp

**Comment by AdrienLemaire** [comment]
@conker84 hi, I've just stumbled against this issue. 
After setting a trigger in my local environment, I failed to deploy this feature to the neo4j cluster environment, and realized that only the system leader allows for `apoc.trigger.add` when my db leader is on another node.

I'm surprised that this isn't documented anywhere, a red warning "not supported on clusters" would have been very welcome when I got started on a trigger-related feature a week ago. 

What are the couple of options available ? Is there anything I can do to get triggers to work in my cluster and not throw away all the work involving neo4j triggers I'm trying to release ?

Running neo4j 4.1 on the GCP marketpace [neo4j enterprise causal cluster](https://github.com/neo-technology/neo4j-google-k8s-marketplace/tree/4.1). Thank you for your support
