### ISSUE TITLE
Providing s3 authentication through environment variables fails when using 'apoc.load.csv'

### ISSUE THREAD

**Issue by mskyttner** [neo4j-contrib/neo4j-apoc-procedures#2198]
Looking at https://neo4j.com/labs/apoc/4.1/import/web-apis/#_using_s3_protocol, I tried using environment variables for setting "accessKey" and "secretKey" values. I verified that such environment variables are set when neo4j starts, `env | grep Key` gives:

accessKey=mysecretaccesskey
secretKey=mysecretkey

I couldn't find any example where those credentials are provided through environment variables. Docs say that this format for the S3 connectionstring should be valid: "s3://endpoint:port/bucket/key if the accessKey, secretKey, and the optional sessionToken are provided in the environment variables". Should those environment variables be named differently to be picked up?

## Actual Behavior (Mandatory)

Running `CALL apoc.load.csv('s3://myminio.object.storage/bibliometrics/authors.csv',{sep:","}) YIELD lineNo, list, strings, map, stringMap` fails with:

```
Neo.ClientError.Procedure.ProcedureCallFailed
Failed to invoke procedure `apoc.load.csv`: Caused by: java.lang.NullPointerException
```

## How to Reproduce the Problem

Use a valid s3 connection string, make sure it works with accessKey and secretKey parts of the URL, then remove those parts of the connection string and expect values set in environment variables "accessKey" and "secretKey" to be automatically used.

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: Linux 
  - Neo4j: 4.0.7
  - Neo4j-Apoc: version provided when installing apoc using NEO4JLABS_PLUGINS '["apoc"'] in Dockerfile

**Comment by vga91** [comment]
@mskyttner 
Yes, the env variables have to be named differently, the documentation isn't so clear.
This env are handled internally by Aws sdk (see: https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/SDKGlobalConfiguration.html)

So, you should insert `AWS_SECRET_KEY` and `AWS_ACCESS_KEY_ID` as env vars. In this way, it should works.
We'll update the documentation asap.

**Comment by mskyttner** [comment]
Thanks!

**Comment by mskyttner** [comment]
Hmm... I couldn't find those envvars listed in the link provided above... I see ACCESS_KEY_ENV_VAR and SECRET_KEY_ENV_VAR fields in those docs, but aren't those Java class fields? What envvars do those come from?

But https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html mentions AWS_SECRET_ACCESS_KEY (differs from above) and AWS_ACCESS_KEY_ID (same as above), used by the AWS CLI tool... Does the SDK require other env vars?

I tried those variations, but still no luck... same error message as before.... I am not sure what I'm doing wrong...

**Comment by vga91** [comment]
Yes, `ACCESS_KEY_ENV_VAR` and `SECRET_KEY_ENV_VAR` are Java field with string values `AWS_ACCESS_KEY_ID` and `AWS_SECRET_KEY` (maybe this page is clearer https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/constant-values.html#com.amazonaws.SDKGlobalConfiguration.ACCESS_KEY_ENV_VAR).

However, can you try using this jar into `plugin` folder instead of using `NEO4JLABS_PLUGINS` (so deleting the apoc .jar from `plugin` folder)?
[apoc-4.0.0.19-all.jar.zip](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/7184769/apoc-4.0.0.19-all.jar.zip)

This contains the latest updates not yet released.

**Comment by conker84** [comment]
@mskyttner ping

**Comment by mskyttner** [comment]
Hi @conker84, simply mounting the jar into the containers internal plugins folder (I'm using https://github.com/KTH-Library/neo4kth) and also setting container environment variables (I'm using an envfile)

AWS_ACCESS_KEY_ID=myminios3login
AWS_SECRET_ACCESS_KEY=myminioS3password

(note names of those environment variables, )

seems to provide expected results....

I tried accessing two forms of URLS, the last two variants listed in the docs at https://neo4j.com/labs/apoc/4.1/import/web-apis/#_using_s3_protocol

- s3://endpoint:port/bucket/key?accessKey=accessKey&secretKey=secretKey[&sessionToken=sessionToken] (sessionToken is optional) or

- s3://endpoint:port/bucket/key if the accessKey, secretKey, and the optional sessionToken are provided in the environment variables

For the last variant, the run-time statement I used looked like:

`CALL apoc.load.csv('s3://myminio.S3.server/bibliometrics/authors.csv',{sep:","}) YIELD lineNo, list, strings, map, stringMap`
