### ISSUE TITLE
Add an "apoc.cypher.runManyReadOnly" procedure that has mode of READ

### ISSUE THREAD

**Issue by ShipatNeo** [neo4j-contrib/neo4j-apoc-procedures#2221]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Feature description (Mandatory)
In neo4j 4.x - if you attempt to call a procedure that has mode of WRITE in a session that is designated as READ session/transaction - the statement will fail regardless if the transaction actually does any writes or not.  Specifically, there are some scenarios where apoc.cypher.runMany() could be used with just reads and this is now failing when trying to have them route to Followers/Read replicas

This is a request to clone the existing apoc.cypher.runMany() procedure but change the mode to READ (or DEFAULT).

**Comment by conker84** [comment]
@ShipatNeo we implemented the procedure, do you need a release?
