### ISSUE TITLE
add a neighbours procedure / function 

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#223]
that expands around a node / set of nodes in parallel using the given rel-type-pattern into a set
and returns that set of nodes.

So that we can then use set functions on those neighbor-sets to find intersections or nodes that are not in both of those sets.

**Comment by jexp** [comment]
@InverseFalcon we have that now, or?
Would be probably also nice as a function.

But not sure if it adds a lot over `[(node)-->(m) | m]` ??

**Comment by InverseFalcon** [comment]
As you say it seems like pattern comprehension covers this. Is there anything in this that adds something else, aside from the parallel execution?

**Comment by jexp** [comment]
@InverseFalcon 
Parallel execution and probably more convenient procedure/function call name?

Or perhaps just some docs.

**Comment by conker84** [comment]
This should be done via `apoc.path.expand`
