### ISSUE TITLE
apoc.date.fields should return properties with singular names

### ISSUE THREAD

**Issue by astrosam** [neo4j-contrib/neo4j-apoc-procedures#224]
In 3.1.0.2, the `apoc.date.fields` function returns a map whose properties all have plural names:

- years
- months
- weekdays
- days
- hours
- minutes
- seconds

An example "years" value would be `2016`. An example "months" value would be `03`.

This naming convention is VERY awkard. Can we change the names to their singular forms?

**Comment by jexp** [comment]
Probably not in a dot release, but we could duplicate the fields with
singular and remove the plural ones in a next major release.

**Comment by conker84** [comment]
I'm closing this since is outdated
