### ISSUE TITLE
Core release of 4.3.0.3 doesn't contain apoc.coll.sortMulti

### ISSUE THREAD

**Issue by benholmes-ft** [neo4j-contrib/neo4j-apoc-procedures#2246]
## Expected Behavior
`apoc.coll.sortMulti` to be included in the core release (according to this [APOC documentation](https://neo4j.com/labs/apoc/4.1/overview/apoc.coll/apoc.coll.sortMulti/))

## Actual Behavior
Error returned when calling function `Unknown function 'apoc.coll.sortMulti'`

## How to Reproduce the Problem 

- Install the core library
- Notice the sortMulti function doesn't appear in autocomplete

### Steps

  1. Install the 4.3.0.3 core library
  2. Notice the sortMulti function doesn't appear in autocomplete 

## Screenshots
![image](https://user-images.githubusercontent.com/87309844/137297031-6e9e3acd-7c15-4e7c-b192-9d63ae72e753.png)

### Versions

  - OS: GrapheneDB
  - Neo4j: 4.3.5
  - Neo4j-Apoc: 4.3.0.3

**Comment by vga91** [comment]
@benholmes-ft  I close the issue because it doesn't seem to be a bug. 
If you still have any problems, please feel free to open the issue
