### ISSUE TITLE
apoc.load procedures don't work anymore with urls containing %

### ISSUE THREAD

**Issue by pjeannet** [neo4j-contrib/neo4j-apoc-procedures#2269]
## Expected Behavior (Mandatory)

We are using `apoc.load.csv` and `apoc.load.xls` to load files from GCP buckets using short lived signed URLs. This was working fine until we updated to apoc v4.3.0.3 yesterday on our dev env.  

## Actual Behavior (Mandatory)

We now get 403 errors from the procedure call. After investigation we noticed that the url loged after failure was not exactly the url we sent. All `%` are being replaced by `%25` which breaks the signature. This looks like an encoding failure or a double encoding happening. 
We had to go back to 4.3.0.0 apoc verion not to encounter the same issue. We also tried with latest 4.2.x versions with same results.

## How to Reproduce the Problem

Sign an url for any csv file using https://cloud.google.com/storage/docs/access-control/signed-urls (or any other file URL containing `%`). Then use this url in an `apoc.load.csv` call.

### Versions

  - OS: Debian 10
  - Neo4j: 4.3.6
  - Neo4j-Apoc: 4.3.0.3

**Comment by jexp** [comment]
@conker84 is there any progress on this we have some more users and customers running into this issue

**Comment by pjeannet** [comment]
Hey, I'm sorry to ask again but do you know when this will be solved? Our Apoc version is starting to lag behind a lot and we want to upgrade it to solve other issues we've had since then. Thanks :)

**Comment by vga91** [comment]
@pjeannet 

I attached a custom apoc `.jar` which should fix the problem.

I tested it with AWS S3, but it should work with GCP as well.
Please, can you try your query with this one?

[apoc-4.3.0.5-all.jar.zip](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/8153934/apoc-4.3.0.5-all.jar.zip)

**Comment by pjeannet** [comment]
@vga91 I just tried the package on a dev env and it worked for me
