### ISSUE TITLE
Utilize KernelTransaction.setStatusDetails() in 4.4

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#2283]
For procedures that have long running operations, like periodic iterate or import procedures, use the new functionality to report progress

* periodic.iterate - how many batches success / how many errors / how many 
* load csv/xml/json
* from document/import-json/import-csv  -> how much data processed (rows, elements) / how much data created in the graph

**Comment by jexp** [comment]
https://github.com/neo-technology/neo4j/blob/dev/public/community/kernel-api/src/main/java/org/neo4j/kernel/api/KernelTransaction.java#L275

**Comment by conker84** [comment]
This one is public:
https://github.com/neo4j/neo4j/blob/4.4/community/kernel-api/src/main/java/org/neo4j/kernel/api/KernelTransaction.java#L275

**Comment by jexp** [comment]
This becomes visible in `SHOW TRANSACTIONS YIELD *` then there is a field for status details.
