### ISSUE TITLE
apoc.refactor.rename.nodeProperty is stuck in an endless loop!

### ISSUE THREAD

**Issue by AleSim94** [neo4j-contrib/neo4j-apoc-procedures#2284]
## Explaining the function in use 
Running apoc.refactor.rename.nodeProperty(oldName, newName, [nodes], config) should rename all node’s property from 'oldName' to 'newName'. If 'nodes' is provided renaming is applied to this set only. As the collection of data is processed in batch via apoc.periodic.iterate these procedures support almost most of the config param as in periodic.iterate.

## Expected Behavior
 I assume this method should take a couple of seconds and not minutes to execute( or never since I did not have the time to wait for it to finish)

## Actual Behavior
When I ran it on a dataset of roughly 63 k nodes to rename a property it just said that the query was executed with no sign of finishing up any time soon( waited a couple of minutes!!!). In the end, to make it work I did it the old way using periodic iterate + SET to rename the node property( see the cypher statements below) and the execution time was approx 1 -2 sec.

## How to Reproduce the Problem
Just have a dataset of 63 k nodes where you want to rename a property on all of the nodes and see if it finishes the execution of the query.

I ran 2 different queries where neither of them worked:

MATCH (n:Label)
WITH collect(n) AS nodes
CALL apoc.refactor.rename.nodeProperty("oldName", "newName",nodes, {batchSize:1000})
YIELD committedOperations
RETURN committedOperations

or 

MATCH (n:Label)
WITH collect(n) AS nodes
CALL apoc.refactor.rename.nodeProperty("oldName", "newName",nodes)
YIELD committedOperations
RETURN committedOperations

So I ended up using a different approach which finished within a couple of seconds

CALL apoc.periodic.iterate(
   'MATCH (n:Label) RETURN n',
   'SET n.newName = n.oldName
    REMOVE n. n.oldName',
   {batchSize:10000, iterateList:true, parallel:true}
)

### Versions

  - OS: Windows 10 enterprise for virtual desktops
  - Neo4j: server version 4.2.9 (enterprise), browser version 4.3.1
  - Neo4j-Apoc: apoc-4.2.0.2-all.jar

**Comment by vga91** [comment]
@AleSim94 
This is definitely weird. 
I tried both `4.2.0.2` and latest `4.2.x` apoc version, and in both cases I created a 63k dataset:
```
unwind range(0, 63000) as id create (n:Label {oldName: id})
```
and executed the query:
```
MATCH (n:Label)
WITH collect(n) AS nodes
CALL apoc.refactor.rename.nodeProperty("oldName", "newName",nodes, {batchSize:1000})
YIELD committedOperations
RETURN committedOperations
```

The query update the props and returns the result after less than 2 secs. 
I tried also with rels connected, and it works.
Please, can you provide a sample dataset to try to replicate your problem?

**Comment by AleSim94** [comment]
@vga91 I tried to do the same calls on a slightly bigger set of nodes (73 k) and I can see it works now! Do not know why it did not work for me previously but it seems to work now. I think we can close this issue, thanks so much @vga91!!!
