### ISSUE TITLE
Geocode.java in Spatial violates the Nominatim AUP of Openstreetmap

### ISSUE THREAD

**Issue by locrawl** [neo4j-contrib/neo4j-apoc-procedures#23]
[Line 24](https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/master/src/main/java/apoc/spatial/Geocode.java#L24): 

`String url = "http://nominatim.openstreetmap.org/search.php?q=" + address.replace(" ", "+") + "&format=json";` 

violates the [acceptable use policy](https://wiki.openstreetmap.org/wiki/Nominatim_usage_policy) on Openstreetmap

> - No heavy uses (an absolute maximum of 1 request per second).
- Provide a valid HTTP Referer or User-Agent identifying the application (stock User-Agents as set by http libraries will not do).

There's no time delay, user agent, or usage enforcement mechanism in place and may result in IP bans. Unless these control features are added, it would be a good idea to implement passing in an API and url string so custom services can be used (mapbox, opencage, etc) instead.

**Comment by jexp** [comment]
@locrawl we added heavy throttling and the ability to provide API keys, hope that's ok.

**Comment by locrawl** [comment]
@jexp Awesome, that was quick. Thanks!
