### ISSUE TITLE
apoc.load.json fails to run if unnecessary / additional unwinds are performed

### ISSUE THREAD

**Issue by jphare** [neo4j-contrib/neo4j-apoc-procedures#231]
If you put in an unnecessary unwind in that returns no data this causes the entire following cypher statement to return no action despite the cypher being valid and not referencing the unnecessary unwind.

This isn't an issue where the json schema is static, it would be an issue where the structure changes and the json doesn't always exactly match the schema - e.g. objects are selectively omitted rather than nulled etc.

I guess a way around this might be to put WITH statements between every unwind but that would double size of unwind code.

This is using Neo4j 3.0.7 & APOC 3.0.4.1

**Comment by jexp** [comment]
Do you have a concrete example? It's totally unrelated to load.json, 
it's that unwinding of null values or empty collections result in *no* rows

You can always use coalesce(value.items, []) or 
UNWIND coalesce(value.items, [null]) as item

to get a "null" item instead.

**Comment by conker84** [comment]
Closed for lacking of feedback
