### ISSUE TITLE
Add method to obtain periodic job code

### ISSUE THREAD

**Issue by orthogonal3** [neo4j-contrib/neo4j-apoc-procedures#2323]
## Background

Periodic jobs can be scheduled with [`apoc.periodic.repeat()`](https://neo4j.com/labs/apoc/4.0/overview/apoc.periodic/apoc.periodic.repeat/).

Once the job is scheduled, it can be found with [`apoc.periodic.list()`](https://neo4j.com/labs/apoc/4.0/overview/apoc.periodic/apoc.periodic.list/)

```
CALL apoc.periodic.list()
╒════════════╤═══════╤══════╤══════╤═══════════╕
│"name"      │"delay"│"rate"│"done"│"cancelled"│
╞════════════╪═══════╪══════╪══════╪═══════════╡
│"test-jobid"│0      │60    │false │false      │
└────────────┴───────┴──────┴──────┴───────────┘
```

But other than the the `name` field of the job, there's no way to view what the job does to confirm it is a specific job that needs cancelling.

## Suggested Feature

One option would be to add an `apoc.periodic.describe()` function that returns the details of the scheduled job, including the Cypher statement:

```
apoc.periodic.describe(name :: STRING?) :: (name :: STRING?, statement :: STRING?, rate :: INTEGER?, config = {} :: MAP?)
```

Or, add an option to `apoc.periodic.list` procedure, like `apoc.periodic.list(verbose :: BOOLEAN?)` to provide further detail?

**Comment by jexp** [comment]
Yep, we can add a verbose config option, or use the new means to discover output parameters to yield the extra `statement` column when it's yielded
