### ISSUE TITLE
Symmetric export-import for JSON documents

### ISSUE THREAD

**Issue by jimwebber** [neo4j-contrib/neo4j-apoc-procedures#2325]
## Feature description

Calling `apoc.export.json.all` results in a JSON file with numeric IDs embedded. This is fine except when you then import with `apoc.import.json` and those IDs appear as properties in your nodes.

I would like an option for these IDs not to appear as node properties on import. A more general solution would be to allow importing to ignore specified property keys.

## Considered alternatives
There are workarounds for this, but they are not always applicable or pleasant.

* Use unique constraints from the application domain instead of IDs, but not all applications have these.
* Clean up afterwards, which is time-consuming for larger databases.

**Comment by jexp** [comment]
We should 

* document the behavior
* add the clean up  as an option to apoc.import.json
* to remove the both unique labels and unique ids for nodes without constraints that were added in the import
