### ISSUE TITLE
text.replace not available anymore?

### ISSUE THREAD

**Issue by adamrabie** [neo4j-contrib/neo4j-apoc-procedures#236]
Just upgraded neo4j to 3.1 and installed latest apoc and noticed there is no longer a procedure for apoc.text.replace.

![image](https://cloud.githubusercontent.com/assets/16122441/21391294/219253cc-c759-11e6-836d-07384448904b.png)

> There is no procedure with the name `apoc.text.replace` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.

**Comment by jexp** [comment]
It is now a function which you can call inline.

see dbms.functions()

**Comment by adamrabie** [comment]
amazing thanks!
