### ISSUE TITLE
Mismatch in apoc.periodic.repeat() information

### ISSUE THREAD

**Issue by JP-Dhabolt** [neo4j-contrib/neo4j-apoc-procedures#237]
When calling dbms.procedures(), the resulting information for the apoc.periodic.repeat() call instead shows apoc.periodic.schedule() in the Description for an example call.  When looking at the code, I only see apoc.periodic.schedule(), and no periodic.repeat().  This is from the apoc-3.1.0.3-all.jar

![image](https://cloud.githubusercontent.com/assets/23241077/21429912/ee670d36-c82e-11e6-916b-067951570c57.png)

**Comment by tuddman** [comment]
also, apoc.periodic.repeat()   is dropping all but the latest scheduled job.   

running `3.0.6` 

<img width="909" alt="screen shot 2017-01-05 at 10 57 31 am" src="https://cloud.githubusercontent.com/assets/33383/21691257/d1481764-d345-11e6-825e-6fc9d128cc78.png">

**Comment by jexp** [comment]
@tuddman could you elaborate on that, from your screenshots I don't think I understand what you mean.

**Comment by jexp** [comment]
There is always only one job of the same name at a time.
And jobs that are done or cancelled are removed regularly from the list.

**Comment by jexp** [comment]
@tuddman also next time please create a new issue

**Comment by tuddman** [comment]
@jexp  I'd like to have two (or more) queries that run periodically on my graph.    in this contrived example, `job-1` and `job-2`      

in a sense these jobs should never _finish_ but act as a continuous monitor for new (unprocessed) nodes as they are added.

**Comment by jexp** [comment]
But scheduled jobs don't return any data? They are rather update-operations or other side-effects.

They should still both run. In your example I didn't see you adding `job-1`

**Comment by tuddman** [comment]
updated. using `3.1.0` with `apoc-3.1.0.3.jar`

how can I have `job-1` _continue_ to run?   i.e. have it **repeat** every n-seconds?

![screenshot from 2017-01-05 20-20-13](https://cloud.githubusercontent.com/assets/33383/21704054/6a84e6bc-d384-11e6-8ceb-c874fb75d487.png)


https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/3.0/src/main/java/apoc/periodic/Periodic.java#L153

**Comment by tuddman** [comment]
can close this issue?

original issue may have been cross installing _originally_ neo 3.1.0  with apoc 3.0.8.4.    With a new install of both 3.1.0 (cleanly installing apoc-3.1.0.3) and 3.0.7 (cleanly installing apoc-3.0.8.4)  both appear to be working now.

**Comment by conker84** [comment]
Closed as requested
