### ISSUE TITLE
apoc.any.isDeleted(node/rel)

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#2372]
For situations where a node or relationship is already deleted it would be good to be able to check that before acessing it and causing an error.

There used to be a method on Node/Relationship for that if not anymore there is a KernelAPI method.

**Comment by danielemansillo** [comment]
@jexp is it fine like this?
![Schermata 2021-12-07 alle 17 34 05](https://user-images.githubusercontent.com/84501597/145069262-4208366a-1728-4cd3-a680-d609ac579570.png)

**Comment by jexp** [comment]
Yep, that looks good
