### ISSUE TITLE
apoc-3.1.0.3-all.jar missing apoc.date functionality

### ISSUE THREAD

**Issue by JP-Dhabolt** [neo4j-contrib/neo4j-apoc-procedures#238]
Calls to various apoc.date stored procedures (apoc.date.formatDefault for example) fail with "Neo.ClientError.Procedure.ProcedureNotFound".  Running dbms.procedures() shows only the following apoc.date procedures.  These procedures are still in the source code and documentation.

![image](https://cloud.githubusercontent.com/assets/23241077/21435329/42656398-c847-11e6-85c2-c87ec8fcd6fb.png)

**Comment by jakeboone02** [comment]
I think the procedures you're looking for were converted to functions, per #144.

**Comment by conker84** [comment]
Fixed in newer versions
