### ISSUE TITLE
Word embeddings support

### ISSUE THREAD

**Issue by tomasonjo** [neo4j-contrib/neo4j-apoc-procedures#2380]
Adding word embedding support in the APOC NLP package would make sense as it can be used in combination with the node embedding or kNN graphs in GDS library.

I have no idea how much would word embedding models bloat the library, but using some pretrained models like https://deeplearning4j.konduit.ai/deeplearning4j/reference/word2vec-glove-doc2vec would be very useful.

**Comment by tomasonjo** [comment]
Even better if the gcp/aws/azure would have an API endpoint as it wouldnt bloat the library. I'll do some research

**Comment by jexp** [comment]
Perhaps add as an extra jar, that people can add if they want.

**Comment by jexp** [comment]
Probably superceded by the LLM embeddings?
