### ISSUE TITLE
Provide procedure to remove relationship from manual index

### ISSUE THREAD

**Issue by cmorgner** [neo4j-contrib/neo4j-apoc-procedures#239]
Right now there's only an `add` procedure, how can I remove relationships from a manual index when it's deleted?

**Comment by sarmbruster** [comment]
When deleting a relationship it's automatically removed from manual indexes. Given that do you still require a procedure to remove something from a manual index?

**Comment by cmorgner** [comment]
No, that should be enough. Thank you! :)
