### ISSUE TITLE
apoc.agg.position(agg-value, element) -> integer

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#2390]
Return position of the element in the list of results, basically just keeping a counter and returning when element = agg value

perhaps it can be even generalized to

apoc.agg.row([predicate])  -> returns row
with boolean parameter returns row only if parameter is true

**Comment by kirkbushell** [comment]
This would be incredible, and thanks to Neo4j's ability to chain clauses, you could then fetch just that row and return the position, as well! Very useful for what I'm working on atm :)
