### ISSUE TITLE
apoc.convert.toJson throws NullPointerException for null values in maps

### ISSUE THREAD

**Issue by h4emp3** [neo4j-contrib/neo4j-apoc-procedures#2394]
This is the same problem as described in #1900 and happens again in the 4.4.0.1 release. As far as I can tell this whole tree is not based upon the 4.2.x.x tree this problem was fixed in.

Just out of curiosity and not meant to be rude: What is the rationale behind not basing newer versions on existing ones?

**Comment by jordanamr** [comment]
Hello, can we get an update on this? This is a critical bug for production services.

**Comment by pkosiec** [comment]
Looks like this issue has been finally resolved in the 4.4.0.2 that was released yesterday 🎉  Didn't test it yet, but there's a ["Fix apoc.convert.toJson NullPointerException with null values in maps"](https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/8d4d94062711193c3f2cbd17bb54ef10d2a4ed82) commit inside the [4.4.0.2](https://github.com/neo4j-contrib/neo4j-apoc-procedures/commits/4.4.0.2) tree.

**Comment by h4emp3** [comment]
I can confirm that [Release v4.4.0.2](https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/tag/4.4.0.2) includes the patch and it works as expected again :)

As the author, I will take the liberty to close this issue. Hope this is ok for everybody!
