### ISSUE TITLE
apoc.util.validate missing

### ISSUE THREAD

**Issue by jbrumwell** [neo4j-contrib/neo4j-apoc-procedures#240]
Calling

`CALL apoc.util.validate(false,'message',null)`

results in 

```
There is no procedure with the name `apoc.util.validate` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.
```

I tried with both 3.1.0.2 and 3.1.0.3, seems like the other functions are available 

`CALL apoc.help('apoc')`

```
Started streaming 282 records after 229 ms and completed after 281 ms.
```

**Comment by Jiropole** [comment]
I think I'm having the same issue, where many documented procedures are simply missing. Please see my comment in #286.

For instance, I would have had the same error as you. If I list the `apoc.util` procedures, I only see:
```
apoc.util.sleep	apoc.util.sleep(duration :: INTEGER?) :: VOID
```

**Comment by Jiropole** [comment]
Ok now I feel dumb. The procedures have become functions, so it was a syntax issue. e.g. this works: `RETURN apoc.date.format(timestamp())`. Maybe this is your issue too, @jbrumwell.

**Comment by jbrumwell** [comment]
Unfortunately it does not seem to work for me

```
```

**Comment by jexp** [comment]
@jbrumwell sorry for the delay, I presume you were looking in 3.1 ?
It seems I forgot to forward merge the change from 3.0
The commit is now there and should be part of the next release early this week.

**Comment by jbrumwell** [comment]
@jexp Thank you and no worries on the delay :+1:
