### ISSUE TITLE
apoc-3.1.0.4-SNAPSHOT.jar missing Map Functions

### ISSUE THREAD

**Issue by capitolmuckrakr** [neo4j-contrib/neo4j-apoc-procedures#241]
Building from source, did a full build, jar works fine, just doesn't have any map functions. I also tried apoc-3.1.0.3-all.jar available via [download](https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/tag/3.1.0.3)  as well, map functions missing from that jar too. Is there an earlier version that has them (compiled/source)? Thanks.

**Comment by jexp** [comment]
Hi @capitolmuckrakr do you mean that they are missing as procedures or *functions* ?

I just tried it with 3.1.0 and the apoc download:

````
return apoc.map.fromPairs([['a','b'],[3,4]]) as map
 
Rows


Text


Code
 ╒═══════════════╕
│"map"          │
╞═══════════════╡
│{"3":4,"a":"b"}│
└───────────────┘
```

**Comment by capitolmuckrakr** [comment]
OK, my n00b mistake, I'm just picking up Neo4j. I was trying to run older code that was CALLing apoc.map.fromPairs. I didn't realize that there were both procedures and functions, just thought it wasn't there, sorry. Thanks for clarifying for me!
