### ISSUE TITLE
Page for  cypher-based-procedures-functions.adoc references missing apoc.custom.procedures.refresh 

### ISSUE THREAD

**Issue by davidlrosenblum** [neo4j-contrib/neo4j-apoc-procedures#2427]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Expected Behavior (Mandatory)
Section removed if this proc is deprecated and removed, or proc put back

## Actual Behavior (Mandatory)
Missing proc is referenced 

## How to Reproduce the Problem
Look at https://neo4j.com/labs/apoc/4.1/cypher-execution/cypher-based-procedures-functions/

### Simple Dataset (where it's possibile)
N/A
```


```

### Steps (Mandatory)

  1.
  1.
  1.

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS:
  - Neo4j:
  - Neo4j-Apoc: 4.4

**Comment by davidlrosenblum** [comment]
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/21196824/149045712-62c056cb-91dc-4869-b720-e8e605de66aa.png">

**Comment by vga91** [comment]
@davidlrosenblum 
The `apoc.custom.procedures.refresh` is not a procedure,
it is a config variable, see here: https://neo4j.com/labs/apoc/4.4/config/

**Comment by vga91** [comment]
@davidlrosenblum 
I close this issue because it doesn't seem to be a bug.
If you still have any problems, please feel free to open the issue
