### ISSUE TITLE
Add mergeRelationships to the GraphRefactoring

### ISSUE THREAD

**Issue by chunkychode** [neo4j-contrib/neo4j-apoc-procedures#243]
i have found the refactoring space very useful when i learned that I've done something wrong early on in the way i populate the database over time. 
The same mistakes i've done that yielded my the usage or mergeNodes have also landed me in the need for mergeRelationships. 
 
It would be nice if in addition to mergeNodes we could have a mergeRelationships.

**Comment by inserpio** [comment]
Hi @chunkychode, how would you like `mergeRelationships` to work?
Would it be ok if we assume that:
1) the list of relationships you'll pass must have the same starting and ending nodes.
2) the first relationship's name will be the name for the merged relationship
3) we'll union all properties and if the same property will be present in more than one relationship will create an array with the intersection of their values.

Example:

`(a)-[:X { m: 1, n: 2, o: 3 }]->(b)`
`(a)-[:Y { m: 1, n: 3, p: 4 }]->(b)`

will result in

`(a)-[:X { m: 1, n: [2, 3], o: 3, p: 4 }]->(b)`

/cc @jexp @AngeloBusato

**Comment by inserpio** [comment]
@jexp @AngeloBusato `mergeNodes` doesn't manage the creation of distinct values arrays.
Should we align it and introduce a parameter for that with a default guaranteeing backward compatibility with current implementation?

**Comment by chunkychode** [comment]
Hi @inserpio i would think that it would work like mergeNodes. 
keeping data consumers in mind i would not change the data type of n in your example above. ( n changes from numeric to array )

basically i would have union properties and the value if the first relationship determines the value of similar property names.

(a)-[X {m: 1, n: 2}]->(b)
(a)-[X {m: 2, p: 3}]->(b)
would result in 
(a)-[X {m: 1, n: 2, p: 3}]->(b)

and thanks for taking a crack at this :)
