### ISSUE TITLE
apoc.warmup how to know if all nodes were loaded

### ISSUE THREAD

**Issue by vvavepacket** [neo4j-contrib/neo4j-apoc-procedures#245]
I have enough ram on my machine, and I gave page cache spacious gigabytes which is far more greater than the size of my database folder. But when I try to run apoc.warmup, theres not much speed improvement?

How do we interpret this so that we can say all nodes has been cached.

pageSize	nodesPerPage	nodesTotal	nodePages	nodesTime	relsPerPage	relsTotal	relPages	relsTime	totalTime
8192	546	477991	1012	0	240	1036235	10374	0	0

Thank you.

**Comment by jexp** [comment]
It only touches one node per page, so that the whole page is loaded.

**Comment by vvavepacket** [comment]
@jexp Could you explain this a little more? In the previous APOC version, there was a 'nodeLoaded' output, but on 3.0.8 versions, it was removed and changed. 

pageSize nodesPerPage nodesTotal nodePages nodesTime relsPerPage relsTotal relPages relsTime totalTime
8192 546 477991 1012 0 240 1036235 10374 0 0

Based on the above, we see that we have 477991 nodes (nodesTotal). What fields does nodesLoaded correspond to here? Thank you.

**Comment by jexp** [comment]
Each page has 8k each node record is 15 bytes, that means each page holds 546 nodes.
To load a page only one node of the page has to be loaded.
So it loads 1012 pages in total.

**Comment by jexp** [comment]
nodePages * nodesPerPage
