### ISSUE TITLE
Clarify latest APOC releases so there isn't confusion between 3.0.x vs 3.1.x

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j-contrib/neo4j-apoc-procedures#246]
With the latest APOC release of 3.0.8.4, the latest release link leads to the 3.0.8.4 release. This, along with the language for this release, "targets Neo4j 3.0.8 and later," makes it seem as if this works with version Neo4j 3.1.x versions, and has led to some confusion on why the latest version isn't working with 3.1.x instances. In [one case](http://stackoverflow.com/questions/41562729/csv-load-changing-string-to-timestamp), there seems to be a possibility of mismatched APOC releases requiring a reinstall to fix, which makes this issue rather damaging if accurate.

I tested this and my Neo4j works fine after removing mismatched APOC jar with MacOS install of Neo4j 3.1.0, but the corruption issue requiring a reinstall may be specific to either the Windows or Windows 64-bit version of Neo4j, confirmation is needed.

Please provide parallel latest release links for separate branches instead of just whichever was published last, and clarify the language in releases so it's clear that releases targeting older Neo4j versions shouldn't be used for newer versions.

**Comment by jexp** [comment]
Good point. Thanks for raising this.

Not sure you saw this version Matrix: https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/3.0/readme.adoc#version-compatibility-matrix

**Comment by InverseFalcon** [comment]
That matrix is quite useful, and the updated language works well. The latest release link still only leads to the single latest APOC jar released, I'm wondering if there's any way to improve this. Separate latest release links per branch, with links to the other latest release branch in the release notes, in case the viewer is on the wrong one?

**Comment by jexp** [comment]
Unfortunately GitHub only links to the "generally" latest release.

So we have to do that manually, I can adopt the readme's to link to the
concrete one.
Thanks for keeping this up.

**Comment by conker84** [comment]
Done in newer releases
