### ISSUE TITLE
Possible issue with removing org.apache.commons.httpclient.URIException

### ISSUE THREAD

**Issue by SJTucker** [neo4j-contrib/neo4j-apoc-procedures#2470]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.
I also commented here https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/2428 because I started seeing issues after this was merged and seems like it could be related to the error I'm seeing.
## Expected Behavior (Mandatory)
Neo4j server starts without error

## Actual Behavior (Mandatory)
Server start throws an exception

## How to Reproduce the Problem
I'm using the 3.5.30 docker image of neo4j with the apoc plugin.  On server start it pulls the 3.5.0.16 apoc jar file and during initialization it throws an exception.

If I set the neo4j image back to 3.5.11, it pulls the apoc 3.5.0.5 jar which seems to start without issue.

### Steps (Mandatory)

  1. use docker image `neo4j:3.5.30`
  2. `NEO4JLABS_PLUGINS: '["apoc"]'` specified in dockerfile
  3.  docker compose up
  4.  exception thrown on server start

## Screenshots (where it's possibile)
(just realized this screenshot was from when i tested with 3.5.20, but the same thing occurred with 3.5.30)
![image](https://user-images.githubusercontent.com/6341992/150199694-666c8afe-27cd-47c5-86e0-fe095d726a89.png)

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: Alpine 3.13.4
  - Neo4j: 3.5.30
  - Neo4j-Apoc: 3.5.0.16

**Comment by SJTucker** [comment]
@vga91, @conker84 do you all think that merged pr (https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/2428) could be related?

**Comment by jacob-ablowitz** [comment]
I and two other members of my development team are experiencing identical symptoms with the official Neo4j 3.5.30 enterprise docker image.

**Comment by suddenrushofsushi** [comment]
Can confirm my team is also experiencing this exact issue with Neo4j 3.5.30 and APOC 3.5.0.16. 

We've worked around this by downgrading to APOC 3.5.0.15: We're manually grabbing the 3.5.0.15 release jar and dropping it into the container's `/var/lib/neo4j/plugins` dir for now.

**Comment by vga91** [comment]
@SJTucker @jacob-ablowitz @suddenrushofsushi 
The issue is due to the related pr is merged but not released in 3.5.0.16. 
This cause the bug and will be fixed asap.
Can you please try with this attached apoc `.jar`, which contains the #2428 fix?

[apoc-3.5.0.16-all.jar.zip](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/7903617/apoc-3.5.0.16-all.jar.zip)

**Comment by stephenpope** [comment]
Having the same issue .. Is there a way to specify the version of apoc it uses in configuration ?

**Comment by karan-kainth** [comment]
Neo4j has confirmed a fix is being worked on. 

https://community.neo4j.com/t/is-apoc-3-5-0-16-broken/50721/2

**Comment by LeoMouyna** [comment]
> Having the same issue .. Is there a way to specify the version of apoc it uses in configuration ?

I tried several months ago but the apoc version used is from a remote config file: https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json which map neo4j version with an apoc version.
Here the implementation: https://github.com/neo4j/docker-neo4j/blob/f168f615d558f1c21a4f49a8ba6d39eb86496cd9/neo4jlabs-plugins.json

**Comment by jacob-ablowitz** [comment]
> @SJTucker @jacob-ablowitz @suddenrushofsushi The issue is due to the related pr is merged but not released in 3.5.0.16. This cause the bug and will be fixed asap. Can you please try with this attached apoc zipped `.jar`, which contains the #2428 fix?
> 
> [apoc-3.5.0.16-all.jar.zip](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/7903617/apoc-3.5.0.16-all.jar.zip)

@vga91 this jar worked for me. Thanks for the super-quick turnaround!

**Comment by jacob-ablowitz** [comment]
Confirming that the release of apoc 3.5.0.17 took place within the last hour and has resolved this issue, it can now be closed. Thanks again!

**Comment by SJTucker** [comment]
@vga91 sorry for the delay.  testing now - hopeful based on other comments it will work, but will report back shortly.

**Comment by SJTucker** [comment]
@vga91 @conker84 thanks for the quick turn around.  the 3.5.0.17 release resolved the issue for me.
