### ISSUE TITLE
make apoc.export.cypher support the format for cypher-shell

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#248]

**Comment by inserpio** [comment]
@jexp what if we add a new parameter `format` with default value `cypher` to leave everything as it's and `cypher-shell` to create a file for the shell?

**Comment by jexp** [comment]
sounds good to me, good idea, default value would be neo4j-shell

and we could have one that's called cypher which just creates plain cypher without tx-control

**Comment by jexp** [comment]
Cypher shell has `:begin`, `:commit`.

https://neo4j.com/docs/operations-manual/current/tools/cypher-shell/
