### ISSUE TITLE
docs statement on default config values not correct

### ISSUE THREAD

**Issue by ryguyrg** [neo4j-contrib/neo4j-apoc-procedures#253]
apoc.export.file.enabled appears to default to false.  the docs indicate it defaults to true.

![image](https://cloud.githubusercontent.com/assets/1041662/22123883/77a63d78-de42-11e6-8ec6-0d4111f96791.png)

**Comment by jexp** [comment]
The docs state that all defaults to false. I can change the docs to show
false/true instead of true as example.
