### ISSUE TITLE
APOC GraphML attributes not loadable by Gephi

### ISSUE THREAD

**Issue by bassman99** [neo4j-contrib/neo4j-apoc-procedures#258]
APOC generated GraphML (latest APOC, latest Neo4j), when loaded into Gephi, does not load attributes.  It sounds like both an APOC issue and a Gephi issue.  Here are some URLs talking about the issue:

- [https://groups.google.com/forum/#!topic/neo4j/UmLnQjffOxM](url)

- [http://forum-gephi.org/viewtopic.php?f=29&t=5939](url)

- https://github.com/gephi/gephi/issues/1656

The 3rd URL is actually the bug-queue for Gephi; apparently the developer has a question about the way APOC generates GraphML.

**Comment by jexp** [comment]
I fixed something (not released yet, that puts generated keys in the correct place in the graphml file)
Perhaps you can test it with an local build of apoc, otherwise please wait for 3.1.0.4

**Comment by Qingmu** [comment]
@jexp I have the same problem that the graphml created by apoc ignore the attributes of nodes when imported by gephi.  (neo4j-cmmunity-3.2.2 with apoc-3.2.0.4.jar, and gephi version 0.9.1). I tried the replacement of apoc with the version 3.1.0.4, but it cannot work.

**Comment by arocketman** [comment]
I have the same problem with Apoc 3.3.0.1
