### ISSUE TITLE
fix / re-add apoc.periodic.countdown

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#260]
Figure out when it was removed and then add it back.

**Comment by albertodelazzari** [comment]
@jexp Is this still valid?

The method is here:
https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/3.1/src/main/java/apoc/periodic/Periodic.java#L156

**Comment by jexp** [comment]
It has no @Procedure, and there might be tests missing :)
