### ISSUE TITLE
Shaded APOC dependencies pollute classpath 

### ISSUE THREAD

**Issue by nioertel** [neo4j-contrib/neo4j-apoc-procedures#2604]
# Situation
We have a Java application that works with Neo4j (version `4.4`). The application connects to Neo4j via Bolt using Neo4j Java driver.
For unit tests we tear up Neo4j inside the same JVM using the [Neo4j harness](https://github.com/neo4j/neo4j/tree/4.4/community/neo4j-harness), expose the bolt port and connect from the application via Bolt. As we are using APOC procedures, we also need to put APOC on the classpath.
So overall the classpath contains:
- Neo4j 4.4 (Enterprise)
- Neo4j Java Driver 4.4.3
- APOC 4.4.0.3
- Our application
- Our application's dependencies

To add APOC to our application, from my understanding of the [official documentation](https://neo4j.com/labs/apoc/4.4/introduction) there are two options:
- APOC Core: `[...] battle hardened procedures and functions that don’t have external dependencies [...]` -> this doesn't seem correct, as it has lots of external dependencies which are shaded into on fat jar
- APOC Full: `[...] additional procedures and functions [...]`

Looking at the [Github releases](https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases), I find the download links for both. The jars are huge, containing shaded versions of all external dependencies of APOC.
Looking at [Maven Central](https://search.maven.org/artifact/org.neo4j.procedure/apoc/4.4.0.3/jar), I find a version with classifier `all` that appears to be the same as APOC Full and a version without classifier that seems to have the same dependencies as APOC Core (but not shaded) but doesn't have the feature set of APOC core.

# Problem Description
There are multiple issues:
1. Having `APOC Full 4.4.0.3` and `Neo4j Java Driver 4.4.3` on the classpath doesn't work as APOC brings a shaded version of the old `Neo4j Java Driver 4.0.0` which is not API compatible.
2. For our use case `APOC Core 4.4.0.3` would be fine which doesn't contain a shaded Neo4j Java driver but it is not available on a public maven repository.
3. We could work around issue 2. by uploading APOC Core to our internal Maven repository but that still leaves lots of other shaded dependencies inside APOC core which may lead to side effects with dependencies of our application. Therefor I'd prefer to use a version of APOC Core that does not contain shaded dependencies, so I have full control of everything (knowing that APOC functionality may break if I override dependency versions).

# Questions / Remarks / Suggestions
1. Please explain the focus/scope of the apoc jar (without classifier) on Maven Central.
2. Is it possible to publish apoc-core to Maven Central as a short term solution?
3. Is it possible to publish a version of apoc-core to Maven Central that does not contain any shaded dependencies?
4. Is there a reason for not upgrading the Neo4j Java Driver in APOC?
5. In the long term it probably would be good to add a prefix to the java package names of shaded dependencies. Lots of other libraries are doing this (e.g, neo4j-logging with Log4j).

# Further Notes
I am aware that using [test containers](https://www.testcontainers.org/modules/databases/neo4j/) instead of the `Neo4j harness` would solve the issue as APOC could be put into the Neo4j container, however that makes the development, testing and debugging process slower so we don't want to use this as the default.

The issue was already discussed in a couple of related issues without solution:
- #1656 ends with the note `We'll add a test-harness example soon.` -> this would be pretty much what I described here and it currently won't work
- #1825 mentioned that there is only the 'small' apoc jar on Maven Central but in the fix only apoc-full but not apoc-core was added
- neo4j/neo4j#12575 was also about the issue that apoc from Maven Central does not contain the core procedures. No real solution for Maven was created but only a Gradle solution that downloads the dependency directly from APOC's GitHub releases during build.

**Comment by MaxAndersson** [comment]
@conker84  Do you have any insight into this issue?

**Comment by conker84** [comment]
I’m currently out of office, I’ll back on Monday and I’ll look at it

**Comment by conker84** [comment]
Hi @nioertel we removed the shaded dep of the java driver approximately two months ago:
https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/5f50cdb4536d28b00cf24f54b6222e9f4f8bb49d

In the next release, you'll find this included.
Btw the best choice for your env is to use (as you mentioned) Testcontainers Neo4j as you may need in your app to test enterprise features, i.e. multi-tenancy, `NODE KEY` constraints, RBAC and so on...

**N.b.** Please consider Testcontainers Neo4j is not expedient as it's used by us in other products like [Neo4j Spark Connector](https://github.com/neo4j-contrib/neo4j-spark-connector) and [Neo4j Streams](https://github.com/neo4j-contrib/neo4j-streams)

/cc @MaxAndersson
