### ISSUE TITLE
Missing procedures like apoc.map.*

### ISSUE THREAD

**Issue by ziadloo** [neo4j-contrib/neo4j-apoc-procedures#261]
When I try to execute this query:

    CALL apoc.map.fromPairs(["a", "b"])

I'll get the following error:

    There is no procedure with the name `apoc.map.fromPairs` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.
    List available procedures

And when I click on the `List available procedures` link, the list does not contain any `apoc.map`. It's in the case that when I run:

    CALL apoc.help("apoc")

The list shows them all. Here are the versions I'm using:

 * Neo4j: 3.1.0
 * Apoc: apoc-3.1.0.3-all.jar (I downloaded the binary version)

If you want to replicate the error since I'm using docker, it would be pretty easy:

    docker run --env=NEO4J_AUTH=none --volume=$HOME/neo4j/data:/data --volume=$HOME/neo4j/plugins:/var/lib/neo4j/plugins --name neo4j_test neo4j:3.1.0

Just make sure you'll create the following folders before hand:

 * $HOME/neo4j/data
 * $HOME/neo4j/plugins

And of course copy the `.jar` file into the plugins folder.

**Comment by ikwattro** [comment]
In neo4j 3.1, what could be moved to user defined functions has been moved to such : 

https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_map_functions

There is no need anymore to use CALL 

https://neo4j.com/docs/developer-manual/current/extending-neo4j/cypher-functions/


List available functions : 

```
CALL dbms.functions()


╒══════════════════════════════╤══════════════════════════════╤══════════════════════════════╤══════════════════════════════╕
│"name"                        │"signature"                   │"description"                 │"roles"                       │
╞══════════════════════════════╪══════════════════════════════╪══════════════════════════════╪══════════════════════════════╡
│"apoc.coll.avg"               │"apoc.coll.avg(numbers :: LIST│"apoc.coll.avg([0.5,1,2.3])"  │["admin","reader","publisher",│
│                              │? OF NUMBER?) :: (FLOAT?)"    │                              │"architect"]                  │
├──────────────────────────────┼──────────────────────────────┼──────────────────────────────┼──────────────────────────────┤
│"apoc.coll.contains"          │"apoc.coll.contains(coll :: LI│"apoc.coll.contains(coll, valu│["admin","reader","publisher",│
│                              │ST? OF ANY?, value :: ANY?) ::│e) optimized contains operatio│"architect"]                  │
│                              │ (BOOLEAN?)"                  │n (using a HashSet) (returns s│                              │
│                              │                              │ingle row or not)"            │                              │
├──────────────────────────────┼──────────────────────────────┼──────────────────────────────┼──────────────────────────────┤
│"apoc.coll.containsAll"       │"apoc.coll.containsAll(coll ::│"apoc.coll.containsAll(coll, v│["admin","reader","publisher",│
│                              │ LIST? OF ANY?, values :: LIST│alues) optimized contains-all │"architect"]                  │
│                              │? OF ANY?) :: (BOOLEAN?)"     │operation (using a HashSet) (r│                              │
│                              │                              │eturns single row or not)"    │                              │
├──────────────────────────────┼──────────────────────────────┼──────────────────────────────┼──────────────────────────────┤
```


Test the `apoc.map.fromPairs()` function, by giving actual pairs : 

```
RETURN apoc.map.fromPairs([["a","b"],["b","c"]]) AS map

╒═════════════════╕
│"map"            │
╞═════════════════╡
│{"a":"b","b":"c"}│
└─────────────────┘

```
