### ISSUE TITLE
Apoc.import.graphml doesn't work for edges

### ISSUE THREAD

**Issue by rohankharwar** [neo4j-contrib/neo4j-apoc-procedures#2659]
## Problem Statement
I am trying to export some data using the `apoc.export.csv.data` and then import using `apoc.import.graphml`.
When I run `apoc.export.csv.data` for extracting both nodes and rels in a single file and then import that single file using `apoc.import.graphml`, it works fine.

But for performance and parallelize it I am trying to run for nodes and rels separately.
So we get 2 files - one for nodes and other for relationships.
Then import each the nodes file first and then the relationship file. 
However the problem is `apoc.import.graphml` works fine for the nodes but then fails for rels giving error as  java null pointer exception.
The Relationship file does have the source and target node ids so it should be able to load the data. 

I can easily reproduce this using the following queries.
## Reproducible steps

//Extract node files
MATCH (person:Person)-[actedIn:ACTED_IN]->(movie:Movie)
WHERE person.name starts with "K"
with collect(person)+collect(movie) as node
CALL apoc.export.graphml.data(node, [], "/Users/rohankharwar/Downloads/movies_nodes.graphml", {stream: false})
YIELD file, nodes, relationships, properties, data
RETURN file, nodes, relationships, properties, data;

//Extract Relationship files
MATCH (person:Person)-[actedIn:ACTED_IN]->(movie:Movie)
WHERE person.name starts with "K"
with collect(person)+collect(movie) as node, collect(actedIn) as rels
CALL apoc.export.graphml.data([], rels, "/Users/rohankharwar/Downloads/movies_rels.graphml", {stream: false})
YIELD file, nodes, relationships, properties, data
RETURN file, nodes, relationships, properties, data;

//graphml file import nodes
CALL apoc.import.graphml("file:///Users/rohankharwar/Downloads/movies_nodes.graphml", {readLabels:true})

//graphml file import rels
CALL apoc.import.graphml("file:///Users/rohankharwar/Downloads/movies_rels.graphml", {readLabels:true})

We get the following error (attached image)

### Simple Dataset (where it's possibile)

I just used the movies dataset. 

### Versions

  - OS: Linux
  - Neo4j: 4.3.10 , 4.4.4
  - Neo4j-Apoc: 4.3.0.5, 4.4.0.3

![nullpointerexception](https://user-images.githubusercontent.com/13203910/160164753-8a709a63-2496-4901-a6e0-0730bd6fbf93.png)

**Comment by robobenklein** [comment]
I can confirm this problem only occurs when `readLabels` is true:

When it is false the ratio of edges to nodes is about 1.0:
![image](https://user-images.githubusercontent.com/5423266/169717387-7e46d12e-7c0f-491f-a37b-74b4279e4f94.png)

When set to true, it ends up missing almost half the edges:
![image](https://user-images.githubusercontent.com/5423266/169717409-c4593bb6-1ce1-4547-963b-b66f93249a24.png)

My dataset is a DAG, with every node having exactly one parent edge, so it's easy to tell that the graph is broken when imported with readLabels.

**Comment by kk60503** [comment]
FYI this is still an issue. Importing graphml with apoc and readLabels set to true, the Neo4j parser skips every other relationship/edge as they appear in the graphml file. My current hack is to write each edge in the graphml file twice.
