### ISSUE TITLE
Feature request : apoc support for MERGE for nodes and rels

### ISSUE THREAD

**Issue by tomzeppenfeldt** [neo4j-contrib/neo4j-apoc-procedures#271]
It would be nice to be able to include MERGE operations in apoc

     CALL apoc.merge.node(mergeLabel,{id:mergeId}) YIELD node
     RETURN node

We now have to use this workaround

     WITH 'MERGE (n:mergeLabel {id:mergeId}) return n' AS cypher
     CALL apoc.cypher.doit(cypher,{}) yield value
     RETURN value.n

And for rels:

    apoc.merge.relationship(from,to,relType) yield rel

**Comment by cstaikos** [comment]
@ophileon can you clarify how the workaround you described works? I've tried the following:
```
 WITH 'MERGE (n:mergeLabel {id:mergeId}) return n' AS cypher
 CALL apoc.cypher.doit(cypher,{mergeLabel: 'myNewLabel', mergeId: 123}) yield value
 RETURN value.n
```

But this seems to create a node with label `mergeLabel`, instead of `myNewLabel` - the node does get an `id` of `123` however.

**Comment by InverseFalcon** [comment]
I think you'd need to use string appending here:

```
WITH 'MERGE (n:' + mergeLabel + ' {id:mergeId}) return n' AS cypher
 CALL apoc.cypher.doit(cypher,{mergeId: 123}) yield value
 RETURN value.n
```

**Comment by cstaikos** [comment]
@InverseFalcon perfect, that did it! Thanks!

**Comment by arganzheng** [comment]
from this article: [Summer 2017 Release of the APOC Procedures Librar](https://dzone.com/articles/summer-2017-release-of-the-apoc-procedures-library), it seem thats apoc has already support merge nodes and relationship.

> There are now procedures to merge nodes and relationships with dynamic labels, relationship-types, and properties (apoc.merge.node/relationship).
>
>```
> CALL apoc.merge.node(['Label'], {id:uniqueValue}, {prop:value,...}) YIELD node;
> CALL apoc.merge.relationship(startNode, 'RELTYPE', {[id:uniqueValue]}, {prop:value}, endNode) YIELD rel;
>```

**Comment by victoriastuart** [comment]
I see that

    CALL apoc.merge.relationship(startNode, 'RELTYPE', {[id:uniqueValue]}, {prop:value}, endNode) YIELD rel;

appears here, https://neo4j.com/blog/apoc-summer-2017-release/, but not here: https://neo4j-contrib.github.io/neo4j-apoc-procedures/

Is there a reason why it has not been added to the latter site?

**Comment by conker84** [comment]
We have merging procs for node and procedures now
