### ISSUE TITLE
Typo in APOC documentation

### ISSUE THREAD

**Issue by ophileon** [neo4j-contrib/neo4j-apoc-procedures#272]
on https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_cypher_execution

CALL apoc.cypher.doIt(fragment, params) yield value

while in fact it is  "doit"  instead of  "doIt"

**Comment by jexp** [comment]
feel free to send a PR directly by editing the file on GH

**Comment by ophileon** [comment]
Dear Michael,

I always get lost in the woods of branches . Even my own developers want to me stay out of it :)   Just not my cup of tea / comfort zone. 

Best,

Tom
