### ISSUE TITLE
Feature Request: apoc.path.subgraphFull()

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j-contrib/neo4j-apoc-procedures#275]
This builds off of the proposed [apoc.path.subgraphNodes()](https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/274) request.

Although apoc.path.subgraphNodes() returns nodes for a subgraph, it doesn't return the complete subgraph with all relationships that exist between all subgraph nodes.

The collection of relationships can be obtained by passing the collection of subgraph node ids to apoc.algo.cover().

This requests a new procedure, apoc.path.subgraphFull(), which uses both subgraphNodes() and Cover.cover() (or a similar method which takes the nodes directly instead of the ids), and returns a GraphResult of the subgraph nodes and all relationships between them.

**Comment by Assiam** [comment]
It is exactly what I have done. I suggest to combine the two algorithms.
Thank you for your help

**Comment by InverseFalcon** [comment]
Fulfilled.

**Comment by Cyoung7** [comment]
@Assiam  this method apoc.path.subgraphAll() can get all the nodes and edges within subgraph,but can not get start node and end node in each edge. how can i solve it. wating for your reply, thanks!

**Comment by InverseFalcon** [comment]
@Cyoung7 You can get the start and end nodes of each edge from the relationship. In Cypher, the functions `startNode(rel)` and `endNode(rel)` will give you the start and end nodes of a relationship.
