### ISSUE TITLE
Unable to import json file with apoc.import.json

### ISSUE THREAD

**Issue by krishnan-pb** [neo4j-contrib/neo4j-apoc-procedures#2759]
## Guidelines

Using apoc version "4.3.0.5.0", trying to import json using the procedure "apoc.import.json("file:///all_6_apr.jsonl")" fails with an exception the node that is is failing in import is in the sample below, which was output of apoc.export.json. It's only this node that failed.

## Expected Behavior (Mandatory)
Import should be successful 

## Actual Behavior (Mandatory)
"ERRORNeo.ClientError.Procedure.ProcedureCallFailed
Failed to invoke procedure apoc.import.json: Caused by: java.lang.NullPointerException"

## How to Reproduce the Problem
 Perform apco json import with the node 

{"type":"node","id":"8214","labels":["VALUE"],"properties":{"modificationDate":1650264267125,"oid":"b3a7d3dc-5746-441a-9f02-c78d884a7826","creationDate":1650264267125,"value":"cases://cases/813b1f38-0159-467e-bb86-a15d13bf7f9f"}}

### Simple Dataset (where it's possibile)

```
apoc.import.json("file:///all_6_apr.jsonl")

```

### Steps (Mandatory)

  1. Create a json file with the above node
  2. Perform apoc.import.json("file:///all_6_apr.jsonl")
  
**The issue seems to be with "labels":["VALUE"] when I change this to "labels":["VALUE1"], import works.**

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: macOS Monterey 12.3.1
  - Neo4j: 4.3.10
  - Neo4j-Apoc: 4.3.0.5.0

**Comment by vga91** [comment]
@krishnan-pb 
I'm not able to replicate the error.

Can you share your whole `.json` file? Maybe something happens before the failing row and/or is present some character not included here with the copy-paste.

Also, to narrow down the possible causes, could you try importing it to a new empty database?
Something strange could have happened regarding the "VALUE" label only.
