### ISSUE TITLE
Feature Request: apoc.algo.mst() to find the minimum spanning tree

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j-contrib/neo4j-apoc-procedures#276]
This requests a new procedure, apoc.algo.mst() (or alternately, apoc.algo.minimumSpanningTree()).

Result could be a GraphResult (list of nodes and list of relationships in the MST).

Possible variants on the procedure can include:

- Find MST given a collection of nodes and a collection of relationships between the given nodes.
- Find MST given a starting node(s), label and relationship filters, and maxLevel depth.

**Comment by conker84** [comment]
We can closed this as it should be managed by GDS
