### ISSUE TITLE
Remove items from linked lists and reconnect procedure

### ISSUE THREAD

**Issue by ikwattro** [neo4j-contrib/neo4j-apoc-procedures#28]
Based on the following example : 

http://stackoverflow.com/questions/37088730/delete-several-items-from-a-linked-list

**Comment by jexp** [comment]
@ikwattro any progress?

**Comment by ikwattro** [comment]
didn't worked on it yet, thanks for reminding

**Comment by jexp** [comment]
I added apoc.nodes.link so far, but no updating of linked lists or removal of elements.
