### ISSUE TITLE
pagerank crashes database

### ISSUE THREAD

**Issue by rotten** [neo4j-contrib/neo4j-apoc-procedures#280]
When I call pagerank multiples times in the same cypher session, I will suddenly abend like this:

```
SSL Connection terminated while receiving data. This can happen due to network instabilities, or due to restarts of the database.

Bye!
Exception in thread "Thread-0" org.neo4j.driver.v1.exceptions.ClientException: Cannot run more statements in the current session as an unrecoverable error has happened. Please close the current session and re-run your statement in a new session.
	at org.neo4j.driver.internal.NetworkSession.ensureNoUnrecoverableError(NetworkSession.java:279)
	at org.neo4j.driver.internal.NetworkSession.reset(NetworkSession.java:127)
	at org.neo4j.shell.state.BoltStateHandler.reset(BoltStateHandler.java:172)
	at org.neo4j.shell.CypherShell.reset(CypherShell.java:184)
	at org.neo4j.shell.CypherShell$1.run(CypherShell.java:192)
```

There is nothing obvious in the neo4j log nor the debug log... however the neo4j instance is usually completely dead.  (ie, crashed and gone from the process table)

I'm guessing there was a memory leak and that the database ran out of heap, but I can't tell.

The bigger graphs die sooner than the smaller graphs, however they all seem to die after a few subsequent runs within one session.

Presumably my solution is to open a new session for each run.  I'll test that shortly.  However, I wanted to raise this issue.

I hate it when databases silently just die.

EDIT to add version detail:
    Neo4j 3.1.0
    APOC 3.1.0.3

**Comment by jexp** [comment]
Can you explain in more detail which of the pagerank procedures you run and *how exactly* you run them?
The pagerank procedure is using some low level APIs and utilizes all CPUs. So you shouldn't run more than one of them. Also it uses separate transaction control from your session.

In general  it makes sense to run only one per session or at least per tx.

**Comment by rotten** [comment]
I'm running pagerank over subgraph - not the entire graph.  I run it over several subgraphs, one at a time. 

`cat mypageranks.cql | cypher-shell`

mypageranks.cql is something like this:

```
// first pagerank
CALL apoc.algo.pageRankWithCypher(
    {
      iterations: 100,
      write: true,
      property: 'pagerank_number_1',
      node_cypher:'none',
      rel_cypher: 'MATCH (n)-[r]->(m) where //some criteria on the edge // return id(n) as source, id(m) as target, 1 as weight'
    }
);

// second pagerank
CALL apoc.algo.pageRankWithCypher(
    {
      iterations: 100,
      write: true,
      property: 'pagerank_number_2',
      node_cypher:'none',
      rel_cypher: 'MATCH (n)-[r]->(m) where // some other criteria // return id(n) as source, id(m) as target, 1 as weight'
    }
);

```

After the 4th one or 5th one, the database just goes *poof*.  I restart the database, take out the first few from the .cql file, and run it again, and they continue on.

**Comment by jexp** [comment]
Ok, thanks for the feedback I look into it.

And you used the same session?

But you're not running them in parallel but one after the other?

**Comment by rotten** [comment]
Correct.  It is a single file with 8 or 9 pageranks in a row, one after the other.

**Comment by conker84** [comment]
Algo procedures are deprecated
