### ISSUE TITLE
Unknown function 'apoc.coll.stdev' for apoc 4.4.0.3

### ISSUE THREAD

**Issue by dstaehler** [neo4j-contrib/neo4j-apoc-procedures#2820]
## Expected Behavior (Mandatory)

RETURN apoc.coll.stdev([10, 12, 23])

expected result 7

## Actual Behavior (Mandatory)

Unknown function 'apoc.coll.stdev' (line 1, column 8 (offset: 7))
"RETURN `apoc`.`coll`.`stdev`(([10, 12, 23])) AS `apoc.coll.stdev([10, 12, 23])`"

### Steps (Mandatory)

  1. RETURN apoc.coll.stdev([10, 12, 23])

### Versions

  - OS: macos 10.15
  - Neo4j: 4.4.4
  - Neo4j-Apoc: 4.4.0.3

Should be ok following documentation for apoc 4.4 - Thanks for having a look at this issue

**Comment by vga91** [comment]
@dstaehler 

It seems there has been an inconsistency between the documentation and the actual releases,  the function was not yet released in `4.4.0.3`, despite the docs. 

Currently. from `4.4.0.4` version the function works correctly.
