### ISSUE TITLE
Bug: error when create array property on node using apoc.create.setProperty (something like #210)

### ISSUE THREAD

**Issue by mfiosins** [neo4j-contrib/neo4j-apoc-procedures#284]
Executing

match(n:Person) CALL apoc.create.setProperty(n, "A",  ["ABC"]) YIELD node RETURN n

gives error 

Failed to call procedure `apoc.create.setProperty(nodes :: ANY?, key :: STRING?, value :: ANY?) :: (node :: NODE?)`: [[ABC]:scala.collection.convert.Wrappers$SeqWrapper] is not a supported property value

This looks similar to #210 

apoc-3.1.0.3, neo4j-community-3.1.1

**Comment by jexp** [comment]
There was a commit missing, thanks for pointing it out.
