### ISSUE TITLE
add apoc.delete.all

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#288]
that cleans out all nodes and rels in batch
and also gets rid of indexes and constraints

**Comment by inserpio** [comment]
@jexp  isn't it too dangerous? are you sure we want to provide it?

**Comment by jexp** [comment]
Good question, this is mostly for testing / experimentation.
So perhaps we should put it into a separate module.

Put it on hold for now.

**Comment by conker84** [comment]
We added the `apoc.periodic.truncate`
