### ISSUE TITLE
Feature Request: date conversion and add functions

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j-contrib/neo4j-apoc-procedures#289]
Most of APOC's date/time functions deal with parsing a timestamp (at some time resolution) from a string, and formatting to go the other direction.

APOC could use some additional date functions for converting a timestamp between different resolutions, and adding/subtracting some amount of time at a specific resolution (though keeping the output at original resolution).

Some possible functions:

`apoc.date.convert(<timestamp>, <timestampResolution>, <desired resolution>)`
example usage: 
`return apoc.date.convert(timestamp(), 'ms', 'd') as todayInDayResolution`

`apoc.date.add(<timestamp>, <timestampResolution>, <numberToAdd>, <addResolution>)`
example usage:
`return apoc.date.add(timestamp(), 'ms', -3, 'd') as threeDaysAgoInMs`

**Comment by jexp** [comment]
Thanks a lot @InverseFalcon !
