### ISSUE TITLE
The `apoc.import.json` constraint check should works only when an unique constraint exists

### ISSUE THREAD

**Issue by vga91** [neo4j-contrib/neo4j-apoc-procedures#2930]
## Expected Behavior (Mandatory)

Missing constraint error

## Actual Behavior (Mandatory)

The import works

## How to Reproduce the Problem

Create a file `all.json` with label `User`:
```
{"type":"node","id":"0","labels":["User"],"properties":{"born":"2015-07-04T19:32:24","name":"Adam","place":{"crs":"wgs-84","latitude":33.46789,"longitude":13.1,"height":null},"male":true,"age":42,"kids":["Sam","Anna","Grace"]}}
```

Try to import the file without constraints:
```
CALL apoc.import.json('all.json')
```
this will throw an error message:
```
Missing constraint required for import. Execute this query: 
CREATE CONSTRAINT ON (n:User) assert n.neo4jImportId IS UNIQUE;
```

Create an existence constraint instead of an unique one.
```
CREATE CONSTRAINT ON (n:User) assert n.neo4jImportId IS NOT NULL
```

Retry the import and note that it's work.

### Versions

  - OS: OSX
  - Neo4j: 4.3.11
  - Neo4j-Apoc: 4.3.0.5

**Comment by JrPeng** [comment]
Hi, do you know what is the oldest version that has merged the request? 
Thank you.
