### ISSUE TITLE
Bug: server settings for local file upload are not honoured

### ISSUE THREAD

**Issue by vasilystfc** [neo4j-contrib/neo4j-apoc-procedures#294]
apoc-3.1.0.3-all under neo4j-community_windows-x64_3_1_1 does not allow the upload of local files despite apoc.import.file.enabled=true is defined in neo4j.conf 

Server configuration shows the parameter as enabled:
{
        "isIs": "false ",
        "name": "apoc.import.file.enabled",
        "description": "Configuration attribute",
        "type": "java.lang.String",
        "value": "true",
        "isReadable": "true",
        "isWriteable": "false "
      }

but this is somehow not honoured by the server. When try to upload local Windows file, the procedure call fails with the message:

Failed to invoke procedure `apoc.load.json`: Caused by: java.lang.RuntimeException: Import from files not enabled, please set apoc.import.file.enabled=true in your neo4j.conf

**Comment by jexp** [comment]
And you edited the neo4j.conf via the Neo4j Desktop UI ?

**Comment by vasilystfc** [comment]
> And you edited the neo4j.conf via the Neo4j Desktop UI ?
No, just in the text editor (Notepad++)

**Comment by InverseFalcon** [comment]
Also encountering this one with Mac CE version 3.1.1 and APOC 3.1.0.3. 

The following are in my neo4j.conf file, but are not being honored:

> apoc.import.file.enabled=true
> apoc.export.file.enabled=true

These are set in the following locations:
~/Documents/Neo4j/.neo4j.conf
~/Documents/Neo4j/neo4j.conf

**Comment by inserpio** [comment]
Closed with #313.

**Comment by szarnyasg** [comment]
Just for the record - we ran into a similar issue on Windows and this issue showed up first in the search results. Even though the required configuration was set, we got the following error message:

> Neo.ClientError.Procedure.ProcedureCallFailed
>
> Failed to invoke procedure `apoc.export.graphml.all`: Caused by: java.lang.RuntimeException: Import from files not enabled, please set apoc.import.file.enabled=true in your neo4j.conf

Restarting Neo4j did not solve the problem, but restarting Windows did.
