### ISSUE TITLE
Export graphml missing data key

### ISSUE THREAD

**Issue by robinsonkwame** [neo4j-contrib/neo4j-apoc-procedures#295]
Under [apoc-3.1.0.3-all.jar](https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/3.1.0.3/apoc-3.1.0.3-all.jar), using `apoc.export.graphml.query`, I typically see:

```
<?xml version="1.0" encoding="UTF-8"?>
<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
<graph id="G" edgedefault="directed">
<node id="n90146" labels=":People:All"><data key="labels">:People:All</data><data key="nodeid">person-3973</data><data key="email">mickey.mouse@gmail.com</data><data key="type">-1</data><data key="gender">male</data><data key="facebook">-1</data><data key="crunchbase">-1</data><data key="age">-1</data><data key="url">-1</data><data key="twitter">-1</data><data key="linkedin">-1</data><data key="angellist">-1</data><data key="label">Mickey Mouse</data></node>
```

with ```<data key=...>``` inside ```<node>```

However, in the output the keys are not specified in advanced per the Graph ML standard (see an example of this [here](https://lists.nongnu.org/archive/html/igraph-help/2011-12/msg00027.html)). Is there a way to force `apoc.export.graphml.query` to include the <key> tags in advance so that they may read by other libraries, such at R's `igraph`?

**Comment by jexp** [comment]
I'm working on this sorry for the delay.

**Comment by dtzWill** [comment]
Dunno if this helps, but what was missing for me was putting "useTypes:true" in the config parameter.

I /did/ end up with minor problem with the produced items, but otherwise fixed the issue for me (using 3.1.0.4).

**Comment by jexp** [comment]
What was the minor problem? Yes keys are not exported by default b/c it is
more expensive (for large exports) to go over all the data first to collect
the information.

**Comment by dtzWill** [comment]
Makes sense. I only found useTypes from looking at the source, and since this issue is about emitting keys I thought I'd share that in case it helps.

The minor issue is the one I reported as #323 and linked above.

**Comment by dtzWill** [comment]
Oh, I edited that link into the comment after reporting it.
