### ISSUE TITLE
apoc 4.4 download link

### ISSUE THREAD

**Issue by Goutham1010** [neo4j-contrib/neo4j-apoc-procedures#2960]
Can you please direct me to apoc-4.4.0.3-all.jar download link

**Comment by neo-technology-build-agent** [comment]
Hello @Goutham1010, the artifacts are down its corresponding release: https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/tag/4.4.0.3

**Comment by ncordon** [comment]
Hello @Goutham1010, the artifacts are down its corresponding release: https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/tag/4.4.0.3
