### ISSUE TITLE
Incompatability of server & apoc during install

### ISSUE THREAD

**Issue by waigitdas** [neo4j-contrib/neo4j-apoc-procedures#2961]
Please see https://discord.com/channels/787399249741479977/831067735499866152/982304484946477056

What is the solution for this which is the default that Neo4j Desktop installs:

The apoc version (4.4.0.5) and the Neo4j DBMS versions [4.4.7] are incompatible.

I want to use v 4.4.7.  When I start the database it completes the process but the debug.log shows lots of apoc procedures not loading.  I can see the procedures in a browser query and they will run in the browser. But when I call them from java code in a plugIn they fail. This is a new problem not see before with the same code. The Maven pom file  was adjusted to accommodate 4.4.7. The config file sets permissions for apoc procedures.

**Comment by waigitdas** [comment]
[debug.log](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/8835373/debug.log)

**Comment by vga91** [comment]
Related to https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/2878

**Comment by vga91** [comment]
Fixed by https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/2885
