### ISSUE TITLE
Feature Request: collection helper functions around duplicated list elements

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j-contrib/neo4j-apoc-procedures#298]
This requests some new apoc.coll functions for dealing with duplicated list elements:

apoc.coll.containsDuplicates(coll) - Returns boolean for whether a collection contains duplicate entries.

apoc.coll.duplicates(coll) - Returns a collection of items which were duplicated in the original collection.

apoc.coll.duplicatesWithCount(coll) - Returns a collection of maps with the following entries: {`item`, `count`}. `item` is the duplicated item, `count` is the number of times the item appears in the collection.

apoc.coll.occurrences(coll, item) - Returns the number of occurrences of the item within the given collection.

**Comment by jexp** [comment]
Makes sense, do you want to take a stab at this?

**Comment by InverseFalcon** [comment]
Sure, I'll give it a go.
