### ISSUE TITLE
apoc.cypher.runSchema is not supported by Neo4j Aura (fulltext search index)

### ISSUE THREAD

**Issue by leonpierre** [neo4j-contrib/neo4j-apoc-procedures#2981]
## Feature description (Mandatory)
Currently we are using apoc.cypher.runSchema to create a fulltext search index to speed up search queries, but on Neo4j Aura that apoc call is not supported. Is there a workaround or it is planned to support this in Neo4j Aura?

## Considered alternatives
None (as far as I know).

## How this feature can improve the project?
To have this functionality in Aura would increase the speed of fulltext searches tremendous.

**Comment by vga91** [comment]
@leonpierre 
Aura instances come with a subset of APOC Core functions/procedures, and `apoc.cypher.runSchema` procedure seems not currently included. The list of functions/procedures provided is [here](https://neo4j.com/docs/aura/platform/apoc/).

I would suggest you add a request to Team Aura via [this link](https://neo4j-aura.canny.io/auradb).
