### ISSUE TITLE
Apoc not working in Neo4j 3.1.1 (on windows)

### ISSUE THREAD

**Issue by sirmad007** [neo4j-contrib/neo4j-apoc-procedures#299]
it seems that apoc is not compatible with neo4j V3.1.1 CE (on windows)
i see only a single procedure of apoc.
i tested the apoc versions v3.1.0.3 and v3.1.0.2.
![procedure](https://cloud.githubusercontent.com/assets/18436278/23395704/524ba816-fd90-11e6-891f-e71692ae80e8.png)

i see nothing special in the log
[debug.log.txt](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/805974/debug.log.txt)

**Comment by jexp** [comment]
What was the reason?

Von meinem iPhone gesendet

**Comment by sirmad007** [comment]
if you use the setup, the plugins are not used from neo4j path, but instead inside the directory of your database. see also here http://stackoverflow.com/questions/42286508/apoc-is-only-partially-installing-its-extension-in-neo4j-one-procedure
