### ISSUE TITLE
apoc.refactor.cloneNodes withRelationships = true - hangs and does not complete call

### ISSUE THREAD

**Issue by mark-sts** [neo4j-contrib/neo4j-apoc-procedures#3000]
When I call apoc.refactor.cloneNodes with the relationships boolean as true, the call simply hangs, I have provided a simple example below.

## Expected Behavior (Mandatory)
Return clone of nodes with relationships

## Actual Behavior (Mandatory)
Call to apoc.refactor.cloneNodes just hangs forever

## How to Reproduce the Problem
CREATE (a:Person {name: "Mark", city: "London"})
CREATE (b:Person {name: "Dan", city: "Hull"})
CREATE (a)-[r:FRIENDS_WITH]->(b)
RETURN a,b

MATCH (p:Person)
WITH collect(p) AS people
CALL apoc.refactor.cloneNodes(people, true)
YIELD input, output
RETURN input, output;

### Steps (Mandatory)

  1.  Execute the cypher above to create person nodes and relationship
  2. Execute the cypher to clone the person nodes with relationships

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: Windows 11
  - Neo4j: 4.4.5
  - Neo4j-Apoc: 4.4.0.6

**Comment by danlechambre** [comment]
I encounter the same problem

**Comment by inf3rnus** [comment]
Same problem with Aura...
