### ISSUE TITLE
APOC.Gephi.add not supporting Unicode?

### ISSUE THREAD

**Issue by waigitdas** [neo4j-contrib/neo4j-apoc-procedures#3013]
Using Neo4j 4.4.8; apoc 4.4.0.6

Is there a fix for apoc.gephi.add to support unicode? I keep getting this error: Invalid UTF-8 middle byte 0x72,  It dumps the data stream into Gephi, until it hits the unlikeable character.

This should support Unicode character

I've using person information which I will not share. But here is the query
```
MATCH path=(m1:DNA_Match)-[r:shared_match]-(m2:DNA_Match) 
WITH path LIMIT 50000
with collect(path) as paths
call apoc.gephi.add(null,'gfg1', paths) yield nodes, relationships, time
return nodes, relationships, time

```
This works well (streams data to Gephi) with some data but then crashes with others.

**Comment by vga91** [comment]
@waigitdas 
Using macOS I was unable to replicate the error, while on windows i get an error similar to yours (with a simple node `(n:Test {name:'äää'})`).
Just to confirm or not, are you using a windows operating system?

**Comment by conker84** [comment]
@waigitdas ping

**Comment by vga91** [comment]
@waigitdas  

Closed for lack of feedback, please feel free to reopen in case you still have problems
