### ISSUE TITLE
constraint issue (create before delete) with mergeNodes

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#303]
Failed to invoke procedure `apoc.refactor.mergeNodes`: Caused by: org.neo4j.graphdb.ConstraintViolationException: Node 1250 already exists with label Organization and property "name"=[INVESCO, LTD.]

we need to delete the node first (or at least the key property) before creating a new one

**Comment by inserpio** [comment]
We could backup the information into a VirtualNode + List<VirtualRelationship>, delete the source and copy from Virtual to target.

**Comment by jexp** [comment]
it should also work if we pull out the properties as a map
Then transfer rels
Delete node
And only then set properties

Von meinem iPhone gesendet
