### ISSUE TITLE
Optionally configure APOC to not store information in the system database but the current database

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#3040]
We've discussed this before but I didn't create an issue for it.

Currently APOC stores information on triggers, custom procs, uuid-handler, etc. in the system database.

As an configuration option it should be possible to also store this information in the current database, which would also alleviate some of the cluster leaderships issues, but with the drawback that there would be additional nodes that don't belong to the actual graph data in the current db.

This would also cover the issues that triggers or custom procedures are deleted when a database is deleted.

**Comment by vga91** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[S2][BT Athena] adding triggers in a causal cluster is awkward](https://trello.com/c/2N3MD4dH/1068-s2bt-athena-adding-triggers-in-a-causal-cluster-is-awkward)

**Comment by vga91** [comment]
Closed since another method was chosen to solve the system db problems with clusters
See here: https://github.com/neo4j/apoc/pull/250
