### ISSUE TITLE
Feature Request: dijkstra confined to a subgraph

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j-contrib/neo4j-apoc-procedures#307]
This requests a new dijkstra procedure that only executes on a defined subgraph, cutting down the complexity and execution time if we can supply boundaries for the algorithm.

This could accept a collection of relationships, or a collection of nodes (unsure if we want to support both of these or only one).

**Comment by Assiam** [comment]
Thank you for creating this issue. It's a good point to optimize dijkstra algorithm

**Comment by jexp** [comment]
https://github.com/neo4j-contrib/neo4j-graph-algorithms
