### ISSUE TITLE
apoc.custom.declareProcedure fails with java.lang.RuntimeException if provided mode is SCHEMA

### ISSUE THREAD

**Issue by psygnoser** [neo4j-contrib/neo4j-apoc-procedures#3072]
## Expected Behavior (Mandatory)

Works fine with `APOC: 4.4.0.3`

## Actual Behavior (Mandatory)

Running with `APOC: 4.4.0.4 - 4.4.0.7` results in error: `Failed to invoke procedure apoc.custom.declareProcedure: Caused by: java.lang.RuntimeException: The query execution type is READ_WRITE, but you provided mode SCHEMA.
Supported modes are [READ, WRITE, WRITE]`

* Note that `WRITE` is declared twice in the whitelist, which seems kind of off...

## How to Reproduce the Problem

Run the following cypher:
```
 CALL apoc.custom.declareProcedure(
    "test() :: (response::INT)",
    "
    call apoc.schema.assert({Foo:['bar']}, null) yield label, key, keys, unique, action

    return 0 as response
    ",
    "SCHEMA"
);
```
* Same happens if you run it with mode `DBMS`

### Versions

  - OS: Fedora 35, CentOS Linux 8
  - Neo4j: 4.4.7
  - Neo4j-Apoc: 4.4.0.4 - 4.4.0.7

**Comment by RobertoSannino** [comment]
It will be resolved in release 5.17.1
