### ISSUE TITLE
neo4j release 3.1.2  not starting with apoc 3.1.0.3

### ISSUE THREAD

**Issue by hdk** [neo4j-contrib/neo4j-apoc-procedures#308]
New neo4j 3.1.2 release wont start up with apoc-3.1.0.3

Trying to compile apoc 3.1 with neo 3.1.2 jars, I get
src/main/java/apoc/schema/AssertSchemaProcedure.java:14: error: cannot find symbol
import org.neo4j.kernel.api.proc.Mode;

Seems the guys at neo have removed org.neo4j.kernel.api.proc.Mode completely

**Comment by jexp** [comment]
I just pushed a fix to the 3.1 branch.
Could you try to build locally again.

Or use this build for now: https://dl.dropboxusercontent.com/u/14493611/apoc-3.1.0.4-SNAPSHOT-all.jar

**Comment by hdk** [comment]
Have a look at the changes in org.neo4j.kernel.api.proc.ProcedureSignature from 3.1.1 to 3.1.2: 
Neo refactored the code to use org.neo4j.kernel.api.proc.Mode instead of org.neo4j.procedure.Mode

Wouldnt changing src/main/java/apoc/schema/AssertSchemaProcedure.java to use Mode from org.neo4j.procedure.Mode fix the problem and keep AssertSchemaProcedure working?

# just an idea, never had a deeper look at neo or apoc code before.

**Comment by jexp** [comment]
Yes of course but that at the same time breaks it for all 3.1.0 and 3.1.1 users.

This is just a temporary fix, we gonna release a proper version soon.

**Comment by johnymontana** [comment]
Just ran into this myself. I can confirm that commit c4169698bc23fb135d1117fa958ce1723c295deb in the 3.1 branch fixes this on Neo4j 3.1.2

**Comment by InverseFalcon** [comment]
New APOC release available targeting Neo4j 3.1.2, see version 3.1.2.5 or later

**Comment by hdk** [comment]
works like a charm!

thanks guys!
