### ISSUE TITLE
Feature Request: apoc.coll.combinations()

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j-contrib/neo4j-apoc-procedures#310]
This requests a function apoc.coll.combinations() which takes a collection, and outputs a list of lists of all possible combinations, with combination sizes from `minK` (default 1) to `maxK` (default -1, meaning the size of the input list).

`apoc.coll.combinations([coll], minK :1, maxK:-1) `

**Comment by jexp** [comment]
What would be a use case?

Von meinem iPhone gesendet

**Comment by InverseFalcon** [comment]
A couple SO questions emerged that could be helped by a function like this. [Here's one](http://stackoverflow.com/questions/42699435/group-nodes-based-on-calculation-of-properties). 

The summary on that one is, given a collection of nodes, find all combinations where the sum of some property in the combination is within a set range. 

Combination functions are bound to be expensive on larger sets of nodes, so there is that to watch out for.

Looking at the original proposal, one k may not be enough, it might be better to have a minK and maxK, allowing more flexibility for the types of combinations to return.

It might also be interesting to consider a predicate parameter to evaluate for each k-set of combinations to filter down results within the function, rather than having to return some gigantic list of results and filter in Cypher after the function return.

**Comment by szarnyasg** [comment]
If I understand correctly, for a set `S` with this would return Cartesian products, e.g. with `minK = 2` and `maxK = 4`, it would return `S×S`, `S×S×S` and `S×S×S×S`.

A closely related use case is to calculate the Cartesian product of k given sets: https://stackoverflow.com/questions/41800990/neo4j-cypher-to-get-combinations/41808490#41808490

**Comment by szarnyasg** [comment]
I guess this is closed by #657.
