### ISSUE TITLE
Trigger calls not working

### ISSUE THREAD

**Issue by danielamigos** [neo4j-contrib/neo4j-apoc-procedures#312]
I have been going through the documentation and I believe I have set everything up to get triggers to work but when I try to list or to add them, I get the follow error message: "Failed to invoke procedure `apoc.trigger.list`: Caused by: java.lang.NullPointerException".

Not sure how to fix. Please help!
![neo](https://cloud.githubusercontent.com/assets/13111905/23829105/6aac7e28-06ad-11e7-8b62-e081fa5d5bb9.jpg)

**Comment by danielamigos** [comment]
I am using Neo4j 3.1.1 with apoc-3.1.0.4.jar

**Comment by AngeloBusato** [comment]
Hi @danielamigos, which package are you using? (zip or executable install)
Have you find something on your log file?

**Comment by DanielBerton** [comment]
I think we can close this issue as we confirm that error happens when the apoc jar is not in the right location.
