### ISSUE TITLE
Plugin failed to install. Error: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by liuxiaobei6667** [neo4j-contrib/neo4j-apoc-procedures#3125]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

### Simple Dataset (where it's possibile)

```
//Insert here a set of Cypher statements that helps us to reproduce the problem

```

### Steps (Mandatory)

  1.
  1.
  1.

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS:
  - Neo4j:
  - Neo4j-Apoc:

**Comment by liuxiaobei6667** [comment]
Plugin failed to install. Error: net::ERR_CONNECTION_REFUSED

**Comment by vga91** [comment]
@liuxiaobei6667 
Can you provide other info, such as the Apoc and neo4j version, steps to reproduce the error and the `neo4j.log` file?
