### ISSUE TITLE
apoc.periodic.repeat() delay bug

### ISSUE THREAD

**Issue by tomasonjo** [neo4j-contrib/neo4j-apoc-procedures#314]
playing around with apoc.periodic.repeat() and i have notice that the delay starts after the query is finished. I think it would be better if cypher query time would be calculated in delay time so we have a uniform scheduled job

**Comment by albertodelazzari** [comment]
@tomasonjo is this issue still opened? Can we move it to the "Done" column?

**Comment by tomasonjo** [comment]
sure, as it is not relevevant... what I actually wanted was periodic scheduling at specific hour...
