### ISSUE TITLE
Add more statistics functions like linear regression

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#316]
Hi @ArslanAle it woudl be great if you could contribute your procedure to APOC. Thanks a lot.

http://stackoverflow.com/questions/41077711/linear-regression-functions-in-cypher

Some more ideas:

1. We could save one property access by using `n.getProperty(key, null)` and check the result for null
2. We should use `Number` as target type for property value and use `number.doubleValue()`
3. for neo4j 3.2 we could use a user defined aggregation function to pass in the values

**Comment by conker84** [comment]
closed via 31e28ca
