### ISSUE TITLE
while using  CALL apoc.export.json.all("/home/anushka/Desktop/cpg-codes/file.json") getting Neo.ClientError.Procedure.ProcedureCallFailed Failed to invoke procedure `apoc.export.json.all`: Caused by: java.lang.ClassNotFoundException: org.neo4j.graphdb.TransactionGuardException

### ISSUE THREAD

**Issue by anushka192001** [neo4j-contrib/neo4j-apoc-procedures#3165]
while using command call apoc.export.json.all() in neo4j browser

getting error
"Failed to invoke procedure apoc.path.subgraphNodes: Caused by: java.lang.ClassNotFoundException: org.neo4j.graphdb.TransactionGuardException"

i already installed this jar file https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/4.1.0.0 in my $NEO4J_HOME/plugins folder in my local machine
and my neo4j desktop version in 1.1.15 and neo4j instance version is 4.4.5

and also changes settings on neo4j desktop to
apoc.import.file.use_neo4j_config=true
apoc.export.file.enabled=true

still not working, i also wrote this issue here https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/3165

**Comment by jexp** [comment]
Hi,
you need to install 4.4.0.9, not 4.1.0.0

https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/tag/4.4.0.9

**Comment by vga91** [comment]
@anushka192001 
Closing this for now, feel free to reopen in case you still have problems with a 4.4.x.x version.
(The latest version is: https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/tag/4.4.0.12)
