### ISSUE TITLE
Improvement: Allow path expander label filters to use multiple operations

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j-contrib/neo4j-apoc-procedures#317]
The available operations when using path expander label filters are: `+`,`-`, `/`, `>`

Currently, only one such operation is allowed in the label filter. This isn't especially clear, as it's easy to interpret some of the syntax as allowing multiple operations.

This requests a change to the label filter to allow up to all operations to be present in the filter. When an operation is specified as the label filter is parsed, it remains the active operation to apply for all subsequent labels until another operation symbol is detected at the start of a label.

However, this does present a challenge for both evaluation precedence (for multi-labeled nodes), and for general interaction between the operations.

Decisions regarding operator interaction:

1. Whitelists (`+`) - Specifically, when no whitelist labels are provided. This is an issue because `-` and `/` and `>` operations had no concept of whitelists, and never had to filter based on them, or their absence. I propose interpreting lack of whitelist labels (empty whitelist) as always allowed, rather than nothing allowed.

2. Termination and end node operators (`/` and `>`) - These operations have a significant effect on the paths returned. They use `EXCLUDE_AND_CONTINUE` for nodes that don't have the associated labels. The only paths returned when these operations are in play are paths with end nodes of the associated labels. I propose that this behavior is kept (docs have been updated to better describe this behavior), but it will affect the outcome of whitelist operations. 

That is, when a node is allowed by the whitelist (either by the whitelist being empty as in above, or when a node's label is in the whitelist), and not present in the blacklist or the include-and-prune list, the behavior must change based on whether or not the `/` and/or `>` operations are in play on certain labels. If so, then allowed nodes through the whitelist must apply an EXCLUDE_AND_CONTINUE evaluation, otherwise they should apply INCLUDE_AND_CONTINUE.

Proposal regarding operator precedence and multi-labeled nodes:

We're evaluating a node that has labels associated with some combination of the operators, instead of just one. What do we do?

I propose the following precedence, defaulting to respecting exclusion first, and inclusion second:

```
- first
/ second
> third
+ fourth
```

According to this proposed precedence, the first operator whose label list includes the label of the evaluated node will handle it accordingly, and no further evaluation will occur.

**Comment by InverseFalcon** [comment]
Feedback and suggestions welcome.

**Comment by jexp** [comment]
@sarmbruster can you have a look.

**Comment by InverseFalcon** [comment]
Updated to include reference to the newly introduced end-node filter `>` in PR #327

**Comment by InverseFalcon** [comment]
Enumerating some of the operator precedence options, and their effect on the graph.

Using the movies graph as the test graph, labeling 'Clint Eastwood' and 'Gene Harris' as :Western.

`MATCH (c:Person) WHERE c.name in ['Clint Eastwood', 'Gene Hackman'] SET c:Western`

This is for the sake of the termination label filter, since there is no path using `:ACTED_IN|:DIRECTED|:PRODUCED` from 'Keanu Reeves' (our start node) to 'Clint Eastwood' except through 'Gene Hackman', so if we used '/Western', we would stop at Gene, and if we used '>Western', we would get both Gene and Clint.

Also using `filterStartNode:false` so we aren't required to add :Person to the whitelist to get results.

**Comment by InverseFalcon** [comment]
Proposed Order 1:
```
- first
/ second
> third
+ fourth
```

Consequences: 

- Blacklist trumps everything. If a label is in the blacklist, it's not going to be in any node of any path returned.
- Termination list stops further expansion, even if the label (or other labels of the node under evaluation) fall under the end node label list or whitelist. `>Western|/Western` will stop at Gene. 
- Termination nodes ignore the whitelist. This means when using whitelist and termination filter together, the whitelist only applies to the nodes in the path up to but not including the end node. `/Western|+Movie` would return a path to Gene, even though :Person isn't in the whitelist.
- End node filter would ignore the whitelist. This is similar to the consequence above with the termination filter, but it also means paths beyond an end node to another end node will be returned even if the first end node in the middle of the path isn't in the whitelist. So `>Western|+Movie` will return a path to Gene, as with the termination filter, but it will also return a path to Clint, where Gene in the path has a label, :Person, not allowed by the whitelist.

The last point is troublesome if we want to make the guarantee that all paths up to (but not including) the end node must be in the whitelist.

We could fix this by checking if the node is in the whitelist before giving our evaluation. `INCLUDE_AND_CONTINUE` as normal if it's in the whitelist, `INCLUDE_AND_PRUNE` if no label of the node is in the whitelist.

**Comment by InverseFalcon** [comment]
Proposed Order 2:
```
- first
/ second
+ third
> fourth
```

Consequences (differences vs proposed order 1): 

- End node filter would respect the whitelist. To be returned as an end node (if not handled by the termination filter), a node's label would have to be in the whitelist. So `>Western|+Movie` won't return any paths, since :Person isn't in the whitelist and Gene is a :Person.

The trouble here is this creates an inconsistency in the handling between the termination filter and the end node filter that I don't think is desirable. One respects the whitelist and the other doesn't.

**Comment by InverseFalcon** [comment]
Proposed Order 3:
```
- first
+ second
/ third
> fourth
```

Consequences (differences vs proposed order 1): 

- Both the termination filter and end node filter would respect the whitelist. To be returned as an end node of a path by either filter, a node's label would have to be in the whitelist. So `>Western|+Movie` and `/Western|+Movie` won't return any paths, since :Person isn't in the whitelist and Gene is a :Person.

This solves the inconsistency from proposed order 2, and ensures that all nodes in the path (including the end node, and excepting the start node if explicitly disabling start node filtering) must be in the whitelist, similar to a `WHERE ALL(n in nodes(path) WHERE n:WhitelistLabel)` clause (or TAIL(nodes(path)) in the case where the start node is not filtered).

**Comment by InverseFalcon** [comment]
I'll stop here because I don't feel other permutations are desirable, but if there's an interest to consider and analyze some of the others, feel free.

**Comment by jexp** [comment]
@InverseFalcon for me Option 1 sounds most sensible with regard to usability.

Perhaps not correctness/formality, but as long as we can still express the more strict requirements, i think it should be good.

**Comment by InverseFalcon** [comment]
Fulfilled.
