### ISSUE TITLE
ArithmeticException calling apoc.schema.nodes

### ISSUE THREAD

**Issue by wdroste** [neo4j-contrib/neo4j-apoc-procedures#3186]
## Expected Behavior (Mandatory)
To present a proper error message or the data.

## Actual Behavior (Mandatory)

Throws ArithmeticException

****@neo4j> CALL apoc.schema.nodes({labels:['DataSet']}) YIELD name, label, properties, status, type;
Failed to invoke procedure `apoc.schema.nodes`: Caused by: java.lang.ArithmeticException: / by zero

## How to Reproduce the Problem

I suspect this because there's a failed index on that label.

### Steps 

This works on labels that do *not* have a failed index, only seems to fail on those that do.

### Versions

  - OS: Linux Ubuntu 20.4
  - Neo4j: 4.4.11
  - Neo4j-Apoc: 4.4.0.3

**Comment by vga91** [comment]
Fixed here: https://github.com/neo4j/apoc/pull/364 and https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3606
