### ISSUE TITLE
apoc.create.clonePathsToVirtual() returns more relationships than it should

### ISSUE THREAD

**Issue by mrksph** [neo4j-contrib/neo4j-apoc-procedures#3187]
Hi,

OS: Windows 10
Neo4j Enterprise Edition: 4.4.10
APOC v4.4.0.9

Using the Neo4j Desktop.

## Expected Behavior (Mandatory)
```
MATCH p=(n:Node{code:"EMIRG"})-[:PARENT*..6]->(v:Node)
RETURN p
```

returns the following graph:

![image](https://user-images.githubusercontent.com/10486135/192509009-c54d42e9-aa4a-430d-8219-60e53cab1c8b.png)

I expect that after running the following query to obtain the same graph, with the same node and relationship count

```
MATCH p=(n:Node{code:"EMIRG"})-[:PARENT*..6]->(v:Node)
WITH collect(p) as p
CALL apoc.create.clonePathsToVirtual(p)
YIELD path
RETURN path
```

## Actual Behavior (Mandatory)

After running the above query, I get the following graph:

![image](https://user-images.githubusercontent.com/10486135/192509868-e7186c3c-3378-4991-929d-97c4c9516985.png)

### Simple Dataset (where it's possible)

```
CREATE (n:Node{code:"EMIRG"}),
		 (n2:Node{code:"F1L3G"}),
		 (n3:Node{code:"F1L4G"}),
		 (n4:Node{code:"38LUG"}),
		 (n5:Node{code:"F1L2G"}),
		 (n6:Node{code:"26LIY"}),
		 (n7:Node{code:"90OHG"}),
		 (n8:Node{code:"E1CXG"}),
		 (n9:Node{code:"EAF1L4"}),
		 (n10:Node{code:"38LU"}),
		 (n11:Node{code:"EAF1L2"}),
		 (n12:Node{code:"MS26LI"}),
		 (n13:Node{code:"90OH"}),
		 (n14:Node{code:"00E1CX"}),
		 (n15:Node{code:"EAF1L3"})
		 CREATE (n)-[:PARENT]->(n2)-[:PARENT]->(n15)
		 CREATE (n)-[:PARENT]->(n3)-[:PARENT]->(n9)
		 CREATE (n)-[:PARENT]->(n4)-[:PARENT]->(n10)
		 CREATE (n)-[:PARENT]->(n5)-[:PARENT]->(n11)
		 CREATE (n)-[:PARENT]->(n5)-[:PARENT]->(n10)
		 CREATE (n)-[:PARENT]->(n6)-[:PARENT]->(n12)
		 CREATE (n)-[:PARENT]->(n7)-[:PARENT]->(n13)
		 CREATE (n)-[:PARENT]->(n8)-[:PARENT]->(n14)
```

### Steps (Mandatory)

  1. Create graph structure
  2. Query the path starting from the root node
  3. Query the path to return a virtual graph
  4. Check that the graph from point nº2 is not the same as nº3

**Comment by mrksph** [comment]
It looks like both `apoc.create.clonePathToVirtual` and` apoc.create.clonePathsToVirtual` uses the same `private method createVirtualPath(Path path);`

The APOC works as expected when the path has a depth of 1. As the depth increases, the relationship from each source node is doubled.

**Comment by vga91** [comment]
Fixed by https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3481 (for 4.4) and https://github.com/neo4j/apoc/pull/328 (for 5.x)
