### ISSUE TITLE
Fingerprinting documentation incorrect

### ISSUE THREAD

**Issue by solter** [neo4j-contrib/neo4j-apoc-procedures#3188]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Expected Behavior (Mandatory)

Documentation for Comparing Graphs/Fingerprinting should align with the actual apoc.hashing functions.

## Actual Behavior (Mandatory)

Documentation for Comparing Graphs/Fingerprinting references the functions `apoc.hashing.graph`, but there is no such problem.

## How to Reproduce the Problem

Look at the v4.4
- [Comapring Graphs / Fingerprinting docs](https://neo4j.com/labs/apoc/4.4/comparing-graphs/fingerprinting/) docs
- [Procedures & Functions / apoc.hashing docs](https://neo4j.com/labs/apoc/4.4/overview/apoc.hashing/) 

### Versions

The [APOC User Guide 4.4](https://neo4j.com/labs/apoc/4.4/)

**Comment by vga91** [comment]
Fixed here for 5.x: https://github.com/neo4j/docs-apoc/pull/117

To be fixed for 4.4 as well
