### ISSUE TITLE
apoc.json.setJsonProperty doesn't exist

### ISSUE THREAD

**Issue by ryguyrg** [neo4j-contrib/neo4j-apoc-procedures#321]
In docs
```
CALL apoc.json.setJsonProperty(node,key,complexValue)
```
Perhaps should be:
```
CALL apoc.convert.setJsonProperty(node,key,complexValue)
```

**Comment by jexp** [comment]
Thanks my bad after a move

We're fixing it by generating these from code during build

Von meinem iPhone gesendet

**Comment by ryguyrg** [comment]
Thanks Michael.  Also can't find the getJsonProperty methods anymore.
