### ISSUE TITLE
Mix-up in apoc.refactor.rename.[label/type] documentation example

### ISSUE THREAD

**Issue by Al3xNov** [neo4j-contrib/neo4j-apoc-procedures#3219]
## Expected Behavior
The example to fit the documentation procedure/function page.

## Actual Behavior
Wrong example on page.

## How to Reproduce the Problem
See example of apoc.refactor.rename.label which changing relationship type.
https://neo4j.com/labs/apoc/4.4/overview/apoc.refactor/apoc.refactor.rename.label/

See example of apoc.refactor.rename.type which changing node label.
https://neo4j.com/labs/apoc/4.4/overview/apoc.refactor/apoc.refactor.rename.type/

### Steps 

  1. Open browser
  1. Follow links above
  1. Scroll down to example

## Screenshots 
![image](https://user-images.githubusercontent.com/69261050/195589050-5a2ef3f9-859b-42bd-b41a-950c1861dfa2.png)
![image](https://user-images.githubusercontent.com/69261050/195589167-680d8623-bac3-4ea3-a31f-ebebe20ca040.png)

## Specifications 
Browser- Chrome, OS- Windows10.

Please swap between the examples :)

**Comment by vga91** [comment]
Fixed here: https://github.com/neo4j/docs-apoc/pull/118/files (5.x) and https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3525 (4.4)
