### ISSUE TITLE
apoc.hashing.fingerprint UnsupportedOperationException: cannot yet deal with [B

### ISSUE THREAD

**Issue by circles-arrows** [neo4j-contrib/neo4j-apoc-procedures#3237]
MATCH (n) RETURN id(n), apoc.hashing.fingerprint(n)

Failed to invoke function `apoc.hashing.fingerprint`: Caused by: java.lang.UnsupportedOperationException: cannot yet deal with [B

The field that makes it fail is of type byte[], when querying the node in the neo4j browser it looks like this:
{
  "identity": [NODE_ID],
  "labels": [
    "[NODE_LABEL]"
  ],
  "properties": {
"Field": {
"0": 6.0,
"1": -80.0,
"2": 16.0,
"3": 0.0,
"4": 31.0,
"5": -117.0,
ETC
    },
  }
}

**Comment by vga91** [comment]
Fixed by https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3480 and https://github.com/neo4j/apoc/pull/332
