### ISSUE TITLE
Bundle apoc-google-cloud-storage-dependencies asset on every release

### ISSUE THREAD

**Issue by ibbn4j** [neo4j-contrib/neo4j-apoc-procedures#3274]
## Feature description (Mandatory)

Currently GCS dependencies is not bundled in released assets. Jar linked from this page https://neo4j.com/labs/apoc/4.4/import/web-apis/#_using_google_cloud_storage is using v3.5. While this current version can be used to understand gs:// protocol but it currently has issue if deployed together with latest Bloom plugins (tested in v2.5.1).

## How this feature can improve the project?

Latest bundled assets should probably works wells with Neo4j Bloom.

**Comment by vga91** [comment]
Fixed here: https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3573 (4.4) and https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3644 (5.x)
