### ISSUE TITLE
add atomic procedures for increment, decrement, etc.

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#332]
that pull a write lock on the node first before reading the property and also handle non-initialized properaties

other ideas:

* add/remove to/from array
* concatenate string
* add/subtract number
* general "compiled-cypher" expression (with optional initializer)

**Comment by inserpio** [comment]
@jexp, let's write down some method signatures for these APOC. @AngeloBusato and @DanielBerton are going to start on it next Monday.

**Comment by jexp** [comment]
procedures should take write lock on node before they read the property

discussion if those procedures should be void (i.e. need no yield) or should return sth e.g. the old, and new values and the node.

call apoc.atomic.add(node/relationship, "property", number) 
call apoc.atomic.concat(node/relationship, "property", "string")
// insert at array position
call apoc.atomic.insert(node/relationship, "property", 0/3/-1, object)
call apoc.atomic.remove(node/relationship, "property", 0/3/-1)
call apoc.atomic.update(node/relationship, "property",  "n.property * 3 + n.property2")
