### ISSUE TITLE
Installing apoc-core causes SLF4J WARN messages in neo4j.log

### ISSUE THREAD

**Issue by tomgeudens** [neo4j-contrib/neo4j-apoc-procedures#3320]
## Expected Behavior (Mandatory)
Suppress WARN messages that put the words "Failed to load" into the neo4j.log when apoc-core is installed.

## Actual Behavior (Mandatory)
Following messages show up in neo4j.log when apoc-core is installed (Neo4j 5.2.0, APOC core 5.2.1)

2022-11-21 18:56:11.834+0000 WARN  SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2022-11-21 18:56:11.835+0000 WARN  SLF4J: Defaulting to no-operation (NOP) logger implementation
2022-11-21 18:56:11.835+0000 WARN  SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

## How to Reproduce the Problem
Just move apoc-core into Neo4j plugins folder and start Neo4j ... then check neo4j.log

### Simple Dataset (where it's possibile)
/

### Steps (Mandatory)
Just move apoc-core into Neo4j plugins folder and start Neo4j ... then check neo4j.log

## Screenshots (where it's possibile)
See above logings

## Specifications (Mandatory)
/

### Versions
  - OS: Linux
  - Neo4j: 5.1.0, 5.2.0
  - Neo4j-Apoc: 5.1.0, 5.2.1

**Comment by vga91** [comment]
Fixed here: https://github.com/neo4j/apoc/pull/274
