### ISSUE TITLE
make sure that manual index operations are read-only

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#334]
create methods in Util.java that use kernel API to access the legacy indexes in read-only transactions for only query procedures.

so there is no need to call  `db.index().forNodes() or forRelationships()`

especially important for running them in a cluster

**Comment by DanielBerton** [comment]
Hi @jexp we added a method in `Util` class to access the legacy index in read-only, but we have two different return type, for example in the class `FreeTextSearch` in the `search` method we could replace :

``` 
return result(db.index().forNodes(index).query(
                new QueryContext(parseFreeTextQuery(query)).sort(Sort.RELEVANCE).top(100)));
``` 
with:

``` 
return  ((GraphDatabaseAPI)db)
                .getDependencyResolver()
                .resolveDependency(ThreadToStatementContextBridge.class).get()
                .readOperations()..nodeLegacyIndexQuery(indexName, new QueryContext(parseFreeTextQuery(query)).sort(Sort.RELEVANCE).top(100)));
``` 
the method call will be: 
``` 
return result(Util.queryIndex(index, new QueryContext(parseFreeTextQuery(query)).sort(Sort.RELEVANCE).top(100)), db);
``` 
In the first case we have an `IndexHits` (graphdb index) as return type, in the second case a `LegacyIndexHits` (kernel API)

We have to adapt the code and work with `LegacyIndexHits`? Or we try to find another way?

**Comment by inserpio** [comment]
Let's implement a transformer from `LegacyIndexHits` to `IndexHits`, like this one:
- https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/3.1/src/main/java/apoc/index/FulltextIndex.java#L115
- https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/3.1/src/main/java/apoc/index/FulltextIndex.java#L122
