### ISSUE TITLE
Update neo4j from 4.4.3 to 5.3.0

### ISSUE THREAD

**Issue by Maheshjayachandran** [neo4j-contrib/neo4j-apoc-procedures#3385]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Expected Behavior (Mandatory)
Facing issue when we update neo4j version from 4.3.0 to 5.3.0

## Actual Behavior (Mandatory)
Version update should happen currently

### Simple Dataset (where it's possibile)

```
//Insert here a set of Cypher statements that helps us to reproduce the problem
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
Defaulted container "mahesh-test-mdm" out of: mahesh-test-mdm, databackup-init (init)
NEO4JLABS_PLUGINS has been renamed to NEO4J_PLUGINS since Neo4j 5.0.0.
The old name will still work, but is likely to be deprecated in future releases.
Installing Plugin 'apoc' from /var/lib/neo4j/labs/apoc-*-core.jar to /var/lib/neo4j/plugins/apoc.jar
Applying default values for plugin apoc to neo4j.conf
Failed to read config: Unrecognized setting. No declared setting with name: apoc.export.file.enabled. Cleanup the config or disable 'server.config.strict_validation.enabled' to continue.
Run with '--verbose' for a more detailed error message.
```

### Steps (Mandatory)

  1.
  1.
  1.

## Specifications (Mandatory)

Currently used versions
updating from 4.3.3 to 5.3.0
### Versions

  - OS:
  - Neo4j:
  - Neo4j-Apoc:

**Comment by nadja-muller** [comment]
Hi. 
Could you try to move the apo specific config values into a dedicated apoc.conf file?
Let us know if that solves your problem.

**Comment by jexp** [comment]
https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3374

**Comment by nadja-muller** [comment]
Feel free to reopen this issue if it is still a problem.
