### ISSUE TITLE
Problem in updating a custom procedure in causal cluster

### ISSUE THREAD

**Issue by aleferr-97** [neo4j-contrib/neo4j-apoc-procedures#3401]
## Expected Behavior (Mandatory)
Successfully replace an older version of a custom procedure after the deletion and new subscription
## Actual Behavior (Mandatory)
Even if the procedure has been removed and registered again (and also the cache has been cleared), when I try to call the custom procedure, the old one is called instead of the new one
### Simple Dataset (where it's possibile)
```
CALL apoc.custom.asProcedure('TrialProcedure','MTCH (n) RETURN count(n) as element','read',[['element','NUMBER']],[['id','NUMBER']])
CALL custom.TrialProcedure(1)  yield element RETURN *
CALL apoc.custom.removeProcedure("TrialProcedure")
CALL apoc.custom.asProcedure('TrialProcedure','MATCH (n) RETURN count(n) as element','read',[['element','NUMBER']],[['id','NUMBER']])
CALL custom.TrialProcedure(1)  yield element RETURN *

```

### Steps (Mandatory)

  1. Register the wrong procedure
  2.  Call it
  3.  Remove the old procedure
  4.  Edit the procedure and register it again
  5.  Call the procedure again

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: Linux
  - Neo4j: 4.4.4
  - Neo4j-Apoc: 4.4.0.1

**Comment by jexp** [comment]
Did you try to call clear caches as indicated in the docs on all cluster members?

**Comment by aleferr-97** [comment]
Yes already tried, but it didn't work
