### ISSUE TITLE
Can't use apoc.create.* on fresh install of neo4j 5

### ISSUE THREAD

**Issue by rogelio-basurto** [neo4j-contrib/neo4j-apoc-procedures#3402]
## Expected Behavior (Mandatory)
I installed the neo4j 5.3 with apoc extended 5.3.0
Out of the box, with no configuration, I should be able to use "CALL apoc.create.setProperty() " in Neo4j Browser. As I passed the function with no values, it should direct me with the missing parameters so I fix it. 

## Actual Behavior (Mandatory)
It says the function can not be found. It gives me the error:
```
Neo.ClientError.Procedure.ProcedureNotFound
There is no procedure with the name `apoc.create.setProperty` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.
```

## How to Reproduce the Problem
Fresh install of neo4j 5.3 with apoc 5.3 and call the function on the browser. 
### Simple Dataset (where it's possible)

```
call apoc.create.setProperty()
```

### Steps (Mandatory)

  1. Install neo4j 5 server
  1. Download apoc-extended
  1. Start neo4j
  1. Open neo4j Browser
  1. Execute "call apoc.create.setProperty()"

## Screenshots (where it's possibile)
![image](https://user-images.githubusercontent.com/77854803/212209113-1713580c-6a18-4948-8450-874b14957164.png)

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: CentOS Stream Release 8
  - Neo4j: 5.3.0
  - Neo4j-Apoc: 5.3.0

**Comment by nadja-muller** [comment]
Hi.
Is it correct that you only installed apoc-extended? The procedures that you want to use are in apoc core, see:
* repository: https://github.com/neo4j/apoc
* documentation: https://neo4j.com/docs/apoc/current/overview/apoc.create/
Could you double check and see if installing apco core solves your issue?

**Comment by rogelio-basurto** [comment]
Oh boy. 

Yes, using only apoc-core it works. I had the idea that the apoc-extended was like the apoc-full in previous versions. How can I configure Neo4j to use both of them? I did search the neo4j manual and probably miss it.

**Comment by nadja-muller** [comment]
Ah, I see. 
In the 5.x releases, apoc core and apoc extended are separate procedure bundles, and can be both used separately without overlap. Together they would make up what was apoc full in the 4.x releases. The only thing you need to do to use them both is to add the jars in the plugin folder (and restart the dbms).
