### ISSUE TITLE
Give clear indication if neo4j 4.4.16 (newest) is supported?

### ISSUE THREAD

**Issue by jkrauska** [neo4j-contrib/neo4j-apoc-procedures#3411]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests. If you have questions on how to use APOC, please ask on [the Neo4j Discussion Forum](https://community.neo4j.com/c/neo4j-graph-platform/procedures-apoc) instead of creating an issue here.

## Expected Behavior (Mandatory)

README says 4.4.0.12 apoc release is related to 4.4.0 release, but unclear if this also supports later 4.4.X releases.

neo4j 4.4.16 was released in Dec 2022, but it's unclear about corresponding apoc support.

## Actual Behavior (Mandatory)

Only shows 4.4.0.12 as current tag for apoc.

## How to Reproduce the Problem

Review current tags in github.

### Simple Dataset (where it's possibile)

```
//Insert here a set of Cypher statements that helps us to reproduce the problem

```

### Steps (Mandatory)

  1.
  1.
  1.

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS:
  - Neo4j:
  - Neo4j-Apoc:

**Comment by gem-neo4j** [comment]
Hi! Thanks for writing in, I'll get the README updated at some point to make it clearer, for now, you can always check our versions.json file [here](https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/master/versions.json) to see compatible versions, in that list you can see "neo4j": "4.4.16" is compatible with "apoc": "4.4.0.12" :) Hope this helps!
