### ISSUE TITLE
add IP whitelist checking also to apoc.spatial.geoCode with custom provider config

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#3416]
like for the other http loading procedures

**Comment by jexp** [comment]
https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/2467

https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3116

**Comment by vga91** [comment]
Fixed by https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3451 and https://github.com/neo4j/apoc/pull/305
