### ISSUE TITLE
apoc.text.slug

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#343]
From: https://github.com/neo4j/neo4j/issues/9090

I want to get an result by word (This is a word) that was in the url of my webpage, www.example.com?q=this-is-a-word.

This is what i use on this moment;

```
MATCH (region:TS_P2000Region)
WHERE replace(replace(region.name,' ','-'),'--','-') =~ 'this-is-a-word'
RETURN region
```

Maybe it is an idea that there is some slug function?

```
MATCH (region:TS_P2000Region)
WHERE apoc.text.slug(region.name,'-'), =~ 'this-is-a-word'
RETURN region
```

the delimiter parameter should be optional and default to `-`

**Comment by tomswinkels** [comment]
I found one problem, the slug must be always set to lowercase. Now i must do `toLower(apoc.text.slug(n.name))`
