### ISSUE TITLE
apoc.load.json not in the list of procedures (neo4j 5.4.0, apoc 5.4.0), though other loaders are

### ISSUE THREAD

**Issue by kroham** [neo4j-contrib/neo4j-apoc-procedures#3458]
Hello,
I am using neo4j 5.4 with apoc 5.4 extended plugin, I do not have apoc.load.json in the list of available procedures, though other loaders (like load.html, load.jdbc, load.csv) are there and work fine. Is it normal or am I doing something wrong? the apoc.help() procedure is also missing..
I updated from previous versions (neo4j 4.3.15, apoc 4.3.06) where I did not have this issue with apoc.load.json. The setup/conf is the same. I tested a local installation and a docker, having the same issue in both for these versions.

## Expected Behavior (Mandatory)
apoc.load.json in the list of available procedures.

## Actual Behavior (Mandatory)
apoc.load.csv, apoc.load.html, etc are there and work fine, but not apoc.load.json

### Versions

  - OS: Ubuntu 22
  - Neo4j: 5.4.0
  - Neo4j-Apoc: 5.4.0
  - 
Thanks in advance
EDIT: found the information in another issue that apoc core is packaged with neo4j 5 releases. Mine does not seem to contain the core procedures. Or if it does, how do I access them?

**Comment by gem-neo4j** [comment]
Hi there!
As of 5.x, APOC got split more officially into APOC core and APOC extended. As you mentioned in your edit, the procedure you are wanting is indeed in core, the other ones belong in APOC extended.

When we say APOC core is packed with Neo4j, it means it is bundled, but not loaded. You need to still install it as a plugin to get it to work.

I am not sure exactly how you are setting up your system, so here are some options:
* Download [APOC core](https://github.com/neo4j/apoc/releases/tag/5.4.1) and install just as you did APOC extended
* Copy the jar from the labs folder of your Neo4j installation ($NEO4J_HOME/labs) into your plugins folder

Here are the [docs](https://neo4j.com/docs/apoc/current/installation/) for core! Hope this helped :) After you have installed it, apoc.help will also be available!
