### ISSUE TITLE
apoc-extended 5.6.0 is not available at https://mvnrepository.com/

### ISSUE THREAD

**Issue by klobuczek** [neo4j-contrib/neo4j-apoc-procedures#3498]

**Comment by Lojjs** [comment]
@klobuczek There was a bit of a delay in this release compared with Neo4j 5.6, but apoc-extended 5.6.0 is now available here: https://mvnrepository.com/artifact/org.neo4j.procedure/apoc-extended 

Best regards Louise, Neo4j
