### ISSUE TITLE
go over all procedures / functions that use restricted APIs and check if we really need them

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#353]
● GraphDatabaseAPI
● KernelTransaction
● DependencyResolver
● UserManager
● EnterpriseAuthManager 
● SecurityLog

replace if possible with

● Log
● TerminationGuard
● GraphDatabaseService (​This now allows creation of new Transactions in new Threads)
● SecurityContext
● ProcedureTransaction

**Comment by inserpio** [comment]
Target version is 3.2

**Comment by inserpio** [comment]
Create a new KernelApi class encapsulting access to Kernel classes

**Comment by jexp** [comment]
Aquiring:
- graph properties
- KernelTX
- Statement
- [Read/Write/TokenWrite]Operations
- TerminationGuard

Possibly move some methods from Util to KernelAPI
