### ISSUE TITLE
Connect mongo to neo4j using apoc

### ISSUE THREAD

**Issue by Assiam** [neo4j-contrib/neo4j-apoc-procedures#355]
I'm trying to connect neo4j to mongodb to retrieve some information. When I use this query:
```CALL apoc.mongodb.first('mongodb://localhost:27017','test','airport',{code:'JFK'}) yield value``` 
then I got this error :
```Unpackable value 51dc2f7bb6e4ab4eb769df93 of type org.bson.types.ObjectId``` 

I'm using mongodb v3.2.4 so I added jars v3.2.2

![image](https://cloud.githubusercontent.com/assets/11077968/24500599/57d148ea-1546-11e7-93cf-fafaf2411d39.png)

Thank you

**Comment by albertodelazzari** [comment]
I think the issue is related to the ObjectId itself. The Neo4jPacker can't handle an object of this type because is not a "native" type so it should be converted to a simple String. I'm working on it.

**Comment by Assiam** [comment]
Thank you for your work.

**Comment by jexp** [comment]
We would have to convert types eg to primitive/strings

Von meinem iPhone gesendet
