### ISSUE TITLE
The apoc.import.json constraint check should work only when a unique constraint exists

### ISSUE THREAD

**Issue by ToucanBran** [neo4j-contrib/neo4j-apoc-procedures#3609]
## Expected Behavior (Mandatory)
Json import successfully imports

## Actual Behavior (Mandatory)
Getting a missing constraint error for every node type

## How to Reproduce the Problem

This is the same issue reference in #2930 . According to PR #3099 , this should be fixed in release 5.8.0, however I confirmed it's still not fixed even in that release. 

### Simple Dataset (where it's possibile)
You can use https://raw.githubusercontent.com/cj2001/nodes2021_kg_workshop/main/json_files/wiki.json

### Steps (Mandatory)

  1. Open neo4j desktop and create a new database, set to version 5.8.0
  1. Install the APOC library
  1. Start the DB and use the given query 
```
CALL apoc.import.json('https://raw.githubusercontent.com/cj2001/nodes2021_kg_workshop/main/json_files/wiki.json')
```
You should see the error given in the screenshot below. When I add the constraint, it works.
## Screenshots (where it's possibile)

![image](https://github.com/neo4j-contrib/neo4j-apoc-procedures/assets/19380503/5014e23c-e44b-4a0b-9d30-93868ff83c0f)

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: Windows 10
  - Neo4j: 5.8.0
  - Neo4j-Apoc: 5.8.0

**Comment by gem-neo4j** [comment]
Hi! I am not sure I am understanding, but this is correct behaviour. You need a unique constraint for it to work. The error you linked to was about the procedure working when any constraint was added (e.g a not null constraint) instead of the specific uniqueness one.

**Comment by ToucanBran** [comment]
@gem-neo4j Hmm... I was following the example shown [here](https://www.youtube.com/watch?v=XaoF43cFCFQ). I know the presenter is using an older version of neo4j (which I confirmed still works) but this behavior would be ideal. 

Here's my use case:

We have a neo4j instance running for our CI/CD pipeline to run integration tests on. When a branch triggers a pipeline:
- a new database is created on that server
- the json which contains specific data for testing is loaded into that database based on the current test data that's loaded for master
- other cypher scripts are run which may modify the graph based on the branch updates
- integration tests are run

If everything passes:
- A call to apoc.export.json.all is called
- This file is pushed to s3 which overwrites the current test data json mentioned earlier
- branch is merged into master

Having to create these uniqueness constraints anytime we want to load in data from a file that apoc output in the first place seems a little odd to me. If that's the intended behavior though, maybe I'm going about this the wrong way?

**Comment by gem-neo4j** [comment]
Hi again :)

I looked a bit more into this, so you're correct that this was not always the case, but it was introduced about a year and a half ago to the procedure (and unfortunately not well documented, hence the confusion!).

If we don't have these constraints, the import will take forever (as it will do a full label scan for each node imported with the generic constraint).

This procedure is not marked as a schema operations procedure, so is not able to make the constraints itself.

I'll create a ticket for my team to improve the documentation around this!

Is is possible for your application to know the names of the labels prior and create those constraints, using perhaps apoc.schema.assert?

**Comment by ToucanBran** [comment]
Unfortunately, no. Is there a way to generate these constraints using apoc
or some other function?

**Comment by ToucanBran** [comment]
I think im just going to suggest we stand up a local instance and restore
from a backup file. Feel free to close this issue since the constraint
error is intended.

**Comment by gem-neo4j** [comment]
Okay, thank you. Sorry I couldn't help more!
