### ISSUE TITLE
Feature question: Should 'minLevel' be allowed on spanningTree(), subgraphNodes() and subgraphAll()?

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j-contrib/neo4j-apoc-procedures#365]
When I implemented these procedures, I left `minLevel` out of the config params, since this produces some unintuitive behavior for users not familiar with `NODE_GLOBAL` uniqueness. 

All three procedures use hard-coded `NODE_GLOBAL` uniqueness. However, that changes the meaning of what `minLevel` does. 

Since nodes will never be visited twice, this means that when `minLevel` is present (such as when using `expandConfig()` with `NODE_GLOBAL` uniqueness and `minLevel`), the paths returned are only those that are above `minLevel`, but not those reachable at levels closer than `minLevel`.  If there are multiple paths to the same node, one with length 2 and several that are longer in length (using paths that adhere to the relationship and label filters), then the node will never be returned if the `minLevel` is above 2, as it's already been visited and won't be visited again.

I'm wondering if this decision was too conservative, and if it should be added back in with appropriate explanation in the documentation, or if the behavior is different enough that it should continue to be excluded by these procedures to avoid confusion.

And of course there may be some confusion already, for those who expect `minLevel` to be available, but don't realize that passing it has no effect on the results.

Suggestions welcome.

**Comment by InverseFalcon** [comment]
@jexp and/or @sarmbruster, would you mind giving this a lookover?

**Comment by jexp** [comment]
@InverseFalcon good question, I'm not 100% sure what the best approach is that satisfies the constraint and still returns sensible results for the node-global setting.

Probably it makes sense to add it back and document it.

**Comment by conker84** [comment]
Looking at the code (and docs) we have the `minLevel` back
