### ISSUE TITLE
removing properties causes index tracking to fail

### ISSUE THREAD

**Issue by sarmbruster** [neo4j-contrib/neo4j-apoc-procedures#367]
this is another subticket of #329 

description is at https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/329#issuecomment-291012510

**Comment by sarmbruster** [comment]
@igorclark: sorry for the long silence on my side. I've pushed a small changed that should fix the issues upon removing properties to a branch, see above. Feedback appreciated.

**Comment by igorclark** [comment]
Hi @sarmbruster! Wonderful, thanks for letting me know - got a lot on here too but will definitely look at this over the next few days and post some feedback. Cheers!

**Comment by igorclark** [comment]
Hi @sarmbruster, my turn to apologise for long delay. Finally got round to testing - partly waiting for everything to get merged and then for `3.1.3.7` binary release to happen. Now that's all in place, removing the properties seems to work fine in `neo4j 3.1.4` and `apoc-3.1.3.7-all.jar`. Thanks!

**Comment by jexp** [comment]
@sarmbruster ping?
