### ISSUE TITLE
Replacement for apoc-4.x-all.jar in v5.x? FYI, this jar is present in Neo4j repository/plugins.

### ISSUE THREAD

**Issue by Kaivalya31** [neo4j-contrib/neo4j-apoc-procedures#3698]
Replacement for apoc-4.x-all.jar in v5.x? FYI, this jar is present in Neo4j repository/plugins.

**Comment by Lojjs** [comment]
@Kaivalya31 The way APOC is packaged has been changed between Neo4j 4 and 5, from core + full (which included both core and extended), to separate packages for core and extended. This blog post is describing the details: https://towardsdatascience.com/what-happened-with-apoc-in-neo4j-v5-core-and-extended-edition-23994cdf0a2c

Please give it a read and comment back if that helps or if you need further assistance.

Best regards Louise, Neo4j

**Comment by Kaivalya31** [comment]
@Lojjs I tried what is suggested in the article but the Neo4j repository is still not starting and I get this error in neo4j-output.log - 'ERROR StatusConsoleListener Reconfiguration failed: No configuration found for '659e0bfd' at 'null' in 'null'
PM org.apache.commons.beanutils.FluentPropertyBeanIntrospector introspect
INFO: Error when creating PropertyDescriptor for public final void org.apache.commons.configuration2.AbstractConfiguration.setProperty(java.lang.String,java.lang.Object)! Ignoring this property.
'

**Comment by ncordon** [comment]
Hey @Kaivalya31, could you please give us more information on what versions of neo4j and apoc are you using? Normally apoc 5.x is only compatible with the same minor version of neo4j 5. [Here](https://neo4j.github.io/apoc/versions.json)'s is a matrix of compatibility, for reference.

This starts okay for me:
```
docker run --restart always --publish=7474:7474 --publish=7687:7687  --env NEO4J_PLUGINS='["apoc"]' \
--env NEO4J_dbms_security_procedures_unrestricted=apoc.\\\* \
neo4j:5.10.0-community
```

**Comment by vga91** [comment]
@Kaivalya31 

Closed for lack of feedback, feel free to reopen in case you still have problems
