### ISSUE TITLE
Link to Version 5.11 is invalid.

### ISSUE THREAD

**Issue by SinaZK** [neo4j-contrib/neo4j-apoc-procedures#3742]
Can't find the 5.11 version in release page and the [link for 5.11](https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/5.11.0) is invalid. Please fix the 5.11 download link.

**Comment by Lojjs** [comment]
APOC extended is not officially supported by Neo4j, but is a lab-project driven on best effort by individuals. Version 5.11 has not yet been released. When it is, it will turn up on the release page and that link.

In case you were looking for the 5.11 release for APOC core, it can be found here: https://github.com/neo4j/apoc/releases/5.11.0

Best regards Louise, Neo4j Cypher team
