### ISSUE TITLE
Remove APOC Core procedures from `TTLLifeCycle.java`

### ISSUE THREAD

**Issue by vga91** [neo4j-contrib/neo4j-apoc-procedures#3777]
The `apoc.ttl.*` procedures use under the hood the apoc.periodic.iterate and the apoc.schema.assert.

See [here](https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/dev/extended/src/main/java/apoc/ttl/TTLLifeCycle.java#L60) and [here](https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/dev/extended/src/main/java/apoc/ttl/TTLLifeCycle.java#L82).

These can cause [(bad timing?) errors](https://neo4j.slack.com/archives/C136J23GE/p1695121535350629) and require APOC Core.

In any case, they are not necessary as they can be replaced by Cypher as well, i.e.:
- `(LIMIT $batchSize (DETACH) DELETE n)` instead of apoc.periodic.iterate
- `CREATE INDEX ... IF NOT EXISTS` instead of apoc.schema.assert

**Comment by martinmiglio** [comment]
Is this issue progressing? 
I am experiencing this with `neo4j:5.13` docker image, with `apoc-5.13.0-extended`.
