### ISSUE TITLE
Release 5.12.0 availability

### ISSUE THREAD

**Issue by AdrianDutu** [neo4j-contrib/neo4j-apoc-procedures#3782]
Hello,

We are heavily depending on the apoc-extended procedures and also are looking into upgrading from v4 to v5. 
I see neo4j and apoc-core released versions 5.12.0 while for extended i only see 5.11.0 as the latest release.

Is the 5.12.0 still being worked on? Is there an ETA for it?

I tried building from source but getting: Task 'publish' not found in project ':core'.

**Comment by Lojjs** [comment]
While APOC Core is supported by Neo4j engineering, APOC extended is a Labs project dependent on individual developers and contributors. We have some people within the organization doing some best effort maintenance. There is no official ETA, but in general apoc-extended is release within 1-2 weeks after the corresponding Neo4j release
