### ISSUE TITLE
utf-8 problem in geocoding

### ISSUE THREAD

**Issue by Elektra58** [neo4j-contrib/neo4j-apoc-procedures#38]
In many countries, addresses have umlauts 
```
CALL apoc.spatial.geocode('Rämistrasse 71 8006 Zürich Switzerland', 1) YIELD location, latitude, longitude, description
```
yields
```
Failed to invoke procedure `apoc.spatial.geocode`: Caused by: java.lang.RuntimeException: Can't read url http://nominatim.openstreetmap.org/search.php?q=R%E4mistrasse+71+8006+Z%FCrich+Switzerland&format=json as json
```

**Utf-encoding** the characters in the query works:
```
CALL apoc.spatial.geocode('R%C3%A4mistrasse 71 8006 Z%C3%BCrich Switzerland', 1) YIELD location, latitude, longitude, description
```
yields
```
(no rows)
```

Would it not be nice to have utf encoding directly in the stored procedures or explicitly delegate it to the user? Thank you!

**Comment by jexp** [comment]
Can you try with a build from source? @craigtaverner has fixed something around that after our 1.0 release.

**Comment by Elektra58** [comment]
Just built from source yesterday

**Comment by Elektra58** [comment]
It might have to do with the single parameter encoder of URLEncode being deprecated （line 159 in Geocode.java).
```java
String url = "http://nominatim.openstreetmap.org/search.php?q=" + URLEncoder.encode(address) + "&format=json";
```

Using 
```java
URLEncoder.encode(address, java.nio.charset.StandardCharsets.UTF_8.toString())
```
or simply
```java
URLEncoder.encode(address, "UTF-8")
```
might do.

**Comment by sarmbruster** [comment]
not sure if that's relevant here, but I've added procedures for urlencode/decode a few days ago in #32

**Comment by craigtaverner** [comment]
I see Stefans code passes "UTF-8" to the second param. So this is basically equivalent to @Elektra58 suggestion. I did not pick an encoder for the geocode work because I thought that not doing so we get a sensible system default, but clearly not. I vote with use @Elektra58 suggestion.

**Comment by craigtaverner** [comment]
Running the existing code on that same address that @Elektra58 used to test, works fine on the mac. I'm assuming the issue here is that he is running on Windows, and a different default codec is assumed.

@Elektra58 Can you confirm you are using windows or using a system with a different default string encoding?

We should choose between:
1- hard code to UTF-8 as Stefan and @Elektra58 suggest
2- make the coded configurable

**Comment by craigtaverner** [comment]
Added a fix at https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/40

This defaults the encoding to UTF-8 and allows configuration to override that. Still not sure this is better than relying on the OS to get it right, but hopefully...

**Comment by Elektra58** [comment]
Yes, confirm Windows 10. Thx for the quick fix. 
I thought because encode(address) with a single parameter is deprecated, you might want to consider specifying UTF-8 as the second parameter like encode(address, "UTF-8")

**Comment by Elektra58** [comment]
Wow! After rebuilding from source, it works beautifully:
```java
latitude	47.374782
longitude	8.54833389838694
description	Universität Zürich, 71, Rämistrasse, Hochschulen, Altstadt, Zürich, Bezirk Zürich, Zürich, 8006, Schweiz, Suisse, Svizzera, Svizra
```
Thank you so much for fixing this so quickly!

**Comment by craigtaverner** [comment]
Our pleasure!
