### ISSUE TITLE
Version mismatch with latest release

### ISSUE THREAD

**Issue by d4v3y0rk** [neo4j-contrib/neo4j-apoc-procedures#3805]
## Expected Behavior (Mandatory)
I am looking for the latest release version to match the latest release of neo4j in dockerhub. On the release page in github for "latest" I see that the latest release is 5.12.0 in the changelog for the release I also see this line:
Bump version 5.13.0 (https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3456) (https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3536) (https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3658) by @vga91 in https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3769

I expect that the version of the release would match the version release for neo4j (which it looks like from that changelog entry is also the expected functionality) but it does not appear that the version of the release is correct. 

## Actual Behavior (Mandatory)
The actual behavior is that the release has a version number that does not appear to match the version in the changelog or the latest version of neo4j. 

## How to Reproduce the Problem
I assume there was some breakdown in the CI/CD and the versioning. 

### Steps (Mandatory)

  1. View the latest release page and read the changelog

## Screenshots (where it's possibile)
<img width="1177" alt="image" src="https://github.com/neo4j-contrib/neo4j-apoc-procedures/assets/651069/d09993f7-0845-426a-bb72-f7a06f61f529">

## Specifications (Mandatory)
apoc version 5.12.0 neo4j version 5.13 (latest release)

Currently used versions

### Versions

  - OS: ubuntu 22.04
  - Neo4j: 5.13.0
  - Neo4j-Apoc: 5.12.0

**Comment by gem-neo4j** [comment]
Hi! Neo4j version 5.13 was just released yesterday and APOC Extended has not yet released its 5.13. This is confusing looking, but a little further down you will see 'Release 5.12' where the versions were fixed up! This was just a small hiccup, but the released version was 5.12 in the end :)

5.13 will be released on Extended as soon as possible I imagine! :D

**Comment by gem-neo4j** [comment]
Hi! Neo4j version 5.13 was just released yesterday and APOC Extended has not yet released its 5.13. This is confusing looking, but a little further down you will see 'Release 5.12' where the versions were fixed up! This was just a small hiccup, but the released version was 5.12 in the end :)

5.13 will be released on Extended as soon as possible I imagine! :D
