### ISSUE TITLE
Enhance ml vertex ai doc to show how to override the default region

### ISSUE THREAD

**Issue by davidlrosenblum** [neo4j-contrib/neo4j-apoc-procedures#3834]
## Feature description (Mandatory)
Add text to describe where to discover where GCP regions are
Add the configuration map that demonstrates the map

## Considered alternatives
I considered asking for a code change to remove the default of region.

## How this feature can improve the project?
Putting this in will reduce requests such has Why am I running out of quota.  How do I change the processing region of the request

**Comment by vga91** [comment]
Fixed [here](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3835/files)
