### ISSUE TITLE
UUID handler throws warnings when deleting nodes

### ISSUE THREAD

**Issue by AndreiStefanie** [neo4j-contrib/neo4j-apoc-procedures#3840]
Warnings are logged whenever nodes are deleted and there is at least one UUID handler installed. This leads to a substantial number of logs for any meaningful workload since a log entry is added for every node being deleted **and** for every UUID handler.

This issue does not seem to happen on 4.4, but I couldn't figure out why.

## Expected Behavior (Mandatory)
No warnings.

## Actual Behavior (Mandatory)
![image](https://github.com/neo4j-contrib/neo4j-apoc-procedures/assets/10050944/2f42ffa3-66f1-453a-8531-0abe310575c4)

### Steps (Mandatory)

  1. Setup at least one UUID handler `USE system CALL apoc.uuid.setup("LabelOne", "neo4j", {addToExistingNodes: false})`
  1. Create a node `CREATE (:LabelOne {name: "test"})`
  1. Delete the node `MATCH (n:LabelOne) DETACH DELETE n`

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: any OS
  - Neo4j: 5.13.0
  - Neo4j-Apoc: 5.13.0

## Proposed solution

It seems that APOC tries to restore the UUID property on deleted nodes. This happens because the [`removedNodeProperties`](https://github.com/neo4j/neo4j/blob/5.13/community/graphdb-api/src/main/java/org/neo4j/graphdb/event/TransactionData.java#L86) method also returns all properties for nodes being deleted in the current transaction.

Perhaps the simplest solution would be to skip checking the properties of deleted nodes. In [UuidHandler.java](https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/5.13/extended/src/main/java/apoc/uuid/UuidHandler.java#L140)

```java
-        Iterable<PropertyEntry<Node>> removedNodeProperties = txData.removedNodeProperties();
+        ArrayList<PropertyEntry<Node>> removedNodeProperties = new ArrayList<>();
+
+        // Filter out deleted nodes
+        for (PropertyEntry<Node> rnp : txData.removedNodeProperties()) {
+            boolean nodeDeleted = false;
+            for (Node n : txData.deletedNodes()) {
+                if (n.getElementId().equals(rnp.entity().getElementId())) {
+                    nodeDeleted = true;
+                    break;
+                }
+            }
+
+            if (nodeDeleted) {
+                continue;
+            }
+
+            removedNodeProperties.add(rnp);
+        }
```

I cannot guarantee this change fixes the issue or that it addresses the root cause - I haven't worked with the Java ecosystem in the past few years and running the project is not feasible for me.

Thank you!

**Comment by vga91** [comment]
Fixed [here](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/4023). Will be released for 5.19.0
