### ISSUE TITLE
Deprecate mapParallel procedure and update docs

### ISSUE THREAD

**Issue by conker84** [neo4j-contrib/neo4j-apoc-procedures#3843]
Deprecate the procs and update the docs by explaining how to move to the Parallel runtime

**Comment by alexanoid** [comment]
Please do not delete apoc.cypher.mapParallel2 because at the moment, the new PARALLEL runtime cannot fully replace it. Details https://stackoverflow.com/questions/77509091/neo4j-parallel-runtime-query-returns-different-result

**Comment by alexanoid** [comment]
For example I'm unable to port my query which is based right now on `apoc.cypher.mapParallel2` to PARALLEL runtime https://stackoverflow.com/questions/77814894/neo4j-on-parallel-runtime-returns-different-results-different-elements-order-c

**Comment by alexanoid** [comment]
Additionally, with the help of `apoc.cypher.mapParallel2`, I can parallelize only a specific part of the query, a feature not achievable with the PARALLEL runtime.
