### ISSUE TITLE
Missing release for neo4j 4.3.24

### ISSUE THREAD

**Issue by EqualMarcus** [neo4j-contrib/neo4j-apoc-procedures#3865]
## Expected Behavior (Mandatory)

4.3.24 exists on
https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json

## Actual Behavior (Mandatory)

4.3.24 does not exist on
https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json

## How to Reproduce the Problem

Look at
https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json

### Steps (Mandatory)

  1. Go to https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json
  2. See Neo4j 4.3.24 missing from list
  3. Know that Neo4j released 4.3.24

## Specifications (Mandatory)

Currently used versions: 4.3.24

**Comment by Lojjs** [comment]
@EqualMarcus As far as I can see 4.3.24 is in the provided link in this entry

 ```
   {
        "neo4j": "4.3.24",
        "neo4jVersion": "4.3.24",
        "apoc": "4.3.0.12",
        "version": "4.3.0.12",
        "url": "http://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/4.3.0.12",
        "homepageUrl": "http://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/4.3.0.12",
        "jar": "https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/4.3.0.12/apoc-4.3.0.12-all.jar",
        "downloadUrl": "https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/4.3.0.12/apoc-4.3.0.12-all.jar",
        "sha1": "6a3496abaf40740e03bc5c177256aa64deb67c6f",
        "sha256": "a59fc3376e2c78716203fc72f00cdaa95c2e3f55fd13a5a774eb00097d4d2d1b",
        "md5": "6acfbf4999e78c075ee4a6b954183bbb",
        "config": {
            "+:dbms.security.procedures.unrestricted": [
                "apoc.*"
            ]
        }
    },
```

Possibly at has been updated after you wrote this issue?
