### ISSUE TITLE
rename key in map: apoc.map.setKey should set key, not Entry (identical to `apoc.map.setEntry`) 

### ISSUE THREAD

**Issue by dorn-gerhard** [neo4j-contrib/neo4j-apoc-procedures#3887]
## Feature description (Mandatory)
There should be an option to rename a key in a map. `apoc.map.setKey` is promising to do so but is identical to `apoc.map.setEntry` which changes the value of a given key.

A possibility could be: `apoc.map.renameKey(map MAP<STRING, ANY>, key STRING, newKey STRING)`

```
apoc.map.setKey({"depends_on": [{
                     "depends_on": "some_value" }],
                 "name": "Mario"
                }, 
               "depends_on", "new_name")
```
should yield
```
{"new_name": [{
   "new_name": "some_value"}],
 "name": "Mario"}
```

## Considered alternatives
A workaround would be iterating through all keys (starting with the most nested key - value pair), getting a temporary value/submap of that key creating a new_key-value/submap pair and remove the old_key-value/submap pair.

**Comment by jexp** [comment]
Perhaps call it renameKey or replaceKey, but regular map APIs don't have such a funciton.
