### ISSUE TITLE
Apoc.trigger.propertiesByKey adding a dynamic label based on newValue vs oldValue does not work

### ISSUE THREAD

**Issue by tomasonjo** [neo4j-contrib/neo4j-apoc-procedures#395]
I have been playing around with apoc.trigger. I created a (a:Test{number:5}) and below query for apoc.trigger, then tried to set the number different, and it does not update labels as it should. Tried out only inner statement with hardcoded values and it works. Using Neo4j 3.1.3 and APOC 3.1.3.6. Nothing in debug.log

```
CALL apoc.trigger.add('test','UNWIND apoc.trigger.propertiesByKey({assignedNodeProperties},"number") AS prop 
WITH prop.node as n,CASE WHEN toFLOAT(prop.oldValue) < toFLOAT(prop.newValue) THEN "increasing" ELSE "decreasing" END AS label 
CALL apoc.create.addLabels( [n], [label]) YIELD node RETURN "none"', {phase:'after'})
```

**Comment by tomasonjo** [comment]
Seems like the issue is with adding dynamic labels in trigger.
```
UNWIND {createdRelationships} as rels WITH startNode(rels) as node set node:What -- works
UNWIND {createdRelationships} as rels WITH startNode(rels) as n WITH n, size((n)-->()) as size SET n:fuKru --works
UNWIND {createdRelationships} as rels WITH startNode(rels) as node WITH node, size((node)-->()) as size set node.size=size -- works

UNWIND {createdRelationships} as rels WITH startNode(rels) as n WITH n, size((n)-->()) as size CALL apoc.create.addLabels( [n], [toString(size)]) YIELD node return distinct("none") -- does not work
UNWIND {createdRelationships} as rels WITH startNode(rels) as n WITH n, size((n)-->()) as size CALL apoc.create.addLabels( [n], ["fu"]) YIELD node return distinct("none") -- does not work
```

**Comment by DanielBerton** [comment]
Hi @tomasonjo the problem has been partially resolved, you are trying to update a property when the transaction has been committed `{phase:'after'}`, but you cannot perform write operations because the transaction is closed.  We have just opened an issue #433 to solve it, in the meantime you can use `{phase:'before'}`. 
`oldValue` and `newValue` are wrong, correct values are `old` and `new`
