### ISSUE TITLE
apoc.refactor.mergeNodes has problems if nodes have relationships to a common node

### ISSUE THREAD

**Issue by tomasonjo** [neo4j-contrib/neo4j-apoc-procedures#397]
I have created a simple test:

```CREATE (:Foo{name:1})<-[:HAS]-(t:Test{name:1})-[:COMMON]->(:Common)<-[:COMMON]-(t1:Test{name:2})-[:HAS]->(:Foo{name:2})```

When I try:
```
MATCH (t1:Test{name:1}),(t2:Test{name:2})
call apoc.refactor.mergeNodes([t1,t2]) yield node
return "none"
```

I get Neo.ClientError.Statement.EntityNotFound and nothing changed with data.

>     Node with id 3 has been deleted in this transaction

In my original problem I had a similar model, but a bigger graph...

```
CREATE (n2:`Domain`:`UNIQUE IMPORT LABEL` {`name`:"", `UNIQUE IMPORT ID`:4222})
CREATE (n1:`Company`:`UNIQUE IMPORT LABEL` {`name`:"AGERO INNOVATIO", `UNIQUE IMPORT ID`:4308})
CREATE (n4:`Invoice`:`UNIQUE IMPORT LABEL` {`UNIQUE IMPORT ID`:4309})
CREATE (n3:`Company`:`UNIQUE IMPORT LABEL` {`name`:"AGERO INNOVATION", `UNIQUE IMPORT ID`:5441})
CREATE (n5:`Invoice`:`UNIQUE IMPORT LABEL` { `date`:"2017-04-06", `UNIQUE IMPORT ID`:5442})
CREATE (n3)-[:`HAS_DOMAIN`]->(n2)
CREATE (n4)-[:`ISSUED_TO`]->(n1)
CREATE (n1)-[:`HAS_DOMAIN`]->(n2)
CREATE (n5)-[:`ISSUED_TO`]->(n3)
CREATE (n3)-[:`FOO`]->()
CREATE (n1)-[:`FOO`]->()
```
And when trying to merge
```
match (c1:Company{name:"AGERO INNOVATION"}),(c2:Company{name:"AGERO INNOVATIO"})
call apoc.refactor.mergeNodes([c1,c2]) YIELD node
return "none"
```

I get a different error Neo.ClientError.Schema.ConstraintValidationFailed and

> Cannot delete node<45>, because it still has relationships. To delete this node, you must first delete its relationships.

**Comment by sarmbruster** [comment]
You can prevent this by doing 
```
MATCH (t1:Test{name:1}),(t2:Test{name:2})
WITH * LIMIT 1
call apoc.refactor.mergeNodes([t1,t2]) yield node
return "none"
```
see #578 as well. I'm closing this one off as a duplicate.

**Comment by kuczera** [comment]
Can i combine this with apoc.periodic.commit in any way ?

**Comment by ElizavetaNosova** [comment]
> You can prevent this by doing
> 
> ```
> MATCH (t1:Test{name:1}),(t2:Test{name:2})
> WITH * LIMIT 1
> call apoc.refactor.mergeNodes([t1,t2]) yield node
> return "none"
> ```
> 
> see #578 as well. I'm closing this one off as a duplicate.

What does the line  "WITH * LIMIT 1" do?
