### ISSUE TITLE
add crontab like job-control

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#404]
apoc.periodic.schedule -> allow cron-like-expressions

`apoc.periodic.at('name', statement, 'cron-like-expression')`

**Comment by albertodelazzari** [comment]
@jexp can we use a library like quartz scheduler? Or anything else?

**Comment by jexp** [comment]
Quartz is quite a monster :) perhaps there is something more lightweight?

I mean after all it is just parsing the cron expression and starting with the necessary delay + interval in the scheduled thread pool?


Michael

**Comment by albertodelazzari** [comment]
@jexp there is something lightweight, maybe we can get some idea for the "crontab-expression" from this project: http://www.sauronsoftware.it/projects/cron4j/index.php and then using simple java schedulers. 

In details I am talking about this: http://www.sauronsoftware.it/projects/cron4j/api/it/sauronsoftware/cron4j/SchedulingPattern.html

The project is free, what do you think?

**Comment by jexp** [comment]
Sounds good.

But I'm currently rethinking if this is a good idea in the first place, or if this isn't something that should live outside of the database?

**Comment by ikwattro** [comment]
Also the lib latest release dates back in 2013 ?

http://www.sauronsoftware.it/projects/cron4j/download.php

https://mvnrepository.com/artifact/it.sauronsoftware.cron4j/cron4j

**Comment by albertodelazzari** [comment]
@ikwattro I think so but we only want to take the "interesting" part of it, in particular I'm talking about the cron expression parser.

@jexp in my opinion it's better to let this piece outside of the database if we are talking about only scheduling any cypher query we want to run at specific time.

**Comment by emregency** [comment]
@jexp is it still something that you consider? Would you recommend [`apoc.periodic.schedule` ](https://neo4j.com/docs/labs/apoc/3.5/background-operations/background-jobs/#periodic-background) as a start to implement cron-like jobs?
