### ISSUE TITLE
Textual representation of the export parquet output file

### ISSUE THREAD

**Issue by vga91** [neo4j-contrib/neo4j-apoc-procedures#4056]
Check if it is possible to export a Parquet file, with the `apoc.export.parquet.*` procedure, in a textual representation instead of a binary one,
and add a flag if so.

See related Slack thread: https://neo4j.slack.com/archives/C136J23GE/p1713856995225349

**Comment by jexp** [comment]
Isn't that just CSV ?

Perhaps just wrap it in base64 encoding?

**Comment by vga91** [comment]
Apache Parquet format is not human-readable and binary-based (instead of text-based) by definition, so there's no way to create a textual output.
Some references:
- https://blog.damavis.com/en/apache-parquet-introduction-and-key-concepts/, 
- https://www.dremio.com/resources/guides/intro-apache-parquet/, 
- https://dskrzypiec.dev/parquet/, 
- https://dskrzypiec.dev/parquet/

So, we should use other formats to create a readable file.

----

Even wrapping the `byte[]` with `new String(..)` is not human-readable, for example:
```
PAR1��ō��ō��ō��ō������ōRR��ς	
1999-01-01
2000-01-01..�֛�12��ō�ʘ����00���Another��ō��ō��ō��ō��ō&&&&&F&
1999-01-01
2000-01-01&F12&F&&&AnotherAnother&F&&&&&:B:|:�:�H�:��(�\�:�H�J�^�:�:�:�:�:�H
apocExport"%name%place%male%age5kidsL<5list%element%born%L�5listDate
```

The same thing by doing `Base64.getEncoder().encodeToString(...)`:
```
UEFSMRUAFSoVKhWWz96QChwVBBUAFQYVCAAAAgAAAAMDBAAAAEFkYW0DAAAASmltFQAVhgEVhgEVl5mAygccFQQVABUGFQgAAAIAAAADATkAAABwb2ludCh7eDogMzMuNDY3ODksIHk6IDEzLjEsIHo6IDEwMC4wLCBjcnM6ICd3Z3MtODQtM2QnfSkVABUOFQ4VssfL6gwcFQQVABUGFQgAAAIAAAADAQEVBBUQFRAV7oel2QE8FQIVBAAAKgAAAAAAAAAVABUQFRAVzZ TkAocFQQVBBUGFQgAAAIAAAADAwADFQAVWBVYFdqq2rkKHBUKFQAVBhUGAAACAAAAAw4DAAAAA/8AAwAAAFNhbQQAAABBbm5hBQAAAEdyYWNlAwAAAFF3ZRUAFRwVHBWAwerUDRwVBBUAFQYVCAAAAgAAAAMBQEmDaE0BAAAVABUaFRoVkK/b0AwcFQQVABUGFQYAAAIAAAADAAMAAAADAAAVABUaFRoVkK/b0AwcFQQVABUGFQYAAAIAAAADAAMAAAADAAAVABUMFQwVqbLFjQUcFQQVABUGFQgAAAIAAAADABUAFQwVDBWpssWNBRwVBBUAFQYVCAAAAgAAAAMAFQAVLBUsFdGq1OUGHBUEFQAVBhUIAAACAAAAAwMYAAAAAAAAABkAAAAAAAAAFQQVEBUQFY 
```

The only usable way seems to be using a `ParquetReader`.



The batch produced which is used via ParquetWriter.write(<batch>)  is something like this:
```
name: Adam
place: point({x: 33.46789, y: 13.1, z: 100.0, crs: 'wgs-84-3d'})
male: true
age: 42
kids
  list
    element: Sam
  list
    element: Anna
  list
    element: Grace
  list
    element: Qwe
born: 1431977544000
__id: 4
__labels
  list
    element: User
```

----

Therefore, instead of parquet, we could use the `apoc.export.yaml.*`,
or also the `apoc.export.csv.*`  / `apoc.export.json.*` would be good.
