### ISSUE TITLE
create.relationship uniqueness

### ISSUE THREAD

**Issue by genxstylez** [neo4j-contrib/neo4j-apoc-procedures#406]
Hi there,

I am trying to create dynamic relationship using variable names, the relation created doesn't seem to be unique. 

I want the `CREATE UNIQUE` ability to be more clear.

Are there anyway I can achieve this?

Cheers.

**Comment by InverseFalcon** [comment]
I don't believe the relationship is unique. We have a separate [feature request](https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/271) open for an `apoc.merge.relationship()` procedure that would likely meet your need for uniqueness

**Comment by jexp** [comment]
Implemented `apoc.merge.relationship`
