### ISSUE TITLE
apoc.load.csv does not close the file on consumption end

### ISSUE THREAD

**Issue by Ava-S** [neo4j-contrib/neo4j-apoc-procedures#4078]
I use Python to preprocess a file and then load it into the database. More specifically, I have defined the following import flow:
	1. Users specify the location of the input file
	2. The code preprocesses the file
	3. The code requests the import directory and moves it to the import folder of the database
	4. The file is imported using `apoc.load.csv`
	5. Once the import is done, I tidy up by deleting the file from the import folder. 

However, after recently upgrading my database from version 5.9.0 to 5.10.0, I'm not allowed to delete the file from the import folder, as it is still being consumed by the database. The error still prevails in version 5.17 (last tested).

## Expected Behavior (Mandatory)

After a file imported using `apoc.load.csv`, the file should be closed on consumption end, so that other processes can access the file.

## Actual Behavior (Mandatory)

The issue arises when I attempt to delete the file post-import. I encounter a PermissionError, signaling that the file is still in use by another process. It seems the database is holding onto the file longer than anticipated, causing a conflict with my cleanup operation.

More specifically, I get this error: `PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '<ne04j>\\import\\import_file.csv`

### Simple Dataset (where it's possibile)

The specific dataset does not matter, it happens with any dataset I try to import.

### Python Code

This is the Python code I use to import and delete the file.
```
# Import file
def import_file(tx):
	result = tx.run('''CALL apoc.periodic.iterate('
                        CALL apoc.load.csv("import_file.csv") yield map as row return row',
                        'CREATE (record:Record)
                        SET record += row'
                    , {batchSize:10000, parallel:true, retries: 1});''')

with self.driver.session(database="neo4j") as session:
        session.execute_write(import_file)

# Delete the file from the import directory
path = Path(self.get_import_directory(), "import_file.csv")
os.remove(path)
```

### Steps (Mandatory)

  1. Import data using `apoc.load.csv` with the Python neo4j driver
  1. Delete the file directly afterwards using Python

## Specifications (Mandatory)

Currently used versions

### Versions

  - OS: Windows 11 Enterprise
  - Neo4j: v5.10
  - Neo4j-Apoc (and extended): v5.10
  - Neo4j driver: v5.10
  - Python v3.11

**Comment by vga91** [comment]
The error seems to occur also without `apoc.periodic.iterate`, and even running the `apoc.load.csv` directly on neo4j browser/desktop, without using python code trying to delete the file via File Explorer.

It could probably be an error in neo4j itself, as the code regarding apoc.load.csv has not changed.

I opened an issue on the neo4j kernel repository, to investigate both sides:
https://github.com/neo4j/neo4j/issues/13480

**Comment by vga91** [comment]
The problem no longer seems to be present with `apoc.load.csv` (using neo4j 5.25.1 and apoc 5.25.0).

The problem would still seem to persist with `apoc.import.json`, which is in APOC Core, 
so that I can close this issue and transfer the related Trello card to the Core board.
