### ISSUE TITLE
[3.1.0.4 - apoc.mongo.*] Causes NoClassDefFoundError: org/bson/conversions/Bson 

### ISSUE THREAD

**Issue by sylvainroussy** [neo4j-contrib/neo4j-apoc-procedures#409]
Hi,
The following query:
```
CALL apoc.mongodb.find("myHost:myPort","myDB","mysCollection",null,null,null)
```

Causes:
` NoClassDefFoundError: org/bson/conversions/Bson ` 

Neo4j at starting logs:
```
Failed to load `apoc.mongodb.MongoDBColl` from plugin jar `/var/lib/neo4j/plugins/apoc-3.1.0.4.jar`: org/bson/conversions/Bson 
```

Neo4j : 3.1.1 (Community and enterprise)
MongoDB : 3.0.14
Apoc : 3.1.0.4 (same error in 3.1.0.3)

Maybe due to mongoDb changes ?

(http://stackoverflow.com/questions/40912639/mongodb-with-java-exception-in-thread-main-java-lang-noclassdeffounderror-org)

**Comment by inserpio** [comment]
No, just add the documented dependencies together with the apoc jar:
https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_interacting_with_mongodb

**Comment by sylvainroussy** [comment]
Argl! Shame on me!
I'm so sorry, this is a Rtfm for me.
Ok, I'm closing this issue.

**Comment by inserpio** [comment]
That's ok! No worries!
Happy it's working for you now!
