### ISSUE TITLE
Date.java overload parse, format and fields methods

### ISSUE THREAD

**Issue by ADTC** [neo4j-contrib/neo4j-apoc-procedures#41]
This is concerning https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/master/src/main/java/apoc/date/Date.java

Instead of having methods like `parseDefault`, `formatDefault` and `fieldsFormatted`, why not just overload the methods with shorter names like `parse`, `format` and `fields`? The format argument would be optional. When not provided it will execute the method without the argument, and when provided it will execute the method with the argument. Wouldn't that be better?

**Comment by tkroman** [comment]
It definitely would be better. However, there's no support for procedure overloading in neo4j currently. Hence, different names.

**Comment by ADTC** [comment]
Thanks, I suspected that.

Quick question. How do I give a custom time zone for the `format` method? Currently it always returns the formatted time in UTC. Can you make a `formatZone` or `formatTZ` method that takes an additional time zone argument (in exactly the same format as the `parse` method would take timezone)?

**Comment by ADTC** [comment]
To be revisited when neo4j supports procedure overloading, _if ever_.
