### ISSUE TITLE
5.20.0 APOC does NOT include core functions and neither does neo4j community edition 5.20.0

### ISSUE THREAD

**Issue by penguinoctopus** [neo4j-contrib/neo4j-apoc-procedures#4119]
I have windows 11. Neo4j is 5.20.0 community edition. I need to use apoc.periodic.iterate and other core functions. They are absent by default in neo4j 5.20.0 community edition. Previously I could just get core neo4j jar, but now the only .jar that I see is the apoc-5.20.0-extended.jar. I can successfully use the functions in this jar but where could I get core functions now?

**Comment by Lojjs** [comment]
@penguinoctopus Are you using Docker or not? And in which folder have you looked for the APOC core jar?

**Comment by Lojjs** [comment]
This repo is only containing APOC full (core + extended) for Neo4j 4.4. For Neo4j 5, core and extended were split up and released separately. This was done by extracting APOC core to its own Github repository: https://github.com/neo4j/apoc. This means that all 5.x releases on the link you provided are for extended while core releases  can be found here: https://github.com/neo4j/apoc/releases
