### ISSUE TITLE
APOC EXPORT CSVs - Add option to export "nothing" for NULL values instead of empty string

### ISSUE THREAD

**Issue by rohankharwar** [neo4j-contrib/neo4j-apoc-procedures#4147]
## Feature description (Mandatory)
APOC EXPORT CSVs - Add option to export "nothing" for NULL values instead of empty string ("")
Currently there is no option and empty string or NULL values are both exported as "" (empty strings) so when we have to load to a different database this does not help. 

No options available as per documentation
https://neo4j.com/labs/apoc/4.4/export/csv/#export-csv-config

**Comment by gem-neo4j** [comment]
This is implemented in the 5.x branch of APOC core now :) Will be released in a month or so, most likely with version: 5.23, the docs will also be updated with more detailed info
