### ISSUE TITLE
Feature Request: Add apoc.node.relationship.degree() for getting the degree of relationship type(s) to or from a node

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j-contrib/neo4j-apoc-procedures#415]
The technique for getting the degree of relationships to or from a node isn't well known or documented (as far as I can tell there's nothing in the developer manual for this, though there is a kb article), so an explicit function for getting the degree of relationships to or from a node may be useful.

We could use the same syntax as the relationshipFilter in path expander procedures, which could let us get degrees for multiple relationship types, with potentially different directions per type (something Cypher currently cannot do).

An example of usage:

```
MATCH (p:Person{name:'Keanu Reeves'})
RETURN apoc.node.relationship.degree(p, '<FRIEND|ACTED_IN>') as connections
```

The name/namespace proposed here matches up with `apoc.node.relationship.exists()`, though perhaps a less verbose name would work better.

**Comment by jexp** [comment]
Implemented

**Comment by InverseFalcon** [comment]
Note that the documentation didn't come across with the code. We'll need to add that in.
