### ISSUE TITLE
Date.java format with custom time zone

### ISSUE THREAD

**Issue by ADTC** [neo4j-contrib/neo4j-apoc-procedures#42]
How do I give a custom time zone for the `format` method? Currently it always returns the formatted time in UTC. Can you make a `formatZone` or `formatTZ` method that takes an additional time zone argument (in exactly the same format as the `parse` method would take timezone)?

I read the source code and there appears to be some timezone support but I don't quite understand. It seems to always default to UTC. How can you force it to a custom timezone?

The fourth argument for the new method could be anything that can be passed into `ZoneId.of(String)` and `TimeZone.getTimeZone(String)` methods, instead of `UTC_ZONE_ID`.

**Comment by jexp** [comment]
Should be resolved, now.

Thanks a lot for your contributions.

**Comment by ADTC** [comment]
It was a lot of fun :) thanks for the good spirits!
