### ISSUE TITLE
Better error messages when missing drivers

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#430]
Probably catch ClassNotFoundExceptions and return/throw a nicer error message, that states
which jars should be put into the plugins directory.

- [ ] JDBC
- [ ] MongoDB
- [ ] Couchbase

Also add tot he docs where to download the right drivers, similar to:
https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_load_jdbc_resources

**Comment by inserpio** [comment]
@AngeloBusato JDBC is missing
