### ISSUE TITLE
apoc.trigger with phase:'after' in update actions doesn't work

### ISSUE THREAD

**Issue by AngeloBusato** [neo4j-contrib/neo4j-apoc-procedures#433]
Related to issue #395 .
On apoc.trigger if we use `phase:'after'` on an update action, procedure doesn't work; it goes in loop because transaction is already close.

**Comment by jexp** [comment]
The transaction is *almost* over, but locks have not been released. So the solution would be to queue it until the tx is really done.

**Comment by conker84** [comment]
we added the `afterAsync` phase in order to manage these use-cases
