### ISSUE TITLE
test export / import of larger graphs to/from cypher

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#439]
e.g. LDBC SF1

-  https://dl.dropboxusercontent.com/u/14493611/ldbc_sf001_p006.tgz

### export to cypher

- [x]  all
- [x] query
- [x] paths, nodes + rels
- [x] graph object

- [x] single file
- [x] many files
- [x] for the different output formats

###  import 
- [x] cypher-shell
- [x] -shell
- [x] apoc.cypher.runFile(s) , apoc.cypher.runSchemaFile(s)

**Comment by cleishm** [comment]
Tested a large import with neo4j-client. ✅

**Comment by jexp** [comment]
Please also document the workflow from exporting from one database and then which commands one can use to import into the next database.

**Comment by jexp** [comment]
@DanielBerton the import via `neo4j-shell -file file.cypher` and `cypher-shell < file.cypher` 
are missing.
