### ISSUE TITLE
Destructure/Serialise Objects

### ISSUE THREAD

**Issue by adam-cowley** [neo4j-contrib/neo4j-apoc-procedures#444]
I'm currently using APOC to merge Twitter information into Neo4j.  Being a bit lazy, I'm trying to mass assign properties to a node but as the JSON response includes embedded objects, Neo is throwing an error.

```
// Abridged
WITH 
{
        "id": 472614080,
        "id_str": "472614080",
        "name": "...",
        "screen_name": "...",   
        "entities": {
            "url": {
                "urls": [{
                    "url": "...",
                    "expanded_url": "...",
                    "display_url": "...",
                    "indices": [0, 22]
                }]
            }
        },
        "status": {
             // etc
         },
        "muting": null,
        "blocking": null,
        "blocked_by": null,
        "translator_type": "regular"
} as user
MERGE (u:User {screen_name:user.screen_name})
SET u += user
```

A procedure to destructure or serialise these objects in bulk would be a massive timesaver.  Maybe `apoc.map.serialize` or `apoc.map.flatten`?

**Comment by jexp** [comment]
Do you have a good idea for a target format?

**Comment by adam-cowley** [comment]
Either a serialised JSON object or a full dot notation of the would be useful, something like
```
(:User {`entities.url.urls.0.url`:"..."})
```

**Comment by conker84** [comment]
You can now use `apoc.map.flatten`
