### ISSUE TITLE
Feature Request - Aggregating intersection and union functions

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j-contrib/neo4j-apoc-procedures#448]
When we have collections in each row, the easiest way to perform union or intersection is to collect into lists of lists, then use `reduce()` along with `apoc.coll.intersection()` or `apoc.coll.union()`. This works, though it can get a bit verbose.

It would be helpful if we had aggregation functions that would automatically perform these operations.

**Comment by jexp** [comment]
@InverseFalcon could you spell out an example?

**Comment by conker84** [comment]
@InverseFalcon can we close this?
