### ISSUE TITLE
Strict mode for apoc.meta.subGraph

### ISSUE THREAD

**Issue by ADTC** [neo4j-contrib/neo4j-apoc-procedures#45]
Can there be a strict mode for `subGraph`? Currently, for the relationship types I specify, all labels that connect those relationship types appear. For me, this makes the `subGraph` not so useful, as it doesn't really allow me to focus on a particular set of labels and/or a particular set of relationships.

I could do the changes. Just let me know your thoughts on this. The map makes it easy to extend the method just by adding support for a new `strict` key (I would like it to default to true, but to keep original behavior, I'll default it to false).

**Comment by jexp** [comment]
Do you have an example? You mean that the labels given should not just be used as start-nodes but also restricted for end-node-labels?

**Comment by ADTC** [comment]
Examples:

**Relationships only:**

`call apoc.meta.subGraph({rels:['CATEGORY_PRODUCT']})`
![Relationships only, lenient](https://cloud.githubusercontent.com/assets/6047296/15451312/b68f2350-1fee-11e6-9b55-4c2878b8a311.png)

`call apoc.meta.subGraph({rels:['CATEGORY_PRODUCT'],strict:true})`
![Relationships only, strict](https://cloud.githubusercontent.com/assets/6047296/15451316/ebd904b8-1fee-11e6-90e8-2c2fe1deea98.png)

**Labels only:**

`call apoc.meta.subGraph({labels:['Category','Product']})`
![Labels only, lenient](https://cloud.githubusercontent.com/assets/6047296/15451330/9410a492-1fef-11e6-8b0c-a3dc1f1817b2.png)

`call apoc.meta.subGraph({labels:['Category','Product'],strict:true})`
![Labels only, strict](https://cloud.githubusercontent.com/assets/6047296/15451334/c45e70de-1fef-11e6-8d92-74f076470acc.png)

**Both:**

`call apoc.meta.subGraph({labels:['Category','Product'], rels:['CATEGORY_PRODUCT']})`
![Both, lenient](https://cloud.githubusercontent.com/assets/6047296/15451323/2949e9ca-1fef-11e6-8677-1bd09a641b5f.png)

`call apoc.meta.subGraph({labels:['Category','Product'], rels:['CATEGORY_PRODUCT'],strict:true})`
![Both, strict](https://cloud.githubusercontent.com/assets/6047296/15451329/46729aba-1fef-11e6-981d-7f03caf4c578.png)

@jexp :)

**Comment by ADTC** [comment]
@jexp do the images make sense? Shall I open a PR?

There is a bug in the base code where the subGraph double-counts a meta relationship from a node to itself. The graph procedure doesn't. I'm still figuring out how to resolve it.

**Comment by jexp** [comment]
Merged, did you add the images to the docs? Could be helpful.

**Comment by ADTC** [comment]
No, but I'd rather not use these. I'll make some clean example images.
