### ISSUE TITLE
node similarity functions

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#450]
that take not only properties into account but the graph structure

allow filter on property names and rel-types and target-labels/property-names to compare

compute a composite score based on similarity of

- attributes (https://github.com/tdebatty/java-string-similarity)
- cardinality of rel-types
- pointing to the same end nodes
- similarity of attributes / labels of end-nodes

Especially important for MDM, data integration and investigative use-cases

**Comment by conker84** [comment]
Done via `apoc.hashing.fingerprinting`
