### ISSUE TITLE
Feature Improvement - Add optional parameter on apoc.schema.assert() for whether existing schema is dropped or not

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j-contrib/neo4j-apoc-procedures#453]
Current behavior in `apoc.schema.assert()` is to drop all indexes and constraints, then add the indexes and constraints that were provided.

According to @jexp, When the procedure was originally written, procedures couldn't do index operations, and it was written to address a customer request to assert the exact schema.

At this point we should have more flexibility in reading and changing the schema from procedures, so it makes sense to add an optional parameter `dropExisting` to control whether or not the entire schema is dropped prior to checking/adding indexes and constraints.

I propose having the default be `dropExisting = false`, as I would guess that most cases of schema assertion will not require dropping previous constraints.

We should also be clear in the documentation, the fact that previous schema was dropped wasn't well documented before, both in the APOC documentation page and the built-in documentation (apoc.help() provided no info on this procedure's behavior).

**Comment by jexp** [comment]
Also rewrite schema.assert to become a regular procedure now.

**Comment by InverseFalcon** [comment]
While I REALLY want to have `dropExisting = false` be default, this may break current usages. I'm going to keep default as `true` for now. Maybe we can flip the default when we reach 3.3.

**Comment by InverseFalcon** [comment]
Fulfilled.
