### ISSUE TITLE
apoc.convert.toTree always convert the relationship type name to lowercase

### ISSUE THREAD

**Issue by joehmchan** [neo4j-contrib/neo4j-apoc-procedures#460]
In https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/203fc1e878054c75d1f6147c747415c329d5aead/src/main/java/apoc/convert/Json.java#L88, it always converts the relationship typeName to lowercase. 

It causes a problem to other program using it, e.g. JSON serialization back to complex object. 

Is it possible to have an option, so that it is not converted to lowercase?

**Comment by jexp** [comment]
Already fixed.
