### ISSUE TITLE
APOC GraphML attributes not loadable by Gephi

### ISSUE THREAD

**Issue by phelps-sg** [neo4j-contrib/neo4j-apoc-procedures#466]
I landed on [Issue 258 (closed)](https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/258)  having encountered the same problem as the OP.

jexp said something was fixed in 3.1.0.4, but I am unable to import GraphML attributes when using APOC 3.1.3.7 and importing it into Gephi 0.9.1.

**Comment by Qingmu** [comment]
Same problem in `neo4j-cmmunity-3.2.2` with `apoc-3.2.0.4.jar`, and `gephi` version 0.9.1. Besides, the replacement of `apoc` with the version 3.1.0.4  stop the running of `neo4j-cmmunity-3.2.2`.

**Comment by jexp** [comment]
You have to use a 3.2.x version of APOC for the 3.2.x versions of Neo4j.

We can look into transmitting other attributes to gephi.

It currently transmits a property that fully or partially contains one of: "name", "title", "label" as caption.
And a configurable "weigth" property.

Which other properties would you want to see in Gephi?

**Comment by jexp** [comment]
@phelps-sg how does this fail: `import GraphML attributes when using `

Do you have an example / error message / screenshot , e.g. for the movies graph?

**Comment by Qingmu** [comment]
@jexp It would be better if apoc can get all the properties automatically instead of  fixed values as "name" and “title”. or how can I change the config files in apoc to add the properties I want to show in gephi ?

`apoc-3.2.0.4` can generate all the properties, e.g. `phonenumber`, into `graphml`, but it fails to add headers, like
`<key id="labels" for="node" attr.name="phonenumber" attr.type="string"/>`

**Comment by jexp** [comment]
What confuses me is that this test, which stores two different attributes also writing the correct key-entries then works.

https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/3.2/src/test/java/apoc/export/graphml/ExportGraphMLTest.java#L93

**Comment by jexp** [comment]
I'll check again.

**Comment by Qingmu** [comment]
Thanks a lot !
And sorry for my poor coding with java or I can contribute to apoc myself.

**Comment by conker84** [comment]
Related to #478
