### ISSUE TITLE
time out because it is file json is too late to read

### ISSUE THREAD

**Issue by kienbui1995** [neo4j-contrib/neo4j-apoc-procedures#468]
I use query in browser:
`CALL apoc.load.json("url")`

Because this url is very slow to return a json (about 80s). So, The neo4j's browser show a error message: 

> Neo.ClientError.Procedure.ProcedureCallFailed Failed to invoke procedure apoc.load.json: .....as json: Read timed out.

I tried with setup:

> unsupported.dbms.executiontime_limit.enabled=true
unsupported.dbms.executiontime_limit.time=100s

but they only work for a Transaction because when I set `unsupported.dbms.executiontime_limit.time=1s`, it return: Neo.ClientError.Transaction.TransactionTimedOut Transaction timeout. (Overtime: 4 ms) but apoc.load.json still exec and return: `Neo.ClientError.Procedure.ProcedureCallFailed` Failed to invoke procedure apoc.load.json: .....as json: Read timed out.

**Comment by kienbui1995** [comment]
How to setup timeout for apoc.load.json()

**Comment by jexp** [comment]
APOC itself has an http connect timeout that you can configure in the config:

in milliseconds

```
apoc.http.timeout.connect=10000
apoc.http.timeout.read=60_000

```
