### ISSUE TITLE
Feature request : apoc.convert.toTree([virtual paths])

### ISSUE THREAD

**Issue by tomzeppenfeldt** [neo4j-contrib/neo4j-apoc-procedures#477]
Possibility to use an array of virtual paths as described here 

https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/476

as an input of  `apoc.convert.ToTree()`

**Comment by conker84** [comment]
We just need to use `apoc.path.create` and pass the result to `apoc.convert.toTree`
