### ISSUE TITLE
Export graphml missing labels of Nodes and Edges

### ISSUE THREAD

**Issue by KenChang168** [neo4j-contrib/neo4j-apoc-procedures#478]
hello, i encountered an issue when i try to export a graphML document for Graphi.
i am using **apoc.export.graphml.query** command as follows ( refrence from (#295) )

`call apoc.export.graphml.query('MATCH p=()-[r]->() RETURN p limit 1000','../../../Ken/GraphML_output/AR.graphml',{useTypes:true})
`
the option **useTypes:true** is worthy for detecting Attributes of Nodes & Edges in Gephi.
However, i found the original Labels of Nodes & Edges in Neo4j is missing !
the meaning is i could not find the Labels of Nodes & Edges in Gephi which are exist in Neo4j.

To solve this problem, i try to Add following Tags to the GraphML document.
```
< key id="label" for="node" attr.name="label" attr.type="string"/ >
< key id="label" for="edge" attr.name="label" attr.type="string"/ >
```
and replace all nodes tag from
`<node id="n150" labels=":CORP"><data key="**labels**">:CORP</data></node>`
into 
`<node id="n150" label=":CORP"><data key="**label**">:CORP</data></node>`

After adjusting, i could see the Labels of Nodes & Edges in Gephi successfully.
node ex.
id             **Label**
n157	**:CORP**	.

edge ex.
Source     Target       Type         id     **Label**
n292	n188	directed	e0	**Order**		

However, all above works are done by myself,
I wonder to know is there any option parameter can i used in  **apoc.export.graphml.query** ??
Or, how could i solve these problem ?? 

Thanks for your help~

**Comment by yixiao5428** [comment]
I have this problem too, is it fixed yet???

**Comment by gjcairo** [comment]
What's going on with this change exactly? This is still broken for me after two years of being reported.

**Comment by vaidagr** [comment]
Still the same...

**Comment by nittonfemton** [comment]
As a workaround, you can add this to the graphml file in the top section.
`<key id="labels" for="node" attr.name="labels"/>
`

Now the "labels" property will be visible in Gephi, and you can copy it to the label column.
