### ISSUE TITLE
There is no procedure with the name `apoc.help` registered for this database instance.

### ISSUE THREAD

**Issue by wangxen** [neo4j-contrib/neo4j-apoc-procedures#482]
For Windows users, should add plugin directory in $Neo4j_Home/conf/neoj4.conf:
dbms.directories.plugins=C:/Program\ Files/Neo4j\ CE\ 3.2.1/plugins
(if your neo4j directory is C:\Program Files\Neo4j CE 3.2.1)

**Comment by jexp** [comment]
Did my comments in the readme not cover it?
