### ISSUE TITLE
be able to register scripts that are run exactly once at startup

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#497]
and "hopefully" at shutdown.

Using db-lifecycle in kernel-extensions with retries if the scripts fail to run due to database not started yet.

The scripts could reside in a directory
or being registered and stored in graph properties (this would also allow them to run on a cluster)

for the latter we have to be aware of readonly vs. rw-scripts

**Comment by conker84** [comment]
Done via apoc initializers
