### ISSUE TITLE
support parameters for neo4j-shell and cypher-shell in export.file

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#500]
`:param name: value`

`create (n:Node {name:$name});`

or use unwind like here: 
http://jexp.de/blog/2017/03/5-tips-tricks-for-fast-batched-updates-of-graph-structures-with-neo4j-and-cypher/

for the 2nd approach we should honor batchsize

probably best to test both approaches

**Comment by johnbodley** [comment]
@jexp having parameters or the ability to unwind nodes/relationships would be fantastic for improving importing of large graphs per:
- https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/503
- https://stackoverflow.com/questions/44688194/efficient-importing-of-cypher-statements

**Comment by NightMachinary** [comment]
Bumping this

**Comment by conker84** [comment]
We have the `cypher-shell` format for exporting data in `apoc.export.cypher`
