### ISSUE TITLE
apoc.export.csv.all hangs

### ISSUE THREAD

**Issue by szarnyasg** [neo4j-contrib/neo4j-apoc-procedures#505]
I am using Neo4j 3.2.1 with the latest stable APOC. If I ask it to YIELD the `relationships` attribute, it hangs (but the `hello.csv` file is created):

```
CALL apoc.export.csv.all('hello.csv', {})
YIELD file, source, format, nodes, properties, time, rows, relationships
RETURN *
```

If I remove it, it runs fine:

```CALL apoc.export.csv.all('hello.csv', {})
YIELD file, source, format, nodes, properties, time, rows
RETURN *
```

```
╒═══════════╤════════╤═══════╤════════════╤══════╤═════════════════════════════╤══════╕
│"file"     │"format"│"nodes"│"properties"│"rows"│"source"                     │"time"│
╞═══════════╪════════╪═══════╪════════════╪══════╪═════════════════════════════╪══════╡
│"hello.csv"│"csv"   │0      │0           │0     │"database: nodes(0), rels(0)"│1     │
└───────────┴────────┴───────┴────────────┴──────┴─────────────────────────────┴──────┘
```

I tried this on an empty DB, on a DB of two nodes and on the movie database. When it hangs, I just get the throbber in the web UI.

**Comment by DanielBerton** [comment]
@jexp  @szarnyasg The problem seems to concern only the Neo4j 3.2.1 version, and only on the browser. For now as workaround you can rename the relationships with another name as :
```
CALL apoc.export.csv.all('hello.csv', {})
YIELD file, source, format, nodes, properties, time, rows, relationships as rels
RETURN *
```
What it hangs is the word `relationships`, to fix it we can change in `ProgressInfo` class the variable `relationships` to `rels`, but it's use in many other apoc.
Perhaps we can specify it on the documantation.

**Comment by jexp** [comment]
Don't rename the column. It's part of the public api. We can raise an issue with the browser team

**Comment by jexp** [comment]
@DanielBerton can you please try it in the cypher-shell?

**Comment by szarnyasg** [comment]
Sorry, I didn't notice that this was done. Just tested with 3.5.8 and works fine. Thanks!
