### ISSUE TITLE
Improve Error Logging to Expose Full Cypher Exception

### ISSUE THREAD

**Issue by bradnussbaum** [neo4j-contrib/neo4j-apoc-procedures#511]
Let’s say we have Cypher:
```
CREATE null RETURN n;
```
This returns the error:
```
Parentheses are required to identify nodes in patterns, i.e. (null) (line 1, column 8 (offset: 7))
"CREATE null RETURN n;"
        ^
```
Util.logErrors does not log out the full exception so that users can see the error message, cypher statement, line and column numbers, etc.

**Comment by conker84** [comment]
We added validation rules into Periodic procedures
