### ISSUE TITLE
apoc.convert.fromJsonMap() does not correctly handle escaped characters in strings

### ISSUE THREAD

**Issue by al-jimwilliams** [neo4j-contrib/neo4j-apoc-procedures#517]
Versions: Neo4j 3.2.2 Community; APOC 3.2.0.3

Escaped characters in strings are not handled correctly in all instances.

This works as expected:

`WITH apoc.convert.fromJsonMap( '{"a":42,"b":"foo\\bar","c":[1,2,3]}') AS p RETURN p.b`
╒═════════╕
│"p.b" │
╞═════════╡
│"foo\bar"│
└─────────┘

Escaping quotes does not work as expected:

```
WITH apoc.convert.fromJsonMap( '{"a":42,"b":"\"foo\"","c":[1,2,3]}') AS p RETURN p.b
```
Neo.ClientError.Procedure.ProcedureCallFailed Failed to invoke function apoc.convert.fromJsonMap: Caused by: java.lang.RuntimeException: Can't convert {"a":42,"b":""foo"","c":[1,2,3]} to Map with path

Doubling down on the reverse solidus (not desirable) gives this result:

`WITH apoc.convert.fromJsonMap( '{"a":42,"b":"\\"foo\\"","c":[1,2,3]}') AS p RETURN p.b`
╒═════════╕
│"p.b" │
╞═════════╡
│"\"foo\""│
└─────────┘

An escaped newline character gets the same error:

`WITH apoc.convert.fromJsonMap( '{"a":42,"b":"foo\nbar","c":[1,2,3]}') AS p RETURN p.b`

Neo.ClientError.Procedure.ProcedureCallFailed Failed to invoke function apoc.convert.fromJsonMap: Caused by: java.lang.RuntimeException: Can't convert {"a":42,"b":"foo bar","c":[1,2,3]} to Map with path

[Note that the newline after "foo" is represented in the string returned by the error message. The error message is given on two lines.]

Is my usage of this procedure correct?

Has anyone seen this problem and fixed or worked around it?

**Comment by jexp** [comment]
This is unrelated to this procedure and apoc, just how Cypher handles escapes in strings.

You figured out most of the rules, please also note that you have here a json-string (with its escape rules) within a cypher string with its own escape rules.

Afaik JSON doesn't allow literal newlines within the JSON-strings

this worked for me (see also the text-result-view):

`WITH apoc.convert.fromJsonMap( '{"a":42,"b":"foo\\nbar","c":[1,2,3]}') AS p RETURN p.b`

**Comment by al-jimwilliams** [comment]
Fair enough.  Although the description of the procedure is brief, I was hoping that valid JSON (including escaped characters in Strings) could be converted to valid Cypher.  It seems incomplete on the part of the procedure not to have handling for escaped characters.

Based on the [Cypher doc](https://neo4j.com/docs/developer-manual/current/cypher/syntax/expressions/#cypher-expressions-string-literals) it appears that JSON and Cypher have nearly a one-to-one mapping of escape characters.  (The exception being Cypher handling UTF-32 characters.)

**Comment by conker84** [comment]
I'm closing this as seems not a real bug

**Comment by fodon** [comment]
This StackOverflow says you can fix it.
https://stackoverflow.com/questions/31537153/jsonparseexception-illegal-unquoted-character-ctrl-char-code-10

mapper.configure(
    JsonReadFeature.ALLOW_UNESCAPED_CONTROL_CHARS.mappedFeature(), 
    true
);
