### ISSUE TITLE
add aggregation functions (3.2) for efficiently getting the nth of a aggregation

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#525]
So instead of doing ´collect(n)[0..5]` or `head(collect(n))`

* `apoc.first(n)`
* `apoc.last(n)`
* `apoc.nth(n,skip)`
* `apoc.subset(n,skip,limit)`

**Comment by zygm0nt** [comment]
I've added a PR to fix this issue. Please check whether strict behaviour in `nth` and `subset` is fine for you.
