### ISSUE TITLE
Issue with automatic indexing when apoc.autoIndex.async=true

### ISSUE THREAD

**Issue by john-bodley** [neo4j-contrib/neo4j-apoc-procedures#534]
I ran into an issue with [automatic index tracking](https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_automatic_index_tracking_for_manual_indexes) for full text search. 

Specifically I wanted to leverage manual indexes as schema indexes can't be leveraged for case insensitive matching, i.e., `MATCH(n:Entity) WHERE n.id =~ '(?i)jane_doe' RETURN n`. 

Following the instructions in the link above in `neo4j.conf` I set, 
```
apoc.autoIndex.async=true
apoc.autoIndex.enabled=true
apoc.autoIndex.tx_handler_stopwatch=true
dbms.security.procedures.unrestricted=apoc.*
```
and ran the following Cypher statement, 
```
CALL apoc.index.addAllNodes('id', {Entity: ['id']}, {autoUpdate: true})
```
which correctly created the index per, 
```
Creating or updating index 'id' with config '{keysForLabel:Entity=id, autoUpdate=true, type=fulltext, to_lower_case=true, provider=lucene, labels=Entity}'
``` 
however when I then tried to perform bulk loading of entities via a script in chunks on 1,000 the system hung after the first of many chunks. Note no additional debug logging existed even though the following flag was set `apoc.autoIndex.tx_handler_stopwatch=true`. 

If I however disabled the async, i.e., `apoc.autoIndex.async=false` which is the default, the bulk loading procedure was successful. 

Note I'm using Neo4j v3.2.1 (community) and APOC 3.2.0.3.

**Comment by jexp** [comment]
@sarmbruster can you please have a look?

**Comment by sarmbruster** [comment]
How did you perform your bulk load? Prior to the bulk load, your graph is empty?

**Comment by johnbodley** [comment]
@sarmbruster prior to the bulk load the graph was empty, i.e., 
```
sudo neo4j stop
sudo rm -rf /var/lib/neo4j/data/databases/graph.db
sudo neo4j start
```
after which I create the required schema and manual indexes, as well as the uniqueness constraints. 

Regarding the bulk load this is actually happening in Python using the official Neo4j driver. The premise is we've updating the Neo4j graph as party of a nightly ETL pipeline which transfer data from Hive to Neo4j. The bulk load is of the form (somewhat simplified), 
```
UNWIND {rows} AS row
MERGE (n:Entity {id: row.properties.id})
  ON CREATE SET n = row.properties
```

Note we're also using the GraphAware [UUID](https://github.com/graphaware/neo4j-uuid) plugin which automatically assigns a UUID property to each node. My assumption is that this uses a separate transaction hook.

**Comment by sarmbruster** [comment]
Earlier this month I've add a commit https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/2a0c08cefe9aacbedd0b92d20ec6c23b2dfe3e33
This might fix the issue you've been seeing. Can you please validate this? Thanks.

**Comment by john-bodley** [comment]
@sarmbruster is your commit part of an APOC release? Currently we're using version `3.2.0.4` though would be happy to test this if it's part of `3.2.0.5` or via a sharable JAR file.

**Comment by john-bodley** [comment]
@sarmbruster upon further investigation I don't think we'll be able to test this in our deployment due to the following issues:
- https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/535
- https://github.com/jexp/neo4j-shell-tools/issues/122

i.e., there's no way currently of exporting/importing our graph either using the APOC procedures or the legacy `neo4j-shell-tools` which support manual indexes.

**Comment by conker84** [comment]
Indexes are now managed by the product
