### ISSUE TITLE
make export.csv configurable if it computes property types upfront

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#536]
make it possible to disable it

also check against the global list property-keys, if we already have the keys we should not continue to compute

we should also sample across all **existing** labels/rel-types combos.

**Comment by jexp** [comment]
If disabled, create just a wide CSV with all property-keys in the DB

**Comment by albertodelazzari** [comment]
@jexp, it's clear how to enable/disable 
```java
Map<String,Class> nodePropTypes = collectPropTypesForNodes(graph);
Map<String,Class> relPropTypes = collectPropTypesForRelationships(graph);
```
Using a configuration parameter.
It's also clear how to avoid repeated computation of an existing pair (property-key, value class).
But I don't understand what you mean when you say 
> a wide CSV with all property-key in the DB

Thanks

**Comment by conker84** [comment]
related to #583
