### ISSUE TITLE
Support for On Create and On Match in apoc.merge.node/relationship

### ISSUE THREAD

**Issue by nishant-jain-94** [neo4j-contrib/neo4j-apoc-procedures#538]
#508 I guess we should be able to differentiate between On Create and On Match. Let's say the simplest one would be on match add new properties than updating it. The best way is to provide different parameters for On Match and On Create Handler.

**Comment by jexp** [comment]
@sarmbruster any progress on this?

**Comment by conker84** [comment]
we new have `onCreateProps` and `onMatchProps`
