### ISSUE TITLE
Allow dynamic labels in apoc.cypher.run query

### ISSUE THREAD

**Issue by pierre-weceipt** [neo4j-contrib/neo4j-apoc-procedures#544]
Hi, I've got a case when I'm importing data from a csv and one of the row is a label. I know that in regular cypher you can't have labels as parameters but i'm wondering if this could be done with apoc for `apoc.cypher.run`.

PS : I can also use a console app + bolt drivers to build the queries string, which is faster than testing the label presence in a where clause when using CSV import, but it would be nice to be able to do it directly from cypher/apoc.

Thanks for the answer!

**Comment by jexp** [comment]
In general within `apoc.cypher.run` you can construct your query from a string, so you can add labels.
I would still recommend using `apoc.create.addLabels`.

You can also join neo4j.com/slack for such quick questions.
