### ISSUE TITLE
Add automatic sanity checks for Neo4j/APOC version combination

### ISSUE THREAD

**Issue by albertodelazzari** [neo4j-contrib/neo4j-apoc-procedures#558]
Some rough sanity check would be good. Perhaps as an extra shell script to be run.
For each of the entries in the JSON:

1. pull neo4j of that version e.g. from dist.neo4j.org or via docker
2. pull the apoc release jar of that version
3. install apoc, and run a bunch of procedures / functions. Esp. read/write/index access/periodic iterate/something that reads config.

Should become a separate issue / task.

see also the old thread issue #461

**Comment by ichbintonywu** [comment]
Got same warning on 4.4.0.4 with neo4j 4.4.7, any incompatibility issue persists?

**Comment by vga91** [comment]
There was a bug with the compatibility check fixed with apoc `4.4.0.6`
