### ISSUE TITLE
Sub Graph access using custom roles

### ISSUE THREAD

**Issue by sridharnampalli** [neo4j-contrib/neo4j-apoc-procedures#561]
Hi All 

i would like to know if there is  any procedures for Security to access sub graph using custom roles and map the value to node  properties values 

i have data  for different countries , but i would like to access the user to have  access to country he belongs 

Role  :Country_USA     node : Country {country:'USA'}   sub graph data  : match (n:Country{country:'USA'})-[]-(m) return (n)-[]-(m)

**Comment by jexp** [comment]
You can access the current user and roles with the built in security procedures.

Currently, there is no data level security in Neo4j but you could do it by putting your query into a procedure and checking the country against the user's permissions (e.g. role).

**Comment by conker84** [comment]
now we have fine grade security access into te product
