### ISSUE TITLE
Add Collection Function to update value at an index

### ISSUE THREAD

**Issue by bradnussbaum** [neo4j-contrib/neo4j-apoc-procedures#569]
This is the required cypher to update a collection index position. There needs to be a simpler way to insert a value into a collection.
`WITH [0,1,2,3,4] AS nums
WITH nums[0..2] AS s1, nums[3..5] AS s3
RETURN s1 + [9] + s3;`

Should be something like....
apoc.coll.set(index, object)

**Comment by jexp** [comment]
Another alternative cypher statement would be

```
WITH [0,1,2,3,4] AS nums
RETURN [n in nums | case when idx = 2 then 9 else n end]
```

**Comment by jexp** [comment]
It also makes sense to add:

* `apoc.coll.insert(coll,index,value)` - optionally value being a list
* `apoc.coll.remove(coll,index,[length=1])`
* append would be handled by cypher already

Syntax for yours: `apoc.coll.set(coll, index, value)`

**Comment by bradnussbaum** [comment]
@jexp thanks for feedback and expanding scope of work ;)

**Comment by bradnussbaum** [comment]
@jexp There is more needed to make these useful. Cypher's immutable collections cause challenges especially in this case where a simple update is desired. Given the following:
`WITH [0,1,2,3,4] AS nums, [{index:0, value:8},{index:3, value:9}] AS updates`
where there is a collection of nums with a collection of updates needing to be applied, how can you get a single collection of nums where the updates can be applied at each index?

Something like this is illegal currently in Cypher but seems intuitive to me.
`
WITH [0,1,2,3,4] AS nums, [{index:0, value:8},{index:3, value:9}] AS updates
WITH reduce(x = nums, u IN updates | x = apoc.coll.set(x,u.index,u.value)) AS nums
RETURN nums;
`

Maybe there is another way to solve this? Returning a new collection each time introduces some challenges I think and immutable collections also pose a challenge.

**Comment by jexp** [comment]
you are comparing x and the result of a function, so you get back a boolean value?
So in the next round you try to run `apoc.coll.set` on that boolean value.

this should work:

```
WITH [0,1,2,3,4] AS nums, [{index:0, value:8},{index:3, value:9}] AS updates 
RETURN reduce(x = nums, u IN updates | apoc.coll.set(x,u.index,u.value)) AS nums 

```

**Comment by bradnussbaum** [comment]
@jexp thanks for this makes sense

**Comment by albertodelazzari** [comment]
Can we close the issue?
