### ISSUE TITLE
Unsupported return type <java.util.stream.Stream<apoc.result.LongResult>> of function defined in <apoc.nodes.Nodes#loadCsvRelationships>.

### ISSUE THREAD

**Issue by ontologiae** [neo4j-contrib/neo4j-apoc-procedures#574]
Hi, I'm trying to add a function in nodes.java that create dynamic relationships from a CSV file, and the compiler doesn't accept it

Here's the function signature
```java
  @Procedure(mode = Mode.WRITE)
  @UserFunction("apoc.nodes.loadCsvRelationships")
  @Description("apoc.nodes.loadCsvRelationships( path, key )")
  public  Stream<LongResult> loadCsvRelationships(@Name("path") final String csvPath, @Name("key") final String idxKey ) {
     //..
   return  Stream.of(new LongResult(an_integer))
  }
```
I get a error : `neo4j-apoc-procedures/src/main/java/apoc/nodes/Nodes.java:144: error: Unsupported return type <java.util.stream.Stream<apoc.result.LongResult>> of function defined in <apoc.nodes.Nodes#loadCsvRelationships>.`

java.util.stream.Stream<apoc.result.LongResult> is a Stream of DTO, I don't understand why it fails

Thank you

**Comment by sarmbruster** [comment]
for usage see e.g. `apoc.nodes.delete` - it uses `Stream<LongResult>`. Could you discuss general questions on how to code procedures for Neo4j in the users slack channel, see https://neo4j.com/slack. There's a channel #neo4j-procedures within slack.

**Comment by ontologiae** [comment]
The problem was I had
```
  @Procedure(mode = Mode.WRITE)
  @UserFunction("apoc.nodes.loadCsvRelationships")
```
in the same time, so it failed. You have to choose one.

Ok the for neo4j Slack, I didn't know it exist.
Sorry for the disturbance.
