### ISSUE TITLE
consistent Label order using export csv

### ISSUE THREAD

**Issue by Josefmo** [neo4j-contrib/neo4j-apoc-procedures#579]
I have recently used the export csv function and have found a problem with the manner labels were exported.   

The labels were all concatenated into 1 column, which wouldn't be an issue.  

However, from row to row, the order of concatenation was all jumbled.  Is there a way to specify the order of the labels so that they are consistent from row to row?

**Comment by jexp** [comment]
We could sort them alphabetically.

**Comment by jexp** [comment]
https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/3.2/src/main/java/apoc/export/util/FormatUtils.java#L41
