### ISSUE TITLE
Error in apoc.do.when - unable to load NODE with id 

### ISSUE THREAD

**Issue by meilechh** [neo4j-contrib/neo4j-apoc-procedures#580]
Here is how to reproduce this issue:
```
CREATE (p1:Person{id: 1}) SET p1.name = 'John Smith'  
CREATE (p2:Person{id: 2}) SET p2.name = 'John Doe'  
CREATE (p1)-[:LIKES]->(p2)  
CREATE (p1)-[:DISLIKES]->(p2);
```
Then create `person.csv` file in `import` directory with this data:
```
"id", "name"
1, "John"
1, "Smith"
```
When running the following query: 
```
LOAD CSV WITH HEADERS FROM 'file:///person.csv' AS row
MATCH (p:Person{id: toInt(row.id)})-[r:LIKES]->()
DELETE r
WITH p
CALL apoc.do.when(NOT EXISTS((p)-[:LIKES]->()), "DETACH DELETE p", "", {p:p}) 
YIELD value RETURN p
```
This fails with this error:
```
Neo.ClientError.Statement.EntityNotFound
Unable to load NODE with id 14958168.
```
But it succeeds when running without apoc.do.when:
```
LOAD CSV WITH HEADERS FROM 'file:///person.csv' AS row
MATCH (p:Person{id: toInt(row.id)})-[r:LIKES]->()
DELETE r
WITH p WHERE NOT EXISTS((p)-[:LIKES]->())
DETACH DELETE p;
```

**Comment by jexp** [comment]
It is executed for each relationship and on the 2nd run p is already deleted.

Does it also happen if you *don't* return p ?
(Which you don't in the other statement)

**Comment by meilechh** [comment]
@jexp I understand that that's what happening, but why would it be so?  This following query is valid: ```WITH null as n WHERE NOT EXISTS((n)-[:LIKES]->()) DETACH DELETE n```.
Regarding your second question, yes its failing all the time.

**Comment by InverseFalcon** [comment]
@meilechh 

Michael's right. 

If you return before the CALL, you can see that you will have p on multiple rows, for each `r` that you matched to previously:

```
LOAD CSV WITH HEADERS FROM 'file:///person.csv' AS row
MATCH (p:Person{id: toInt(row.id)})-[r:LIKES]->()
DELETE r
RETURN p
```

The difference between the query using `apoc.do.when()` and the query without it is what gets executed, and when.

In the query without the CALL, the WITH and the WHERE NOT EXISTS... execute for all rows of p. And then the DETACH DELETE executes for all rows, which executes just fine even after the first row deletes p.

In the query with the CALL, the entire `apoc.do.when()` executes for each row. After execution for the first row, p is deleted. The second execution has no p to use in the NOT EXISTS predicate, and an error occurs. 

You would see the same thing if you matched to a node, deleted it, and returned a predicate using EXISTS() (or NOT EXISTS()) on a pattern with the deleted node.

**Comment by meilechh** [comment]
@InverseFalcon It makes sense.
Is there a way I can check if the node got deleted?

**Comment by meilechh** [comment]
I gauss the only way to do it would be to add a temporary property and then delete all nodes with this property.

**Comment by meilechh** [comment]
I tried to do this, but it does not work the `:Person` node is not getting delete:
```LOAD CSV WITH HEADERS FROM 'file:///person.csv' AS row
MATCH (p:Person{id: toInt(row.id)})-[r:LIKES]->()
DELETE r
WITH p
CALL apoc.do.when(NOT EXISTS((p)-[:LIKES]->()), "SET p._to_delete = true", "", {p:p}) YIELD value
WITH value
MATCH (p:Person) WHERE p._to_delete
DETACH DELETE p;```

**Comment by meilechh** [comment]
I got it, I had to do an EagerAggregation before the match:
```
LOAD CSV WITH HEADERS FROM 'file:///person.csv' AS row
MATCH (p:Person{id: toInt(row.id)})-[r:LIKES]->()
DELETE r
WITH p
CALL apoc.do.when(NOT EXISTS((p)-[:LIKES]->()), "SET p._to_delete = true", "", {p:p}) YIELD value
WITH count(value) as cnt
MATCH (p:Person) WHERE p._to_delete
DETACH DELETE p;
```

**Comment by InverseFalcon** [comment]
If all you need is to know whether or not the node was deleted, and only delete when there are no :LIKES relationships, you can do that without needing to do additional matches, or even the conditional:

```
LOAD CSV WITH HEADERS FROM 'file:///person.csv' AS row
MATCH (p:Person{id: toInt(row.id)})-[r:LIKES]->()
DELETE r
WITH distinct p
WHERE NOT EXISTS((p)-[:LIKES]->())
DETACH DELETE p
```
