### ISSUE TITLE
apoc.export.csv.all command unresponsive

### ISSUE THREAD

**Issue by amyth** [neo4j-contrib/neo4j-apoc-procedures#583]
Hi, I am trying to export a large neo4j db to a csv file. The total db size is about 122 gigs. The server I am trying to run this on pretty small dev server (2 cores, 8G ram, 500G disk, ubuntu) but I don't see no progress. I understand it may take a long time to process such big data, but it's already been 24 hrs and no progress. Following is a screen shot.

![screenshot](https://s26.postimg.org/kkbsd8wo9/Screen_Shot_2017-09-07_at_10.53.07_AM.png)

I also could not find anything related either in `debug.log` or `neo4j.log`. I am not even sure if this thing is actually processing the data or not as my CPU usage is almost nil. Please see the following screen shot.

![htop cpu/memory usage](https://s26.postimg.org/g0zjrqesp/Screen_Shot_2017-09-07_at_10.56.36_AM.png)

The `exp.csv` has been created but the file size has been `0` ever since. Any inputs will be much appreciated.

**update: version information**

Neo4J : 3.2.3 (Community)
Apoc Procedures: apoc-3.2.0.4-all.jar
OS: Ubuntu 16.04.3 LTS

**Comment by jexp** [comment]
Thanks for your feedback, the current implementation does a double scan to determine property types and counts, so it is probably not well suited for you.

Perhaps this approach is better:

https://neo4j.com/blog/export-csv-from-neo4j-curl-cypher-jq/

**Comment by jexp** [comment]
@neo4j-contrib/larus 

## make export csv all smarter

- similar to export.cypher
- add configuration that avoids double scan by default, only test the first 100 or 1000 nodes
- output into different files per label  / rel type
- process in parallel

**Comment by conker84** [comment]
related to #536
