### ISSUE TITLE
apoc.algo.dijkstra: Failed to call procedure:  RELATIONSHIP has no property with propertyKey

### ISSUE THREAD

**Issue by stdob** [neo4j-contrib/neo4j-apoc-procedures#59]
If one of the relations in the pattern has no properties responsible for the weight, the query produces an error:

```
MATCH (Start:Glycogenesis {title:'Glucose'}), 
             (End:Metabolism {title:'Lipid'})
CALL apoc.algo.dijkstra(Start, End, 'wClass>', 'path_index') YIELD path, weight
RETURN path, weight
```

> Failed to call procedure apoc.algo.dijkstra(startNode :: NODE?, endNode :: NODE?, relationshipTypesAndDirections :: STRING?, weightPropertyName :: STRING?) :: (path :: PATH?, weight :: FLOAT?): RELATIONSHIP[**{id}**] has no property with propertyKey="path_index".
> 
> Neo.ClientError.Procedure.ProcedureCallFailed

**Upd.:**

Adding nodes and relationships:

```
MERGE (Start1:Test {name:'Start1'})
MERGE (Middle1:Test {name:'Middle1'})
MERGE (End1:Test {name:'End1'})
MERGE (Start1)-[:rel {cost: 10}]->(Middle1)-[:rel {cost: 20}]->(End1)

MERGE (Start2:Test {name:'Start2'})
MERGE (Middle2:Test {name:'Middle2'})
MERGE (End2:Test {name:'End2'})
MERGE (Start2)-[:rel {cost: 10}]->(Middle2)-[:rel]->(End2)
```

This query is executed without error:

```
MATCH (Start:Test {name:'Start1'}), (End: Test {name:'End1'})
CALL apoc.algo.dijkstra(Start, End, 'rel>', 'cost') YIELD path, weight
RETURN path, weight
```

But this query again gives the same error (`RELATIONSHIP[...] has no property with propertyKey="cost".`):

```
MATCH (Start:Test {name:'Start2'}), (Middle: Test {name:'Middle2'})
CALL apoc.algo.dijkstra(Start, Middle, 'rel>', 'cost') YIELD path, weight
RETURN path, weight
```

**Comment by jexp** [comment]
That's what `dijkstraWithDefaultWeight` is for.

```
apoc.algo.dijkstraWithDefaultWeight(startNode, endNode, 'KNOWS|<WORKS_WITH|IS_MANAGER_OF>', 'distance', 10) YIELD path, weight
```

**Comment by stdob** [comment]
Thank you, but I know about it. I think, nevertheless, it is not quite correct behavior of the procedure: it would be appropriate not to throw an exception if the property is not found, but reject (filter) this pattern (path). 

In fact, the output will only include those paths in which every relationship has a property responsible for the weight, and this property is a number.

**Comment by jexp** [comment]
Ok, fair point.

**Comment by sarmbruster** [comment]
How about using dijekstraWtihDefaultWeight with a very high default value? This way the given relationship should never become a shortest path. Would this be good enough?

**Comment by jexp** [comment]
@stdob what do you think about @sarmbruster's suggestion?

**Comment by stdob** [comment]
@jexp Works, but, in my opinion, this is a workaround ...

**Comment by maxlazarus** [comment]
I agree, if there is no valid property with a numerical value this should fail properly and filter the path. High default weight is a bit of a hack.
