### ISSUE TITLE
add apoc.convert.toInteger function that converts any object into a whole number

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#593]
* boolean : true=1, false = 0
* string -> parseLong
* Number -> longValue
* other -> parseLong(toString())
* perhaps support hex too
* possibly remove non digit characters
* if we were funny we could even support some basic calculations in strings :)

same for toFloat

**Comment by dodie** [comment]
Hi @jexp ! I'd work on this feature if it ok for you!

**Comment by zygm0nt** [comment]
There's a commit update in connected PR.

**Comment by albertodelazzari** [comment]
Can we close also this issue?
