### ISSUE TITLE
Neo4j 3.3 support

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#595]
See the branch: https://github.com/neo4j-contrib/neo4j-apoc-procedures/tree/3.3

I fixed the compile errors, but there are about 90+ test errors, some are in Neo4j, others have to be resolved.

@pontusmelke worked on this here, which we can try to apply in a local neo4j build
https://github.com/neo4j/neo4j/pull/10077

**Comment by agalazis** [comment]
so is 3.3 supported ? I feel quite puzzled. what is this then? :https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/3.3.0.1/apoc-3.3.0.1-all.jar

**Comment by jexp** [comment]
Yes
