### ISSUE TITLE
apoc.import.file.use_neo4j_config=true does not work as expected

### ISSUE THREAD

**Issue by tomasonjo** [neo4j-contrib/neo4j-apoc-procedures#597]
I am using neo4j CE 3.2.3 with the latest build APOC for 3.2 branch.

Following example from https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/3.2/src/test/java/apoc/config/ConfigTest.java
I have set the conf to:
```
dbms.directories.import=import
dbms.security.allow_csv_import_from_file_urls=true
apoc.import.file.use_neo4j_config=true
```

If I try to import a json file like this:

```
CALL apoc.load.json("file:///business.json") YIELD value
return value limit 5
```

I get an error stating:

> Failed to invoke procedure `apoc.load.json`: Caused by: java.lang.RuntimeException: Import from files not enabled, please set apoc.import.file.enabled=true in your neo4j.conf

After setting this conf in the neo4j.conf importing jsons works, but I have to specify full machine length, instead of `load.json` using the default directory specified by `dbms.directories.import=import`, which would allow me to use calls like below for files in `import` folder:

```
CALL apoc.load.json("file:///business.json") YIELD value
return value limit 5
```

**Comment by jexp** [comment]
@tomasonjo did you change it in the right config file? You know there is that issue with the different config files esp. in CE in Neo4j-Desktop
