### ISSUE TITLE
Add support for pearson similarity measure

### ISSUE THREAD

**Issue by tomasonjo** [neo4j-contrib/neo4j-apoc-procedures#599]
It would be cool to have a procedure that calculated [Pearson correlation coefficient](https://en.wikipedia.org/wiki/Pearson_correlation_coefficient) so that we could use it for creating networks.
It fits in the "similarity","distance" club like  `apoc.algo.PearsonSimilarity([1,2],[2,3])`

**Comment by jexp** [comment]
It's in graph algos now.
