### ISSUE TITLE
add a configuration option to mergeNodes that allows to combine relationships of the same type and direction

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#600]
So in case of duplicate relationships you don't end up with several of them at the end.

The default would be to not change them
And then there would be the option to combine them by type/direction if the properties are the same
And combine them if the properties differ and then apply the refactoring-config property merge thing

**Comment by sylvainroussy** [comment]
Do you want something like that?

```
apoc.refactor.mergeNodes([node1,node2], config)
```

Where config looks like:
```
{
   mergeRelationships : "none | identical | merge"
}

with Exception if two properties with same keys have different values.

**Comment by AngeloBusato** [comment]
@jexp mergeRelationships works with rels who has the same start and the same end nodes. So in this case we have to merge end/start nodes too. Right?

**Comment by jexp** [comment]
This issue talks about `mergeNodes` not `mergeRelationships` ?

**Comment by jexp** [comment]
I think it's better to have this explicit.

I.e. `mergeNodes` on node 1 and then `mergeNodes` on node 2 

should leave the relationships in middle merged.
