### ISSUE TITLE
Missing tests for import file from folder (csv, json and xml)

### ISSUE THREAD

**Issue by DanielBerton** [neo4j-contrib/neo4j-apoc-procedures#605]
Add tests for  `apoc.load.csv`, `apoc.load.json`  and `apoc.load.xml`
Set a constraint in a specific folder, and test the relative path.
Configuration example for tests: 
```
.setConfig("apoc.import.file.enabled","true")
.setConfig("apoc.import.file.use_neo4j_config", "true")
.setConfig("dbms.directories.import", "build/resources/test")
.setConfig("dbms.security.allow_csv_import_from_file_urls","true")
```
Test the relative path `CALL apoc.load.json("file://map.json")` and the exception if we try to use a full path.

**Comment by conker84** [comment]
closed via 3558084
