### ISSUE TITLE
Add arabic <-> roman numeral conversion

### ISSUE THREAD

**Issue by steffenkoenig** [neo4j-contrib/neo4j-apoc-procedures#608]
On a small project I use arabic and roman numerals. Filtering for a range of roman numbers currently forces me to store both types. 

A really simplified version of what I want 
MATCH (t:Test) WHERE t.number <= apoc.RomanToArabic("IV")  AND t.number >= apoc.RomanToArabic("X") RETURN t
or
CREATE (t:Test {number: apoc.ArabicToRoma(5)}) RETURN t

**Comment by zygm0nt** [comment]
I've added a PR to resolve this ticket.
