### ISSUE TITLE
Export file location

### ISSUE THREAD

**Issue by szarnyasg** [neo4j-contrib/neo4j-apoc-procedures#609]
The export commands seem to save the file to whichever directory Neo4j was started from.

So if I restart Neo4j from a particular directory:

```
/home/szarnyasg/asdf $ ~/neo4j/bin/neo4j restart`
```

And export a file like this:

```
CALL apoc.export.cypher.all('my.cypher', {})
YIELD file, source, format, nodes, properties, time, rows, relationships as rels
RETURN *
```

It will end up in that directory.

```
/home/szarnyasg/asdf $ ll my.cypher 
-rw-r--r-- 1 szarnyasg szarnyasg 7037 Sep 26 18:27 my.cypher
```

This took me some time to figure out. Is this intentional? Or maybe this should be clarified in the docs? (If so, I'm happy to submit a PR.)

**Comment by DanielBerton** [comment]
@szarnyasg if you don't give a path for the export file like:

```
CALL apoc.export.cypher.all('/home/user/Programs/neo4j-3.2.3/my.cypher', {})
YIELD file, source, format, nodes, properties, time, rows, relationships as rels
RETURN *	
```

it use the directory where neo4j has started, the same for the other exports :`csv`, `graphml`.
Is not intentional, no default folder is set for the file
