### ISSUE TITLE
There is no procedure with the name `apoc.algo.allSimplePaths` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.

### ISSUE THREAD

**Issue by gongotar** [neo4j-contrib/neo4j-apoc-procedures#61]
When I try to call allSimplePath in my query I get the following error:
There is no procedure with the name `apoc.algo.allSimplePaths` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.

Here is my query:
match (from:STATION{name:"s3"}),  (to:STATION{name:"s7"}) 
CALL apoc.algo.allSimplePaths(from, to, '<L2S|L2S>', 10) yield path as path, weight as weight 
return path ORDER BY length(path) asc limit 100

**Comment by jexp** [comment]
How did you install it. This was not yet released.

**Comment by jexp** [comment]
Build it locally or wait for the next release please.

**Comment by jexp** [comment]
Resolved with the 1.1.0 release: https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/latest
