### ISSUE TITLE
JDBC Type Conversation Issues from Oracle

### ISSUE THREAD

**Issue by bradnussbaum** [neo4j-contrib/neo4j-apoc-procedures#610]
1. Apoc is not handling Oracle Timestamps
~~2. Apoc is not handling Oracle Number (converts to String)~~
~~3. Apoc is not handling correct character encoding~~

**Comment by bradnussbaum** [comment]
Removed character encoding issue - confirmed this is working as expected when connecting to Oracle db. In this case, Oracle was using AL32UTF8.

> --Oracle UTF8 is Unicode revision 3.0 in 8.1.7 and up. AL32UTF8 is updated with newer Unicode versions in each major release, in Oracle RDBMS 12.1 it is updated to Unicode 6.1,
> Besides the difference in Unicode version the "big difference" between UTF8 and AL32UTF8 is that AL32UTF8 has build in support for "Supplementary characters" who are encoded using "Surrogate Pairs" ( also wrongly known as "Surrogate characters") .
> Oracle UTF8 (Unicode 3.0) stores supplementary characters as 2 characters, totalling 6 bytes, using "modified UTF-8" instead of the "standard UTF-8" (implemented in Oracle 9.2 and up using AL32UTF8 ) of 4 bytes for a supplementary character.
> This "modified UTF-8" is also called CESU-8 .
>  
> Practically this means that in 99% of the data UTF8 and AL32UTF8 are the same for *storing* data.Only supplementary characters differ in the actual stored bytes/codes between UTF8 and AL32UTF8.


> The JDBC drivers perform all character set conversions transparently. No user intervention is necessary for the conversions to occur.
https://docs.oracle.com/cd/A81042_01/DOC/java.816/a81354/advanc1.htm#1003420

**Comment by bradnussbaum** [comment]
~~2. Apoc is not handling Oracle Number (converts to String)~~
Removed Number conversion to String as there isn't a sensible automatic way to convert an Oracle Number to Neo4j native property at this time e.g. java BigDecimal is not a supported type.

From @jexp:
We can do: convert to long if precisions == 0 and it fits into a long otherwise string
convert to double if there is no loss of precision from the conversion otherwise string
and/or provide a mapping to load-jdbc that's adhered to
the "otherwise string" can result in half the properties being longs and half being strings if you think about incrementing id's (if the id's exceed 2^64)

**Comment by bradnussbaum** [comment]
1. Apoc is not handling Oracle Timestamps

It's possible to convert native Oracle Timestamp during the SQL select of an apoc.jdbc.load call. For example, a column Q_TIMESTAMP could be selected as follows:
`TO_CHAR(Q_TIMESTAMP, ‘yyyy-mm-dd”T”HH24:MI:SS.ff3"Z”‘) AS Q_TIMESTAMP`

**Comment by davidfauth** [comment]
JDBC driver from Oracle returns TIMESTAMP (oracle only) instead of compliant java.sql.Timestamp
* Would require  `import oracle.sql.TIMESTAMP;`
* Or see the first answer here:
https://stackoverflow.com/questions/13269564/java-lang-classcastexception-Oracle-sql-timestamp-cannot-be-cast-to-java-sql-ti

**Comment by sarmbruster** [comment]
don't like the idea of hardly depending on oracle driver classes here.
By setting `-Doracle.jdbc.J2EE13Compliant=true` you'd get back something extending `java.sql.Timestamp`, see https://stackoverflow.com/a/22055190/158701
I suggest that we add to the apoc docs that users of Oracle should amend to their neo4j.conf:
 `dbms.jvm.additional=-Doracle.jdbc.J2EE13Compliant=true`
