### ISSUE TITLE
Pipe | cannot be used as array separator in apoc.load.csv procedure

### ISSUE THREAD

**Issue by IraRe** [neo4j-contrib/neo4j-apoc-procedures#626]
In my CSV file, I have a column PumMedIDs with ids separated by '|'
I tried following import statement:
```
CALL apoc.load.csv(
    'file:///file.csv',
    {arraySep:'|',mapping:{PubMedIDs:{array:true,arraySep:'|'}}})
YIELD lineNo, list, map
RETURN lineNo, map.PubMedIDs, limit 20
```
Unfortunately, the pubMedIDs get separated by every character and not by the separator.
By using `\|` as separator I get:
```
Invalid input '|': expected '\', ''', '"', 'b', 'f', 'n', 'r', 't', UTF16 or UTF32 (line 3, column 17 (offset: 109))
"    {arraySep:'\|',mapping:{PubMedIDs:{array:true,arraySep:'\|'}}})"
```
and using `\\|` results in
```
Failed to call procedure `apoc.load.csv(url :: STRING?, config :: MAP?) :: (lineNo :: INTEGER?, list :: LIST? OF ANY?, map :: MAP?)`: Unexpected internal error near index 1
\
```
The split function works just fine with pipes |
So, I just added the PubMedIDs as it is, and splitted the property afterwards.

The CSV I have used can be found here:
[http://ctdbase.org/downloads/#top](URL)

**Comment by jexp** [comment]
solution: switch to Pattern.split(value) here https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/3.2/src/main/java/apoc/load/LoadCsv.java#L93

and add a test

**Comment by IraRe** [comment]
Hello everyone! 
I know the issue is already closed, but I actually got back to the same import and I still cannot use | (pipe) as an array separator. Here is my cypher load query:
```
CALL apoc.load.csv('http://ctdbase.org/reports/CTD_chemicals.csv.gz',
{sep:",",skip:29,limit:5,header:false,arraySep:'|'}) 
YIELD lineNo, list 
return list[0] as ChemicalName, list[1] as ChemicalID, list[2] as CasRN, 
list[3] as Definition, list[4] as ParentIDs, list[5] as TreeNumbers, 
list[6] as ParentTreeNumbers, list[7] as Synonyms, list[8] as DrugBankIDs
```
I don't get any error messages anymore, but the arrays (Synonyms, TreeNumbers, etc) don't get actually splitted and get returned as a string.
