### ISSUE TITLE
String normalisation

### ISSUE THREAD

**Issue by legraphista** [neo4j-contrib/neo4j-apoc-procedures#628]
Any plans to support string normalisation? 
```
NFC — Normalization Form Canonical Composition.
NFD — Normalization Form Canonical Decomposition.
NFKC — Normalization Form Compatibility Composition.
NFKD — Normalization Form Compatibility Decomposition.
```

Thank you for the great work that has been poured into this project!

**Comment by legraphista** [comment]
Hmm 🤔 
I found the code [here](https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/3.1/src/main/java/apoc/text/Strings.java#L88-L91) but when calling `apoc.text.clean("test")` it returns an unregistered procedure error.

I'm using the following: 
Neo4j: 3.1.7
Apoc: 3.1.3.8-all

**Comment by legraphista** [comment]
Closed in favour of #629

**Comment by jexp** [comment]
@legraphista is there a Java library that does these? 

That one is a user definined function now. You can use `RETURN apoc.text.clean("test")`

**Comment by legraphista** [comment]
Yes @jexp, I used it. 
It does NFD as expected, but after cleaning it up it also strips the text out of any non-alphanumeric characters  [at this line](https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/3.1/src/main/java/apoc/text/Strings.java#L167). 

I think there should be an option to toggle the stripping of non-alphanumeric characters.

For example if you want to clean a sentence, you need to split it, clean it word by word then join it back together.
