### ISSUE TITLE
APOC maven build fails apoc.gephi.GephiTest

### ISSUE THREAD

**Issue by guglielmo** [neo4j-contrib/neo4j-apoc-procedures#64]
Just pulled the master branch, and tried to build the jar with

    mvn clean install

I get the following error in tests:

    Results :

    Tests in error: 
      testAdd(apoc.gephi.GephiTest): Failed to invoke procedure `apoc.gephi.add`: Caused by: java.lang.RuntimeException: Can't read url http://localhost:8080/workspace1?operation=updateGraph as json

    Tests run: 317, Failures: 0, Errors: 1, Skipped: 9

    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 01:48 min
    [INFO] Finished at: 2016-07-12T17:40:35+02:00
    [INFO] Final Memory: 18M/437M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project apoc: There are test failures.
    [ERROR] 
    [ERROR] Please refer to /Users/gu/Workspace/neo4j-apoc-procedures/target/surefire-reports for the individual test results.
    [ERROR] -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

This is the file in surefire-reports:
[apoc.gephi.GephiTest.txt](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/359750/apoc.gephi.GephiTest.txt)

**Comment by guglielmo** [comment]
For newbies: gephi must be installed if you want to compile neo4j-apoc.
The Graph Streaming plugin must be installed and the streaming master must be started within Gephi, too.

Follow the instructions on the main neo4j-apoc documentation, and you'll be ok.

I guess this dependence should be marked as a pre-requisite.

**Comment by jexp** [comment]
Thanks for raising it, it should also work without then, it skips the test. 

But there was a change in the exception that was thrown in case of refused connections.
