### ISSUE TITLE
couchbase connectivity

### ISSUE THREAD

**Issue by graphadvantage** [neo4j-contrib/neo4j-apoc-procedures#645]
Hi

I need some guidance on how to use apoc.couchbase with couchbase 4.6 and 5.

5 has deprecated bucket passwords in favor of user passwords
4.6 has bucket passwords using sasl auth

Please provide an example of proper connection syntax for each version (eg with bucket passwords for 4.6 and without bucket passwords for 5.0)

https://forums.couchbase.com/t/running-n1ql-via-rest-api-with-bucket-password/12084/2

I'd also like some guidance on proper versions of java-client, core-io and rx-java for both 4.6 and 5.0

thanks for your help!

Michael

**Comment by inserpio** [comment]
Hi Michael, I'll ping you back later for any clarification (dinner time for me now), but I haven't tested the apoc with couchbase 5, maybe some adjustment are required.

Lib versions are documented in the apoc guide

**Comment by graphadvantage** [comment]
Hi Lorenzo,

Thanks!

Here's a 4.6 bucket called amazon, configured with a password "couchdb"
{"name":"amazon","bucketType":"membase","authType":"sasl","saslPassword":"couchdb","proxyPort":0,"replicaIndex":false,"uri":"/pools/default/buckets/amazon?

Here's a 5 bucket, made in 5 with no password
{"name":"amazon1","bucketType":"membase","authType":"sasl","proxyPort":0,"uri":"/pools/default/buckets/amazon1?

Here's a 4.6 bucket, upgraded to 5, password now stripped
{"name":"amazon","bucketType":"membase","authType":"sasl","proxyPort":0,"uri":"/pools/default/buckets/amazon?

Connecting in 5 to the default bucket
```
CALL apoc.couchbase.exists(['127.0.0.1:8091','Administrator','couchdb'],'default', 'key::AZZZOVIBXHGDR_B00BJZ5C12') yield value RETURN value
```
Failed to invoke procedure `apoc.couchbase.exists`: Caused by: java.lang.RuntimeException: java.util.concurrent.TimeoutException

Connecting in 5 to a new (or upgraded) bucket
```
CALL apoc.couchbase.exists(['127.0.0.1:8091','Administrator','couchdb'],'amazon1', 'key::AZZZOVIBXHGDR_B00BJZ5C12') yield value RETURN value
```
Failed to invoke procedure `apoc.couchbase.exists`: Caused by: com.couchbase.client.java.error.InvalidPasswordException: Passwords for bucket "amazon1" do not match.

logs show
2017-11-04 01:05:16.503+0000 WARN  [null][KeyValueEndpoint]: Authentication Failure.
2017-11-04 01:05:16.511+0000 WARN  Unknown ResponseStatus with Protocol HTTP: 401
2017-11-04 01:05:16.515+0000 WARN  Unknown ResponseStatus with Protocol HTTP: 401

I'm using java-client-2.3.1, core-io-1.3.1, rxjava-1.1.5

If I upgrade any of these, I get a null-pointer exception.

Thanks 

Michael

**Comment by graphadvantage** [comment]
Hi Lorenzo - just checking on this, were you able to reproduce this?

**Comment by graphadvantage** [comment]
Hi @inserpio, @jexp 

Were you able to confirm?

Thanks

Michael

**Comment by inserpio** [comment]
Yeah, that's correct. We're thinking about how to manage different apoc vs difference couchbase versions. We need to combine both...
Anyway in the meantime I can provide you an updated version of apoc on the fly.
Which neo4j version do you use?

**Comment by graphadvantage** [comment]
I'd love builds for 3.3.0 and 3.2.7 - thanks -Michael

**Comment by inserpio** [comment]
Hi @graphadvantage, could you try with the attached distribution?
It contains an upgraded version of the couchbase procedures with their dependencies.
Just unzip it into the plugin folder.

I introduced the two new parameters `username` and `password` to all procedures, right after the `bucket` parameter. For example:

`CALL apoc.couchbase.get(['localhost'], 'default', 'apoc', 'couchbase', 'artist:vincent_van_gogh')`,
where `apoc` is the user and `couchbase` the password granted for accessing the `default` bucket.

**If you want to skip the authentication phase (mostly for backward compatibility) then you just have to pass null for both username and password**.

Waiting for your feedback!
Thanks,
Lorenzo

[apoc-3.2.3.5-all.zip](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/1486131/apoc-3.2.3.5-all.zip)

**Comment by graphadvantage** [comment]
Hi @inserpio 

Thanks Lorenzo, this is great! - if you wouldn't mind making a 3.3 build I'll test that as well (I use both versions).

Thanks,

Michael

**Comment by graphadvantage** [comment]
Tested on Couchbase 5 with 3.2.7 - works well, thank you.

```
CALL apoc.couchbase.query(['127.0.0.1'],'my_bucket','neo4j','couchdb','SELECT * FROM `my_bucket` WHERE field_id = "0738710423"') yield queryResult
RETURN queryResult
```

```
CALL apoc.couchbase.get(['127.0.0.1'],'my_bucket','neo4j','couchdb', 'some_doc_id') YIELD content
RETURN content
```

```
CALL apoc.couchbase.exists(['127.0.0.1'],'my_bucket','neo4j','couchdb', 'some_doc_id') YIELD value
RETURN value
```

```
WITH {some_key: "some_string"} AS map, "some_doc_id" as doc_id
WITH doc_id, apoc.convert.toJson(map) AS json
CALL apoc.couchbase.insert(['127.0.0.1'],'my_bucket','neo4j','couchdb', doc_id, json) yield id, expiry, cas, mutationToken, content
RETURN id, expiry, cas, mutationToken, content
```

Thanks! Michael

**Comment by jexp** [comment]
@graphadvantage  how do the 3.2.x and 3.3.x fail with the couchbase 5.0 driver ?
I'm not sure what our difference is between 3.1.x and the other versions that makes it fail.

**Comment by jexp** [comment]
@inserpio to capture  different couchbase versions, if needed we can do:

1. create an interface that contains the different operations we need
2. have several implementations for the different couchbase drivers
3. try to instantiate the newest variant and on failure try the next older version, until it matches the one that the user provided as jar or none matching is found then it should fail.

**Comment by graphadvantage** [comment]
@jexp I think @inserpio 's changes for 3.2.7 worked, perhaps if you just pull them into a 3.3 branch I'm happy to test. The main difference is that CB deprecated bucket level auth in favor of more general RBAC model.  So now basic auth is required.

**Comment by InverseFalcon** [comment]
Hello, checking for a status on this one.

Also requesting clearer documentation of which versions / approaches are supported, and corresponding examples.

We seem to reference this in the current APOC docs, would be good to know how this fits into what's currently supported, and how to use it:

`apoc.couchbase.<key>.uri=couchbase-url-with-credentials`
