### ISSUE TITLE
Typos in Algos section of docs

### ISSUE THREAD

**Issue by qosmy-michael** [neo4j-contrib/neo4j-apoc-procedures#65]
Hi,

found a couple typos in the docs...

MATCH (node:Node)
WHERE node.id %2 = 0
WITH collect(node) AS nodes
CALL apoc.algo.closeness(['TYPE'],nodes,INCOMING) YIELD node, score
RETURN node, score
ORDER BY score DESC

should read
--> CALL apoc.algo.closeness(['TYPE'],nodes,'INCOMING') YIELD node, score

MATCH (node:Node)
WHERE node.id %2 = 0
WITH collect(node) AS nodes
CALL apoc.algo.betweenness(['TYPE'],nodes,BOTH) YIELD node, score
RETURN node, score
ORDER BY score DESC

should read
--> CALL apoc.algo.betweenness(['TYPE'],nodes,'BOTH') YIELD node, score

thanks!

**Comment by jexp** [comment]
Thanks a lot for reporting, I'll fix it.

Michael

**Comment by qosmy-michael** [comment]
Hi Michael

Just closed it thanks!

Thanks,

Michael

Michael Moore, Ph.D.
Founder/CEO
Qosmy, Inc.
415 516 0255
michael@qosmy.com
http://www.qosmy.com

“The Voice of Every Customer"

**Comment by jexp** [comment]
Done.

**Comment by qosmy-michael** [comment]
Hi Michael

I thought I would share that I really enjoyed your article on the Galaxy visualization with ngraph  & vivagraph.js  –  good stuff, really nice visualization tools.

I used it with a couple of tweaks to visualize one of my client’s graphs, they really liked it.

Thanks
Michael

Michael Moore, Ph.D.
Founder/CEO
Qosmy, Inc.
415 516 0255
michael@qosmy.com
http://www.qosmy.com

“The Voice of Every Customer"

**Comment by jexp** [comment]
Thanks so much! Very appreciated 

Keep the feedback coming. 

Just as a note that amazing three.js viz was not mine. I'm not good enough at design for that. 

Von meinem iPhone gesendet
