### ISSUE TITLE
Configuration of export CSV is inconsistent with the docs

### ISSUE THREAD

**Issue by szarnyasg** [neo4j-contrib/neo4j-apoc-procedures#652]
Using this single node as the sample dataset:
```
CREATE (:SomePerson {id: 1, name: 'John'})
```
Exporting to CSV does not work as specified in the docs (Table 8 in [Export/Import](https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_export_import)):

```
CALL apoc.export.csv.query('MATCH (x:SomePerson) RETURN x.id, x.name', 'file.csv', {delim: ';'})
```

This should give a CSV with semicolons and without quotes. Instead, it gives:
```
"x.id","x.name"
"1","John"
```

After diving into the code a bit, I realized that I should look around the `ExportConfig` class:

https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/37034baf539a4957c0a11fde2fc461ef5ab71b24/src/main/java/apoc/export/util/ExportConfig.java#L59-L70

This suggests that the delimiter is defined by `d` and indeed it is:
```
CALL apoc.export.csv.query('MATCH (x:SomePerson) RETURN x.id, x.name', 'file.csv', {d: ';'})
```
This results is:
```
"x.id";"x.name"
"1";"John"
```

Quotes are supposed to be defined by the `quotes` boolean library, but I could not turn them off with `quotes: false`.

**Comment by jexp** [comment]
@szarnyasg Would you mind fixing both (support `d` and `delim`) and fix the quotes config
 if you are looking at the code already?

**Comment by szarnyasg** [comment]
@jexp I'm looking into it this morning. It seems there are multiple issues: the `useTypes` field does not work either:

```
CALL apoc.export.csv.query(
  "MATCH (u:User) return u.age, u.name, u.male, u.kids, labels(u)",
  "query.csv",
  {useTypes: true, d: '|', quotes: false}
)
```

```
"u.age"|"u.name"|"u.male"|"u.kids"|"labels(u)"
"42"|"foo"|"true"|"[""a"",""b"",""c""]"|"[""User""]"
"42"|"bar"|""|""|"[""User""]"
"12"|""|""|""|"[""User""]"
```

**Comment by szarnyasg** [comment]
I looked into it. The delimiter issue was trivial to fix. However, without the quotes, the [opencsv](http://opencsv.sourceforge.net/) 2.3 library does not work correctly when quotes are turned off: the separator character is not escaped.

The opencsv 2.3 library was releasd in 2011, so I was suspicious that this issue has been fixed since then. To demonstrate this, I created an example project that has both opencsv 2.3 (`net.sf.opencsv`) and 4.0 (`com.opencsv`) as a dependency: https://github.com/szarnyasg/opencsv-test/tree/master/src/test/java

The results show the difference.

```$ head /tmp/my*csv
==> /tmp/my23.csv <==
Foo Bar,Bar, F.,123

==> /tmp/my40.csv <==
Foo Bar,Bar\, F.,123
```

@jexp do you think it would be possible to update the opencsv dependency in APOC?

**Comment by szarnyasg** [comment]
By the way, I checked the dependency tree: https://gist.github.com/szarnyasg/79f4e612169dccd86232ffd793107375

opencsv is a transitive dependency of `org.neo4j:neo4j-cypher`, defined here: https://github.com/neo4j/neo4j/blob/3128665316c75295d156511098ae11b5634700de/pom.xml#L1030 and here: https://github.com/neo4j/neo4j/blob/3128665316c75295d156511098ae11b5634700de/community/cypher/cypher/pom.xml#L341

**Comment by szarnyasg** [comment]
See PR https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/879

**Comment by szarnyasg** [comment]
Eventually, PR #12009 was closed as wontfix, so this issue will require another round of thinking.

**Comment by jexp** [comment]
@mneedham we need to expose the config options of export csv in the docs (see above).
Esp. quoting / escaping seems important.
