### ISSUE TITLE
Non-deterministic PageRank implementation

### ISSUE THREAD

**Issue by szarnyasg** [neo4j-contrib/neo4j-apoc-procedures#658]
The [`shouldGetPageRankWithCypherExpectedResultWithoutNodesParallel` test method](https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/3.2/src/test/java/apoc/algo/PageRankTest.java#L182) in `apoc.algo.PageRankTest` fails sometimes. This is quite difficult to reproduce, but as a quick-and-dirty approach, I did the following:

- I deleted the classes for all other tests.
- Ran the tests in Bash until they failed with `while ./gradlew clean test; do :; done`.

The first 23 succeeded but the 24th failed. See the output at https://gist.github.com/szarnyasg/ce75bb618e335ff392e07a61260bdc83, and also the related [branch](https://github.com/szarnyasg/neo4j-apoc-procedures/tree/nondet-pagerank-test) in my fork.

The tests failed on the following assertion:

```
java.lang.AssertionError: expected:<2.87711> but was:<3.60256>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:553)
	at org.junit.Assert.assertEquals(Assert.java:683)
	at apoc.algo.PageRankTest.shouldGetPageRankWithCypherExpectedResultWithoutNodesParallel(PageRankTest.java:192)
```

When it failed for the first time (before I started deliberately testing for it), I got a completely different PageRank value, so it can fail with many different values.

```
java.lang.AssertionError: expected:<2.87711> but was:<0.81203>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:553)
	at org.junit.Assert.assertEquals(Assert.java:683)
	at apoc.algo.PageRankTest.shouldGetPageRankWithCypherExpectedResultWithoutNodesParallel(PageRankTest.java:192)
```

This suggests that the PageRank implementation is nondeterministic under some circumstances. Of course, parallel execution is the biggest suspect (is parallel execution set by `batchSize:3`? I cannot find it in the [docs](https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_pagerank_algorithm)).

**Comment by szarnyasg** [comment]
As a larger issue, many tests are highly non-deterministic, which makes the build fail often: https://travis-ci.org/neo4j-contrib/neo4j-apoc-procedures/builds
This makes it difficult to track changes, bisect, etc.

**Comment by jexp** [comment]
Ignore that. 
The Apoc PR will go away anyway.

Yes most likely parallel execution.

**Comment by szarnyasg** [comment]
@jexp I see - this makes sense with the dedicated graph algo library. I am closing this as WONFIX.
