### ISSUE TITLE
apoc.export.cypher exports with upper case :BEGIN :COMMIT

### ISSUE THREAD

**Issue by sylvainroussy** [neo4j-contrib/neo4j-apoc-procedures#659]
Hi,

Using _apoc.export.cypher_ procedures with _cypher-shell_ format exports cypher-shell statements in upper case. But the cypher-shell wants these statements in lower case.

Neo4j v3.3.0-enterprise
Apoc v 3.3.0.1

**Comment by jexp** [comment]
Thanks for spotting Sylvain, would you mind sending a PR?

**Comment by sylvainroussy** [comment]
Sure, done.

**Comment by jexp** [comment]
Fixed by #662
