### ISSUE TITLE
apoc.export.graphml.query

### ISSUE THREAD

**Issue by jasonumd** [neo4j-contrib/neo4j-apoc-procedures#667]
When I call apoc.export.graphml.query I continuously get the following error:

Failed to invoke procedure `apoc.export.graphml.query`: Caused by: java.lang.RuntimeException: Import from files not enabled, please set apoc.import.file.enabled=true in your neo4j.conf

I've placed both apoc.import.file.enabled=true AND apoc.export.file.enabled=true at various places of my neo4j.conf file, but still can't execute a call to apoc.export.graphml.query.

Windows 7
neo4j 3.3.0
apoc 3.3.0.1

**Comment by jexp** [comment]
Are you using neo4j desktop?

Von meinem iPhone gesendet

**Comment by jasonumd** [comment]
No, just the straight 3.3.0 Community Edition.

**Comment by jasonumd** [comment]
CE Windows installers used to be available on this page, but now have disappeared. I assume because of the new Desktop version.

https://neo4j.com/download/other-releases/

**Comment by jexp** [comment]
The config file is somewhere else with the old installer

https://neo4j.com/docs/operations-manual/current/configuration/file-locations/

**Comment by jasonumd** [comment]
I'm editing the following file:

C:\Users\Jason\AppData\Roaming\Neo4j Community Edition\neo4j.conf

This is based on clicking Options -> Edit from the opening neo4j screen. So this falls in line with the link you sent. Still, not working.

**Comment by jexp** [comment]
Can you also check the plugin location? And compare it with the docs link.
It has to be in:

* Windows: `C:\Program Files\Neo4j CE <version>\plugins`

In general try to migrate away from the old Installer app, it's user experience is really not great.

**Comment by jasonumd** [comment]
I uninstalled the Windows Community Edition version and installed the Neo4j Desktop version and got it to work. So I would say this issue can be closed. Especially since it looks like the desktop version is the new way.

**Comment by jexp** [comment]
Thank you!
