### ISSUE TITLE
Kindly remove the reference to apoc.version() functions from Readme. There is no such function.

### ISSUE THREAD

**Issue by oberoivarun** [neo4j-contrib/neo4j-apoc-procedures#668]
I installed APOC on docker and was testing whether it was working properly or not using the `return apoc.version()` statement. Only to realize hours later that there is no such function. At least on version 3.1.2.5 for Neo4J version 3.1.2.

Please either remove it or add a clause to it.

Thanks

**Comment by jexp** [comment]
Not for the older version, no, only for 3.2.x we can port it back.

**Comment by conker84** [comment]
I'm closing this as it's quite old
