### ISSUE TITLE
apoc.algo.cover failing with runtime exception

### ISSUE THREAD

**Issue by qosmy-michael** [neo4j-contrib/neo4j-apoc-procedures#67]
Hi Michael,

from the 1.1 release

MATCH (n:TestData) CALL apoc.algo.cover(n) YIELD rel RETURN *

Failed to invoke procedure `apoc.algo.cover`: Caused by: java.lang.RuntimeException: Can't convert class org.neo4j.kernel.impl.core.NodeProxy to a stream of long ids

thanks

Michael

**Comment by ikwattro** [comment]
Hi @qosmy-michael, seems like the documentation is misleading.

You need to pass a collection of ids to the procedure : 

```
MATCH (n:TestData) WITH collect(id(n)) as nodes CALL apoc.algo.cover(nodes) YIELD rel RETURN *
```

**Comment by qosmy-michael** [comment]
aha  - thanks!
