### ISSUE TITLE
Release link to version 3.1.3.9 404's

### ISSUE THREAD

**Issue by jsmonet** [neo4j-contrib/neo4j-apoc-procedures#680]
I might just be jumping the gun on an unpublished release, but the link to 3.1.3.9 404's and that release isn't showing on the releases page. Any insight? 

Thanks, folks

**Comment by jexp** [comment]
The last 3.1 release was this:
https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/tag/3.1.3.8
