### ISSUE TITLE
Missing Procedures

### ISSUE THREAD

**Issue by jkassis** [neo4j-contrib/neo4j-apoc-procedures#685]
i've got apoc, but not apoc.map procedures.

![image](https://user-images.githubusercontent.com/3630156/33538017-e03a44d4-d873-11e7-9704-112fdf3d309a.png)

**Comment by InverseFalcon** [comment]
No issue here, `apoc.map.*` are functions, not procedures (same goes with the rest of the helper functions). They can be called inline just like any other function, without needing CALL or YIELD.

You can see these with `CALL dbms.functions()`
