### ISSUE TITLE
add support for repeating patterns to expand

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#691]
I know that the traversal-fw has been used for that where you pass an array of rel-types (and/or) labels and then fit the path-index to index of that array modulo array length

like: `"<FROM,TO>" with an similar syntax for labels, 

or just allow cypher pattern syntax in general

`(:Airport)<-[:FROM]-(:Flight)-[:TO]->(:Airport)`

**Comment by InverseFalcon** [comment]
Implemented by #739
