### ISSUE TITLE
CALL apoc.load.json path ignores config file setting

### ISSUE THREAD

**Issue by jphare** [neo4j-contrib/neo4j-apoc-procedures#70]
Great set of stored procs!

I noticed a small issue with CALL apoc.load.json, not sure I'd call it a bug though.  If you are loading JSON locally you have to use a different path convention to the CSV loader if you have a default path set in the config file.  Not a massive issue but using windows 10 I seem to spend a fair amount of time tweaking paths until they work.....

For example with windows 10 the CSV loader format is:

USING PERIODIC COMMIT
LOAD CSV WITH HEADERS FROM "file:///file.csv" AS line

The equivalent in APOC would be:

WITH "file:///C:/default_location/file.json" AS url
CALL apoc.load.json(url) YIELD value

**Comment by jexp** [comment]
Yes it's totally different apis

But good point at aligning them

Von meinem iPhone gesendet

**Comment by inserpio** [comment]
Need to read `dbms.directories.import` in the `neo4j.conf` file and act accordingly
