### ISSUE TITLE
apoc.index.search 'Node NNNN not found' in auto_update index

### ISSUE THREAD

**Issue by vstruchkov** [neo4j-contrib/neo4j-apoc-procedures#700]
Hello

I create auto_update index (NameIndex) with following parameters

{
"autoUpdate": "true",
"provider": "lucene",
"type": "fulltext",
"to_lower_case": "true",
"keysForLabel:Name": "value",
"labels": "Name"
}
and in my neo4j.conf I add string
apoc.autoIndex.enabled=true

Then I delete some node with query
MATCH (l:Locality)-[:Name]->(n:Name) WHERE id(l)={nodeId} DETACH DELETE n

After that I try to search removed value, for example
call apoc.index.search('NameIndex','Москва') yield node match (l:Locality)-[:Name]->(node) return id(l) as id, node.value as value

The query result is "Failed to invoke procedure apoc.index.search: Caused by: org.neo4j.graphdb.NotFoundException: Node 62030 not found"
The correct result is '(no changes, no records)'

Neo4j version: 3.2.6
Operating system: Linux Mint 17.3 Rosa
API/Driver: Browser
APOC-version: apoc-3.2.0.4-all.jar

**Comment by jexp** [comment]
@sarmbruster are the nodes deleted from the index too in the EventHandler?

@vstruchkov I pushed some updates, which should deal with that. Could you try with a local build?

**Comment by vstruchkov** [comment]
Hello Michael (@jexp).

My steps:
1. Clone and rebuild apoc to version apoc-3.2.3.5
2. Restart neo4j 
3. Rebuild index with new version of APOC _Started streaming 1 records after 108218 ms and completed after 108218 ms._
4. Run my test query "call apoc.index.search('NameIndex','Москва') yield node match (l:Locality)-[:Name]->(node) return id(l) as id, node.value as value, node.language as language" _Started streaming 19 records after 57 ms and completed after 65 ms._
5. Run my script which remove all Node with value="Москва"
6. Insert new Node with value="Москва"
7. Run my test query "call apoc.index.search('NameIndex','Москва') yield node match (l:Locality)-[:Name]->(node) return id(l) as id, node.value as value, node.language as language"
8. Recive new error **Write operations are not allowed for user 'neo4j' with FULL restricted to READ.**

**Comment by vstruchkov** [comment]
@jexp,
I update my neo4j package to version 3.3.1 and download source code for apoc with 3.3 branch, rebuild it
All work correct
Thanks

**Comment by vstruchkov** [comment]
I receive " Write operations are not allowed for user 'neo4j' with FULL restricted to READ" again

Neo4j version 3.3.2
Apoc version 3.3.0.1

**Comment by vstruchkov** [comment]
I have autoUpdate configuration 
1) in index creation query
2) in neo4j.conf

This error occur during continuous insert/delete nodes which is part of index

**Comment by arsanjea** [comment]
I am getting the same issue when upgrading to the latest version of APOC v 3.3.0.2:
```Write operations are not allowed for user 'neo4j' with roles [admin] restricted to READ```
@jexp let me know if you need any additional data and how we can help. This happens every time I delete a node that's a target of the index.
Thanks!

**Comment by sarmbruster** [comment]
@arsanjea should already be fixed by https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/030dbf50be73091ed421d0f05ad591cc48a8fdb5. Not yet released, so please test on a custom build.
