### ISSUE TITLE
APOC subGraphAll procedure is not returning all relationships present in neo4j

### ISSUE THREAD

**Issue by lindashopping07** [neo4j-contrib/neo4j-apoc-procedures#702]
Sample project repo to replicate the issue:
https://gitlab.com/lindamthomas07/Neo4jRelationshipsMissing.git

Query used:
match (revision:RevisionNode{revisionNo:44}) call apoc.path.subgraphAll(revision,{maxLevel:1}) yield nodes,relationships return nodes,relationships;

Requirement: fetch all nodes connected to particular revision node and relationship among the nodes

Queries used to verify above behavior:
match (revision:RevisionNode{revisionNo:44}) call apoc.path.subgraphAll(revision,{maxLevel:1}) yield nodes,relationships  return size(apoc.coll.toSet(nodes)) as nodes, size(apoc.coll.toSet(relationships)) as rels

nodes	rels
84000	139997

match (revision:RevisionNode{revisionNo:44}) -[q:HAS_LOAD]-() return count(q)
count(q)
28000

match (revision:RevisionNode{revisionNo:44}) -[q:HAS_DATNODE]-() return count(q)
count(q)
27999

match (revision:RevisionNode{revisionNo:44}) -[q:HAS_DEPENDENT]-() return count(q)
count(q)
28000

match (revision:RevisionNode{revisionNo:44}) -[:HAS_DATNODE]- (:DataNode) -[q:RESIDES_IN]-() return count(q)
count(q)
27999

match (revision:RevisionNode{revisionNo:44}) -[:HAS_DEPENDENT]- (:DataDependentNode) -[q:DEPENDENT_ON]-() return count(q)
count(q)
28000

Total relationships - 139998

**Comment by jexp** [comment]
@InverseFalcon you might want to track your investigations here.

**Comment by jexp** [comment]
@InverseFalcon any update on this?

**Comment by InverseFalcon** [comment]
@lindashopping07 I'm not too familiar with SDN, so any help on running this and the means you're using to execute the queries after loading the graph would be welcome. If you could generate a graph.db folder and zip that and make that available, that would help our investigations and take SDN out of the picture.

Otherwise, here's some of the trouble encountered running your project:

Also, Neo4j isn't supplied as a dependency, so I don't know what version of Neo4j (and subsequently APOC) you're using for your test. 

When running with the bolt driver, I'm able to run the project, but unable to make REST queries to trigger revision creation.

If I change it to use the embedded driver (and supply a Neo4j dependency), I'm able to run the project, and able to initiate the REST query to trigger revision creation, but this hangs on the project, so the changes never get committed, so I'm unable to test with APOC later.

**Comment by lindashopping07** [comment]
@InverseFalcon  I am sorry about the trouble you had.  Please follow below steps to replicate the issue:
Prerequisite:
1. neo4j server (neo4j 3.3 CE)
2. java 1.8
3. maven 3.3

Once neo4j server is up:
1. Open application.properties file and set username and password of neo4j server
2. Open RevisionControllerTest.java class
3. Select createRevisionTest method **(only method name)** right click -> run as ->Junit Test
 OR
4. right click anywhere in the class -> run as ->Junit Test

The test would trigger neo4j operations to create nodes. default count I have given is 28k. You can change this in RevisionService.java. Kindly change the loop count value.

Query I have used to verify is mentioned in the description. please check.

Thank You!!

**Comment by InverseFalcon** [comment]
Unable to replicate this.

My concern though is that in your results we're seeing odd relationship counts. Per your code the count for each of those queries should be the same: 28000. Yet for at least two of those queries the relationship count is one off.

My thought is that we might be seeing some db corruption here during the loading process. It would be worth inspecting your debug.log and neo4j.log files and checking for any messages around relationship or node creation.

You can use the consistency checker on an offline database to see if there are any consistency issues present. That may explain both the inconsistent counts (both from the individual queries, and from the subgraphAll() call).

Some other queries you can add to those you're already running:

`MATCH ()-[r]->() RETURN count(r)` 
This will return the relationship count from the counts store. For individual types of relationships, you can add the relationship type to the query.

**Comment by lindashopping07** [comment]
@InverseFalcon 
yes, that was another issue we faced and had raised jira.
 https://jira.spring.io/browse/DATAGRAPH-1055
Frantisek Hartman from Neo4j SDN traced the root cause and provided the fix in a snapshot version. However, even when relationships count is correct, there are inconsistencies in apoc subGraphAll query. 

Thank you for your time!!

**Comment by InverseFalcon** [comment]
@lindashopping07 Were you able to perform the consistency checks on the db? Once we can confirm that the db is consistent, then we can move forward to troubleshooting the procedure. Can you also provide results of your tests when using the SDN fix on a consistent database?

**Comment by lindashopping07** [comment]
@InverseFalcon  
couldn't replicate the issue with SDN fix snapshot version 		
`<neo4j-ogm.version>3.0.3-SNAPSHOT</neo4j-ogm.version>`.
Maybe we can close this issue and reopen if any inconsistencies found later? However, initially, we really had faced this issue with apoc procedure. But that might have something to do with SDN fix. 

Thank you for your time!!

**Comment by InverseFalcon** [comment]
No problem, we'll close for now, but feel free to reopen or open another issue if this pops up again!
