### ISSUE TITLE
APOC availability on graphghists ?

### ISSUE THREAD

**Issue by adriens** [neo4j-contrib/neo4j-apoc-procedures#705]
Hi guys, still me ...for one easy question ;-p

Is APOC available (by default i mean) on graphghists platform ?

https://portal.graphgist.org/

Thanks, have a nice day.

Kind Regards,

Adrien

**Comment by adriens** [comment]
It seems that the answer is sadly....no 😭 :

![2017-12-28 08_24_04-graph de la brousse en folie - edit - graphgist portal](https://user-images.githubusercontent.com/5235127/34393751-d893c258-eba8-11e7-95a1-362d29b4abe0.png)

**Comment by jexp** [comment]
Most of them should still be available. Which neo4j-version did you specify?
Will fix it with the next release.

**Comment by jexp** [comment]
It's on my desk

**Comment by adriens** [comment]
Thanks a lot ! 🎆

**Comment by conker84** [comment]
I'm closing this as it should be available now.
Please check https://console.neo4j.org/
