### ISSUE TITLE
apoc.load.json not restricted to dbms.directories.import

### ISSUE THREAD

**Issue by Dcanzano** [neo4j-contrib/neo4j-apoc-procedures#706]
https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/70  indicates that one can for example run

call apoc.load.json("file:////home/neo4j/neo4j-enterprise-3.3.0/bin/myfile.json") yield value return value; 

and this will properly read said file.   this is probably not a good idea for the file://// could represent any file on the filesystem.   Similar to LOAD CSV we should probably restrict apoc.load.json to the value reported by 

conf/neo4j.conf parameter of  dbms.directories.import

**Comment by conker84** [comment]
closed via 3558084
