### ISSUE TITLE
Range search on Integer values for Manual Index created using apoc.index.addRelationship

### ISSUE THREAD

**Issue by rohankharwar** [neo4j-contrib/neo4j-apoc-procedures#707]
I am using ` apoc.index.addRelationship(r,['rating'])` where rating is an integer and creating manual index on relationship property. 
However when doing Range Search based on integer value, it is considering string range search.
For example (based on Movie DB example)

```
CALL apoc.index.relationships('REVIEWED','rating:[94 to ]') YIELD rel, start AS person, end AS movie
RETURN person,movie,rel;
```

This query should give 2 rels for 95 and 100. But does not give 100 as it is doing string search. 
We tested `95 to *` and throws an error:

```
Failed to invoke procedure `apoc.index.relationships`: Caused by: java.lang.RuntimeException: org.apache.lucene.queryparser.classic.ParseException: Cannot parse 'rating:[94 to *]': Encountered " <RANGE_GOOP> "* "" at line 1, column 14.
Was expecting one of:
    "]" ...
    "}" ...
```

I believe we have to index it in apoc explicitely as numeric field
Lucene implementation currently does not do this automatically.

Change should be if the value is numeric add `ValueContext.numeric(value)`
Have to check if we have to change the querying too.

**Comment by conker84** [comment]
Index procedures are deprecated
