### ISSUE TITLE
Guidelines to contribute new functions

### ISSUE THREAD

**Issue by adriens** [neo4j-contrib/neo4j-apoc-procedures#709]
Hi,

i've begun to use apoc last week, for now, within a very limited scope (https://www.linkedin.com/pulse/l%C3%B4%C3%B4%C3%B4ngin-cest-qui-quest-au-centre-de-la-bd-%C3%A0-nous-brousse-sales/).

I read the documentation and i will vey probably begin to use for example jdbc and xml loading features very soon.

But...i have some new UDF in mind that i could not find in the current versions, so here is the question : where could i find some guidelines on how to contribute to the project, for example if i want to add new functions ? That would be great ! You guys could get some well formatted PR.

Thanks in advance for your help.

Best Regards,

Adrien

**Comment by jexp** [comment]
Hi Adrien, 
sorry for the delay in answering. We'd love your contributions.
Basically, you only have to sign the CLA https://neo4j.com/developer/cla/
And then you can start sending PRs :)
You find a lot of examples for simple UDFs e.g. in Strings.java or Coll.java and the accompanying tests.

**Comment by jexp** [comment]
I added a contribution document: https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/3.2/CONTRIBUTING.adoc

**Comment by adriens** [comment]
Hi @jexp , thanks a lot for your answer on how develop and sumbit contribs.
No worry for you answer'sdelay, i'm quite busy two, but i've added this to my TODO list.
Have a nice week !
