### ISSUE TITLE
Update readme.adoc for find all the procedure in Neo4j 3.x

### ISSUE THREAD

**Issue by anuragknoldus** [neo4j-contrib/neo4j-apoc-procedures#71]

**Comment by jexp** [comment]
The idea is to generate overview.adoc during build time from the sproc compiler,
and probably also use that information for the apoc.help instead of having to do classfile scanning
@fbiville

**Comment by jexp** [comment]
We should be pretty good with the coverage in overview.adoc right now.
But I still want it to be generated, e.g. with one file per package by the build system @fbiville

**Comment by fbiville** [comment]
I will have a look next week, it should not be too hard!
