### ISSUE TITLE
apoc.create.vRelationship - sort results by property value of virtual relationship

### ISSUE THREAD

**Issue by Joshua-Yu** [neo4j-contrib/neo4j-apoc-procedures#712]
Hi there,

Using the stackoverflow data, I have the following query to count how many paths between Tag 'neo4j' and other tags, and then keep the value in the property of a virtual relationship: 

MATCH (t:Tag{tagId:'neo4j'})  
WITH t
CALL apoc.path.expandConfig(t,{relationshipFilter:'HAS_TAG',labelFilter:'+Post|/Tag',uniqueness:'RELATIONSHIP_PATH'}) YIELD path
WITH t,filter(n IN nodes(path) WHERE n.tagId <> 'neo4j' AND n.tagId IS NOT NULL) AS tags
WITH t,extract(n IN tags | n.tagId) AS tag, count(tags) AS counts
MATCH (t2:Tag{tagId:tag[0]})
CALL apoc.create.vRelationship(t, 'ASSOCIATED_WITH',{count:counts},t2) YIELD rel
RETURN t,t2,rel ORDER BY **rel.count** DESC LIMIT 20

The result screen is attached below. What I found is the sorting seems not working. 

Can someone please advise? 

![5-01-2018 1-29-46 pm](https://user-images.githubusercontent.com/34237687/34593085-b326fb28-f21c-11e7-92fa-af6865e54bfa.png)

Cheers

Joshua

**Comment by jexp** [comment]
Unfortunately, that's not possible as Cypher accesses data of nodes and relationships one API below virtual nodes and rels (which only exist in apoc not in Neo4j).

So you'd have to sort by your original `count` variable.

Usually you use virtual nodes and rels for display purposes (where ordering doesn't matter).

Does it work otherwise (visually)?

**Comment by Joshua-Yu** [comment]
Ok, that is fine. Yeah the display part works.

Cheers

Joshua

On 5 Jan 2018 8:27 PM, "Michael Hunger" <notifications@github.com> wrote:

Unfortunately, that's not possible as Cypher accesses data of nodes and
relationships one API below virtual nodes and rels (which only exist in
apoc not in Neo4j).

So you'd have to sort by your original count variable.

Usually you use virtual nodes and rels for display purposes (where ordering
doesn't matter).

Does it work otherwise (visually)?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/712#issuecomment-355509845>,
or mute the thread

**Comment by Joshua-Yu** [comment]
Closed.
