### ISSUE TITLE
Problem with apoc.date.parse with third arguments

### ISSUE THREAD

**Issue by dimitriSpb** [neo4j-contrib/neo4j-apoc-procedures#715]
Hi all,

I try to compare date with APOC and I want to specify date format (third parameters).
But is I specify date format parameters, query don't work.

This is example : 
I do a test game here : http://console.neo4j.org/r/qhq3u4
And this is 3 queries to simulate issue :
WORKS FINE : 
```
 MATCH (n:MyDate) where apoc.date.parse(n.created_at,'ms') > apoc.date.parse('2018-01-01 00:00:00', 'ms')  
RETURN n.created_at ,apoc.date.parse(n.created_at, 'ms') as MS_NODE  , apoc.date.parse('2018-01-01 00:00:00','ms') as MS_TO_COMPARE 
```

NOT WORKING WITH DATE FORMAT : 
```
MATCH (n:MyDate) where apoc.date.parse(n.created_at,'ms','YYYY-MM-dd HH:mm:ss') > apoc.date.parse('2018-01-01 00:00:00', 'ms')  
RETURN n.created_at ,apoc.date.parse(n.created_at, 'ms','YYYY-MM-dd HH:mm:ss') as MS_NODE  , apoc.date.parse('2018-01-01 00:00:00','ms','YYYY-MM-dd HH:mm:ss') as MS_TO_COMPARE
```

NOT WORKING WITH DATE FORMAT (and 00:00:01) : 
```
MATCH (n:MyDate) where apoc.date.parse(n.created_at,'ms','YYYY-MM-dd HH:mm:ss') > apoc.date.parse('2018-01-01 00:00:01', 'ms')  
RETURN n.created_at ,apoc.date.parse(n.created_at, 'ms','YYYY-MM-dd HH:mm:ss') as MS_NODE  , apoc.date.parse('2018-01-01 00:00:01','ms','YYYY-MM-dd HH:mm:ss') as MS_TO_COMPARE
```

Neo4J version : 3.1.4
Apoc version : 3.3.0.1

**Comment by jexp** [comment]
Found it.
The `YYYY` is not the same as `yyyy` the former means "week-year"

So if you change your `YYYY` to `yyyy` it should work.

And the default formatting pattern is: 

`public static final String DEFAULT_FORMAT = "yyyy-MM-dd HH:mm:ss";`

https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/3.2/src/main/java/apoc/date/Date.java#L32

see: https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html

> If week year 'Y' is specified and the calendar doesn't support any week years, the calendar year ('y') is used instead. The support of week years can be tested with a call to getCalendar().isWeekDateSupported().

> A week year is in sync with a WEEK_OF_YEAR cycle. All weeks between the first and last weeks (inclusive) have the same week year value. Therefore, the first and last days of a week year may have different calendar year values.

> For example, January 1, 1998 is a Thursday. If getFirstDayOfWeek() is MONDAY and getMinimalDaysInFirstWeek() is 4 (ISO 8601 standard compatible setting), then week 1 of 1998 starts on December 29, 1997, and ends on January 4, 1998. The week year is 1998 for the last three days of calendar year 1997. If, however, getFirstDayOfWeek() is SUNDAY, then week 1 of 1998 starts on January 4, 1998, and ends on January 10, 1998; the first three days of 1998 then are part of week 53 of 1997 and their week year is 1997.

**Comment by dimitriSpb** [comment]
Thanks you !!
It's my falte, I use bad date format sorry
