### ISSUE TITLE
apoc.es.post or apoc.es.put not working at all on ES6.1

### ISSUE THREAD

**Issue by neildobson-au** [neo4j-contrib/neo4j-apoc-procedures#716]
I've been trying various ES integrations quite successfully from https://neo4j.com/developer/elastic-search/ and now I'm trying to do some custom integration with APOC.

A call to apoc.es.get works successfully returning results. But writing data always fails.
`call apoc.es.post("localhost","tweets","users","1",null,{name:"Chris"})`
returns:

> ERROR Neo.ClientError.Procedure.ProcedureCallFailed
`
Failed to invoke procedure `apoc.es.post`: Caused by: java.lang.RuntimeException: Can't read url http://localhost:9200/tweets/users/1 as json: Server returned HTTP response code: 406 for URL: http://localhost:9200/tweets/users/1`

ES is working fine. I can execute the same query in Kibana console or elsewhere
`PUT tweets/users/1
{
    "name":"Chris"
}`
returns
`{
  "_index": "tweets",
  "_type": "users",
  "_id": "1",
  "_version": 1,
  "result": "created",
  "_shards": {
    "total": 2,
    "successful": 1,
    "failed": 0
  },
  "_seq_no": 0,
  "_primary_term": 1
}`

It seems as though the write is failing (but the error is swallowed) and then a subsequent read on the document _id yields nothing

I'm using ElasticSearch version 6.1.1, Neo4j v.3.3.1 Community, apoc-3.3.0.1-all. The other [Graphaware ](https://github.com/graphaware/neo4j-to-elasticsearch) and [Neo4j](https://github.com/neo4j-contrib/neo4j-elasticsearch) plugins (which are now disabled and removed) were successfully syncing data to ES previously.

**Comment by neildobson-au** [comment]
Not sure if it is related to https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/179 but if I take the same (or similar) query from that post and try to run it:
`CALL apoc.es.query("localhost","tweets","users",null,{query:{match_all:{}}})`
I get the response:

> ERROR Neo.ClientError.Procedure.ProcedureCallFailed
`Failed to invoke procedure `apoc.es.query`: Caused by: java.lang.RuntimeException: Can't read url http://localhost:9200/tweets/users/_search as json: Server returned HTTP response code: 406 for URL: http://localhost:9200/tweets/users/_search`

**Comment by jexp** [comment]
Which ES version are you running?

**Comment by jexp** [comment]
I just checked with 5.1.1 (what I had locally installed) and the unit-tests worked:

https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/3.2/src/test/java/apoc/es/ElasticSearchTest.java#L270

**Comment by neildobson-au** [comment]
Yes I just confirmed with 5.1.1 these work fine:
`call apoc.es.put("localhost","tweets","users","1",null,{name:"Chris"})`
`call apoc.es.query("localhost","tweets","users",null,{query:{match_all:{}}})`
Under 6.1.1 they both fail.
This is good enough for now, we can continue with 5.1.1 for testing purposes. Maybe ES has changed something in the new version?

**Comment by albertodelazzari** [comment]
@neildobson-au, @jexp  something has changed from ES 5.x to 6.x in the REST API.
For example JSON can't have unquoted fields and also ES 6.x enforce you to specify a content type so it's better to check ElasticSearchTest using ES 6.x.

More info can be found at [REST changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_60_rest_changes.html)

**Comment by jexp** [comment]
Pushed, please check with a local build of apoc or let me know if you need one.
