### ISSUE TITLE
apoc.algo.pageRank has Java StackOverflowError on small graph

### ISSUE THREAD

**Issue by Joshua-Yu** [neo4j-contrib/neo4j-apoc-procedures#717]
Hi,

I was testing the new Page Rank algorithm in APOC 3.2.3 for the smallest graph below: 

CREATE (c:Character{name: 'Char1'});

CREATE (c:Character{name: 'Char2'});

MATCH (c1:Character{name:'Char1'}), (c2:Character{name:'Char2'})
CREATE (c1) -[i:INTERACTS]-> (c2)
RETURN i

Basically it's just a graph of 2 Character nodes connected by 1 relationship of INTERACTS. Then I used the following Cypher to calculate their pageRank: 

MATCH (c1:Character) 
WHERE c1.name in ['Char1','Char2'] 
WITH COLLECT(c1) AS characters
CALL apoc.algo.pageRankWithConfig(characters,{iterations:1, types:'INTERACTS'}) YIELD node, score
RETURN node, score
ORDER BY score DESC

No surprise it only took some ms to return the results in a graph database that only has these 2 nodes and 1 relationship. 

However, when I created the identical nodes and relationship as an **isolated** sub-graph in an existing database of some million nodes and 60 millions of relationships, even if none of the existing node is connected to Char1 or Char2, I got the Java StackoverflowError for the same query as above, after some minutes of running.

My machine still has 30%+ unused RAM, and the Java Heap memo is about 40% free. 

I had a feeling that when PageRank is kicked off, it was trying to load the whole database into memory, even though I specified the relationship type to be only 'INTERACTS'. I also observed a burst of usage of all 4 CPU cores at the time the query is executed. 

Can someone please advise? Did I miss anything here?

Cheers 

Joshua

**Comment by jexp** [comment]
Best use neo4j-graph-algorithms library 

I think here you might have run into a condition that pulls in the whole graph 

Can you share the exception?

Von meinem iPhone gesendet

**Comment by conker84** [comment]
algo procedures are deprecated
