### ISSUE TITLE
GraphML import and labels

### ISSUE THREAD

**Issue by dennisrd** [neo4j-contrib/neo4j-apoc-procedures#721]
In the GraphML file that I import, I would like to avoid using the attribute _labels_ on <node/> elements, because that attribute is not part of the GraphML spec.
I am specifying the label(s) in a GraphML <data/> element.

Example: instead of
`<node id="foo" labels=":BAR"/>`
I have:
`<node id="foo">
  <data key="labels">:BAR</data>
</node>`

Is there a way to import into Neo4j so that the labels show up in the graph?
I would like to avoid having to postprocess the graph (using some Cypher query to move data properties to labels) after importing it.

**Comment by jexp** [comment]
good idea we can add that as an option, would need this to be a list if possible.

**Comment by jexp** [comment]
Did you try to use the config option: `{readLabels:true}`

I think that one already does what you want to do.

**Comment by dennisrd** [comment]
@jexp : you're right, `{readLabels:true}` does it, for node labels at least. Thanks!
Now I also want to have something similar for relationships/edges.
I have tried
`<edge id="1" source="2" target="3"> <data key="labels">:EDGE_LABEL</data> </edge>`
and
`<edge id="1" source="2" target="3"> <data key="labels">EDGE_LABEL</data> </edge>`
as well as using `"label"` and `"type"` instead of `"labels"` for the key (and of course specifying `{readLabels:true}`), but none of this imports the relationship types; all I get is the default relationship type `RELATED`.

**Comment by rescuehero** [comment]
are you talking about importing files edited by yed?
