### ISSUE TITLE
apoc.cypher.runFile taking a long time to load small dataset

### ISSUE THREAD

**Issue by stuartlaurie** [neo4j-contrib/neo4j-apoc-procedures#732]
While trying to take a subset of a graph (so i could test re-factoring on a smaller set) I was trying a few ways to export/import.

when trying to export using (Neo4j 3.3.2 Enterprise - APOC 3.3.0.1)

`call apoc.export.cypher.query("match (n)-[r]-(n2) return * limit 100","/tmp/mysubset.cypher",{})`

and then

`apoc.cypher.runFile("/tmp/mysubset.cypher") yield row, result`

Each format (plain, cypher-shell, neo4j-shell) failed to load with various explainable errors

By using format:plain and removing the 'schema' statements and running them before the call to apoc I could import using the `apoc.cypher.runFile` command but the import took a long time ~5-10 mins  (for 37 nodes,100 relationships)

**Comment by jexp** [comment]
Is that related to your graph data?
I try to reproduce with the movie graph.

**Comment by jexp** [comment]
did you see the docs here: https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_many_files_separatefiles_config

**Comment by jexp** [comment]
did you also run the schema file?
