### ISSUE TITLE
Feature request: A* with nodes to include/exclude

### ISSUE THREAD

**Issue by Yoshiiiiiii** [neo4j-contrib/neo4j-apoc-procedures#733]
The include nodes have to be inluded in the resulting path. With multiple include nodes i'd recommend to do A* between all the nodes and find the best order of nodes by brute-force-search (from node and to node still remain at the start and end of the path). Of course the amount of inlcude nodes shouldn't be to high. The exclude nodes should simply be excluded from the resulting path. 
The procedure call could look like this:
```
MATCH (n:NODE)
WHERE n.NODE_ELID='BLOCK1' OR n.NODE_ELID='BLOCK2'
WITH COLLECT(n) AS excludeNodes  
MATCH (m:NODE)
WHERE m.NODE_ELID='MUST1' OR m.NODE_ELID='MUST2'
WITH excludeNodes, COLLECT(m) AS includeNodes
MATCH (from:NODE{NODE_ELID:'START'}),(to:NODE{NODE_ELID:'END'})  
CALL apoc.algo.aStarExt(from,to,'CONNECTED_TO','DISTANCE','COORD_X','COORD_Y',excludeNodes,includeNodes) yield path as path, weight as weight
RETURN path, weight
```
Heres my code (feel free to use it, but its probably just bad quality. I'm still a trainee)
[PathFinding.java.txt](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/1688444/PathFinding.java.txt)
[WeightedPathResult.java.txt](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/1688445/WeightedPathResult.java.txt)

There is a problem in it i couldn't even log. When you call the procedure with not existing includeNodes the result is always empty. It doesnt create a logfile for this call even though its the first thing to do in the procedure. Also you dont get an error from Neo4j. For not existing excludeNodes it somehow still works fine. 
I'd like to avoid the guava lib. The concat works suprisingly but the path is not really a single path. In the result you can still see the diffrent paths and their weights.

**Comment by jexp** [comment]
Should be re-issued to the github.com/neo4j-contrib/neo4j-graph-algorithms
