### ISSUE TITLE
3.4 incompatible

### ISSUE THREAD

**Issue by Meatballs1** [neo4j-contrib/neo4j-apoc-procedures#734]
Trying to use 3.3.0.1 with 3.4-alpha6 get the following exception which causes neo4j to fail to start:

`Caused by: java.lang.ClassNotFoundException: org.neo4j.kernel.api.security.SecurityContext`

I think SecurityContext has been renamed to LoginContext somewhere along the way.

Any chance we can get an alpha 3.4 apoc release? :D

**Comment by victoriastuart** [comment]
Ditt, with: apoc-3.3.0.2-all.jar + neo4j-community-3.4.0-alpha09

```
[victoria@victoria ~]$ neo4j console
Active database: graph.db
Directories in use:
  home:         /mnt/Vancouver/apps/neo4j/neo4j-community-3.4.0-alpha09
  config:       /mnt/Vancouver/apps/neo4j/neo4j-community-3.4.0-alpha09/conf
  logs:         /mnt/Vancouver/apps/neo4j/neo4j-community-3.4.0-alpha09/logs
  plugins:      /mnt/Vancouver/apps/neo4j/neo4j-community-3.4.0-alpha09/plugins
  import:       /mnt/Vancouver/apps/neo4j/neo4j-community-3.4.0-alpha09/import
  data:         /mnt/Vancouver/apps/neo4j/neo4j-community-3.4.0-alpha09/data
  certificates: /mnt/Vancouver/apps/neo4j/neo4j-community-3.4.0-alpha09/certificates
  run:          /mnt/Vancouver/apps/neo4j/neo4j-community-3.4.0-alpha09/run
Starting Neo4j.
2018-03-19 22:50:17.629+0000 INFO  ======== Neo4j 3.4.0-alpha09 ========
2018-03-19 22:50:17.652+0000 INFO  Starting...
2018-03-19 22:50:18.819+0000 INFO  Bolt enabled on 127.0.0.1:7687.
2018-03-19 22:50:19.010+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@37fdfb05' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.api.security.SecurityContext". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@37fdfb05' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.api.security.SecurityContext".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@37fdfb05' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.api.security.SecurityContext".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
...
```

**Comment by jexp** [comment]
As there are massive internal changes to the Kernel API I wanted to wait until beta01 for any APOC development on 3.4.

**Comment by jexp** [comment]
Any reason you're already on 3.4-alpha? Just curious :)

**Comment by victoriastuart** [comment]
No worries ... I hadn't been using Neo4j recently, so I earlie today I downloaded the (linux) CE from their website, that took me to this link

  https://neo4j.com/download-thanks-beta/?edition=community&release=3.4.0-alpha09&flavour=unix

which happens to be v.3.4.

Honestly, I hadn't noticed that it was a pre-release (https://neo4j.com/download/other-releases/#releases).  ;-)

**Comment by jexp** [comment]
Ah, yes the top-box are the pre-releases,  the other downloads are down there in the table.

As soon as there is a beta I check the apoc compatibility.

**Comment by Meatballs1** [comment]
I'm using 3.4 because I needed https://github.com/neo4j/neo4j/pull/10433 because I was getting OOM errors otherwise. Currently I'm on  a custom build with that PR merged in but still apoc compatible... :)

**Comment by jexp** [comment]
We're going to look into it now, with main efforts after beta02 when the Kernel API changes are in.

**Comment by valer-cara** [comment]
Same issue here - i'm using 3.4 for prometheus metrics

**Comment by sarmbruster** [comment]
I did push a 3.4 branch to the repo yesterday. Please grab it, build it and give it a test. We sill do an official 3.4 apoc release once Neo4j 3.4.0 is released.
If you find any issues in 3.4 please raise a separate ticket since I'm closing this one off.

**Comment by Meatballs1** [comment]
@sarmbruster Seems to work ok with 3.4-rc01 thanks a lot :D

**Comment by sarmbruster** [comment]
@Meatballs1 thanks :-)
