### ISSUE TITLE
apoc.index.search return too many results

### ISSUE THREAD

**Issue by vstruchkov** [neo4j-contrib/neo4j-apoc-procedures#737]
Below my test

create (:Test {value:"One One One"})
create (:Test {value:"One One Two"})
create (:Test {value:"One One Three"})
create (:Test {value:"Two One One"})
create (:Test {value:"Two Two One"})
create (:Test {value:"Three One One"})

call apoc.index.addAllNodes('Test',{Test:["value"]},{autoUpdate:true})

1) call apoc.index.search('Test','One*') yield node, weight return node.value,weight
╒═══════════════╤════════╕
│"node.value"   │"weight"│
╞═══════════════╪════════╡
│"Three One One"│1       │
├───────────────┼────────┤
│"Two Two One"  │1       │
├───────────────┼────────┤
│"One One Three"│1       │
├───────────────┼────────┤
│"One One One"  │1       │
├───────────────┼────────┤
│"Two One One"  │1       │
├───────────────┼────────┤
│"One One Two"  │1       │
└───────────────┴────────┘
All correct - 6 rows.

2) call apoc.index.search('Test','One One*') yield node, weight return node.value,weight
╒═══════════════╤══════════════════╕
│"node.value"   │"weight"          │
╞═══════════════╪══════════════════╡
│"One One One"  │1.2365717887878418│
├───────────────┼──────────────────┤
│"Three One One"│1.14976167678833  │
├───────────────┼──────────────────┤
│"One One Three"│1.14976167678833  │
├───────────────┼──────────────────┤
│"Two One One"  │1.14976167678833  │
├───────────────┼──────────────────┤
│"One One Two"  │1.14976167678833  │
├───────────────┼──────────────────┤
│"Two Two One"  │1.0366284847259521│
└───────────────┴──────────────────┘
6 rows again. Why? I think that correct result is 5 rows.

3) call apoc.index.search('Test','One One One*') yield node, weight return node.value,weight
╒═══════════════╤══════════════════╕
│"node.value"   │"weight"          │
╞═══════════════╪══════════════════╡
│"One One One"  │1.4361846446990967│
├───────────────┼──────────────────┤
│"Three One One"│1.290334939956665 │
├───────────────┼──────────────────┤
│"One One Three"│1.290334939956665 │
├───────────────┼──────────────────┤
│"Two One One"  │1.290334939956665 │
├───────────────┼──────────────────┤
│"One One Two"  │1.290334939956665 │
├───────────────┼──────────────────┤
│"Two Two One"  │1.1002600193023682│
└───────────────┴──────────────────┘
6 row again. 
But 'One One One' is in only 1 rows.

**Comment by jexp** [comment]
Lucene splits on spaces, so if you want to keep the space you have to wrap them with double quotes `'"One One"'` but then it doesn't allow wildcards anymore (afaik) and you have to turn it into `One AND Two`
