### ISSUE TITLE
Feature Request: IP Address / Subnet Mask utilities

### ISSUE THREAD

**Issue by jhashemi** [neo4j-contrib/neo4j-apoc-procedures#74]
I was thinking of something along these lines: 

match (ip:IpAddress) where apoc.IpAddress.IsInSameNetwork(nodewithipaddress,MASK)
yield return ip

**Comment by jexp** [comment]
Do you think the bit-operations that are already in apoc can help you there?

**Comment by jexp** [comment]
I think such a function is quite specific and probably more suited to a network/data-center related library of procedures.
