### ISSUE TITLE
Improvement request - allow `apoc.path.subgraphAll()` to restrict the relationships in the subgraph

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j-contrib/neo4j-apoc-procedures#750]
Requested from #745 .
Current behavior is that the relationships provided by the relationshipFilter only apply to the expansion out to nodes of the subgraph. Then all relationships between the subgraph nodes are obtained (this is the equivalent to performing `subgraphNodes()`, collecting them, and then calling `apoc.algo.cover()`, which is actually what's happening under the hood).

This requests an additional field for `subgraphAll()` that restricts the `cover()` operation to only relationships of certain types.

This improvement should probably also be applied to the `cover()` procedure as well.

**Comment by dkoslicki** [comment]
+1 on this issue: If apoc.path.subgraphAll() has a filter option, it seems more natural to return only things that pass this filter.

**Comment by conker84** [comment]
algo procedures are deprecated, feel free to reopen if I misunderstood the request
