### ISSUE TITLE
Executing iterate / commit on FOLLOWER errors with java.lang.NullPointerException

### ISSUE THREAD

**Issue by mg6maciej** [neo4j-contrib/neo4j-apoc-procedures#751]
The error "message" is not intuitive. I'd suggest adding info about the root cause.

<img width="1313" alt="image" src="https://user-images.githubusercontent.com/1316369/36902849-310d47e6-1e2c-11e8-9aac-7bd16b38cebd.png">

**Comment by conker84** [comment]
we improved the error management, feel free to reopen if you want
