### ISSUE TITLE
Function apoc.coll.combinations is missing in 3.3.02 distribution

### ISSUE THREAD

**Issue by krisgeus** [neo4j-contrib/neo4j-apoc-procedures#752]
issue #657 mentioned adding apoc.coll.combinations function. This was added to apoc version 3.2 in commit 306f7fbdb2ba1270a1738ec28a85a9c7eb0dd754. Somehow merging to 3.3 in commit 0fc0507926d18bf99df91a05fb033f07afaa6932 only added the docs and not the code.

PR is coming to fix this in 3.3

**Comment by krisgeus** [comment]
PR is merged. So issue can be closed I guess @InverseFalcon?

**Comment by jexp** [comment]
Thanks a lot!
