### ISSUE TITLE
apoc.group.nodes error -> return indivdiual nodes + rels

### ISSUE THREAD

**Issue by tomasonjo** [neo4j-contrib/neo4j-apoc-procedures#758]
i tried a simple use-case for `apoc.group.nodes`

data:

    :play movies

network:

    MATCH (p1:Person)-->(:Movie)<--(p2:Person) where id(p1) < id(p2)
    MERGE (p1)-[r:KNOWS]-(p2) 
    ON CREATE SET r.weight = 1
    ON MATCH SET r.weight = r.weight + 1

Label propagation;

    CALL algo.labelPropagation('Person','KNOWS','BOTH',{iterations:10,partitionProperty:'lpa'})

Try to group nodes by labels:

    call apoc.nodes.group(['Person'],['lpa'],[{},{}])

I get back only single vNode:

![resul](https://user-images.githubusercontent.com/19948365/37257042-cb264f42-2563-11e8-8d97-d24711ec67b1.png)

and an error in the debug.log

> 2018-03-11 18:35:26.336+0000 ERROR Client triggered an unexpected error [UnknownError]: Access to record Node[-5,used=false,rel=-1,prop=-1,labels=Inline(0x0:[]),light,secondaryUnitId=-1] went out of bounds of the page. The record size is 15 bytes, and the access was at offset -75 bytes into page 0, and the pages have a capacity of 8190 bytes. The mapped store file in question is /home/tomaz/neo4j/neo4j-community-3.3.3/data/databases/graphy.db/neostore.nodestore.db, reference 0bdeef12-33de-4022-ba39-a7854d088fb8. 

To my understanding every community should be grouped into it's own Vnode and we can then play around with different rel and node aggregation.

**Comment by jexp** [comment]
Thanks a lot, so well have to change the return types to return individual nodes.
