### ISSUE TITLE
requesting better error messaging on apoc.load.csv when file does not exist

### ISSUE THREAD

**Issue by Dcanzano** [neo4j-contrib/neo4j-apoc-procedures#761]
Using Neo4j 3.3.3 and APOC 

````
-rw-rw-r-- 1 neo4j neo4j 7271085 Oct 29 11:58 ../plugins/apoc-3.3.0.1-all.jar
````

when running 

````
neo4j> CALL apoc.load.csv('file:////MyFile.txt',{sep:'|',failOnError:false}) yield lineNo, map;
+--------------+
| lineNo | map |
+--------------+
| 0      |     |
+--------------+
````

and the file MyFile.txt does not exist, but the cypher output provides no indication as such.   However if one runs `LOAD CSV` with a file that does not exist, then one receives appropriate error messaging, for example

````
neo4j> load csv from 'file:////MyFile.txt' as line return line;
Couldn't load the external resource at: file:/home/neo4j/neo4j-enterprise-3.3.3/import/MyFile.txt
````

Requesting apoc.load.csv provide appropriate error messaging

**Comment by Dcanzano** [comment]
@jexp if thats the case, use {failOnError:true}  can we then update https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_loading_data_from_web_apis_json_xml_csv  and specifically the last table entry which describes apoc.load.csv and what the value {config} options are and that they include this failonError:true

**Comment by vga91** [comment]
`FailOnError` added [here](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/1235) in `web-apic.adoc`
