### ISSUE TITLE
dijkstra algorithm based on a weight cost return only the shortest Path. 

### ISSUE THREAD

**Issue by HamzaKhribi** [neo4j-contrib/neo4j-apoc-procedures#763]
Hello everyone, i have a question about dijkstra apoc procedure. I have a large database and when i issue dijkstra procedure it works fine but only gives me the shortest path. I am wondering if there is an extension of dijkstra that gives me all the paths ordered from the shortest to longuest based on the relationship cost. Some people suggested aStar but i don't have lat and lon attributes in my nodes.
I have asked for help in the slack group and they asked me to report it as an issue. I hope  you guys can add it as an improvement because it's really helpful.

**Comment by sarmbruster** [comment]
GraphAlgoFactory has a built-in function for this, see https://neo4j.com/docs/java-reference/current/javadocs/org/neo4j/graphalgo/GraphAlgoFactory.html#dijkstra-org.neo4j.graphdb.PathExpander-org.neo4j.graphalgo.CostEvaluator-int-
Should be easy to overload existing apoc.algo.dijkstra with this.

**Comment by HamzaKhribi** [comment]
True graphFactory has that built in but PathFinder and PathExpander classes only work on graphDB nodes type and i want to process dijkstra on my database built using neo4j ogm. when i try to cast my ne4j node entity to Node i have this error 
> .BusStation cannot be cast to org.neo4j.graphdb.Node
The probleme is that PathExpander and PathFinder in graphFactory only accept nodes of type graphDB in their constructors
can you help me to make it work using node entities of neo4j?

**Comment by HamzaKhribi** [comment]
I hope they will add this feature to the dijkstra procedure
