### ISSUE TITLE
Missing Iterator Utils in apoc .jar file

### ISSUE THREAD

**Issue by finnagin** [neo4j-contrib/neo4j-apoc-procedures#765]
I've ran into this issue both with apoc 3.3.0.2/neo4j 3.3.3 as well as with apoc 3.2.3.6/neo4j 3.2.6 both running in docker containers.

When calling: 
```
match (n:pharos_drug) where n.name="ibuprofen" call apoc.path.subgraphAll(n, {maxLevel:1, relationshipFilter:'targets>'}) yield nodes, relationships return nodes, relationships
``` 
I received the following error: "Failed to invoke procedure `apoc.path.subgraphAll`: Caused by: java.lang.NoClassDefFoundError: org/apache/commons/collections/IteratorUtils"

After reading this error I thought that maybe I missed a step when following the [installation directions](https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_using_apoc_with_neo4j_docker_image) in the documentation but after combing through the documentation for a while I couldn't find any extra configuration steps for installation other than those for [hive](https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_support_for_hive_with_kerberos_auth), [mongoDB](https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_interacting_with_mongodb), and [couchbase.](https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_interacting_with_couchbase)

To fix the issue I unpacked the apoc .jar file and put [apache commons collections 3.2.2](https://commons.apache.org/proper/commons-collections/download_collections.cgi) into the directory org/apache/commons/collections/ and then repacked it. Then, after putting this new .jar file into the neo4j plugins directory everything worked fine.

This leads me to believe that there may be missing dependencies (apache commons collections) in the .jar files (at least for 3.3.0.2 & 3.2.3.6) available for download [here.](https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases)

I am new to both neo4j and apoc so I apologize ahead of time if there is anything I missed in the documentation or if there is a config file I failed to use or if there is some other obvious thing I missed when looking into this issue.

**Comment by sarmbruster** [comment]
this only happens on community edition, couldn't reproduce on enterprise. @finnagin does that match your observations?

**Comment by sarmbruster** [comment]
nevermind. Neo4j enterprise does have commons-collection on board (as a transitive dependency) whereas community does not depend on it.
I'll change apoc code to not depend on commons-collections at all.

**Comment by tmerten** [comment]
It looks like this fix has not been released. Are you intending to create a bug fix release for this?

**Comment by tmerten** [comment]
Yeah, I did so thanks. The question was just out of curiosity ;).
