### ISSUE TITLE
Add node/rel property filtering during expansion to path expanders

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j-contrib/neo4j-apoc-procedures#767]
Currently path expanders are limited to relationship type and label filtering. Add in the ability to filter on properties during expansion.

**Comment by Emptyfruit** [comment]
Is there a workaround to get similar behaviour ?

**Comment by mperini** [comment]
> Is there a workaround to get similar behaviour ?

Definitely **not** an elegant solution, and only works for fixed-length queries, but you could try filtering on properties during expansion by concatenating multiple calls to the same procedure, and applying the filtering at the end of each call.

For example the query:
```
MATCH p=(n {id: "12345"})<-[:MY_RELATION*1..2]-()
WHERE all(rel in relationships(p) WHERE rel.my_property > 0)
RETURN p
```

could be reproduced by calling 2 times the `apoc.path.expandConfig()` procedure with `maxLevel: 1`, each time using as starting point the end result of the previous call:
```
MATCH (n {id: "12345"})
CALL apoc.path.expandConfig(n, {
    maxLevel: 1,
    bfs: false,
    relationshipFilter: "<MY_RELATION"
})
YIELD path WHERE all(rel in relationships(path) WHERE rel.my_property > 0)
WITH path as path_1
CALL apoc.path.expandConfig(last(nodes(path_1)), {
    maxLevel: 1,
    bfs: false,
    relationshipFilter: "<MY_RELATION"
})
YIELD path WHERE all(rel in relationships(path) WHERE rel.my_property > 0)
RETURN path
```
This being said, I would much more appreciate to have APOC handling the filtering.

**Comment by romaderi12** [comment]
Hi,
I'm interesting in the same way to filter on node property this time. is there a way to stop expand on node with specific property  eg status ?

Regards,
Romain
