### ISSUE TITLE
IllegalArgumentException when using apoc.cypher.runFirstColumn with a query that contains directed relationship

### ISSUE THREAD

**Issue by johnymontana** [neo4j-contrib/neo4j-apoc-procedures#776]
Calling `apoc.cypher.runFirstColumn` with a query that contains a directed relationship the following error occurs:

```
Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke function `apoc.cypher.runFirstColumn`: Caused by: java.lang.IllegalArgumentException: Can not be converted to long: org.neo4j.kernel.impl.core.NodeProxy
```

To reproduce (using `:play movies` data):

```
MATCH (m:Movie)
RETURN apoc.cypher.runFirstColumn('WITH {m} AS m MATCH (m)<-[:ACTED_IN]-(:Person)-[:ACTED_IN]->(rec:Movie) RETURN rec LIMIT 10', {m:m}, true)
```
(results in error above)

Similar queries work fine however:

```
MATCH (m:Movie)
RETURN apoc.cypher.runFirstColumn('WITH {m} AS m RETURN m LIMIT 10', {m:m}, true)
```
(works fine)

```
MATCH (m:Movie)
RETURN apoc.cypher.runFirstColumn('WITH {m} AS m MATCH (m)-[:ACTED_IN]-(:Person)-[:ACTED_IN]-(rec:Movie) RETURN rec LIMIT 10', {m:m}, true)
```
(works fine)

The error seems to occur only when using directed relationships.

**Comment by johnymontana** [comment]
See similar issue in neo4j-graphql: https://github.com/neo4j-graphql/neo4j-graphql/issues/98

**Comment by jexp** [comment]
It's related to the runtime used, the **compiled runtime** has an issue with the that query.

Can you try to set the default runtime to slotted?

`unsupported.cypher.runtime=SLOTTED`

**Comment by johnymontana** [comment]
I tested setting runtime to slotted as suggested and this seems to be a good temporary workaround  (at least with neo4j-graphql-js).

**Comment by joeflack4** [comment]
@johnymontana How does one "set the default runtime"? I'm encountering a similar problem while trying out the grand-stack-starter tutorial: https://github.com/grand-stack/grand-stack-starter/issues/8
