### ISSUE TITLE
APOC Neo.ClientError.Procedure.ProcedureCallFailed

### ISSUE THREAD

**Issue by 444728248** [neo4j-contrib/neo4j-apoc-procedures#777]
#CQL
MATCH (user:CaseInfo) WHERE user.XKBH = 'K00001'
CALL apoc.path.subgraphAll(user, {maxLevel:2,relationshipFilter:'DNA串并'}) YIELD nodes, relationships
RETURN nodes, relationships;

## Failed to invoke procedure `apoc.path.subgraphAll`: Caused by: java.lang.NoClassDefFoundError: org/apache/commons/collections/IteratorUtils

**Comment by sarmbruster** [comment]
Duplicate of #765. Already fixed.
