### ISSUE TITLE
please document apoc.http.timeout.connect and apoc.http.timeout.read

### ISSUE THREAD

**Issue by Dcanzano** [neo4j-contrib/neo4j-apoc-procedures#779]
please add to the APOC doc at https://neo4j-contrib.github.io/neo4j-apoc-procedures/ details on

apoc.http.timeout.connect 

and 

apoc.http.timeout.read

https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/3.3/src/main/java/apoc/util/Util.java#L279-L280

**Comment by jexp** [comment]
https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/468
