### ISSUE TITLE
add functions to create byte arrays

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#784]
- from hex string
- from base64 string
- from int[] / long[]

and to those formats too

**Comment by binarycoded** [comment]
Hi @jexp 
have you thought about just adding java helper methods that support those conversions or implementing user functions for that? If user functions, how can we return the byte arrays? Converted as string?
Best regards

**Comment by cskardon** [comment]
@jexp - The original checkin above (https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/5b5fcc5a91f42445109552065f7f386d54a5bfee) contains a test for odd length hex strings, for example:

```
ABC = 0xAB 0x0C
```

But:

```
AB0C = 0xAB 0x0C
```

as well. 
In my view - `ABC = 0x0A 0xBC` -- what are your thoughts?

**Comment by jexp** [comment]
Isn't there a standard for that or such?

**Comment by conker84** [comment]
Closing for lack of feedback, feel free to reopen in case you have more info
