### ISSUE TITLE
apoc.index.addAllNodes fails silently when string submitted > 32k

### ISSUE THREAD

**Issue by mimomenome** [neo4j-contrib/neo4j-apoc-procedures#787]
we found with the apoc.index.addAllNodes that it was silently generating an exception (reported via support) - we had to cut the string back below 32k bytes… 

Apparently it should be handling this by splitting the string and calling add: 

32k limit in handled gracefully inside neo4j - looks like I was wrong. `FreeTextSearch.populate` should split the string in 32k chucks and call `add` multiple times.

Thanks!
M. 

log output follows: 
/22/2018 10:27:47 AM2018-03-22 16:27:47.832+0000 INFO  starting batching from `match (f:File ) where length(f.FullText)>=24000 return f` operation using iteration `set f.FullText = left(f.FullText,23000)` in separate thread
3/22/2018 10:30:45 AM2018-03-22 16:30:45.564+0000 INFO  Dropping existing index ‘Files’, with config: {keysForLabel:File=FullText, autoUpdate=true, provider=lucene, type=fulltext, to_lower_case=true, labels=File}
3/22/2018 10:30:45 AM2018-03-22 16:30:45.594+0000 INFO  Creating or updating index ‘Files’ with config ‘{keysForLabel:File=FullText, autoUpdate=true, type=fulltext, to_lower_case=true, provider=lucene, labels=File}’
3/22/2018 10:43:00 AMException in thread “pool-3-thread-50” java.lang.IllegalArgumentException: Property value bytes length: 33612 is longer then 32766, which is maximum supported length of indexed property value.
3/22/2018 10:43:00 AM    at org.neo4j.kernel.impl.api.IndexValueLengthValidator.validate(IndexValueLengthValidator.java:44)
3/22/2018 10:43:00 AM    at org.neo4j.kernel.impl.api.ExplicitIndexValueValidator.validate(ExplicitIndexValueValidator.java:41)
3/22/2018 10:43:00 AM    at org.neo4j.index.impl.lucene.explicit.LuceneExplicitIndex.assertValidValue(LuceneExplicitIndex.java:144)
3/22/2018 10:43:00 AM    at org.neo4j.index.impl.lucene.explicit.LuceneExplicitIndex.addNode(LuceneExplicitIndex.java:108)
3/22/2018 10:43:00 AM    at org.neo4j.kernel.impl.api.StateHandlingStatementOperations.nodeAddToExplicitIndex(StateHandlingStatementOperations.java:1570)
3/22/2018 10:43:00 AM    at org.neo4j.kernel.impl.api.OperationsFacade.nodeAddToExplicitIndex(OperationsFacade.java:1129)
3/22/2018 10:43:00 AM    at org.neo4j.kernel.impl.coreapi.ExplicitIndexProxy$Type$1.add(ExplicitIndexProxy.java:92)
3/22/2018 10:43:00 AM    at org.neo4j.kernel.impl.coreapi.ExplicitIndexProxy.internalAdd(ExplicitIndexProxy.java:495)
3/22/2018 10:43:00 AM    at org.neo4j.kernel.impl.coreapi.ExplicitIndexProxy.add(ExplicitIndexProxy.java:349)
3/22/2018 10:43:00 AM    at apoc.index.FreeTextSearch.populate(FreeTextSearch.java:169)
3/22/2018 10:43:00 AM    at apoc.index.FreeTextSearch.lambda$addAllNodes$0(FreeTextSearch.java:62)
3/22/2018 10:43:00 AM    at apoc.util.AsyncStream.lambda$async$0(AsyncStream.java:20)

**Comment by sarmbruster** [comment]
APOC fulltext will be deprecated soon as we have full fledged fulltext capabilities directly in Neo4j 3.5. Therefore it's  `won't fix`.
