### ISSUE TITLE
max value in apoc.agg.statistics does not match either apoc.coll.max nor builtin Max() in Cypher

### ISSUE THREAD

**Issue by lamLeX** [neo4j-contrib/neo4j-apoc-procedures#788]
I tried with the the set values given in the text file.
[datasource.txt](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/1917361/datasource.txt)

the result of Cypher's `Max()` and `apoc.coll.max()` are the same
but the max value returned by `apoc.agg.statistics()` is different from both `Max()` and `apoc.coll.max()`

**Comment by jexp** [comment]
We need to change that max, min are computed traditionally and not with HdrHistogram, which we should only use for percentiles.
