### ISSUE TITLE
APOC Intersection issue

### ISSUE THREAD

**Issue by ericmonk** [neo4j-contrib/neo4j-apoc-procedures#789]
Case2 below should work without explicitly casting between Integers or Longs.  Case4 shows a current work-around for this.

/* case1: this works */
WITH [1,2] as set1, [2,3] as set2
WITH apoc.coll.intersection(set1, set2) as intersection
RETURN intersection

/* case2: this doesn't work */
WITH apoc.convert.fromJsonMap('{"numbers":[1,2]}') as set1, [2,3] as set2
WITH apoc.coll.intersection(set1.numbers, set2) as intersection
RETURN intersection

/* case3: this works */
WITH apoc.convert.fromJsonMap('{"numbers":[1,2]}') as set1, [2,3] as set2
RETURN filter(number IN set1.numbers WHERE number IN set2) as intersection

/* case4: works - work around for case2 */
WITH apoc.convert.fromJsonMap('{"numbers":[1,2]}') as set1, [2,3] as set2
WITH apoc.coll.intersection([x in set1.numbers | tointeger(x)], set2) as intersection
RETURN intersection

**Comment by inserpio** [comment]
@jexp should we change `fromJsonMap` customizing number conversion to long by default or would you work on the `intersection` procedure to solve the issue? `intersection` currently use `Set#retailAll` that uses `equals` as the comparator which of course returns false when you compare long and integer values

**Comment by jexp** [comment]
Yes same for float>double

**Comment by jexp** [comment]
Yes same for float>double

**Comment by conker84** [comment]
Hi @jexp what do you think about Alberto's request regarding the update of Jackson version to 2.x?

**Comment by jexp** [comment]
Yes to both
