### ISSUE TITLE
Active Page Cache Warmup

### ISSUE THREAD

**Issue by moxious** [neo4j-contrib/neo4j-apoc-procedures#791]
Neo4j 3.4 enterprise introduces a new feature where the page cache can be saved to disk and restored on startup:  https://github.com/neo4j/neo4j/pull/10957

This perhaps replaces `apoc.warmup.run()` for neo4j >= 3.4 enterprise.

@sarmbruster recommended for this procedure to check for edition, and use existing behavior for CE and do noop + log on EE, which seems sensible.

**Comment by jexp** [comment]
If pages are are loaded warmup just takes seconds on huge graphs

**Comment by jexp** [comment]
Is that behavior enabled by default on EE ?

**Comment by albertodelazzari** [comment]
The feature is enabled by default in Neo4j. 
The property `unsupported.dbms.memory.pagecache.warmup.enable` is true and you have to disable it explicitly.

**Comment by jexp** [comment]
It not really replaces it, I built a new version of warmup that uses some new API and also warms up indexes. Just need some feedback from the field-team.

**Comment by jexp** [comment]
I don't think we have to do something actively here.

If folks need apoc warmup they can use it, otherwise if the auto-warmup works fine for them they don't need to use apoc warmup.
E.g. I'm not sure that PC profiles make it through a backup.

**Comment by conker84** [comment]
@jexp @moxious is this still valid?
