### ISSUE TITLE
apoc.index.search - strange work with non-standart analyzer

### ISSUE THREAD

**Issue by vstruchkov** [neo4j-contrib/neo4j-apoc-procedures#792]
I create fulltext index with Russian analyzer

> call apoc.index.addAllNodes('RusNameIndex',{Name:["value"]},{autoUpdate:true,analyzer:'org.apache.lucene.analysis.ru.RussianAnalyzer'})

Than try to search value

> call apoc.index.search('RusNameIndex','"Сергей Павлович Карпов"') yield node,weight match (:Person)-[:Name]->(node) return distinct node.value as name,weight limit 10

I recieve (no changes, no records)
Than try to search with match 

> match (p:Person)-[:Name]->(n:Name) where n.value='Сергей Павлович Карпов' return count(*)

And recieve 
count(*)=2

I search equal string and get different results

**Comment by vstruchkov** [comment]
Michael, I create fulltext-index with apoc procedure addAllNodes.
I expect that apoc-clause (with Russian analyzer) and match-clause return same result.

**Comment by jexp** [comment]
But you customized the apoc index with a custom analyzer for Russian.

While the built in index just uses the default analyzer.

As this question is more about Neo4j's built in index, would you mind asking it at github.com/neo4j/neo4j/issues ?

**Comment by vstruchkov** [comment]
Michael,
As I understand the match-clause uses build-in index. In my example it works fine, I receive two result with searching Russian phrase. 
But apoc fulltext-index with Russian analyzer return nothing.  My question is why? Where is error?

**Comment by vstruchkov** [comment]
@jexp 

I found similar behaviour in English words.
`match (:ReleaseOrganization)-[:Name]-(n:Name) where n.value='Lund University.' return n.value;`
This query return 
╒══════════════════╕
│"n.value"         │
╞══════════════════╡
│"Lund University."│
└──────────────────┘

then using apoc.index.search

`call apoc.index.search('NameIndex','Univ*') yield node match (:ReleaseOrganization)-[:Name]->(node) return distinct node.value as name limit 10`
This query return
`  (no changes, no records)  `

Index creation string `call apoc.index.addAllNodes('NameIndex',{Name:["value"]},{autoUpdate:true})`

**Comment by conker84** [comment]
Indexes are now part of the product, I'm closing this
