### ISSUE TITLE
Inconsistent ordering in apoc.coll.sort*

### ISSUE THREAD

**Issue by cskardon** [neo4j-contrib/neo4j-apoc-procedures#797]
There is an inconsistency in the default way the `apoc.coll.sort` methods sort, bearing in mind that the default for Cypher is to order in Ascending, I would expect _all_ the sort methods to also sort in that way by default.

`apoc.coll.sort` orders in ASC 
`apoc.coll.sortMaps` orders in ASC
`apoc.coll.sortMulti` orders in **DESC**
`apoc.coll.sortNodes` orders in ASC

I think they should all be ASC, as the default is.

Fix wise - it's pretty simple, the problem is - it would be a **breaking** change, as anyone who is currently using `sortMulti` and expecting it to work in it's current way would have problems.

If it's something that _should_ be fixed, let me know and I'll get on it, but I won't work on it unless it's decided it's a 'goer'. :)

**Comment by jexp** [comment]
yes please fix, this seems to be an oversight, looking forward to your PR

usually, it's asc, if you need desc, then you can reverse the list.

**Comment by cskardon** [comment]
Should this now be closed as per this [comment](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/800#issuecomment-387628557)?

**Comment by jexp** [comment]
Probably we should make it clearer in the documentation.

The other ones are by default ascending b/c there is no means to indicate sort order (AFAIR).

**Comment by cskardon** [comment]
From what I can see - your memory serves you correctly - So.

Given "99% of cases are descending..." should 

1. The others be switched to DESC by default
2. Nothing be done

Something to consider (in my view) is whether APOC would want a 'DESC' order for the other sorts - I know you can just reverse them, but that seems a bit cludgy.. 

If I considered doing the latter option of adding a DESC option - I would add a 'properties' thing like the other methods have, so:

`apoc.coll.sortNodes(COLLECT(t), 'Name', {desc: true})`

Which I think is clearer and doesn't rely on string parsing.
