### ISSUE TITLE
apoc.export.cypher.query format plain and cypherFormat updateAll don't work properly

### ISSUE THREAD

**Issue by dotbenj** [neo4j-contrib/neo4j-apoc-procedures#799]
According to the [documentation](https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_export_to_cypher_script)

If we select format: 'plain' and cypherFormat: 'updateAll' it should generate a file with plain cypher (without begin/commit/await).

I try this for generate a file for a subgraphe with both neo4j-community-3.2.5/apoc-3.2.0.2 and neo4j-coommunity-3.3.5/apoc-3.3.0.1 and everytime I generate this I've got default neo4j-shell file with begin/commit/await and it's with create and not merge like it should be with the option cypherFormat: 'updateAll'.

here is my query to generate the file:
`call apoc.export.cypher.query('MY_QUERY','/PATH/TO/MY/FILE/exportPlain.cypher',{format:'plain',cypherFormat:'updateAll'})`

Did a made something wrong or maybe it's a problem of version ?

**Comment by conker84** [comment]
Hi @beninja are you still affected by this problem?

**Comment by conker84** [comment]
Closed for lack of feedback
