### ISSUE TITLE
Neo4j APOC remove trigger NPE

### ISSUE THREAD

**Issue by Artgit** [neo4j-contrib/neo4j-apoc-procedures#801]
I need to delete APOC trigger. The following call works fine in case the trigger already exists:

    CALL apoc.trigger.remove('RELATIONSHIP_INDEX_ADD_HAS_VALUE_ON');

but fails with the following exception:

> Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke
> procedure `apoc.trigger.remove`: Caused by:
> java.lang.NullPointerException

if the trigger is absent.

How to properly try to remove the trigger and not fail in case it doesn't exist?

**Comment by Dcanzano** [comment]
having more details on APOC version and Neo4j version would help as well

**Comment by Dcanzano** [comment]
and if you are getting a NullPointerException I might expect your $NEO4J_HOME/logs/debug.log will contain more of the stack trace.   Could you please post a snippet of that stack trace

**Comment by alexiudice** [comment]
You could check if the trigger exists and delete it only if it is found:

`CALL apoc.trigger.list() YIELD name
WITH collect(name) AS names, ['RELATIONSHIP_INDEX_ADD_HAS_VALUE_ON'] AS triggersToBeDeleted
WITH filter(x IN names WHERE x in triggersToBeDeleted) AS foundTriggers
UNWIND foundTriggers AS foundTrigger
CALL apoc.trigger.remove(foundTrigger) YIELD name
RETURN name`

**Comment by conker84** [comment]
Closed as we have a valid answer
