### ISSUE TITLE
Neo.ClientError.Security.Forbidden: Write operations are not allowed for user 'neo4j' with FULL restricted to READ.

### ISSUE THREAD

**Issue by Artgit** [neo4j-contrib/neo4j-apoc-procedures#802]
I use Neo4j 3.3.5 and apoc-3.3.0.2-all.jar 

I have installed the following triggers:

`CALL apoc.trigger.add('RELATIONSHIP_INDEX_ADD_HAS_VALUE_ON', 'UNWIND {createdRelationships} AS r MATCH (d:Decision)-[r:HAS_VALUE_ON]->(ch:Characteristic) CALL apoc.index.addRelationship(r, keys(r)) RETURN count(*)', {phase:'after'});`
`
CALL apoc.trigger.add('RELATIONSHIP_INDEX_REMOVE_HAS_VALUE_ON', \"UNWIND {deletedRelationships} AS r MATCH (d:Decision)-[r:HAS_VALUE_ON]->(ch:Characteristic) CALL apoc.index.removeRelationshipByName('HAS_VALUE_ON', r) RETURN count(*)\", {phase:'after'});`

but when I try to access the index with the following query:

CALL apoc.index.relationships('HAS_VALUE_ON', 'property.1.4:"1"') YIELD start as childD

it fails with the following exception:

`Neo.ClientError.Security.Forbidden: Write operations are not allowed for user 'neo4j' with FULL restricted to READ.`

What am I doing wrong and how to fix it ?

**Comment by conker84** [comment]
hi @Artgit do you still have this problem?

**Comment by flaviamissi** [comment]
I'm seeing it too with `apoc.cypher.run` on neo4j desktop. neo4j 3.5.8.

**Comment by jexp** [comment]
Which user are you using there? And what permissions do they have?

**Comment by flaviamissi** [comment]
> Which user are you using there? And what permissions do they have?

tried with both a user I created myself, and then the neo4j user. 
I did realise using APOC to run my cypher query wasn't needed in the end, so that's how I got to move forward..

**Comment by antikvarBE** [comment]
Experiencing this issue too on my 3.5.14. This happens when trying to use apoc.cypher.runMany.

**Comment by sarmbruster** [comment]
you shouldn't do any write operations in a `{phase:'after'}` trigger. At that point the transaction is already committed. After triggers are intended e.g. to porpagate tx contents to other systems.

**Comment by aleksanderlech** [comment]
Same problem spotted on Neo4j 3.5.16 and APOC 3.5.0.11 while runnint `db.index.fulltext.createNodeIndex` within `apoc.do.when`.

**Comment by MbICJIb** [comment]
I have the same issue wile calling apoc.jdbc.load within apoc.do.when. Even without writing anything.
Neo4j version is 3.5.19. apoc version 3.5.0.12

**Comment by jexp** [comment]
Need to use when do

What permissions does your user have?

What is your full statement

**Comment by conker84** [comment]
Closed for lack of feedback

**Comment by hlin863** [comment]
I have installed Neo4j for code implementation in a full-text index query with this function for creating a full-text query, `create_fulltext_index`, in the class `MovieSearch`:

```
class MovieSearch:
    def __init__(self, connection: Neo4jConnection):
        self.connection = connection

    def create_fulltext_index(self):
        query = """
        CREATE FULLTEXT INDEX Movie_plot_ft IF NOT EXISTS
        FOR (x:Movie)
        ON EACH [x.plot]
        """
        try:
            self.connection.execute_write(query)
            print("Full-text index created or already exists.")
        except neo4j.exceptions.Forbidden as e:
            print(f"Permission denied while creating full-text index: {e}")
            print("Proceeding without creating the index. Ensure it exists or ask an admin to create it.")
```

When the function `create_fulltext_index` is called, there is an error message, `Neo.ClientError.Procedure.ProcedureCallFailed`, with the full message:

> neo4j.exceptions.ClientError: {code: Neo.ClientError.Procedure.ProcedureCallFailed} {message: Failed to invoke procedure `db.index.fulltext.queryNodes`: Caused by: java.lang.IllegalArgumentException: There is no such fulltext schema index: Movie_plot_ft}

How do I implement a fix to ensure a successful full-text query operation?
