### ISSUE TITLE
Failed to invoke procedure `apoc.do.when`: Caused by: scala.MatchError: SetIncludingPropertiesFromMapItem

### ISSUE THREAD

**Issue by ShangyanLi** [neo4j-contrib/neo4j-apoc-procedures#803]
The query below
`LOAD CSV WITH HEADERS FROM "file:///investors_medium.csv"`
`AS row FIELDTERMINATOR '\t'`
`OPTIONAL MATCH (p:P {uuid: row.uuid})`
`CALL apoc.do.when((p IS NULL), 'MATCH (o:O {uuid: ruuid}) SET o += row {.*}', 'SET p += row {.*}', {p:p, ruuid:row.uuid, row:row}) YIELD value AS v`
`RETURN v LIMIT 10`
results in the following error:
`Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `apoc.do.when`: Caused by: scala.MatchError: SetIncludingPropertiesFromMapItem(Variable(p),DesugaredMapProjection(Variable(row),List(),true)) (of class org.neo4j.cypher.internal.frontend.v3_3.ast.SetIncludingPropertiesFromMapItem)`

To clarify: I am loading each row and trying to match its uuid field with uuid's in the DB, which could either belong to a `P` node or an `O` node (using a classic Cypher `MATCH (n) WHERE n:O OR n:P AND n.uuid = row.uuid` loses the advantage of label-based indexing and gets extremely slow - hence using `apoc.do.when` here), then update the node properties with the full `row` map. However, the `SET o += row {.*}` syntax doesn't seem to work here. 

I confirmed that `SET o += row {.*}` works outside `apoc.do.when`, and even calling something like `RETURN row {.*}` works for `apoc.when`.

Any help? Thanks!

**Comment by jexp** [comment]
Which neo4j version were you using? Is it still happening?

And can you share some sample data where that happens?

**Comment by conker84** [comment]
Closing for lack of feedback
