### ISSUE TITLE
APOC trigger and assignedRelationshipProperties with apoc.index.in function

### ISSUE THREAD

**Issue by Artgit** [neo4j-contrib/neo4j-apoc-procedures#805]
I have created the following trigger:

    CALL apoc.trigger.add('TEST_TRIGGER', "UNWIND keys({assignedRelationshipProperties}) AS key UNWIND {assignedRelationshipProperties}[key] AS map WITH map WHERE type(map.relationship) = 'LIVES_IN' CALL apoc.index.addRelationship(map.relationship, keys(map.relationship)) RETURN count(*)", {phase:'before'})

verified that trigger exists by `CALL apoc.trigger.list()`

create the following nodes and relationship:

    CREATE (p:Person) return p
    CREATE (c:City) return c
    
    MATCH (p:Person), (c:City) CREATE (p)-[r:LIVES_IN]->(c) RETURN type(r)

tried to access it by index query:

    MATCH (p:Person)-[r:LIVES_IN]->(c:City) CALL apoc.index.in(c, 'LIVES_IN', 'time:10') YIELD node AS person RETURN person

the query returns empty result which is fine for now.

assigned relationship new property `time` with value = `10`:

    MATCH (p:Person)-[r:LIVES_IN]->(c:City) SET r.time = 10 RETURN r

tried to access it by index query:

    MATCH (p:Person)-[r:LIVES_IN]->(c:City) CALL apoc.index.in(c, 'LIVES_IN', 'time:10') YIELD node AS person RETURN person

the query successfully returns the expected `Person` node

Now, I reassigned the `time` property another value = `11`

    MATCH (p:Person)-[r:LIVES_IN]->(c:City) SET r.time = 11 RETURN r

tried to access it by index query one more time:

    MATCH (p:Person)-[r:LIVES_IN]->(c:City) CALL apoc.index.in(c, 'LIVES_IN', 'time:10') YIELD node AS person RETURN person
    MATCH (p:Person)-[r:LIVES_IN]->(c:City) CALL apoc.index.in(c, 'LIVES_IN', 'time:11') YIELD node AS person RETURN person

the query returns empty result for both of them.. 

What am I doing wrong and why was the index not updated after the property change? 

This is also the corresponding StackOverflow question on this issue: https://stackoverflow.com/questions/50254049/neo4j-apoc-assignedrelationshipproperties-removedrelationshipproperties-trigger

**Comment by conker84** [comment]
Fixed in v 3.4.0.1 (see [stackoverflow](https://stackoverflow.com/questions/50254049/neo4j-apoc-assignedrelationshipproperties-removedrelationshipproperties-trigger#comment-87867810))
