### ISSUE TITLE
Add procedure to assign x and y coordinates, given grid dimensions and 

### ISSUE THREAD

**Issue by graham-macleod** [neo4j-contrib/neo4j-apoc-procedures#808]
It would be great if neo4j provided functionality which meant you didn't have to write your own program to assign x and y coordinates to nodes for visualisation purposes.  Sure, there are many libraries out there which do this for you on the fly, but some visualisation tools don't support dynamic graph visualisation (such as Tableau) and need the coordinates to be held in the data.

A procedure which, given a graph, and the dimensions of the grid could in theory be created to provide this functionality to avoid users having to code this themselves.

networkx for python has a [spring_layout function](https://networkx.github.io/documentation/networkx-1.9/reference/generated/networkx.drawing.layout.spring_layout.html#networkx.drawing.layout.spring_layout) that uses ther Fruchterman-Reingold force-directed algorithm to achieve this.

**Comment by conker84** [comment]
I this should not been done into APOC if there is more demand please add +1 and we're happy to work on it
