### ISSUE TITLE
apoc.index.addNodeMap adding a square bracket into the index value for multi valued properties

### ISSUE THREAD

**Issue by jamallucas** [neo4j-contrib/neo4j-apoc-procedures#814]
Hi,
If I follow the APOC User Guide Documentation
section Add "document" to index
but changing the the third line to create an employee called 'Joseph' instead of 'Martin'

```
CREATE (company:Company {name:'Neo4j,Inc.'})
CREATE (company)<-[:WORKS_AT {since:2013}]-(:Employee {name:'Mark'})
CREATE (company)<-[:WORKS_AT {since:2014}]-(:Employee {name:'Joseph'})
```

and continue following the example by running the following cypher query to populate the index 'Company' with the id of the company associated with employees and start dates

```
MATCH (company:Company)<-[worksAt:WORKS_AT]-(employee)
WITH company, { name: company.name, employees:collect(employee.name),startDates:collect(worksAt.since)} as data
CALL apoc.index.addNodeMap(company, data)
RETURN count(*)
```

If I run the query given in the example

```
CALL apoc.index.nodes('Company','employees:Ma*')
```

it does not return anything. 

I did a bit of investigation in the index using a tool called Luke, and noticed that what is actually stored as the value for the key 'employees' is two things

Field| Text
------------ | -------------
employees | [mark,
employees | joseph]

so when I search for 'employees:Ma*', it doesn't return anythings as the value stored in the index starts with a '['.
However if I run the query

```
CALL apoc.index.nodes('Company','employees:Jo*')
```

 it does return the node. 

So I assumed that the procedure addNodeMap is adding the square brackets into the values of the multi valued properties instead of insert only the text.

the procedure addNodeMapByName has the same problem.

**Comment by jexp** [comment]
That is really weird, it should notice that it's an array and store it as an array
Thanks for reporting

**Comment by jexp** [comment]
Pushed a fix, you'd have to use a local build though
which version are you at?

**Comment by jamallucas** [comment]
I'm using version 3.4.0.1.
Do you have any idea, when you guys are releasing another version?

**Comment by jexp** [comment]
You can try this version meanwhile: https://www.dropbox.com/s/vbqenjd3du2kt2e/apoc-3.4.0.1-all.jar?dl=0

**Comment by jamallucas** [comment]
Awesome thanks Michael!!!
