### ISSUE TITLE
add NumericRangeQuery feature over manual indexesto APOC

### ISSUE THREAD

**Issue by Artgit** [neo4j-contrib/neo4j-apoc-procedures#817]
I was able to port my Neo4j 3.4.0/apoc-3.4.0.1-all.jar application to use manual indexes and APOC procedures instead of queries over the indexles relationship properties. Everything is working like a charm except one last thing - I ran into the issue with non-string Lucene range queries. 

They are not working as expected, for example:

I have created the following triggers which add all of the relationship properties(of different types) into the manual index:

```
CALL apoc.trigger.add('HAS_VALUE_ON_CREATED_RELATIONSHIPS_TRIGGER', 
"UNWIND {createdRelationships} AS r WITH r 
WHERE type(r) = 'HAS_VALUE_ON' 
CALL apoc.index.addRelationship(r, keys(r)) RETURN true", 
{phase:'before'})

CALL apoc.trigger.add('HAS_VALUE_ON_ASSIGNED_RELATIONSHIP_PROPERTIES_TRIGGER', 
"UNWIND keys({assignedRelationshipProperties}) AS key 
UNWIND {assignedRelationshipProperties}[key] AS map WITH map 
WHERE type(map.relationship) = 'HAS_VALUE_ON' 
CALL apoc.index.addRelationship(map.relationship, keys(map.relationship)) RETURN true", 
{phase:'before'})
```

One of my relationship property contains `Long `timestamp values but looks like by default Neo4j Lucene index treats them as `String` and this is why when I call the query with the following Lucene predicate on this index: `value:[2 TO 6]`,  let's say:

`CALL apoc.index.between(decision,'HAS_VALUE_ON',characteristic,'value:[2 TO 6]') YIELD rel`

I receive the following response:

```
567986400000
567986400000
567986400000
536450400000
536450400000
599608800000
536450400000
567986400000
```

that is obviously not the something that was expected.

Also, the query can contain a mix of numeric and non-numeric conditions, for example

`(value:("Java" ".NET")) AND (optionIds:(1) AND property.1.4:[2 TO 6])`

Could you please add to APOC the functionality(if it does not already exist there) that will allow running `NumericRangeQuery` for the manual indexes?

**Comment by conker84** [comment]
now you can leverage lucene indexes via the product, I'm closing this.
