### ISSUE TITLE
APOC docs error: "apoc.nodes.group()" not "apoc.group.nodes()"

### ISSUE THREAD

**Issue by victoriastuart** [neo4j-contrib/neo4j-apoc-procedures#818]
In the docs

https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_node_grouping

shouldn't 

    call apoc.group.nodes(...)

correctly be

    call apoc.nodes.group(...)

![apoc.nodes.group_docs_error.png](https://user-images.githubusercontent.com/2575920/40819492-3fdcd16c-6510-11e8-996b-e82c6cde0cb2.png)

**Comment by jexp** [comment]
yes you're right, my bad.

**Comment by jexp** [comment]
Fixed, thanks!

**Comment by jexp** [comment]
Cool example btw. If you have more requiremetns / ideas for the procedure, please let us know.

Also would love to see an article on your work!!
