### ISSUE TITLE
apoc.refactor.categorize duplicated categorization nodes

### ISSUE THREAD

**Issue by karol-brejna-i** [neo4j-contrib/neo4j-apoc-procedures#826]
Neo4j version: 3.4
APOC version: 3.4.0.1

From the docs:
`Categorize replaces string property values on nodes with relationship to a unique category node for that property value.`

After running it, I got multiple (duplicated) categorization nodes.

### Prepare data
```
match (n) detach delete n

with ["PL", "DE"] as countries
unwind countries as country
foreach (no in RANGE(1, 4) |
  create (n:Company {name:country+no, country:country})
)

match (n) return n
╒═════════════════════════════╕
│"n"                          │
╞═════════════════════════════╡
│{"name":"PL1","country":"PL"}│
├─────────────────────────────┤
│{"name":"PL2","country":"PL"}│
├─────────────────────────────┤
│{"name":"PL3","country":"PL"}│
├─────────────────────────────┤
│{"name":"PL4","country":"PL"}│
├─────────────────────────────┤
│{"name":"DE1","country":"DE"}│
├─────────────────────────────┤
│{"name":"DE2","country":"DE"}│
├─────────────────────────────┤
│{"name":"DE3","country":"DE"}│
├─────────────────────────────┤
│{"name":"DE4","country":"DE"}│
└─────────────────────────────┘
```
### Verify correctnes of the call

```
CALL apoc.refactor.categorize('country','OPERATES_IN',true,'Country', 'name', [], 1)

match (n:Company)-[r:OPERATES_IN]->(c:Country) 
return ID(n) as company, ID(c) as country_ID, c.name as country_name


╒═════════╤════════════╤══════════════╕
│"company"│"country_ID"│"country_name"│
╞═════════╪════════════╪══════════════╡
│5395     │5426        │"PL"          │
├─────────┼────────────┼──────────────┤
│5412     │5427        │"DE"          │
├─────────┼────────────┼──────────────┤
│4299     │5446        │"PL"          │
├─────────┼────────────┼──────────────┤
│5411     │5447        │"DE"          │
├─────────┼────────────┼──────────────┤
│4184     │5466        │"PL"          │
├─────────┼────────────┼──────────────┤
│5410     │5467        │"DE"          │
├─────────┼────────────┼──────────────┤
│4183     │5486        │"PL"          │
├─────────┼────────────┼──────────────┤
│5413     │5487        │"DE"          │
└─────────┴────────────┴──────────────┘
```

You can observe that there are multiple PL and DE nodes (different IDs).

### Workaround
Using the same input dataset but batch size that enables the procedure to "swallow" the data in one go fixes the problem:

```
CALL apoc.refactor.categorize('country','OPERATES_IN',true,'Country', 'name', [], 8)

match (n:Company)-[r:OPERATES_IN]->(c:Country) 
return ID(n) as company, ID(c) as country_ID, c.name as country_name
╒═════════╤════════════╤══════════════╕
│"company"│"country_ID"│"country_name"│
╞═════════╪════════════╪══════════════╡
│5414     │5448        │"PL"          │
├─────────┼────────────┼──────────────┤
│5415     │5448        │"PL"          │
├─────────┼────────────┼──────────────┤
│5416     │5448        │"PL"          │
├─────────┼────────────┼──────────────┤
│5417     │5448        │"PL"          │
├─────────┼────────────┼──────────────┤
│5418     │5449        │"DE"          │
├─────────┼────────────┼──────────────┤
│5419     │5449        │"DE"          │
├─────────┼────────────┼──────────────┤
│5420     │5449        │"DE"          │
├─────────┼────────────┼──────────────┤
│5421     │5449        │"DE"          │
└─────────┴────────────┴──────────────┘
```

## Other thoughts
The guide (https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_categorization) says:
`Categorize replaces string property values on nodes with relationship to a unique category node for that property value.`

But the source code documentation have slightly different description (https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/3.4/src/main/java/apoc/refactor/GraphRefactoring.java#L257):
`apoc.refactor.categorize(sourceKey, type, outgoing, label, targetKey, copiedKeys, batchSize) turn each unique propertyKey into a category node and connect to it")`

It's "to unique category node" vs "unique propertyKey into a category node".

It looks like the procedure does what the code description promises. On the other hand the behaviour from the first description, in my opinion, is expected by the users.

**Comment by karol-brejna-i** [comment]
If controlling the multiplication of category nodes is a problem (due to parallelism), maybe a simple (included into the categorization method) merge of category nodes at the end would suffice...

This seems to be another workaround for the problem. For my example from issue description, the following would work:
```
match (c:Country) with c.name as cname, collect(c) as cnodes
CALL apoc.refactor.mergeNodes(cnodes, {}) YIELD node RETURN node
```

**Comment by jexp** [comment]
Thanks a lot for pointing this out, there should be no duplicates at all. It might be more suitable to change the code to first group streams of nodes by category-value and then crate the category nodes and then parallelize the connection creation.

But perhaps this is all overkill and the procedure should just delegate to a call like this:

CALL apoc.refactor.categorize('country','OPERATES_IN',true,'Country', 'name', [], 1)

```
call apoc.periodic.iterate(
   'match (n) where exists(n.country) return n',
   'merge (c:Country {name:n.country}) MERGE (n)-[:OPERATES_IN]->(c)',
   {batchSize:10000, iterateList:true, parallel:false}
)

```

**Comment by karol-brejna-i** [comment]
The script is what I ended up doing (+ `remove c.country`).
