### ISSUE TITLE
missing unit in apoc.date.field()

### ISSUE THREAD

**Issue by ArGeBre** [neo4j-contrib/neo4j-apoc-procedures#835]
The function apoc.date.fields() returns a map of fields, including weekdays:
` {
    'weekdays': 5,
    'years': 2015,
    'seconds': 5,
    'zoneid': 'EET',
    'minutes': 4,
    'hours': 3,
    'months': 1,
    'days': 2
  }`

In contrast, the function apoc.date.field() is missing the capability to return the field weekdays. This would be very simple to add to apoc.date.Date class. See attached diff file:

[Date_diff.txt](https://github.com/neo4j-contrib/neo4j-apoc-procedures/files/2119795/Date_diff.txt)

**Comment by jexp** [comment]
Can you please sign the CLA and send a PR? Thanks :)
