### ISSUE TITLE
apoc-3.4.0.1-all.jar

### ISSUE THREAD

**Issue by vesko50** [neo4j-contrib/neo4j-apoc-procedures#839]
I am not able to download  apoc-3.4.0.1-all.jar. Access is not allowed, but I can download proper .ZIP file

**Comment by jexp** [comment]
It is probably an issue with your browser? 
Can you try to download the URL with curl or wget or such?

**Comment by vesko50** [comment]
Thanks Michael,

It is bug with latest Google browser. It use to work in the past.

I think they just did fix. Now it is working.


Vesko




________________________________

**Comment by InverseFalcon** [comment]
Per comment, closing issue.
