### ISSUE TITLE
apoc.load.csv requires uri to be absolute path

### ISSUE THREAD

**Issue by davidfauth** [neo4j-contrib/neo4j-apoc-procedures#841]
Can we change apoc.load.csv to mimic LOAD CSV where it will use the import directory by default unless the #dbms.directories.import=import in the configuration file is commented out?

**Comment by AngeloBusato** [comment]
@davidfauth you have to set this variable on neo4j.conf 

*apoc.import.file.use_neo4j_config=true*

which use import directory.

documentation -> https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_load_csv_and_xls

**Comment by davidfauth** [comment]
@AngeloBusato Even with that setting enabled on 3.4.1 and apoc-3.4.0.1-all.jar, this does not work.

CALL apoc.load.csv('file:///EventPolicy.csv', {header:true,sep:'|'}) yield map as row
 RETURN row
 LIMIT 10

Error is: 
Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `apoc.load.csv`: Caused by: java.io.FileNotFoundException: /EventPolicy.csv (No such file or directory)

**Comment by albertodelazzari** [comment]
The error seems related to `apoc.util.FileUtils#changeFileUrlIfImportDirectoryConstrained` and how this method creates the path, in particular for Windows OS systems.

@davidfauth are you using Windows, isn't it?

**Comment by albertodelazzari** [comment]
As requested we will align the behaviour to mimic the same behaviour of the `LOAD CSV` cypher directive. If "dbms.directories.import" is not commented out then we always consider a relative path when importing otherwise it will be always an absolute one.

**Comment by conker84** [comment]
Hi @jexp what do you think about Alberto's comment where he says:

_If we use `db.getDependencyResolver().resolveDependency(Config.class).getValue("dbms.directories.import")` when creating apoc config we can benefit of the automatic resolution of the relative path with respect to the neo4j_home._

Can we proceed in this way?

**Comment by conker84** [comment]
In particular in order to maintain the backwards compatibility we was wondering something like this in `ApocConfiguration`:

```java
Map<String, String> params = db.getDependencyResolver().resolveDependency(Config.class)
                .getConfigValues().entrySet().stream()
                .collect(Collectors.toMap(e -> e.getKey(), e -> e.getValue().valueAsString().orElse(StringUtils.EMPTY)));
```
