### ISSUE TITLE
Better handle apoc.trigger.enabled=false

### ISSUE THREAD

**Issue by kvegter** [neo4j-contrib/neo4j-apoc-procedures#845]
When the apoc.trigger.enabled=false or there is no apoc.trigger.enabled setting in the neo4j.conf file, all the calls to apoc.trigger.* fail with a null pointer exception in the browser.
It would be better is the message is "apoc.trigger.enabled is false in neo4j.conf" (or something like that)

**Comment by alexiudice** [comment]
I agree a better handle for this would be useful. I created a PR that I think solves the problem (#861).
