### ISSUE TITLE
apoc.periodic.iterate fails when updating from a map

### ISSUE THREAD

**Issue by gregcarlin** [neo4j-contrib/neo4j-apoc-procedures#846]
I'm using `apoc.periodic.iterate` to update a large number of nodes at once. Specifically, each node has a property called "details" that contains a json object serialized as a string. I want to update each node so the key-value pairs in the json object become properties of the node. Specifically, I am wondering why the following query fails:

    CALL apoc.periodic.iterate('MATCH (n) RETURN n', 'SET n += apoc.convert.fromJsonMap(n.details)');

(specifically, each batch fails with a NullPointerException) but this query succeeds:

    CALL apoc.periodic.iterate('MATCH (n) RETURN ID(n) AS i', 'MATCH (n) WHERE ID(n) = i SET n += apoc.convert.fromJsonMap(n.details)');

Is this expected behavior? I can't find any documentation indicating why the original query wouldn't work, and similar queries, such as this one, are fine:

    CALL apoc.periodic.iterate('MATCH (n) RETURN n', 'SET n.test += apoc.convert.fromJsonMap(n.details).field');

I built the server from a recent source (ie. I'm running 3.5-SNAPSHOT) and am using the neo4j shell bundled in the build.

**Comment by jexp** [comment]
hmm I don't know about the behavoir of snapshot builds (which is not recommended for any use than for contributors)
Also for neo4j-shell you need to make sure it sees the right apoc jar there needs to be a 2nd copy in the graph.db/plugins folder.


Short of some of those properties being null I'm not sure what a reason for that could be. Any chance you can share the data with me?
If you're building yourself you can also just start the shell in debug mode, connect with your IDE with the APOC project open and set an Exception Breakpoint on NPE.
Then you should see where it occurrs.

**Comment by gregcarlin** [comment]
Oh! - there are almost definitely some properties of `n.details` that are null. Would that be the issue? It seems strange that it would work in the second query but not the first.

**Comment by jexp** [comment]
Any progress here @gregcarlin on sharing an example?

**Comment by conker84** [comment]
Seems not a real bug, feel free to reopen in case you have more info
