### ISSUE TITLE
Inexact relationship parameter in apoc.algo.closeness()&apoc.algo.betweenness()

### ISSUE THREAD

**Issue by thenoNOno** [neo4j-contrib/neo4j-apoc-procedures#847]
When the parameter of the incoming relation type is taken, all relations of the types in the graph are taken out for calculation.
In fact, when calculating closeness, it is more desirable to calculate only the relationship in the subgraph.
because:
When I calculate on the subgraph
1. It takes a lot of unnecessary computing resources.
2. It has an indeterminate effect on the result of calculation (I don't know whether the same name relation in graph will participate in calculation).

**path&code** 

`~/neo4j-apoc-procedures/src/main/java/apoc/algo/Centrality.java`

> public Stream<NodeScore> closeness(
>             @Name("types") List<String> types,
>             @Name("nodes") List<Node> nodes,
>             @Name("direction") String direction) {
>         assertParametersNotNull(types, nodes);
>         try {
>             RelationshipType[] relationshipTypes = types.isEmpty()
>                     ? Util.allRelationshipTypes(db)
>                     **_: Util.toRelTypes(types);_**
>             SingleSourceShortestPath<Double> sssp = new SingleSourceShortestPathDijkstra<>(
>                     0.0,
>                     null,
>                     (relationship, dir) -> 1.0,
>                     new DoubleAdder(),
>                     new DoubleComparator(),
>                     Util.parseDirection(direction),
>                     relationshipTypes);

`~/neo4j-apoc-procedures/src/main/java/apoc/util/Util.java`

> public static RelationshipType[] **_toRelTypes_**(List<String> relTypeStrings) {
>         RelationshipType[] relTypes = new RelationshipType[relTypeStrings.size()];
>         for (int i = 0; i < relTypes.length; i++) {
>             relTypes[i] = RelationshipType.withName(relTypeStrings.get(i));
>         }
>         return relTypes;
>     }
>

**Comment by jexp** [comment]
Please use github.com/neo4j-contrib/neo4j-graph-algorithms instead
