### ISSUE TITLE
Feature Request: Add weight threshold to dijkstra algorithm

### ISSUE THREAD

**Issue by machosec** [neo4j-contrib/neo4j-apoc-procedures#867]
Hi,
Neo4j often crashes when using apoc dijkstra algorithm with big and complex graphs, espcially if no path exist.
An interesting way to avoid this behavior is to set a maximum distance/weight that the dijkstra algorithm won't exceed ("stop if cost reached"), limiting the possbility of crashes/long run times.
This feature is also very useful when multiple results are desired (eba8848b6bc8524aa3e70691ed189f6c1225a64f), but with a certain degree of control (Using `WHERE weight < n` is not a solution in this case).

Such feature would be awsome!
Keep up the great work.

**Comment by machosec** [comment]
Hi @jexp. Thanks for the reply.
I looked at neo4j-graph-algorithms and didn't find any implementation of dijkstra or any other alternative (A* is not compatible) that may contain the feature I mentioned. Why do you recommend neo4j-graph-algorithms over APOC?

**Comment by conker84** [comment]
Use GDS now, APOC algo are deprecated
