### ISSUE TITLE
Similarity algorithms aren't available

### ISSUE THREAD

**Issue by legolego** [neo4j-contrib/neo4j-apoc-procedures#880]
These algorithms aren't available in Neo4j 3.4.5 with APOC 3.4.0.2:
apoc.algo.cosineSimilarity
apoc.algo.euclideanDistance
apoc.algo.euclideanSimilarity

but help on them is avavilabe.

calling: `call apoc.algo.cosineSimilarity()`

results in:
`Neo.ClientError.Procedure.ProcedureNotFound: There is no procedure with the name `apoc.algo.cosineSimilarity` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.`

![image](https://user-images.githubusercontent.com/1666188/44002720-56f9e75c-9e15-11e8-8433-5629d8438c69.png)

**Comment by sarmbruster** [comment]
those are not procedures but user defined functions instead. Use them in expressions e.g. `MATCH (...) RETURN apoc.algo.cosineSimilarity(...)`
