### ISSUE TITLE
apoc.map.fromPairs does not work

### ISSUE THREAD

**Issue by kuczera** [neo4j-contrib/neo4j-apoc-procedures#883]
When i try this query in my neo4j 3.4.5 DB with apoc properly installed:

`
call apoc.load.xml("https://raw.githubusercontent.com/kuczera/Graphentechnologien/master/docs/data/books.xml", '/catalog/book') yield value as catalog
UNWIND catalog._children as book
WITH book.id as id, [attr IN book._children WHERE attr._type IN ['author','title'] | [attr._type, attr._text]] as pairs
CALL apoc.map.fromPairs(pairs) yield value
RETURN id, value.author, value.title
`

i get an error:

> Neo.ClientError.Procedure.ProcedureNotFound: There is no procedure with the name `apoc.map.fromPairs` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.

but apoc is properly installed when i run 

> CALL dbms.functions()

**Comment by InverseFalcon** [comment]
This is a function, not a procedure, so no need to use CALL or YIELD, just use it inline:

```
call apoc.load.xml("https://raw.githubusercontent.com/kuczera/Graphentechnologien/master/docs/data/books.xml", '/catalog/book') yield value as catalog 
UNWIND catalog._children as book 
WITH book.id as id, [attr IN book._children WHERE attr._type IN ['author','title'] | [attr._type, attr._text]] as pairs 
WITH id, apoc.map.fromPairs(pairs) as value 
RETURN id, value.author, value.title
```

**Comment by kuczera** [comment]
Then i get this error: 

> Neo.ClientError.Procedure.ProcedureCallFailed
Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke function `apoc.map.fromPairs`: Caused by: java.lang.NullPointerException

**Comment by jexp** [comment]
Can you just return the "pairs" and see what's in there.

**Comment by kuczera** [comment]
With this 
`call apoc.load.xml("https://raw.githubusercontent.com/kuczera/Graphentechnologien/master/docs/data/books.xml", '/catalog/book') yield value as catalog 
UNWIND catalog._children as book 
WITH book.id as id, 
[attr IN book._children WHERE attr._type IN ['author','title'] |
[attr._type, attr._text]] as pairs
RETURN pairs`

you get 

`

pairs
--
null
null
null
null
null
null
null
null
null
null
null
null
null
null

The query is from [https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/3.4/docs/loadxml.adoc](https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/3.4/docs/loadxml.adoc) as I'm actually trying to understand how apoc.load.xml works but wether the example file bokks.xml is reachable nor the query works (i published the file again under [https://raw.githubusercontent.com/kuczera/Graphentechnologien/master/docs/data/books.xml](https://raw.githubusercontent.com/kuczera/Graphentechnologien/master/docs/data/books.xml)
`

**Comment by jexp** [comment]
Looks like a clear sign that the query is wrong :)

**Comment by jexp** [comment]
Due to your xpath expression you're already reaching into the catalogue, so `value` is `book` entries.


```
call apoc.load.xml("https://raw.githubusercontent.com/kuczera/Graphentechnologien/master/docs/data/books.xml", '/catalog/book') 
yield value as book 
WITH book.id as id, [attr IN book._children WHERE attr._type IN ['author','title'] | [attr._type, attr._text]] as pairs 
RETURN pairs
```
