### ISSUE TITLE
apoc.load.jdbc fails with special characters in connection string

### ISSUE THREAD

**Issue by oaicstef** [neo4j-contrib/neo4j-apoc-procedures#885]
Hi, 
I'm having an issue with the apoc.load.jdbc method. 
I was investigating into the source code and I found the issue, here I attach the unit test I prepared to confirm the bug:

```
@Test(expected = RuntimeException.class)
 public void testLoadJdbcWithSpecialChar() throws Exception {

        String connStr = "jdbc:derby;database=db1;user=client0;password=1234#5$6#;encrypt=true;trustServerCertificate=false;loginTimeout=30;";
        db.execute("CALL apoc.load.jdbc('" + connStr + "', 'PERSON')").next();
    }

```

In my production environment I have to connect to a sql server database.
I was trying to generate the jar package but I'm having some trouble with the class version.

**Comment by conker84** [comment]
closed via 5c8c827
