### ISSUE TITLE
apoc.meta.graph() > A node is missing its label

### ISSUE THREAD

**Issue by adriens** [neo4j-contrib/neo4j-apoc-procedures#888]
On a given node, the description is not working as expected :

![2018-08-16 17_02_31-neo4j bolt___localhost_7687 - neo4j browser](https://user-images.githubusercontent.com/5235127/44191297-6e16c900-a176-11e8-911d-0c6f47ce4a47.png)

**Comment by adriens** [comment]
Find below a give node properties :

![2018-08-16 17_05_54-neo4j bolt___localhost_7687 - neo4j browser](https://user-images.githubusercontent.com/5235127/44191353-ccdc4280-a176-11e8-80d3-6b13f19675b6.png)

**Comment by jexp** [comment]
Unrelated to apoc, you have to select the caption to show in your browser UI.
It can get confused if you do meta-graph in between or other uses of the label.

Click the label on top  and then select the caption below the graph viz.

**Comment by adriens** [comment]
Same behavior on `db.schema` :

![2018-08-16 17_10_00-neo4j bolt___localhost_7687 - neo4j browser](https://user-images.githubusercontent.com/5235127/44191477-5d1a8780-a177-11e8-8df0-a0f05837a610.png)

**Comment by adriens** [comment]
@jexp : still, why does this always happen on the same Label ?..even without focusing on none please ?

![2018-08-16 17_12_23-neo4j bolt___localhost_7687 - neo4j browser](https://user-images.githubusercontent.com/5235127/44191570-c69a9600-a177-11e8-9670-3cab8198304d.png)
