### ISSUE TITLE
Question on Full Text Search

### ISSUE THREAD

**Issue by SageAgastya** [neo4j-contrib/neo4j-apoc-procedures#889]
Hi,
 Please tell me if this is not the right place to ask questions.
I'd like to filter the nodes of a Cypher query result based on keywords. For that, I'm thinking of dynamically creating an index that associates the query that gave the result. 
Looking at `apoc.index.addAllNodes `, It indexes all nodes in the graph. Just wondering  if there is something like `apoc.index.addNodes(List<ids of nodes returned in the result>, properties to index)`
Fortunately, the nodes, in this case, are of the same label. i.e same set of properties 

Is there any such method available. Wasnt obvious for me to find it in this project. 

Could you shed some light on this? Alternatively could you please suggest where I can ask this question.

Cheers!
Phaneendra

**Comment by jexp** [comment]
you can just use cypher

```
match (n:Label)
call apoc.index.addNode(n, ["prop1","prop2"])

```

**Comment by SageAgastya** [comment]
Hi Michael,
 Thank you. 

How to add a node to an index with a custom name (not by label). I tried to use this one.

```
match (n:test {id: "xyz"})
call apoc.index.addNodeByName("index_12345", n, ["id"])

```
This one seems to have created a non-fulltext index.
```

{
  "type": "exact",
  "provider": "lucene"
}
```

Also, search procedure is not available. How to search that node in a full-text manner.

```
CALL apoc.index.search("index_12345", "xyz", 10);
Neo.ClientError.Procedure.ProcedureRegistrationFailed: apoc.index.search is unavailable because it is sandboxed and has dependencies outside of the sandbox. Sandboxing is controlled by the dbms.security.procedures.unrestricted setting. Only unrestrict procedures you can trust with access to database internals.
```

@jexp 

Cheers!
Phaneendra
