### ISSUE TITLE
 apoc.schema.assert are not deleted all indexes

### ISSUE THREAD

**Issue by tomswinkels** [neo4j-contrib/neo4j-apoc-procedures#890]
When i run `CALL apoc.schema.assert({}, {})` not all indexes are deleted. 

The indexes with more propertys are not deleted.

I have manual deleted that index `DROP CONSTRAINT ON (n:Coordinates) ASSERT (n.Latitude, n.Longitude) IS NODE KEY`

**Comment by jexp** [comment]
This procedure was built at a time without composite indexes.

There was originally a version which handled them but had a more complex API, perhaps it's time to revive that from the attic.
