### ISSUE TITLE
Make file export for CSV & GraphML network friendly 

### ISSUE THREAD

**Issue by nickithewatt** [neo4j-contrib/neo4j-apoc-procedures#894]
Hi,

I am accessing a remote Neo4j instance (for example via cypher-shell) and would like to request for the CSV export functionality to be able to write to a stream, which in turn would ultimately allow me to write it out to where ever is needed after that. Specifically it would be helpful to be able to call the `apoc.export.csv.all` procedure and receive the result as a stream. The `apoc.export.cypher.all` procedure has already been adapted to do this and streams the results if no `fileName` is specified (This was done as part of addressing https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/143).

Below is an example of what this may look like if based on the same approach as `apoc.export.cypher.all`:

```
bin/cypher-shell -a bolt://remoteserver:remoteport -u username -p password 
'CALL apoc.export.csv.all("", {})' > /mylocalhost/export.csv
```

Would be really great if this were possible for CSV exports as well :)

**Comment by jexp** [comment]
Good point, basically passing null as a file argument.
Shouldn't be so hard to implement as I already did it for the other approach.

**Comment by jexp** [comment]
good points both.

I started with the CSV one but haven't finished it yet.

In general, if you or someone at OpenCredo has time + interest to contribute, I'm happy to take pull requests. :)

**Comment by nickithewatt** [comment]
We have interest, time however is always the struggle :)
 
If you have already started the CSV one, might be worth you finishing that one off? We can then try and do the graphml one after that time permitting!

**Comment by jexp** [comment]
@nickithewatt I finished and pushed the CSV one, was a bit more involved than expected.

Cleaned up the code a bit, but it's still not as great as I want it to have.

**Comment by nickithewatt** [comment]
Thanks @jexp will have a look!
