### ISSUE TITLE
algo.louvain.stream drops an error

### ISSUE THREAD

**Issue by kuczera** [neo4j-contrib/neo4j-apoc-procedures#895]
If i run the query:

`CALL algo.louvain.stream("IndexPerson", "KNOWS", {})
YIELD nodeId, community
MATCH (user:IndexPerson) WHERE id(user) = nodeId
RETURN user.name1 AS user, community
ORDER BY community;`

neo4j 3.4.6 drops an error:

> Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `algo.louvain.stream`: Caused by: java.lang.ArrayIndexOutOfBoundsException: 2357

**Comment by jexp** [comment]
Can you please raise the issue in: github.com/neo4j-contrib/neo4j-graph-algorithms

Thanks!
