### ISSUE TITLE
make apoc.meta.* sample at batches

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#899]
i.e. if there are 100000 user nodes, sample each 1000th node (jump over the iterateator from findNodes()

**Comment by jexp** [comment]
Also provide additional options for the user to select sampling, including -1 for all.

**Comment by conker84** [comment]
@jexp we would deprecate these procedures (they can be replaced by `db.schema`):
* `apoc.meta.subGraph`
* `apoc.meta.graphSample`
* `apoc.meta.graph`
What do you think?

**Comment by jexp** [comment]
I'm not 100% sure that's what I wanted. Let's discuss.

If a user has 10M nodes should we ask them to provide the nth subsection or just the total number to sample? Esp. as it's per label, one label might have 10 nodes another 9M 

So we should take the node-count per label into account when computing the sampling.

**Comment by jexp** [comment]
@conker84 suggestion form Stefan, randomize the jump a bit to avoid to touch only certain structures from import.
