### ISSUE TITLE
Add two procedures to quickly read from and write to kafka

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#904]
```
apoc.kafka.send(server, topic, data, {config})

apoc.kafka.receive(server, topic, offset) yield value
```

**Comment by bradnussbaum** [comment]
@jexp We are working on generic broker integration. Let's collaborate on this one.

**Comment by bradnussbaum** [comment]
@jexp Please see https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/905

**Comment by mimomenome** [comment]
This would be excellent - we could really use this!

**Comment by conker84** [comment]
I'm closing this since is managed by the Neo4j Streams Plugin
