### ISSUE TITLE
Add TestContainer Integration

### ISSUE THREAD

**Issue by alexiudice** [neo4j-contrib/neo4j-apoc-procedures#907]
Test Containers (https://www.testcontainers.org/) would really help with creating tests when working with other systems integrated with APOC. 

We should have a way to start up an independent container holding images of applications (such as Elasticsearch, Kafka, or RabbitMQ) through testcontainers, and run tests against the applications. This way we could automate tests that reflect a real-world environment. 

TestContainers can run any number of docker images in a test context, making it a very flexible framework and invaluable tool for testing.

**Comment by albertodelazzari** [comment]
I added various integration test using Testcontainers for the ETL project so I think we can do the same for APOC

**Comment by alexiudice** [comment]
Just wondering if anyone has had any progress with this task. I have not yet taken a deep look at the integration needed.
