### ISSUE TITLE
Add more efficient ways for export cypher script.

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#908]
1. performance test using unwind + literals for batches
1. performance test using parameters
1. optionally consider exporting csv with the cypher script and using load csv instead

see: https://medium.com/neo4j/5-tips-tricks-for-fast-batched-updates-of-graph-structures-with-neo4j-and-cypher-73c7f693c8cc

**Comment by conker84** [comment]
closed via 3929ec8
