### ISSUE TITLE
Sugestion: add a neo4j function for FORMAT or TRANSFORM

### ISSUE THREAD

**Issue by JavierSJ** [neo4j-contrib/neo4j-apoc-procedures#91]
Being new with neo4j, I can't found a integrated function that transform the output of numbers or strings.
Is "ugly" to see something like 12345678.901234, instead of clearest 12,345,678.90.
The same for dates, or strings. In fact, one of the most usefull and powerfull functions in Excel is, the ability to format a cell value.

Hope it helps
regards
Javier

**Comment by jexp** [comment]
Kinda apoc.number.format, apoc.number.parse similar to apoc.date.*

Should be straightforward to implement using Java's DecimalFormat plus some extra config that can hold thousand and decimal-separator.

If you have any java knowledge feel free to take a stab at it and send a PR.

**Comment by inserpio** [comment]
https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/123
