### ISSUE TITLE
virtual paths and graphs

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#914]
create proper, independent, virtual paths/graphs perhaps with a config option in

`apoc.graph.fromXXX`

add a procedure and function: 

- apoc.create.vPath(path)
- apoc.create.vPaths(paths)

alternatively we can also allow object as parameter and allow relationship,node, or lists of both.

**Comment by conker84** [comment]
We now have:

- `apoc.graph.fromPath`
- `apoc.graph.fromPaths`

We need:

- `apoc.create.vPath(path)`
- `apoc.create.vPaths(paths)`
