### ISSUE TITLE
pagerank scoring error-It's all zero

### ISSUE THREAD

**Issue by crazyyanchao** [neo4j-contrib/neo4j-apoc-procedures#925]
I run cypher on 3.4.0.1 is ok , but 3.4.0.3 the calculated scores were all 0.
```
MATCH (n:Org)
WITH collect(n) as nodes
CALL apoc.algo.pageRank(nodes) YIELD node,score 
RETURN node.name,score
```
I test it on database  3.4.1 and 3.4.7,but result is same
but why?

**Comment by conker84** [comment]
Hi @crazyyanchao ,
unfortunately the current PageRank implementation is deprecated, could I suggest to use the new dedicated [Graph Algo Package](https://github.com/neo4j-contrib/neo4j-graph-algorithms)?
This package provides an highly optimazed version of the PageRank.

**Comment by crazyyanchao** [comment]
OK,Thanks~

**Comment by conker84** [comment]
As I said the current PageRank implementation in APOC is deprecated so don't consider these results.
Thanks
Andrea
