### ISSUE TITLE
Round-trip for apoc.export.csv.all

### ISSUE THREAD

**Issue by mcolburn** [neo4j-contrib/neo4j-apoc-procedures#928]
It would be good if the file generated by apoc.export.csv.all could be imported into an empty database using the neo4j-admin import command without modification to the generated file.

**Comment by conker84** [comment]
Hi @mcolburn can you detail with an example of what kind of modification do you have to do?

**Comment by mcolburn** [comment]
At the moment, I am swamped with work.  You should be able to reproduce the issue simply by doing the following:

Load a sample CSV dataset into Neo4j using the neo4j-admin import command.
Export the data as a CSV using apoc.
Delete the data from neo4j.
Repeat #1, but for the csv input use the files exported in step #2.

My request is that when apoc exports data as csv, the files should be directly usable by neo4j-admin import.

Thank you!

**Comment by conker84** [comment]
closed via 8473920
