### ISSUE TITLE
Server does not start with bare apoc apoc-3.4.0.3.jar from maven central

### ISSUE THREAD

**Issue by klobuczek** [neo4j-contrib/neo4j-apoc-procedures#929]
After having upgraded to apoc-3.4.0.3.jar from maven central the server does not start anymore with missing libraries e.g.
```
2018-09-27 20:16:13.614+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6e149395' was successfully initialized, but failed to start. Please see the attached cause exception "com.jayway.jsonpath.Configuration". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6e149395' was successfully initialized, but failed to start. Please see the attached cause exception "com.jayway.jsonpath.Configuration".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6e149395' was successfully initialized, but failed to start. Please see the attached cause exception "com.jayway.jsonpath.Configuration".
```
After satisfying all the missing jar files like json-path, json-smart, asm, the next errror is `java.lang.IncompatibleClassChangeError`. 

The neo4j server version is 3.4.7 and the previous apoc version works without any changes.

**Comment by jexp** [comment]
Oh you should never use that, always use the jar from github release.
Or a real maven depdendency.

**Comment by jexp** [comment]
Sure use what everyone else uses to automate the deployment :)

https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json

**Comment by klobuczek** [comment]
I'm sorry, but I still have difficulties here. Why is apoc-all not deployed to maven central while apoc is? We have our own procedures which depend on apoc. It does not feel right to build and test our project with apoc but then deploy apoc-all to the server.

**Comment by jexp** [comment]
Please note that the main usage of apoc is to be intended as procedure jar file to be installed in a Neo4j server.

If you have apoc as a maven dependency and then build your project it should pull all official dependencies that are not optional, e.g. jsonpath.

You see here that the dependencies are listed here as "compile" scope, that could be the reason they are not pulled in. I also checked, there was no "-all" jar deployed to maven central. Would have to check the build scripts.

https://search.maven.org/artifact/org.neo4j.procedure/apoc/3.4.0.3/jar


For Neo4j itself you have to manage the neo4j dependencies yourself.

**Comment by jexp** [comment]
I also don't think your own procedures should depend on apoc, most procedures should be stand-alone and only depend on  Neo4j itself.

**Comment by klobuczek** [comment]
Thanks for looking into the build scripts. The reason our procedures depend on apoc is that there are a lot of useful utility classes in apoc that can be reused when implementing procedures. We did not want to rewrite those.
