### ISSUE TITLE
export function label ordering

### ISSUE THREAD

**Issue by maxdemarzi** [neo4j-contrib/neo4j-apoc-procedures#930]
can we get the labels output for each node in the export function to be sorted. 
Sometimes seeing label1:label2 other times label2:label1 and that makes comparing graphs a little harder.

**Comment by jexp** [comment]
I guess we currently take them in the order we get them from the DB.

We could sort alphabetically or by frequency.

**Comment by conker84** [comment]
Hi @jexp and @maxdemarzi it would be good order them alphabetically?
