### ISSUE TITLE
custom.asProcedure documention fixes

### ISSUE THREAD

**Issue by garystewart** [neo4j-contrib/neo4j-apoc-procedures#933]
Hi,

On the page: [Apoc page](https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_custom_procedures_with_code_apoc_custom_asprocedure_code)

There is no mention of the third input which is read/write.  (discovered this via the test cases in the code) 
Also there is a typo - asProcdure (missing e) in the example.  It would be helpful to share a few more examples to help get started quicker.

Thanks,
Gary

**Comment by jexp** [comment]
Yes you're right. Thanks for the feedback.

If you want to help, we're happy to accept pull requests :)
