### ISSUE TITLE
Unable to Fetch Data that Cloned Using apoc.refactor.cloneNodesWithRelationships in Single Function

### ISSUE THREAD

**Issue by wanzzzone** [neo4j-contrib/neo4j-apoc-procedures#943]
Hi

Currently I have this problem where I can't fetch the duplicated node after the node is cloned using apoc.refactor.cloneNodesWithRelationships. 
So my structure code is just like this :

ObjectService : 
function List<String> copyObject(param) {
     objectRepository.copyUsingApoc(param); //This repo basically contains the apoc clone query & return the new cloned ids
}

function List<Object> findObjectByClonedIds(List<String> cloneIds) {
     objectRepository.findObjectByCloneIds(cloneIds); //Contains normal match query with where id in
}

AnotherService : 

function copy(param) {
     List<String> cloneIds = objectService.copyUsingApoc(param);
     List<Objects> listClonedObjects = objectService.findObjectByClonedIds(cloneIds);
     
     .....
     //Other function that process the data from listClonedObjects
     .....
}

Fyi: Both service have @Transactional

The problem here is I can't fetch the newly duplicated listClonedObjects. Therefore making error when I try to access the newly cloned because the list empty. However when i didn't fetch the data (comment it) and let the transaction finish. I can find the nodes duplicated correctly in the database. The question is can i fetch the newly cloned data when the transaction is running ? 
I have tried separating the function from the controller (assuming it will go to different transaction and the transaction already flushed) But still data can't be fetched. Any workaround or solution for this case ?

Thank you

**Comment by jexp** [comment]
If your first tx is not committed yet you cannot access it from outside. 

You can get it from within the tx

Or let it finish first

**Comment by conker84** [comment]
Hi @wanzzzone which framework are you using? Spring?

**Comment by wanzzzone** [comment]
Hi,

An update about this issue. Sorry but just found out it was my query fault.
I did use a query like this.

MATCH (p:A)-[r1:A_has_B]->(l:B) 
WHERE p.id IN {0} WITH COLLECT(l) as oldBList 
CALL apoc.refactor.cloneNodesWithRelationships(oldBList) YIELD output 
CALL apoc.create.uuid() YIELD uuid SET output.id = uuid 
WITH COLLECT(output.id) as copiedIds
MATCH (l2:B)-[r1]-() 
WHERE l2.id IN copiedIdsAND r1.id IS NOT NULL 
CALL apoc.create.uuid() YIELD uuid 
SET r1.id = uuid 
WITH copiedIds as copiedIds
UNWIND(copiedIds) as result
RETURN result

Apparently I have a case where there isn't any relationship with B that have r.id therefore the copiedIds somehow not returned to the result query. Making it seems like transactional problem.

Thanks for all the helps
