### ISSUE TITLE
help:not getting any results for type exact

### ISSUE THREAD

**Issue by balaa** [neo4j-contrib/neo4j-apoc-procedures#944]
i have created  nodes as follows:
create (:Test1 {value:"CREAM CHEESE"})
create (:Test1 {value:"SOUR CREAM CHEESE"})
create (:Test1 {value:"STRAWBERRY CREAM CHEESE"})
create (:Test1 {value:"CREAM CHEESE 44567"})
create (:Test1 {value:"CREAM CHEESE PEPPER"})
create (:Test1 {value:"CHEESE CREAM"})
create (:Test1 {value:"SOUR CREAM CHEESE"})
create (:Test1 {value:"CREAM CHEESE"})
create (:Test1 {value:"CREAM CHEESE PROSCIUTTO"})
create (:Test1 {value:"SOUR CREAM CHEESE"})
create (:Test1 {value:"CREAM CHEESE"})
create (:Test1 {value:"CREAM CHEESE SPRAY DRIED"})
create (:Test1 {value:"AVOCADO CREAM CHEESE A16"})
create (:Test1 {value:"ONION GARLIC CREAM CHEESE"})
create (:Test1 {value:"CREAM CHEESE BLACK PEPPER"})
then 
call apoc.index.addAllNodes('search',{Test1:["value"]},{autoUpdate:true,type:"exact"})
but when i run the following to get exact match im not getting any results
call apoc.index.search('search','CREAM CHEESE') yield node, weight return node.value,weight

 i understand by default the type is fulltext so i gave the type but im not getting any results,  when is search for CREAM CHEESE i should get only CREAM CHEESE  not CREAM CHEESE PROSCIUTTO or CREAM CHEESE BLACK PEPPER or SOUR CREAM CHEESE

**Comment by conker84** [comment]
Hi @balaa which Neo4j and APOC version are you using?

**Comment by jexp** [comment]
As fulltext indexes made it into the product in 3.5 we will deprecate and remove these procedures from APOC. So please try it within Neo4j and raise the error there if it persists.
Thanks a lot.
