### ISSUE TITLE
Passing a delimiter to `apoc.import.csv` results in "String cannot be cast" error

### ISSUE THREAD

**Issue by ArthurClemens** [neo4j-contrib/neo4j-apoc-procedures#948]
I am experiencing the same bug as reported on SO: https://stackoverflow.com/questions/52046831/neo4j-apoc-apoc-import-csv-error

```
CALL apoc.import.csv(
  [{fileName: 'file:/<path>/persons.csv', labels: ['Person']}],
  [{fileName: 'file:/<path>/knows.csv', type: 'KNOWS'}],
  {delimiter: '|', arrayDelimiter: ',', stringIds: false}
)
```
Results in 
```
apoc "java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Character"
```

This does not happen when `delimiter` is not set.

**Comment by jexp** [comment]
Thanks Arthur for reporting.

@szarnyasg could you have a look.

**Comment by szarnyasg** [comment]
Thanks for reporting this @ArthurClemens and @jexp for pinging me. I submitted a PR with a test for the issue.
I fixed issues with the quotation characters, which was made possible by an earlier PR #879 that bumped the openCSV dependency.
