### ISSUE TITLE
load unknown set of attributes using apoc.load.json

### ISSUE THREAD

**Issue by zfallahnejad** [neo4j-contrib/neo4j-apoc-procedures#952]
I have a json file an I want to load it with "apoc.load.json". My json file looks like below. Each line corresponds to a different page and these pages can have a different set of attributes.
{
    "pages":
    [
        {"page_id": 1, "page_title": "title1", "name":"John", "age":25,...},
        {"page_id": 2, "page_title": "title2", "name":"David", "family":"Smith",...},
        ...
    ]
}
Now, I can load this json file like below and have each line as a Node, but I don't know how to load their attributes. I can't find any example for loading a node with unknown set of attributes. I would appreciate it if you could help me figure this out.

CALL apoc.load.json("file:///path.json") YIELD value
unwind value.pages as p
WITH p
MERGE (page:Page {pid:p.page_id,title:p.page_title})

**Comment by jexp** [comment]
Each of your p is a map so you can do anything you can do with a map

Assign it to a node filter keys() or use any of the apoc map functions for data preparation 

See the load json and map functions videos
Https://r.neo4j.com/apoc-videos

**Comment by zfallahnejad** [comment]
Thanks
