### ISSUE TITLE
apoc.coll.union not whitelisted by cypher interpreter Neo4j 3.4.7

### ISSUE THREAD

**Issue by graphadvantage** [neo4j-contrib/neo4j-apoc-procedures#955]
BUG

WITH [1,2,3] AS coll_1, [3,4,5] AS coll_2 RETURN apoc.coll.union(coll_1,coll_2)

returns

Neo.ClientError.Statement.SyntaxError: Variable `apoc` not defined (line 1, column 50 (offset: 49))
"WITH [1,2,3] AS coll_1, [3,4,5] AS coll_2 RETURN apoc.coll.union"

Cypher interpreter is assuming this is a UNION operator call

Work around:

WITH [1,2,3] AS coll_1, [3,4,5] AS coll_2 RETURN apoc.convert.toSet(apoc.coll.unionAll(coll_1,coll_2))

Thanks, Michael

                                                  ^

**Comment by jexp** [comment]
Which version of neo4j and browser? 

Works for me in the browser when you disable the multi-line editor and also cypher-shell.
I report it to the browser team.
