### ISSUE TITLE
Procedures results are truncated because queue.offer is used instead of queue.put 

### ISSUE THREAD

**Issue by eastlondoner** [neo4j-contrib/neo4j-apoc-procedures#958]
Discovered with
```
CALL apoc.export.cypher.all(null, {format:"plain",streamStatements:true,batchSize:10}) YIELD RETURN cypherStatements LIMIT 100000000', {})
```
If the batch size is small on my DB this only returns 1000 rows and doesn't reach the end.
If I increase the batch size e.g. to 2000 then eventually everything is returned in <1000 rows.
Obviously this will be dependent on your graph, but the procedure always truncates responses at 1000 rows.

@sarmbruster spotted that the cause is using `queue.offer` instead of `queue.put` here:
https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/0839f02317357b6c04f40f39f5c8ebfe0c924b53/src/main/java/apoc/export/cypher/ExportCypher.java#L108

I searched the code and found some more instances of queue.offer being used which look suspect to me:

https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/0839f02317357b6c04f40f39f5c8ebfe0c924b53/src/main/java/apoc/export/csv/ExportCSV.java#L105

https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/39559c80aeb510d4dfe9adb0354354eb23a34604/src/main/java/apoc/cypher/Cypher.java#L166

I think we should change all of them to put. Switching to put probably requires addition of a timeout. I'm not sure where that would come from though?

**Comment by jexp** [comment]
Thanks a lot for reporting Andrew. I'm putting together a PR.

Unfortunately, put has no timeout but would block forever, but we can use `offer` with a timeout.
And then fail if offer after the timeout was not successful.
