### ISSUE TITLE
apoc.number.format(number, decimals, language)

### ISSUE THREAD

**Issue by Marc-Roth** [neo4j-contrib/neo4j-apoc-procedures#964]
Hi guys,

is it possible to have another overload of this function as we often need to return formatted values with varying decimals?
I've got this workaround, but for true, it looks a bit freaky inside my queries (though it's minimized there).
 
```vb
with {number: 12345.12345, decimals: 3} as node,
    {name: "DE"} as language

call apoc.cypher.run(
    "unwind range(0, coalesce($decimals, 0) - 1) as range " +
    "with '.' + apoc.text.join(collect('0'), '') as decimals " +
    "with apoc.number.format(" +
        "$number, " +
        "'#,##0' + decimals, " +
        "toLower($language)" +
    ") as formatted " +
    "return formatted",
    {
        number: node.number,
        decimals: node.decimals,
        language: language.name
    }
) yield value

return value.formatted
```
Kind regards,
Marc

**Comment by jexp** [comment]
If so it would go into an optional config map option.

**Comment by conker84** [comment]
Hi @Marc-Roth what about:
`return apoc.number.format(12345.1, "###,###.000")` that returns `12,345.100`
or 
`return apoc.number.format(12345.12345, "###,###.000")` that returns `12,345.123`

**Comment by Marc-Roth** [comment]
Hi @conker84 ,
the problem is that we need to take care of the decimals dynamically. We need to return data like 20.**0**° as well as 0.**0001**mm with this function. So the default apoc.number.format doesn't work unfortunatelly.

**Comment by conker84** [comment]
Could you provide some test case?

**Comment by Marc-Roth** [comment]
The main purpose is for our mapping module. There we need to convert data from component attributes stored inside some bill of materials and pass the output to the reporting module.
Here some examples and my conversion routine:
```vb
with [
    {name: 'avg. strain temperature', value: 20.00015, uom: '°C', template: {name: 'Temperatures', decimals: 1, language: "DE"}},
    {name: 'max. tollerance', value: 0.0001, uom: 'mm', template: {name: 'Tollerances', decimals: 5, language: "DE"}},
    {name: 'min. voltage', value: 115.00, uom: 'V', template: {name: 'Integer', decimals: 0, language: "DE"}},
    {name: 'max. voltage', value: 118.00, uom: 'V', template: {name: 'Integer', decimals: 0, language: "DE"}}
] as data
unwind data as node

call apoc.cypher.run(
    "unwind range(0, coalesce($decimals, 0) - 1) as range with case when $decimals=0 then '' else '.' + apoc.text.join(collect('0'), '') end as decimals with apoc.number.format($number, '#,##0' + decimals, toLower($language)) as formatted return formatted",
    {number: node.value, decimals: node.template.decimals, language: node.template.language}
) yield value

return node.name, value.formatted
```

**Comment by conker84** [comment]
I think that adding a `decimal` field could lead to some collision with the pattern that an user can provide. What about this query?
```
with [
    {name: 'avg. strain temperature', value: 20.00015, uom: '°C', template: {name: 'Temperatures', decimals: 1, language: "DE"}},
    {name: 'max. tollerance', value: 0.0001, uom: 'mm', template: {name: 'Tollerances', decimals: 5, language: "DE"}},
    {name: 'min. voltage', value: 115.00, uom: 'V', template: {name: 'Integer', decimals: 0, language: "DE"}},
    {name: 'max. voltage', value: 118.00, uom: 'V', template: {name: 'Integer', decimals: 0, language: "DE"}}
] as data
unwind data as node
return node.name as name, node.value as value, replace(apoc.text.format('%.' + node.template.decimals + 'f', [node.value]), '.', ',') as formatted, node.uom as uom
```
The part `replace(apoc.text.format('%.' + node.template.decimals + 'f', [node.value]), '.', ',')` is necessary because as-is the function `apoc.text.format` allows only `Locale.ENGLISH` I think we must add the locale as an option to it

**Comment by Marc-Roth** [comment]
That's pretty cool! I'll take this one and wait until the locale gets in because we also need to take care about that.

**Comment by conker84** [comment]
I created the #985 so you could track it
Thanks for your feedback!
