### ISSUE TITLE
parallel2 stackoverflow error

### ISSUE THREAD

**Issue by ponduripradeep** [neo4j-contrib/neo4j-apoc-procedures#965]
Parallel2 works fine but gives stackoverflow error sometimes

![image](https://user-images.githubusercontent.com/41084282/47624033-17baf480-daee-11e8-9fbd-f51ad7d8f99b.png)

**Comment by alexiudice** [comment]
Could you give more details? What parameters you are passing into the parallel2 procedure? What context are you calling this in?

**Comment by ponduripradeep** [comment]
**High level overview of query**
WITH [person1,person2,....,person 10000]  as persons
call apoc.cypher.parallel2( " match(i:Person {name:p}) with i 
CALL apoc.path.subgraphNodes(i,{relationshipFilter:'sponsor_of>',bfs:false, uniqueness:'NONE'}) YIELD node as dowline return count(downline)",{p:persons},'p') yield value

Query Description: Suppose I have 1M of person nodes, for each person I want to calculate their downline in parallel.

With python multiprocessing I made this whole query run in different threads, will that be an issue?

**Comment by conker84** [comment]
this should be fixed via #1193, feel free to reopen in case the error come back
