### ISSUE TITLE
apoc.load.json() not working...

### ISSUE THREAD

**Issue by AnselmJeong** [neo4j-contrib/neo4j-apoc-procedures#968]
I've been following the apoc.load.json() section on "APOC User Guide 3.4.0.3", but it did not work as described in the guide.
The command in "Load JSON StackOverflow Example" produced the following error.

<img width="729" alt="screen shot 2018-11-04 at 3 04 08 pm" src="https://user-images.githubusercontent.com/1776524/47960777-4b909f80-e043-11e8-85a1-2f0b8f12e7b0.png">

The neo4j desktop version is 1.1.12 and the Apoc version is 3.4.0.3

**Comment by conker84** [comment]
Hi @AnselmJeong,
please try with this query:
```
WITH "https://api.stackexchange.com/2.2/questions?pagesize=100&order=desc&sort=creation&tagged=neo4j&site=stackoverflow" AS url
CALL apoc.load.json(url) YIELD value
UNWIND value.items AS item
RETURN item.title, item.owner, item.creation_date, keys(item)
```
Thanks!

**Comment by conker84** [comment]
There is a bug related to #901
