### ISSUE TITLE
apoc.load.jsonParams will not work with sites using self-signed SSL certificates

### ISSUE THREAD

**Issue by pdrangeid** [neo4j-contrib/neo4j-apoc-procedures#978]
Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure apoc.load.jsonParams: Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Attempting to use apoc.load.json & apoc.load.json Params to connect with VMware vCenter appliance webAPI to query objects.

The site does not have an SSL certificate signed from a CA, but instead using default self-signed certificates.  Suspect this may be part of the JVM layer, but thought I would ask if there is a way to pass a parameter to tell APOC to ignore certificate errors.

**Comment by jexp** [comment]
I don't want to disable certificate checks in APOC in general.

Did you try to take that certificate and import in into the JVMs keystore?

See Option 1 here: https://stackoverflow.com/questions/2893819/accept-servers-self-signed-ssl-certificate-in-java-client

**Comment by conker84** [comment]
closed for lack of feedback
