### ISSUE TITLE
Use new API for distinct index values

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#979]
From 3.4.10:

Hello, https://github.com/neo-technology/neo4j/pull/778 have been merged, so when a new 3.4 release is out consider using that thing from the procedure instead

**Comment by jexp** [comment]
@sarmbruster did we look into this yet?

**Comment by sarmbruster** [comment]
Not that I'm aware of.

**Comment by conker84** [comment]
This should be done now, feel free to reopen in case it doesn't
