### ISSUE TITLE
apoc.meta.type should give consistent type info

### ISSUE THREAD

**Issue by kvegter** [neo4j-contrib/neo4j-apoc-procedures#981]
apoc.meta.type should give proper info for the type especially for Arrays of Temporal and Point data types. In the property column is the name of the property if it ends with an A it is an array.

|property|expected type|current apoc meta type |
| --- | --- | --- |
|date | Date | LocalDate  |  
|dateA | Date[] |LIST |
|datetime | LocalDateTime | LocalDateTime |
|dateTimeA | LocalDateTime[] | LIST |  
|float | Float | FLOAT |
|floatA | Float[] |double[][] |
|localDateTime | LocalDateTime | LocalDateTime |  
|localDateTimeA | LocalDateTime[] | LIST |
|localtime | LocalTime | LocalTime |
|localtimeA | LocalTime[] |LIST |
|name | String | STRING |
|nameA | String[] | STRING[] |  
|integer | Integer | INTEGER |  
|integerA | Integer[] | long[][] |  
|placeOfBirth | PointValue | PointValue |
|placeOfBirthA | PointValue[] | LIST |  
|time | Time | OffsetTime |
|timeA | Time[]| LIST |

**Comment by kvegter** [comment]
I think I made an error with localDateTime in the table above. the distinction between ZonedDateTime and LocalDateTime is lost

**Comment by kvegter** [comment]
wrong button

**Comment by jexp** [comment]
A problem is that we might not easily change what it returns as folks might rely on the old texts.
So we might need to add a different function and deprecate this one.

Where did you take the names from? I guess we should use the same output that `db.procedures()` uses for parameters/result colum types.

I.e. why `PointValue` and not `Point`?
