### ISSUE TITLE
Add ability to provide label to schema functions for filtered results

### ISSUE THREAD

**Issue by stuartlaurie** [neo4j-contrib/neo4j-apoc-procedures#991]
Currently when using e.g. apoc.schema.nodes() If i want to find out information about a specific label I have to post filter the results e.g. to find out constraints on 'Email' i would do:

CALL apoc.schema.nodes() yield label, properties
with * where label="Email" return properties

It would be great if we could provide the label directly to the procedure e.g.

CALL apoc.schema.nodes("Email") yield properties

**Comment by jexp** [comment]
Actually I forgot to comment on this:
I want this to be an _optional_ config option, like for apoc.meta.subgraph: `{labels:[array], relationships:[array], exclude:[array]}`

We should use the same approach for apoc.meta.data, apoc.meta.schema and apoc.meta.graph

The config can also include other options later, like sampling, see https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/899
