### ISSUE TITLE
Add a mode to export.cypher that batches updates

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-apoc-procedures#998]
this should happen in two steps
use batch size for max size

1. group same nodes / rel-patterns with a prefixed unwind:
`UNWIND [....] AS row MERGE (:Label {id:row.id}) SET n += row.properties, SET n:Label2`

2. parameters, at least for cypher-shell with `:param rows => [{....},{....},{....}]`
and then use `UNWIND $rows AS row MERGE (:Label {id:row.id}) SET n += row.properties, SET n:Label2`

**Comment by conker84** [comment]
closed via 3929ec8
