### ISSUE TITLE
A* returns bad path.

### ISSUE THREAD

**Issue by Legolash2o** [neo4j-contrib/neo4j-apoc-procedures#999]
I'm running both the apoc Dijkstra and apoc A* algorithm on openstreetmap UK data. Dijkstra seems to be working correctly but A* is bring back a weird result. It does the same when using the Neo4j web interface as well.

I only use: highway=motorway,trunk,primary,secondary,motorway_link,trunk_link,primary_link,secondary_link

Dijkstra vs A* https://imgur.com/nKkOeYD
Zoomed in https://imgur.com/DX6sJbd
Red is Dijkstra and blue is A*

The area in the red box looks like it's going the longer way round as there is route between the two roundabouts. It's the same near the area (Grays)

**Possibly Related**
Another but possibly related issue too is that if I add sea route from start to finish with a length of 100000, it returns that as the result enough though via road it's about 700 miles.

```
match(s:Node {UID: 60224115}), (e: Node { UID: 4582764124}) 
CALL apoc.algo.dijkstra(s, e, 'Highway>', 'Length') YIELD path, weight 
RETURN path, weight LIMIT 1

match(s:Node {UID: 60224115}), (e: Node { UID: 4582764124}) 
CALL apoc.algo.aStar(s, e,'Highway>' ,'Length','Latitude','Longitude') YIELD path, weight 
RETURN path, weight LIMIT 1
```

**Comment by Legolash2o** [comment]
Thanks for the reply. It still looks wrong when switching.

https://imgur.com/dYMqYaW

**Comment by Legolash2o** [comment]
It seems to be going the wrong way when it comes to a oneways. The data in my graph matches OSM directions on oneways. I have that when it finds the node, it needs to reverse back and doing that incorrectly, but that's just a hunch.

https://imgur.com/ElnaogV
https://imgur.com/of0lY9H

I forgot to mention that I'm only using highway=motorway,trunk,primary,secondary,motorway_link,trunk_link,primary_link,secondary_link

**Comment by sarmbruster** [comment]
Is there a way for you to share your database? I can also provide a private channel for this.
Would be much easier to debug with the same data at hand.

**Comment by Legolash2o** [comment]
I can share with you with CSVs I outputted and the commands I used?

**Comment by Legolash2o** [comment]
Hopefully this contains enough for you to rebuild the database.

https://universityofhull.box.com/s/dz4bwqvk4y7c0v3ca168nut64bol1qwu

**Comment by Legolash2o** [comment]
Thanks!

Just an update Dijkstra also goes up wrong on oneway streets. I changed the edge from "Highway>" to "<Highway" and it seems to look better.
https://imgur.com/uIrUYYP

A* still seems to be making weird decisions though.
https://imgur.com/4cItUAw

**Comment by Legolash2o** [comment]
It might be worth stopping for a while as I think I found a bug in the code that turns my OSM into CSV. I didn't include that roundabout is oneway and only looked for oneway tags.

**Comment by sarmbruster** [comment]
Ok, so I'm on hold until you get back.

**Comment by Legolash2o** [comment]
Just finished testing. I was wrong about the going up the wrong ways but it still returning a very different result than Dijkstra
https://imgur.com/Vf0BhK1

It is also making weird decisions. Below is an example where it would be quicker to go the route I drawn, it down this sort of thing alot. 
https://imgur.com/yV4Xvs1

Another example is that if I add edges between the start and end i.e. via the sea and that route is longer, it will still give me that as a route because there's less nodes between them. sea for example would be 700 miles whereas by road is 600 miles. It's almost as if it stops search as soon as it finds the end node even though it may not be the quickest. Not sure if that's how A* works.

**CSV files**
https://universityofhull.box.com/s/91elldmoh2qmcwyqulld157ret1v2ivj

**Comment by sarmbruster** [comment]
since apoc just delegates to a astar function inside neo4j I guess it needs to be fixed in Neo4j and not in apoc. Need to investigate more.

**Comment by conker84** [comment]
This can be done in GDS now
